(asdf:defsystem "mognitio"
  :description "Mognitio compiler"
  :version "0.5.0"
  :depends-on ("sb-posix")
  :serial t
  :components ((:file "src/packages")
               (:file "src/diagnostics")
               (:file "src/runtime-failure")
               (:file "src/integer")
               (:file "src/source")
               (:file "src/syntax")
               (:file "src/lexer")
               (:file "src/parser")
               (:file "src/semantic")
               (:file "src/checked-program")
               (:file "src/text-runtime")
               (:file "src/backend-common-lisp")
               (:file "src/target")
               (:file "src/ir")
               (:file "src/root-analysis")
               (:file "src/root-verifier")
               (:file "src/register-allocation")
               (:file "src/object-model")
               (:file "src/native-context")
               (:file "src/native-frame")
               (:file "src/machine-ir")
               (:file "src/amd64")
               (:file "src/elf")
               (:file "src/backend-native")
               (:file "src/artifact")
               (:file "src/driver")
               (:file "src/cli"))
  :in-order-to ((asdf:test-op (asdf:test-op "mognitio/tests"))))

(asdf:defsystem "mognitio/tests"
  :depends-on ("mognitio")
  :serial t
  :components ((:file "tests/harness")
               (:file "tests/source-frontend")
               (:file "tests/semantic-backend")
               (:file "tests/driver-process")
               (:file "tests/generated")
               (:file "tests/native-ir")
               (:file "tests/native-process")
               (:file "tests/native-generated")
               (:file "tests/v03-kernel")
               (:file "tests/v03-merge")
               (:file "tests/v03-generated")
               (:file "tests/v04-allocation")
               (:file "tests/v04-functions")
               (:file "tests/v04-generated")
               (:file "tests/v04-boundaries")
               (:file "tests/v04-artifacts")
               (:file "tests/v05-core")
               (:file "tests/v05-functions")
               (:file "tests/v05-values")
               (:file "tests/v05-loops")
               (:file "tests/v05-generated")
               (:file "tests/v05-conformance")
               (:file "tests/v05-boundaries")
               (:file "tests/v06-compatibility")
               (:file "tests/v06-frontend")
               (:file "tests/v06-host")
               (:file "tests/v06-core")
               (:file "tests/v06-roots")
               (:file "tests/v06-native-frames"))
  :perform (asdf:test-op (op system)
             (declare (ignore op system))
             (uiop:symbol-call :mognitio.tests :run-tests)))
