(defpackage #:mognitio.tests
  (:use #:cl #:mognitio.diagnostics #:mognitio.source #:mognitio.syntax
        #:mognitio.frontend #:mognitio.semantic #:mognitio.backend.cl)
  (:export #:run-tests))
(in-package #:mognitio.tests)
(eval-when (:compile-toplevel :load-toplevel :execute) (require :sb-posix))

(defvar *tests* nil)
(defvar *assertions* 0)
(defvar *temp* nil)
(defvar *serial* 0)
(defvar *processes* 0)

(defmacro deftest (name &body body)
  `(progn (defun ,name () ,@body)
          (pushnew ',name *tests*)))
(defun is (value &optional (description "Assertion failed"))
  (incf *assertions*)
  (unless value (error "~A" description)))
(defun same (expected actual)
  (is (equalp expected actual)
      (format nil "Expected ~S, got ~S" expected actual)))
(defmacro signals (kind &body body)
  `(is (handler-case (progn ,@body nil) (,kind () t))
        ,(format nil "Expected ~A" kind)))
(defmacro replacing ((name replacement) &body body)
  (let ((old (gensym)))
    `(let ((,old (fdefinition ',name)))
       (unwind-protect
            (progn (setf (fdefinition ',name) ,replacement) ,@body)
         (setf (fdefinition ',name) ,old)))))
(defun root-path (name)
  (asdf:system-relative-pathname "mognitio" name))
(defun fresh-path (&optional (suffix ".mgn"))
  (merge-pathnames (format nil "case-~D~A" (incf *serial*) suffix) *temp*))
(defun put-text (path text)
  (with-open-file (out path
                       :direction :output :if-exists :supersede
                       :external-format :utf-8)
    (write-string text out))
  path)
(defun put-bytes (path bytes)
  (with-open-file (out path :direction :output :if-exists :supersede
                           :element-type '(unsigned-byte 8))
    (write-sequence bytes out))
  path)
(defun text-source (text &optional (path "test.mgn"))
  (decode-source path (sb-ext:string-to-octets text :external-format :utf-8)))
(defun parse-text (text)
  (let ((source (text-source text)))
    (parse-program source (lex-source source))))
(defun compiled-result (text)
  (execute-program (compile-program (check-program (parse-text text)))))
(defun diagnostic-of (thunk)
  (handler-case (progn (funcall thunk) (error "Expected compiler failure"))
    (compiler-failure (condition) (failure-diagnostic condition))))
(defun driver-result (argv)
  (let* ((out (make-string-output-stream)) (err (make-string-output-stream))
         (code (mognitio.driver:run-cli argv out err)))
    (values (get-output-stream-string out) (get-output-stream-string err) code)))

(defun process-result (argv &key directory (timeout 20))
  ;; Files avoid pipe-buffer deadlocks while the parent enforces the timeout.
  (let* ((out (fresh-path ".stdout")) (err (fresh-path ".stderr"))
         (process (uiop:launch-program argv :directory (or directory *temp*)
                                            :input nil :output out :error-output err))
         (deadline (+ (get-internal-real-time)
                      (* timeout internal-time-units-per-second))))
    (incf *processes*)
    (unwind-protect
         (progn
           (loop while (uiop:process-alive-p process)
                 do (when (> (get-internal-real-time) deadline)
                      (error "Child process timeout: ~S" argv))
                    (sleep 0.01))
           (let ((code (uiop:wait-process process)))
             (values (uiop:read-file-string out :external-format :utf-8)
                     (uiop:read-file-string err :external-format :utf-8) code)))
      (when (uiop:process-alive-p process)
        (uiop:terminate-process process :urgent t))
      (uiop:wait-process process)
      (when (probe-file out) (delete-file out))
      (when (probe-file err) (delete-file err)))))

(defun cli-result (args &rest options)
  (apply #'process-result (cons (namestring (root-path "bin/mgn")) args) options))
(defun expect-cli (args code &key output phase directory)
  (multiple-value-bind (out err actual) (cli-result args :directory directory)
    (is (= code actual) (format nil "Args=~S expected exit ~D, got ~D: ~A" args code actual err))
    (same (or output "") out)
    (if (zerop code) (same "" err)
        (progn (is (plusp (length err))) (same 1 (count #\Newline err))))
    (when phase (is (search (format nil ": ~A:" phase) err)))
    err))
(defun expect-source (text result)
  (let ((path (put-text (fresh-path) text)))
    (same result (compiled-result text))
    (expect-cli (list "run" (namestring path)) 0
                :output (format nil "~A~%" (if (eq result :true) "true" "false")))))
(defun expect-invalid (text phase)
  (let ((path (put-text (fresh-path) text)))
    (expect-cli (list "run" (namestring path)) 1 :phase phase)))

(defun run-tests ()
  (let* ((*assertions* 0) (*serial* 0) (*processes* 0)
         (*temp* (uiop:ensure-directory-pathname
                  (sb-posix:mkdtemp
                   (namestring (merge-pathnames "mognitio-tests-XXXXXX"
                                                (uiop:temporary-directory))))))
         (failed 0))
    (unwind-protect
         (progn
           (dolist (test (reverse *tests*))
             (handler-case (progn (funcall test) (format t "PASS ~A~%" test))
               (error (condition)
                 (incf failed) (format t "FAIL ~A: ~A~%" test condition))))
           (format t "Tests=~D Assertions=~D Processes=~D Failures=~D~%"
                   (length *tests*) *assertions* *processes* failed)
           (when (plusp failed) (error "Mognitio tests failed")))
      (uiop:delete-directory-tree *temp* :validate t :if-does-not-exist :ignore))))
