(in-package #:mognitio.tests)

(defun build-args (source output &optional reverse-options)
  (append (list "build")
          (if reverse-options
              (list "--output" (sb-ext:native-namestring output) "--target" "linux/amd64")
              (list "--target" "linux/amd64" "--output" (sb-ext:native-namestring output)))
          (list (sb-ext:native-namestring source))))
(defun read-bytes (path)
  (with-open-file (stream path :element-type '(unsigned-byte 8))
    (let ((bytes (make-array (file-length stream) :element-type '(unsigned-byte 8))))
      (same (length bytes) (read-sequence bytes stream))
      bytes)))
(defun expect-driver (args expected &optional phase)
  (multiple-value-bind (out err code) (driver-result args)
    (same expected code) (same "" out)
    (if (zerop expected) (same "" err)
        (progn (same 1 (count #\Newline err)) (is (plusp (length err)))))
    (when phase (is (search phase err)))))
(defun build-text (text)
  (let ((source (put-text (fresh-path) text)) (output (fresh-path ".elf")))
    (expect-driver (build-args source output) 0)
    output))
(defun expect-artifact (path result &rest options)
  (multiple-value-bind (out err code)
      (apply #'process-result (list (sb-ext:native-namestring path)) options)
    (same 0 code) (same "" err)
    (same (format nil "~(~A~)~%" result) out)))
(defun temporary-images ()
  (directory (merge-pathnames ".mgn-build-*" *temp*)))

(deftest n09-n10-n26-n28-invocations
  (let ((source (put-text (fresh-path) "true")) (output (fresh-path ".txt")))
    (dolist (reverse '(nil t))
      (expect-cli (build-args source output reverse) 0)
      (expect-artifact output :true))
    (dolist (name '("artifact" "artifact.MGN"))
      (let ((named-output (merge-pathnames name *temp*)))
        (expect-cli (build-args source named-output) 0)
        (expect-artifact named-output :true)))
    (dolist (args (list
                  '("build") '("build" "--target" "linux/amd64" "a.mgn")
                  '("build" "--output" "out" "a.mgn")
                  '("build" "--target" "linux/AMD64" "--output" "out" "a.mgn")
                  '("build" "--target" "linux/amd64" "--target" "linux/amd64" "a.mgn")
                  '("build" "--output" "x" "--output" "y" "a.mgn")
                  '("build" "--target=linux/amd64" "--output" "out" "a.mgn")
                  '("build" "a.mgn" "--target" "linux/amd64" "--output" "out")
                  '("build" "--target" "linux/amd64" "--output" "" "a.mgn")
                  (append (build-args source output) '("extra"))))
      (expect-cli args 2))
    (dolist (suffix '(".MGN" ".txt" "" "-" ".mgn.bak"))
      (let ((invalid (put-text (fresh-path suffix) "true")))
        (expect-cli (list "run" (namestring invalid)) 2)
        (expect-cli (build-args invalid output) 2)))
    (let ((before (read-bytes output)))
      (expect-cli (build-args (merge-pathnames "absent.txt" *temp*) output) 2)
      (same before (read-bytes output)))
    (delete-file output)
    (expect-cli (build-args (merge-pathnames "absent.txt" *temp*) output) 2)
    (is (not (probe-file output)))))

(deftest n04-n08-native-source-regression
  (let ((output (fresh-path ".elf")))
    (dolist (space (list " " (string #\Tab) (string #\Newline)
                         (string #\Return) (format nil "~C~C" #\Return #\Newline)))
      (let ((source (put-text (fresh-path) (format nil "~Atrue~A" space space))))
        (expect-cli (build-args source output) 0)
        (expect-artifact output :true)))
    (dolist (bytes (list (sb-ext:string-to-octets (format nil " ~Ctrue~%" #\Tab)
                                                 :external-format :utf-8)
                        #(239 187 191 116 114 117 101)))
      (let ((source (put-bytes (fresh-path) bytes)))
        (expect-cli (build-args source output) 0)
        (expect-artifact output :true)))
    (dolist (case '((#(255) "source") (#(192 128) "source")
                    (#(237 160 128) "source") (#(244 144 128 128) "source")
                    (#(239 187 191 239 187 191 116 114 117 101) "source")
                    (#(64) "lex")))
      (let ((source (put-bytes (fresh-path) (first case))))
        (expect-cli (build-args source output) 1 :phase (second case))))
    (dolist (text '("" "true false" "(true)" "if(true){}else{false}"
                    "if(true){true}else if(false){true}else{false}"
                    "if(true){true}else{true false}" "if(false){@}else{true}"))
      (let ((source (put-text (fresh-path) text)))
        (expect-cli (build-args source output) 1
                    :phase (if (find #\@ text) "lex" "parse"))))
    (let ((source (put-text (fresh-path) (format nil "if(true){true}else{~%@}"))))
      (is (search ":2:1: lex:" (expect-cli (build-args source output) 1))))))

(deftest n11-n14-n29-paths-publication
  (let ((source (put-text (fresh-path) "false")) (output (fresh-path ".out")))
    (put-text output "previous")
    (expect-cli (build-args source output) 0)
    (is (logtest #o100 (sb-posix:stat-mode (sb-posix:stat (namestring output)))))
    (expect-artifact output :false)
    (let ((before (read-bytes output)))
      (put-text source "true false")
      (expect-cli (build-args source output) 1 :phase "parse")
      (same before (read-bytes output)))
    (put-text source "true")
    (expect-cli (build-args source source) 2)
    (let ((alias (fresh-path ".link")) (symbolic (fresh-path ".mgn")))
      (sb-posix:link (namestring source) (namestring alias))
      (expect-cli (build-args source alias) 2)
      (sb-posix:symlink (namestring source) (namestring symbolic))
      (expect-cli (build-args source symbolic) 2)
      (expect-cli (build-args symbolic source) 2)
      (expect-cli (build-args symbolic output) 0)
      (let ((target (put-text (fresh-path ".txt") "false"))
            (link (fresh-path ".mgn")))
        (sb-posix:symlink (namestring target) (namestring link))
        (expect-cli (build-args link output) 0)
        (expect-artifact output :false)))
    (expect-cli (build-args source (merge-pathnames "missing-parent/out" *temp*)) 2)
    (expect-cli (build-args source *temp*) 2)
    (let ((fifo (fresh-path ".fifo")))
      (sb-posix:mkfifo (namestring fifo) #o600)
      (expect-cli (build-args source fifo) 2))
    (let ((directory (merge-pathnames "directory.mgn/" *temp*)))
      (ensure-directories-exist directory)
      (expect-cli (build-args directory output) 2))
    (is (not (zerop (sb-posix:getuid))) "Permission cases require non-root")
    (unwind-protect
         (progn (sb-posix:chmod (namestring source) 0)
                (expect-cli (build-args source output) 2))
      (sb-posix:chmod (namestring source) #o600))
    (let* ((directory (merge-pathnames "read-only/" *temp*))
           (destination (merge-pathnames "output" directory)))
      (ensure-directories-exist directory)
      (put-text destination "keep")
      (unwind-protect
           (progn
             (sb-posix:chmod (namestring directory) #o500)
             (expect-cli (build-args source destination) 2)
             (same "keep" (uiop:read-file-string destination))
             (expect-cli (build-args source (merge-pathnames "new" directory)) 2))
        (sb-posix:chmod (namestring directory) #o700))))
  (let ((directory (merge-pathnames "other 日本語 cwd/" *temp*)))
    (ensure-directories-exist directory)
    (dolist (name '("space name.mgn" "日本語.mgn" "*.mgn" "file[1]?.mgn" "-.mgn"))
      (let ((source (merge-pathnames (sb-ext:parse-native-namestring name) directory)))
        (put-text source "true")
        (expect-cli (list "build" "--output" "-" "--target" "linux/amd64" name)
                    0 :directory directory)
        (expect-artifact (merge-pathnames "-" directory) :true)))
    (expect-cli '("build" "--target" "linux/amd64" "--output" "new" "-")
                2 :directory directory)))

(deftest d05-d07-native-stopping-and-publication-faults
  (let ((source (put-text (fresh-path) "true")) (output (fresh-path ".out")))
    (replacing (mognitio.backend.cl:compile-program
                (lambda (&rest args) (declare (ignore args)) (error "CL compilation reached")))
      (replacing (mognitio.backend.cl:execute-program
                  (lambda (&rest args) (declare (ignore args)) (error "CL execution reached")))
        (expect-driver (build-args source output) 0)))
    (dolist (name '(mognitio.ir:lower-program mognitio.ir:verify-module
                    mognitio.machine:lower-module mognitio.amd64:encode mognitio.elf:make-image))
      (let ((original (fdefinition name)))
        (unwind-protect
             (progn
               (setf (fdefinition name)
                     (lambda (&rest args) (declare (ignore args)) (error "Injected native fault")))
               (replacing (mognitio.artifact:publish-image
                           (lambda (&rest args) (declare (ignore args)) (error "Publication reached")))
                 (expect-driver (build-args source output) 3 ":1:1: internal:")))
          (setf (fdefinition name) original))))
    (dolist (name '(mognitio.artifact::write-image mognitio.artifact::flush-image
                    mognitio.artifact::set-executable mognitio.artifact::close-image
                    mognitio.artifact::replace-image))
      (dolist (existing '(nil t))
        (when (probe-file output) (delete-file output))
        (when existing (put-text output "keep"))
        (let ((original (fdefinition name)))
          (unwind-protect
               (progn
                 (setf (fdefinition name)
                       (lambda (&rest args)
                         (when (eq name 'mognitio.artifact::write-image)
                           (write-sequence (first args) (second args) :end 8))
                         (error 'file-error :pathname output)))
                 (expect-driver (build-args source output) 2))
            (setf (fdefinition name) original)))
        (if existing (same "keep" (uiop:read-file-string output))
            (is (not (probe-file output))))
        (same nil (temporary-images))))
    (put-text source "@")
    (let ((calls 0))
      (replacing (mognitio.backend.native:compile-program
                  (lambda (&rest args) (declare (ignore args)) (incf calls)))
        (expect-driver (build-args source output) 1 "lex:"))
      (same 0 calls))
    (let ((calls 0))
      (replacing (mognitio.artifact:validate-paths
                  (lambda (&rest args) (declare (ignore args)) (incf calls)))
        (expect-driver (build-args (fresh-path ".txt") output) 2))
      (same 0 calls))))

(deftest n22-n23-native-runtime
  (dolist (value '(:true :false))
    (let ((artifact (build-text (render-tree value))))
      (multiple-value-bind (out err code)
          (process-result (list "env" "-i" "PATH=/nonexistent" "IGNORED=value"
                                (namestring artifact) "extra" "--ignored"))
        (same 0 code) (same "" err) (same (format nil "~(~A~)~%" value) out))
      (dolist (mode '("partial-eintr" "zero" "error"))
        (multiple-value-bind (out err code)
            (process-result (list "python3" (namestring (root-path "tests/runtime-syscalls.py"))
                                  (namestring artifact) mode))
          (same (if (string= mode "partial-eintr") 0 1) code)
          (same "" err)
          (same (if (string= mode "partial-eintr") (format nil "~(~A~)~%" value) "") out)))
      (dolist (redirect '("exec \"$1\" > /dev/full" "exec \"$1\" 1>&-"))
        (multiple-value-bind (out err code)
            (process-result (list "sh" "-c" redirect "runtime-test" (namestring artifact)))
          (is (not (zerop code))) (same "" out) (same "" err))))))

(defun native-fault-main ()
  (let* ((args (uiop:command-line-arguments))
         (mode (first args)) (source (second args)) (output (third args))
         (name (cdr (assoc mode
                          '(("lower" . mognitio.ir:lower-program)
                            ("verify" . mognitio.ir:verify-module)
                            ("machine" . mognitio.machine:lower-module)
                            ("encode" . mognitio.amd64:encode)
                            ("image" . mognitio.elf:make-image)
                            ("semantic" . mognitio.semantic:check-program)
                            ("write" . mognitio.artifact::write-image)
                            ("flush" . mognitio.artifact::flush-image)
                            ("chmod" . mognitio.artifact::set-executable)
                            ("close" . mognitio.artifact::close-image)
                            ("rename" . mognitio.artifact::replace-image))
                          :test #'string=))))
    (unless name (error "Unknown test fault"))
    (setf (fdefinition name)
          (lambda (&rest values)
            (cond ((string= mode "semantic")
                   (fail-at (node-span (program-root (first values))) :semantic "Injected"))
                  ((member mode '("write" "flush" "chmod" "close" "rename") :test #'string=)
                   (error 'file-error :pathname output))
                  (t (error "Injected native failure")))))
    (sb-ext:exit :code (mognitio.driver:run-cli
                       (build-args source output) *standard-output* *error-output*))))

(deftest n16-native-process-faults
  (let ((source (put-text (fresh-path) "true")) (output (fresh-path ".out")))
    (dolist (mode '("lower" "verify" "machine" "encode" "image" "semantic"
                    "write" "flush" "chmod" "close" "rename"))
      (put-text output "keep")
      (multiple-value-bind (out err code)
          (process-result (list "sbcl" "--noinform" "--script"
                                (namestring (root-path "tests/native-fault-entry.lisp"))
                                mode (namestring source) (namestring output)))
        (same (cond ((string= mode "semantic") 1)
                    ((member mode '("write" "flush" "chmod" "close" "rename")
                             :test #'string=) 2)
                    (t 3)) code)
        (same "" out) (same 1 (count #\Newline err))
        (when (= code 3) (is (search ":1:1: internal:" err))))
      (same "keep" (uiop:read-file-string output))
      (same nil (temporary-images)))))

(deftest d04-no-external-generation
  (let ((source (put-text (fresh-path) "if(true){false}else{true}"))
        (output (fresh-path ".elf"))
        (tools (merge-pathnames "compiler-tools/" *temp*)))
    (ensure-directories-exist tools)
    (sb-posix:symlink (sb-posix:readlink "/proc/self/exe")
                      (namestring (merge-pathnames "sbcl" tools)))
    (put-text (merge-pathnames "dirname" tools)
              (format nil "#!/bin/sh~%case $1 in --) shift;; esac~%printf '%s\\n' \"\${1%/*}\"~%"))
    (sb-posix:chmod (namestring (merge-pathnames "dirname" tools)) #o700)
    (multiple-value-bind (out err code)
        (process-result (append (list "env" (format nil "PATH=~A" (namestring tools))
                                     (namestring (root-path "bin/mgn")))
                               (build-args source output)))
      (same 0 code) (same "" out) (same "" err))
    (expect-artifact output :false)
    (replacing (uiop:launch-program
                (lambda (&rest args) (declare (ignore args)) (error "External process reached")))
      (sb-ext:without-package-locks
        (replacing (sb-ext:run-program
                    (lambda (&rest args) (declare (ignore args)) (error "External process reached")))
          (expect-driver (build-args source output) 0))))))

(deftest d08-missing-bootstrap-entry
  (let* ((copy (merge-pathnames "missing-entry/" *temp*))
         (launcher (merge-pathnames "bin/mgn" copy)))
    (ensure-directories-exist launcher)
    (uiop:copy-file (root-path "bin/mgn") launcher)
    (sb-posix:chmod (namestring launcher) #o700)
    (multiple-value-bind (out err code) (process-result (list (namestring launcher)))
      (same 3 code) (same "" out)
      (same (format nil "mgn: internal: Compiler bootstrap failed~%") err))))

(deftest native-host-output-isolation
  (let ((source (put-text (fresh-path) "true")) (output (fresh-path ".elf"))
        (original (fdefinition 'mognitio.ir:lower-program)))
    (replacing (mognitio.ir:lower-program
                (lambda (checked)
                  (write-line "Host output" *standard-output*)
                  (write-line "Host diagnostic" *error-output*)
                  (write-line "Host trace" *trace-output*)
                  (funcall original checked)))
      (expect-driver (build-args source output) 0))))

(deftest n12-n14-all-failures-preserve-output
  (let ((source (put-text (fresh-path) "true")) (output (fresh-path ".out")))
    (dolist (existing '(nil t))
      (when existing (put-text output "keep"))
      (dolist (text '("@" "true false"))
        (put-text source text)
        (expect-cli (build-args source output) 1)
        (if existing (same "keep" (uiop:read-file-string output))
            (is (not (probe-file output)))))
      (expect-cli (build-args (fresh-path) output) 2)
      (if existing (same "keep" (uiop:read-file-string output))
          (is (not (probe-file output))))
      (put-text source "true")
      (replacing (mognitio.elf:make-image
                  (lambda (&rest args) (declare (ignore args)) (error "Image failure")))
        (expect-driver (build-args source output) 3 "internal:"))
      (if existing (same "keep" (uiop:read-file-string output))
          (is (not (probe-file output))))
      (same nil (temporary-images)))))

(deftest n12-n16-io-diagnostic-attribution
  (let ((source (put-text (fresh-path) "true"))
        (output (put-text (fresh-path ".out") "keep")))
    (labels ((check-path (input destination expected)
               (let ((diagnostic
                       (diagnostic-of
                        (lambda ()
                          (mognitio.artifact:validate-paths
                           (namestring input) (namestring destination))))))
                 (same (namestring expected) (diagnostic-path diagnostic)))
               (let ((stderr (expect-cli (build-args input destination) 2)))
                 (is (eql 0 (search (concatenate 'string
                                                (one-line (namestring expected)) ":")
                                     stderr))))
               (same "keep" (uiop:read-file-string output))))
      (let ((missing (fresh-path)))
        (check-path missing output missing))
      (let ((directory (fresh-path)))
        (sb-posix:mkdir (namestring directory) #o700)
        (check-path directory output directory))
      (let ((missing-parent (merge-pathnames "absent-directory/output" *temp*)))
        (check-path source missing-parent missing-parent)
        (is (not (probe-file missing-parent))))
      (check-path source *temp* *temp*)
      (let* ((directory (merge-pathnames "no-search-permission/" *temp*))
             (hidden (merge-pathnames "hidden.mgn" directory)))
        (ensure-directories-exist directory)
        (put-text hidden "true")
        (is (not (zerop (sb-posix:getuid))) "Permission case requires non-root")
        (unwind-protect
             (progn
               (sb-posix:chmod (namestring directory) 0)
               (check-path hidden output hidden)
               (check-path source hidden hidden))
          (sb-posix:chmod (namestring directory) #o700))))))
