(in-package #:mognitio.tests)

(defun tree-if-count (tree)
  (if (atom tree) 0 (1+ (reduce #'+ tree :key #'tree-if-count))))
(defun check-native-tree (tree)
  (let* ((text (render-tree tree)) (expected (oracle tree))
         (ir (native-ir text)) (machine (mognitio.machine:lower-module ir)))
    (same expected (compiled-result text))
    (same (tree-if-count tree)
          (count :branch (mognitio.ir:module-blocks ir)
                 :key (lambda (block) (first (mognitio.ir:basic-block-terminator block)))))
    (same (tree-if-count tree)
          (count-if (lambda (inst)
                      (let ((target (first (mognitio.machine:instruction-operands inst))))
                        (and (eq (mognitio.machine:instruction-opcode inst) :jz)
                             (consp target) (eq (first target) :block) (plusp (second target)))))
                    machine))
    (expect-artifact (build-text text) expected)))

(deftest n01-n03-d03-generated-native
  (dolist (value '(:true :false)) (check-native-tree value))
  (dolist (condition '(:true :false))
    (dolist (then '(:true :false))
      (dolist (else '(:true :false)) (check-native-tree (list condition then else)))))
  (let ((state 9622))
    (labels ((next-number ()
               (setf state (mod (+ (* state 1664525) 1013904223) 4294967296)))
             (tree (remaining)
               (if (or (zerop remaining) (< (mod (ash (next-number) -16) 8) 3))
                   (if (evenp (ash (next-number) -16)) :true :false)
                   (list (tree (1- remaining)) (tree (1- remaining)) (tree (1- remaining))))))
      (dotimes (index 128)
        (let ((tree (tree 5)))
          (handler-case (check-native-tree tree)
            (error (condition)
              (error "seed=9622 depth=5 sample=~D input=~A: ~A"
                     index (render-tree tree) condition))))))))

(deftest n24-d08-deterministic-cold-warm-relocation
  (let* ((copy (merge-pathnames "compiler 日本語 copy/" *temp*))
         (cache (merge-pathnames "native-cache/" *temp*))
         (source (put-text (fresh-path) "var x = 1; let n = if(true){x = 2; 3}else{4}; x + n == 6"))
         (output (fresh-path ".elf")) (baseline nil))
    (dolist (file (append (list (root-path "mognitio.asd") (root-path "bin/mgn"))
                          (directory (merge-pathnames (make-pathname :name :wild :type "lisp")
                                                      (root-path "src/")))
                          (directory (merge-pathnames (make-pathname :name :wild :type "lisp")
                                                      (root-path "scripts/")))))
      (let ((destination (merge-pathnames (enough-namestring file (root-path "")) copy)))
        (ensure-directories-exist destination)
        (uiop:copy-file file destination)))
    (sb-posix:chmod (namestring (merge-pathnames "bin/mgn" copy)) #o700)
    (is (not (probe-file cache)))
    (dolist (launcher (list (root-path "bin/mgn") (merge-pathnames "bin/mgn" copy)
                            (merge-pathnames "bin/mgn" copy)))
      (multiple-value-bind (out err code)
          (process-result
           (append (list "env" (format nil "XDG_CACHE_HOME=~A" (namestring cache))
                         "ASDF_OUTPUT_TRANSLATIONS=" "CL_SOURCE_REGISTRY="
                         (namestring launcher))
                   (build-args source output))
           :directory copy)
        (is (zerop code) (format nil "Relocated build failed: ~A ~A" out err))
        (same "" out) (same "" err))
      (let ((bytes (read-bytes output)))
        (if baseline (same baseline bytes) (setf baseline bytes))))
    (is (probe-file cache))
    (let ((other (put-text (merge-pathnames "different name.mgn" copy)
                           (uiop:read-file-string source))))
      (let ((different-output (merge-pathnames "renamed artifact.MGN" *temp*)))
        (expect-cli (build-args other different-output) 0 :directory copy)
        (same baseline (read-bytes different-output))))
    (delete-file source)
    ;; The executable remains usable after its source and copied compiler are removed.
    (uiop:delete-directory-tree copy :validate t)
    (uiop:delete-directory-tree cache :validate t)
    (expect-artifact output :false)))
