(in-package #:mognitio.tests)

;; Test-only trees and mathematical oracle; never call production arithmetic.
(defun v03-oracle (tree state)
  (labels ((ev (n) (v03-oracle n state))
           (bound (n)
             (unless (<= (- (expt 2 63)) n (1- (expt 2 63)))
               (throw 'oracle-failure "integer overflow")) n))
    (cond ((integerp tree) tree)
          ((eq tree :x) (car state))
          (t (case (first tree)
               (:if (if (ev (second tree)) (ev (third tree)) (ev (fourth tree))))
               (:update (setf (car state) (ev (second tree))) (ev (third tree)))
               (otherwise
                (let* ((a (ev (second tree))) (b (ev (third tree))))
                  (case (first tree)
                    (:lt (< a b))
                    (:add (bound (+ a b))) (:sub (bound (- a b))) (:mul (bound (* a b)))
                    ((:div :rem)
                     (when (zerop b)
                       (throw 'oracle-failure
                         (if (eq (first tree) :div) "division by zero" "remainder by zero")))
                     (when (and (= a (- (expt 2 63))) (= b -1))
                       (throw 'oracle-failure "integer overflow"))
                     (let* ((magnitude (floor (abs a) (abs b)))
                            (q (if (eq (minusp a) (minusp b)) magnitude (- magnitude))))
                       (if (eq (first tree) :div) q (- a (* q b)))))
                    (otherwise (error "Invalid oracle node"))))))))))
(defun v03-render (tree)
  (cond ((integerp tree) (if (minusp tree) (format nil "(~D)" tree) (format nil "~D" tree))) ((eq tree :x) "x")
        ((eq (first tree) :if)
         (format nil "if(~A){~A}else{~A}" (v03-render (second tree))
                 (v03-render (third tree)) (v03-render (fourth tree))))
        ((eq (first tree) :update)
         (format nil "if(true){x = ~A; ~A}else{0}" (v03-render (second tree))
                 (v03-render (third tree))))
        (t (format nil "(~A ~A ~A)" (v03-render (second tree))
                   (ecase (first tree) (:lt "<") (:add "+") (:sub "-") (:mul "*") (:div "/") (:rem "%"))
                   (v03-render (third tree))))))
(deftest v03-generated-oracle
  (let ((seed 314159265) (successes 0) (failures 0))
    (labels ((next (n) (setf seed (mod (+ (* seed 1664525) 1013904223) 4294967296))
                       (mod (ash seed -8) n))
             (leaf () (nth (next 10) (list :x 0 1 -1 2 -7 13 97
                                           (- (expt 2 63)) (1- (expt 2 63)))))
             (tree (depth)
               (if (zerop depth) (leaf)
                   (case (next 8)
                     (0 (list :if (list :lt (tree (1- depth)) (tree (1- depth)))
                              (tree (1- depth)) (tree (1- depth))))
                     (1 (list :update (tree (1- depth)) (tree (1- depth))))
                     (2 (leaf))
                     (otherwise (list (nth (next 5) '(:add :sub :mul :div :rem))
                                      (tree (1- depth)) (tree (1- depth))))))))
      (dotimes (i 128)
        (let* ((initial (- (next 15) 7)) (tree (tree 3)) (state (list initial))
               (expected (catch 'oracle-failure (list (v03-oracle tree state) (car state))))
               (source
                 (format nil "var x = ~D; let outcome = ~A; ~A" initial (v03-render tree)
                   (if (listp expected)
                       (format nil "if(outcome == ~D){x == ~D}else{false}" (first expected) (second expected))
                       "true"))))
          (handler-case
              (if (listp expected) (progn (incf successes) (v03-positive source :true))
                  (progn (incf failures) (v03-runtime source expected)))
            (error (c) (error "seed=314159265 depth=3 sample=~D input=~A: ~A" i source c)))))
      (is (plusp successes)) (is (plusp failures)))))
