(in-package #:mognitio.tests)

(deftest v04-checked-and-ir-boundaries
  (dolist (mutation
            (list
             (lambda (c) (clrhash (mognitio.semantic::checked-program-summaries c)))
             (lambda (c) (clrhash (mognitio.semantic::checked-program-calls c)))
             (lambda (c) (clrhash (mognitio.semantic::checked-program-returns c)))
             (lambda (c) (setf (local-symbol-owner (aref (checked-program-bindings c) 0)) 0))
             (lambda (c) (setf (mognitio.semantic::local-symbol-type (aref (checked-program-bindings c) 0)) nil))
             (lambda (c) (setf (signature-id (aref (checked-program-signatures c) 1)) 99))))
    (let ((checked (check-program (parse-text "function f(x: int): int { return x; } f(1) == 1"))))
      (funcall mutation checked)
      (signals internal-failure (compile-program checked))
      (signals internal-failure (mognitio.ir:lower-program checked))))
  (dolist (mutation
            (list (lambda (call function) (declare (ignore function)) (setf (mognitio.ir:instruction-value call) 99))
                  (lambda (call function) (declare (ignore function)) (setf (mognitio.ir:instruction-operands call) nil))
                  (lambda (call function) (declare (ignore function)) (setf (mognitio.ir:instruction-type call) :bool))
                  (lambda (call function) (declare (ignore call)) (setf (mognitio.ir:ir-function-parameter-types function) '(:bool)))))
    (let* ((module (native-ir "function f(x: int): int { x } f(1) == 1"))
           (call (find :call (mognitio.ir:basic-block-instructions (first (entry-blocks module)))
                       :key #'mognitio.ir:instruction-op)))
      (funcall mutation call (second (mognitio.ir:module-functions module)))
      (signals internal-failure (mognitio.ir:verify-module module))))
  ;; Callee is changed to call itself while retaining a valid typed SSA graph.
  (let* ((module (native-ir "function f(x: int): int { x + 1 } f(1) == 2"))
         (function (second (mognitio.ir:module-functions module)))
         (block (first (mognitio.ir:ir-function-blocks function)))
         (inst (find :add (mognitio.ir:basic-block-instructions block) :key #'mognitio.ir:instruction-op)))
    (setf (mognitio.ir:instruction-op inst) :call (mognitio.ir:instruction-value inst) 1
          (mognitio.ir:instruction-operands inst) '(0))
    (signals internal-failure (mognitio.ir:verify-module module))))

(deftest v04-call-barriers-and-pressure
  (let* ((module (native-ir "function f(x: int): int { x + 1 } let a = 5; a + f(2) == 8"))
         (allocation (mognitio.regalloc:allocate-function (first (mognitio.ir:module-functions module))))
         (locations (mognitio.regalloc:allocation-locations allocation)))
    (is (integerp (gethash 0 locations)))
    (setf (gethash 0 locations) :r8)
    (signals internal-failure (mognitio.regalloc:verify-allocation allocation)))
  (v03-positive
   (with-output-to-string (out)
     (write-string "function smash(a: int, b: int, c: int, d: int, e: int, f: int, g: int, h: int): int { a + b + c + d + e + f + g + h } " out)
     (write-string "function repeat(x: int): int { x + smash(x, x + 1, x + 2, x + 3, x + 4, x + 5, x + 6, x + 7) + x } " out)
     (dotimes (i 32) (format out "let x~D = ~D; " i i))
     (write-string "let n = repeat(3) + repeat(7); " out)
     (dotimes (i 32) (format out "x~D + " i))
     (write-string "n == 652" out)) :true)
  (v03-positive "function pack(a: int, b: int): int { a * 10 + b } function inc(x: int): int { x + 1 } pack(inc(2), inc(inc(4))) == 36" :true))

(deftest v04-handwritten-abi
  ;; This caller and callee do not use source lowering or allocation. Assert
  ;; alignment, argument offsets, register clobbers and RSP/RBP after each call.
  (let* ((forms
           '((:align-stack) (:clear-frame) (:call (:function 0)) (:mov-eax 60) (:syscall) (:ud2)
             (:label (:function 0)) (:push-rbp) (:mov-reg :rbp :rsp)
             (:push-zero) (:push-zero) (:push-zero) (:push-zero)
             (:store-frame -8 :rsp) (:store-frame -16 :rbp)
             (:imm-rax -9223372036854775808) (:store-out 0 :rax)
             (:imm-rax 1) (:store-out 8 :rax)
             (:call (:function 1)) (:imm-rcx -9223372036854775808) (:cmp) (:jnz :bad)
             (:mov-reg :rax :rsp) (:load-frame :rcx -8) (:cmp) (:jnz :bad)
             (:mov-reg :rax :rbp) (:load-frame :rcx -16) (:cmp) (:jnz :bad)
             (:call (:function 1)) (:imm-rcx -9223372036854775808) (:cmp) (:jnz :bad)
             (:mov-reg :rax :rsp) (:load-frame :rcx -8) (:cmp) (:jnz :bad)
             (:mov-reg :rax :rbp) (:load-frame :rcx -16) (:cmp) (:jnz :bad)
             (:mov-edi 0) (:mov-reg :rsp :rbp) (:pop-rbp) (:ret)
             (:label (:function 1)) (:push-rbp) (:mov-reg :rbp :rsp)
             (:mov-reg :rax :rsp) (:imm-rcx 16) (:cqo) (:idiv)
             (:mov-rax-rdx) (:test) (:jnz :bad)
             (:load-frame :rax 24) (:imm-rcx 1) (:cmp) (:jnz :bad)
             (:imm-rax 99) (:mov-reg :r8 :rax) (:mov-reg :r9 :rax)
             (:mov-reg :r10 :rax) (:mov-reg :r11 :rax)
             (:load-frame :rax 16) (:mov-reg :rsp :rbp) (:pop-rbp) (:ret)
             (:label :bad) (:mov-edi 99) (:mov-eax 60) (:syscall) (:ud2)))
         (image (mognitio.elf:make-image (mognitio.amd64:encode (apply #'machine forms))))
         (path (put-bytes (fresh-path ".elf") image)))
    (sb-posix:chmod (namestring path) #o700)
    (multiple-value-bind (out err code) (process-result (list (namestring path)))
      (same 0 code) (same "" out) (same "" err))))

(deftest v04-large-argument-frame-and-host-symbols
  (v03-positive
   (with-output-to-string (out)
     (write-string "function many(" out)
     (dotimes (i 600) (when (plusp i) (write-string ", " out)) (format out "a~D: int" i))
     (write-string "): bool { a0 + a599 == 599 } many(" out)
     (dotimes (i 600) (when (plusp i) (write-string ", " out)) (format out "~D" i))
     (write-string ")" out)) :true)
  (let* ((checked (check-program (parse-text "function f(x: int): int { return x; } function g(x: int): int { return f(x); } let x = 5; g(x) == 5")))
         (form (mognitio.backend.cl::program-form checked))
         (definitions (second form))
         (names (mapcar #'first definitions))
         (blocks (mapcar (lambda (definition) (second (third definition))) definitions)))
    (same 'cl:labels (first form))
    (same (list 'cl:declare (cons 'cl:notinline names)) (third form))
    (same 'cl:let (first (fourth form)))
    (dolist (symbol (append names blocks)) (is (null (symbol-package symbol))))
    (is (not (eq (first blocks) (second blocks))))
    (loop for definition in definitions for block in blocks do
      (same 'cl:block (first (third definition)))
      (same 'cl:return-from (first (third (third definition))))
      (same block (second (third (third definition)))))))
