(in-package #:mognitio.tests)

(deftest v04-allocation-and-copy-invariants
  ;; Simultaneous expected tuples are compared to the sequential copy schedule.
  (dolist (locations '((:r8 :r9) (:r8 :r9 :r10) (-8 -16 -24) (:r8 -8 :r10 -16)))
    (dotimes (shift (length locations))
      (let* ((sources (append (nthcdr shift locations) (subseq locations 0 shift)))
             (copies (mapcar #'cons locations sources)) (state (make-hash-table)))
        (loop for location in locations for value from 10 do (setf (gethash location state) value))
        (let ((expected (mapcar (lambda (source) (gethash source state)) sources)))
          (dolist (move (mognitio.regalloc:parallel-copies copies -800))
            (setf (gethash (car move) state) (gethash (cdr move) state)))
          (same expected (mapcar (lambda (location) (gethash location state)) locations))))))
  (signals internal-failure (mognitio.regalloc:parallel-copies '((:r8 . :r9)) :r8))
  (signals internal-failure (mognitio.regalloc:parallel-copies '((:r8 . :r9) (:r8 . :r10)) -8))
  (let* ((function (first (mognitio.ir:module-functions (native-ir "let a = 1; let b = 2; a + b == 3"))))
         (allocation (mognitio.regalloc:allocate-function function)))
    (same '((0 3 7) (1 6 7) (2 9 13) (3 12 13) (4 15 16))
          (mapcar (lambda (i) (list (mognitio.regalloc:interval-id i)
                                    (mognitio.regalloc:interval-start i)
                                    (mognitio.regalloc:interval-end i)))
                  (mognitio.regalloc:allocation-intervals allocation)))
    (same 0 (mognitio.regalloc:allocation-spill-count allocation))
    (setf (gethash 0 (mognitio.regalloc:allocation-locations allocation)) :r8
          (gethash 1 (mognitio.regalloc:allocation-locations allocation)) :r8)
    (signals internal-failure (mognitio.regalloc:verify-allocation allocation)))
  ;; Every binding is live at the final sum, forcing a frame larger than a page.
  (let* ((text (with-output-to-string (out)
                 (dotimes (i 600) (format out "let x~D = ~D; " i i))
                 (dotimes (i 600) (when (plusp i) (write-string " + " out)) (format out "x~D" i))
                 (write-string " == 179700" out)))
         (function (first (mognitio.ir:module-functions (native-ir text))))
         (allocation (mognitio.regalloc:allocate-function function)))
    (is (> (* 8 (mognitio.regalloc:allocation-spill-count allocation)) 4096))
    (v03-positive text :true))
  (v03-positive "var a = 1; var b = 2; let x = branch when{(true)=>{let tmp = a; a = b; b = tmp; 3},else=>{4}}; a * 10 + b == 21" :true))
