(in-package #:mognitio.tests)

;; Independent test trees, environments and lexical return targets. No production
;; AST, completion, arithmetic, SSA or register-allocation code is used by the oracle.
(defun v04-math (op a b)
  (labels ((bound (n)
             (unless (<= (- (expt 2 63)) n (1- (expt 2 63)))
               (throw 'v04-failure "integer overflow")) n))
    (case op
      (:add (bound (+ a b))) (:sub (bound (- a b))) (:mul (bound (* a b)))
      (:lt (< a b))
      ((:div :rem)
       (when (zerop b) (throw 'v04-failure (if (eq op :div) "division by zero" "remainder by zero")))
       (when (and (= a (- (expt 2 63))) (= b -1)) (throw 'v04-failure "integer overflow"))
       (let* ((magnitude (floor (abs a) (abs b)))
              (quotient (if (eq (minusp a) (minusp b)) magnitude (- magnitude))))
         (if (eq op :div) quotient (- a (* quotient b)))))
      (otherwise (error "Invalid oracle operation")))))

(defun v04-evaluate (tree functions environment return-target)
  (labels ((ev (child) (v04-evaluate child functions environment return-target)))
    (cond ((integerp tree) tree)
          ((member tree '(:n :flag :x)) (gethash tree environment))
          ((eq tree :true) t) ((eq tree :false) nil)
          (t (case (first tree)
               (:call
                (let* ((n (ev (third tree))) (flag (ev (fourth tree)))
                       (callee-env (make-hash-table)) (callee-return (gensym)))
                  (setf (gethash :n callee-env) n (gethash :x callee-env) n (gethash :flag callee-env) flag)
                  (catch callee-return
                    (v04-evaluate (aref functions (second tree)) functions callee-env callee-return))))
               (:if (if (ev (second tree)) (ev (third tree)) (ev (fourth tree))))
               (:early (if (ev (second tree)) (throw return-target (ev (third tree))) (ev (fourth tree))))
               (:update (setf (gethash :x environment) (ev (second tree))) (ev (third tree)))
               (otherwise
                (let* ((a (ev (second tree))) (b (ev (third tree))))
                  (v04-math (first tree) a b))))))))

(defun v04-render (tree)
  (cond ((integerp tree) (if (minusp tree) (format nil "(~D)" tree) (format nil "~D" tree)))
        ((keywordp tree) (string-downcase (symbol-name tree)))
        (t (case (first tree)
             (:call (format nil "f~D(~A, ~A)" (second tree) (v04-render (third tree)) (v04-render (fourth tree))))
             (:if (format nil "branch when{(~A)=>{~A},else=>{~A}}" (v04-render (second tree))
                          (v04-render (third tree)) (v04-render (fourth tree))))
             (:early (format nil "branch when{(~A)=>{return ~A;},else=>{~A}}" (v04-render (second tree))
                             (v04-render (third tree)) (v04-render (fourth tree))))
             (:update (format nil "branch when{(true)=>{x = ~A; ~A},else=>{0}}" (v04-render (second tree)) (v04-render (third tree))))
             (otherwise (format nil "(~A ~A ~A)" (v04-render (second tree))
                          (ecase (first tree) (:add "+") (:sub "-") (:mul "*") (:div "/") (:rem "%") (:lt "<"))
                          (v04-render (third tree))))))))

(deftest v04-generated-independent-oracle
  (let ((state 20260916) (successes 0) (failures 0))
    (labels ((next (n) (setf state (mod (+ (* state 1664525) 1013904223) 4294967296))
                       (mod (ash state -8) n))
             (leaf () (nth (next 10) (list :n :x 0 1 -1 2 7 -9 (- (expt 2 63)) (1- (expt 2 63)))))
             (boolean-tree (owner depth)
               (if (or (zerop depth) (zerop (next 2))) (nth (next 3) '(:true :false :flag))
                   (list :lt (tree owner (1- depth)) (tree owner (1- depth)))))
             (tree (owner depth)
               (if (zerop depth) (leaf)
                   (case (next 8)
                     (0 (leaf))
                     (1 (if (= owner 3) (leaf)
                            (list :call (+ owner 1 (next (- 3 owner)))
                                  (tree owner (1- depth)) (boolean-tree owner (1- depth)))))
                     ((2 3) (list (if (zerop (next 2)) :early :if)
                                  (boolean-tree owner (1- depth))
                                  (tree owner (1- depth)) (tree owner (1- depth))))
                     (4 (list :update (tree owner (1- depth)) (tree owner (1- depth))))
                     (otherwise (list (nth (next 5) '(:add :sub :mul :div :rem))
                                      (tree owner (1- depth)) (tree owner (1- depth))))))))
      (dotimes (sample 128)
        (let* ((functions (make-array 4)) (initial (- (next 19) 9)))
          (dotimes (id 4) (setf (aref functions id) (list :add (tree id 3) :x)))
          (let* ((entry (list :add (list :call 0 initial :true) (list :call 0 (+ initial 1) :false)))
                 (expected (catch 'v04-failure (list (v04-evaluate entry functions (make-hash-table) nil))))
                 (source
                   (with-output-to-string (out)
                     (dolist (id '(3 2 1 0))
                       (format out "let f~D = function(n: int, flag: bool): int { var x = n; ~A }; " id (v04-render (aref functions id))))
                     (format out "let result = ~A; ~A" (v04-render entry)
                             (if (listp expected) (format nil "result == ~D" (first expected)) "true")))))
            (handler-case
                (if (listp expected) (progn (incf successes) (v03-positive source :true))
                    (progn (incf failures) (v03-runtime source expected)))
              (error (condition)
                (error "seed=20260916 depth=3 sample=~D source=~A: ~A" sample source condition))))))
      (is (plusp successes)) (is (plusp failures)))))
