(in-package #:mognitio.tests)

;; Test-only trees, mutable cells and explicit completion records. Neither
;; backend nor the production AST, flow analysis or arithmetic is an oracle.
(defun v05-evaluate (tree functions environment owner)
  (labels ((normal (value) (list :normal value))
           (ev (node) (v05-evaluate node functions environment owner))
           (value (result) (second result))
           (complete-p (result) (eq (first result) :normal)))
    (case (first tree)
      (:literal (normal (second tree)))
      (:function (normal (list :function (second tree))))
      (:name (normal (cdr (assoc (second tree) environment))))
      (:set
       (let ((result (ev (third tree))))
         (if (complete-p result) (progn (setf (cdr (assoc (second tree) environment)) (value result)) (normal :void)) result)))
      (:sequence
       (dolist (statement (second tree))
         (if (eq (first statement) :let)
             (let ((result (ev (third statement))))
               (unless (complete-p result) (return-from v05-evaluate result))
               (push (cons (second statement) (value result)) environment))
             (let ((result (ev statement)))
               (unless (complete-p result) (return-from v05-evaluate result)))))
       (if (third tree) (ev (third tree)) (normal :void)))
      (:if
       (let ((test (ev (second tree))))
         (if (complete-p test) (ev (if (eq (value test) :true) (third tree) (fourth tree))) test)))
      (:binary
       (let* ((left (ev (third tree))) (right (when (complete-p left) (ev (fourth tree)))))
         (cond ((not (complete-p left)) left) ((not (complete-p right)) right)
               (t (normal (case (second tree)
                            (:eq (if (equal (value left) (value right)) :true :false))
                            (:lt (if (< (value left) (value right)) :true :false))
                            (otherwise (v04-math (second tree) (value left) (value right)))))))))
      (:call
       (let ((callee (ev (second tree))) (arguments nil))
         (unless (complete-p callee) (return-from v05-evaluate callee))
         (dolist (argument (third tree))
           (let ((result (ev argument)))
             (unless (complete-p result) (return-from v05-evaluate result))
             (push (value result) arguments)))
         (let* ((id (second (value callee))) (function (aref functions id))
                (result (v05-evaluate (second function) functions
                                     (mapcar #'cons (first function) (nreverse arguments)) id)))
           (if (and (eq (first result) :return) (= id (second result))) (normal (third result)) result))))
      (:return
       (let ((result (ev (second tree))))
         (if (complete-p result) (list :return owner (value result)) result)))
      (:break
       (let ((result (if (third tree) (ev (third tree)) (normal :void))))
         (if (complete-p result) (list :break (second tree) (value result)) result)))
      (:continue (list :continue (second tree)))
      (:loop
       (loop for iteration from 0 below 9 do
         (let ((condition (if (third tree) (ev (third tree)) (normal :true))))
           (case (first condition)
             (:break (return-from v05-evaluate (if (eql (second condition) (second tree)) (normal (third condition)) condition)))
             (:return (return-from v05-evaluate condition))
             (:continue (unless (eql (second condition) (second tree)) (return-from v05-evaluate condition)))
             (:normal
              (when (eq (value condition) :false) (return-from v05-evaluate (normal :void)))
              (let ((result (ev (fourth tree))))
                (case (first result)
                  (:break (if (eql (second result) (second tree)) (return-from v05-evaluate (normal (third result)))
                              (return-from v05-evaluate result)))
                  (:continue (unless (eql (second result) (second tree)) (return-from v05-evaluate result)))
                  (:return (return-from v05-evaluate result)))))))
         finally (error "Generated loop exceeded its independent bound")))
      (otherwise (error "Unknown oracle node: ~S" tree)))))

(defun v05-render (tree)
  (labels ((render (node) (v05-render node)))
    (case (first tree)
      (:literal (if (integerp (second tree)) (format nil "(~D)" (second tree))
                    (string-downcase (second tree))))
      (:function (format nil "f~D" (second tree)))
      (:name (string-downcase (second tree)))
      (:set (format nil "~(~A~) = ~A;" (second tree) (render (third tree))))
      (:let (format nil "var ~(~A~): ~(~A~) = ~A;" (second tree) (fourth tree) (render (third tree))))
      (:sequence
       (with-output-to-string (out)
         (write-string "{" out)
         (dolist (statement (second tree))
           (write-string (render statement) out)
           (unless (member (first statement) '(:let :set :return :break :continue)) (write-string ";" out)))
         (when (third tree) (write-string (render (third tree)) out))
         (write-string "}" out)))
      (:if (format nil "branch when{(~A)=>{~A},else=>{~A}}" (render (second tree)) (render (third tree)) (render (fourth tree))))
      (:binary (format nil "(~A ~A ~A)" (render (third tree))
                       (ecase (second tree) (:add "+") (:sub "-") (:mul "*") (:div "/") (:rem "%") (:eq "==") (:lt "<"))
                       (render (fourth tree))))
      (:call (format nil "(~A)(~{~A~^,~})" (render (second tree)) (mapcar #'render (third tree))))
      (:return (format nil "return ~A;" (render (second tree))))
      (:break (format nil "break~A;" (if (third tree) (concatenate 'string " " (render (third tree))) "")))
      (:continue "continue;")
      (:loop (format nil "loop~A ~A" (if (third tree) (format nil " while(~A)" (render (third tree))) "")
                     (render (fourth tree))))
      (otherwise (error "Unknown renderer node")))))

(deftest v05-generated-control-oracle
  (let ((state 20260920) (normal-count 0) (failure-count 0))
    (labels ((next (n) (setf state (mod (+ (* state 1664525) 1013904223) 4294967296)) (mod (ash state -8) n))
             (lit (value) (list :literal value))
             (name (key) (list :name key))
             (binary (op a b) (list :binary op a b))
             (seq (statements &optional tail) (list :sequence statements tail))
             (call (id args) (list :call (list :function id) args))
             (expression (depth)
               (if (zerop depth) (if (zerop (next 2)) (name :i) (lit (- (next 9) 4)))
                   (case (next 4)
                     (0 (call 2 (list (expression (1- depth)))))
                     (1 (list :if (name :flip) (expression (1- depth)) (expression (1- depth))))
                     (otherwise (binary (nth (next 3) '(:add :sub :mul)) (expression (1- depth)) (expression (1- depth))))))))
      (dotimes (sample 128)
        (let* ((limit (1+ (next 8))) (conditional (zerop (next 2))) (early (zerop (next 3)))
               (functions (make-array 4))
               (right (seq (list (list :set :flip (list :if (name :flip) (lit :false) (lit :true))))
                           (call 2 (list (expression 4)))))
               (selected (list :if (name :flip) (list :function 0) (list :function 1)))
               (compute (list :call selected (list (call 2 (list (binary :add (name :base) (name :i)))) right)))
               (body (seq (append
                           (list (list :set :i (binary :add (name :i) (lit 1))))
                           (when (zerop (mod sample 3))
                             (list (list :if (binary :lt (name :i) (lit limit))
                                         (seq (list (list :continue 0))) (seq nil))))
                           (list (list :set :total (binary :add (name :total) compute)))
                           (when early
                             (list (list :if (binary :eq (name :i) (lit limit))
                                         (seq (list (list :return (name :total)))) (seq nil))))
                           (unless conditional
                             (list (list :if (binary :eq (name :i) (lit limit))
                                         (seq (list (list :break 0 (name :total)))) (seq nil)))))))
               (loop-node (list :loop 0 (when conditional (binary :lt (name :i) (lit limit))) body))
               (worker (seq (list (list :let :base (lit (if (zerop (mod sample 11)) (1- (expt 2 63)) (- (next 19) 9))) :int)
                                  (list :let :i (lit 0) :int) (list :let :total (lit 0) :int) (list :let :flip (lit :true) :bool))
                            (if conditional (seq (list loop-node) (name :total)) loop-node))))
          (setf (aref functions 0) (list '(:left :right) (binary :add (name :left) (name :right)))
                (aref functions 1) (list '(:left :right) (binary :sub (name :left) (name :right)))
                (aref functions 2) (list '(:value) (name :value))
                (aref functions 3) (list nil worker))
          (let* ((entry (call 3 nil))
                 (expected (catch 'v04-failure (v05-evaluate entry functions nil nil)))
                 (source
                   (with-output-to-string (out)
                     (loop for fn across functions for id from 0 do
                       (format out "let f~D:function(~{~A~^,~}):int=function(~{~A~^,~}): int {~A}; " id
                               (mapcar (constantly "int") (first fn))
                               (mapcar (lambda (p) (format nil "~(~A~): int" p)) (first fn))
                               (v05-render (second fn))))
                     (format out "let result: int = ~A; ~A" (v05-render entry)
                             (if (stringp expected) "true" (format nil "result == (~D)" (second expected)))))))
            (handler-case
                (if (stringp expected) (progn (incf failure-count) (v03-runtime source expected))
                    (progn (same :normal (first expected)) (incf normal-count) (v03-positive source :true)))
              (error (condition) (error "seed=20260920 sample=~D expected=~S source=~A: ~A" sample expected source condition))))))
      (is (plusp normal-count)) (is (plusp failure-count)))))
