(in-package #:mognitio.tests)

(deftest v06-native-encoding-and-literals
  (same :mognitio-internal-v3 (mognitio.target:target-abi (mognitio.target:linux-amd64)))
  (dolist (pair '(((:load-word :rax :r15 0) "498b8700000000")
                  ((:store-word :r15 0 :rax) "49898700000000")
                  ((:lea-base :rax :rbp -40) "488d85d8ffffff")
                  ((:load-byte :r9 :r12 1) "450fb68c2401000000")
                  ((:store-byte :r13 2 :rdi) "4188bd02000000")
                  ((:add-imm :rdx 8) "4881c208000000")
                  ((:cmp-imm :rax 6) "4881f806000000")))
    (same (hex-bytes (second pair)) (mognitio.amd64:encode (machine (first pair)))))
  (same #(1 0 0 0 0 0 0 0 2) (mognitio.amd64:encode (machine '(:bytes 1) '(:align 8) '(:bytes 2))))
  (let* ((module (native-ir "let a=\"A\\0日\"; true"))
         (code (mognitio.machine:lower-module module)))
    (multiple-value-bind (bytes labels) (mognitio.amd64:encode code)
      (dolist (id '(0 1))
        (let ((offset (mognitio.object:image-symbol-offset (gethash (list :text id) labels))))
          (same 0 (mod offset 8))
          (same (if (zerop id) 32 40) (image-integer bytes offset 8))
          (same 5 (image-integer bytes (+ offset 8) 8))
          (same (if (zerop id) 0 5) (image-integer bytes (+ offset 16) 8))
          (same (if (zerop id) 0 3) (image-integer bytes (+ offset 24) 8))
          (when (= id 1) (same #(65 0 230 151 165 0 0 0) (subseq bytes (+ offset 32) (+ offset 40))))))
      (same bytes (mognitio.amd64:encode (mognitio.machine:lower-module (native-ir "let a=\"A\\0日\"; true"))))))
  (dolist (forms '(((:lea-text (:function 1)) (:label (:function 1)) (:ret))
                  ((:call (:text 0)) (:label (:text 0)) (:bytes 0))
                  ((:jb (:text 0)) (:label (:text 0)) (:bytes 0))
                  ((:align 3)) ((:load-word :rax :r16 0)) ((:load-byte :rax :r15 2147483648))))
    (signals internal-failure (mognitio.amd64:encode (apply #'machine forms)))))

(defun v06-frame-capture (source)
  (let ((original (fdefinition 'mognitio.frame:verify-sections)) (capture nil))
    (replacing (mognitio.frame:verify-sections
                 (lambda (&rest arguments) (push arguments capture) (apply original arguments)))
      (mognitio.machine:lower-module (native-ir source)))
    (reverse capture)))

(deftest v06-native-frame-verifier-negatives
  (let ((source "let f=function(s:string):string{s}; let x=f(\"x\"); let y=f(x); true"))
    (dolist (mutation '(:reserve-size :missing-root :wrong-home :before-call :no-clear :no-unlink :clobber-result :overlap :missing-site :extra-call))
      (destructuring-bind (function allocation roots layout sections body) (first (v06-frame-capture source))
        (let* ((publication (find :publish sections :key #'first))
               (unlink (find :unlink sections :key #'first)))
          (flet ((replace-section (section forms)
                   (setf (third section) forms)
                   (replace body forms :start1 (fourth section))))
            (ecase mutation
              (:reserve-size (let* ((section (find :reserve sections :key #'first)) (forms (copy-tree (third section))))
                               (setf (second (first forms)) 1) (replace-section section forms)))
              (:missing-root (replace-section publication (append (subseq (third publication) 0 2) '((:imm-rax 0) (:store-frame -32 :rax)))))
              (:wrong-home (let ((forms (copy-tree (third publication))))
                             (setf (third forms) '(:mov-reg :rax :r11)) (replace-section publication forms)))
              (:before-call (let ((forms (copy-tree (third publication))))
                              (setf (first forms) '(:call (:function 1))) (replace-section publication forms)))
              (:no-clear (let ((forms (copy-tree (third publication))))
                           (setf (first forms) '(:imm-rax 99)) (replace-section publication forms)))
              (:no-unlink (setf sections (remove unlink sections)))
              (:clobber-result (replace-section unlink (list (list :load-frame :rax (mognitio.frame:layout-root-offset layout)) '(:store-word :r15 0 :rax))))
              (:overlap (setf (mognitio.frame:layout-root-offset layout) (mognitio.frame:layout-temporary layout)))
              (:missing-site (setf sections (remove publication sections)))
              (:extra-call (setf (first body) '(:call (:function 1))))))
          (signals internal-failure (mognitio.frame:verify-sections function allocation roots layout sections body)))))))

(defun v06-abi-bad () '((:label :bad) (:mov-edi 99) (:mov-eax 60) (:syscall) (:ud2)))
(deftest v06-generated-caller-handwritten-text-callee
  (let ((source "let probe=function(s:string,v:void,n:int,b:bool):string{s}; let r=probe(\"a\",void,7,true); let z=probe(r,void,7,true); true")
        (callee (append
          '((:label (:function 1)) (:push-rbp) (:mov-reg :rbp :rsp)
            (:mov-reg :rax :rsp) (:imm-rcx 16) (:cqo) (:idiv) (:mov-rax-rdx) (:test) (:jnz :bad)
            (:load-frame :rax 24) (:test) (:jnz :bad)
            (:load-frame :rax 32) (:imm-rcx 7) (:cmp) (:jnz :bad)
            (:load-frame :rax 40) (:imm-rcx 1) (:cmp) (:jnz :bad)
            (:load-word :rcx :r15 0) (:mov-reg :rax :rcx) (:test) (:jz :bad)
            (:load-word :rax :rcx 0) (:test) (:jnz :bad)
            (:load-word :rax :rcx 8) (:cmp-imm :rax 1) (:jnz :bad)
            (:load-word :rax :rcx 16) (:load-frame :rcx 16) (:cmp) (:jnz :bad)
            (:load-word :rax :r15 16) (:test) (:jle :bad)
            (:imm-rax 99) (:mov-reg :r8 :rax) (:mov-reg :r9 :rax) (:mov-reg :r10 :rax) (:mov-reg :r11 :rax)
            (:mov-reg :rcx :rax) (:mov-reg :rdx :rax) (:mov-reg :rsi :rax) (:mov-reg :rdi :rax)
            (:load-frame :rax 16) (:mov-reg :rsp :rbp) (:pop-rbp) (:ret)) (v06-abi-bad))))
    (multiple-value-bind (out err code) (v05-cross-abi source 1 callee)
      (same 0 code) (same (format nil "true~%") out) (same "" err))))

(deftest v06-handwritten-caller-generated-text-callee
  (let* ((source "let probe=function(s:string,v:void,n:int,b:bool):string{s}; let unused=\"a\"; true")
         (caller (append
           '((:label (:function 0)) (:push-rbp) (:mov-reg :rbp :rsp))
           (loop repeat 12 collect '(:push-zero))
           '((:store-frame -8 :r15) (:store-frame -16 :rsp)
             (:lea-text (:text 1)) (:store-frame -32 :rax)
             (:imm-rax 1) (:store-frame -40 :rax) (:lea-base :rax :rbp -48) (:store-word :r15 0 :rax)
             (:imm-rax 50) (:store-frame -24 :rax) (:label :again)
             (:lea-text (:text 1)) (:store-out 0 :rax) (:imm-rax 0) (:store-out 8 :rax)
             (:imm-rax 7) (:store-out 16 :rax) (:imm-rax 1) (:store-out 24 :rax)
             (:call (:function 1)) (:mov-reg :rdx :rax) (:lea-text (:text 1)) (:cmp-rax-rdx) (:jnz :bad)
             (:mov-reg :rax :r15) (:load-frame :rcx -8) (:cmp) (:jnz :bad)
             (:mov-reg :rax :rsp) (:load-frame :rcx -16) (:cmp) (:jnz :bad)
             (:load-word :rdx :r15 0) (:lea-base :rax :rbp -48) (:cmp-rax-rdx) (:jnz :bad)
             (:load-frame :rax -24) (:imm-rcx 1) (:sub) (:store-frame -24 :rax) (:test) (:jnz :again)
             (:imm-rax 0) (:store-word :r15 0 :rax)
             (:imm-rax 1) (:mov-reg :rsp :rbp) (:pop-rbp) (:ret)) (v06-abi-bad))))
    (multiple-value-bind (out err code) (v05-cross-abi source 0 caller)
      (same 0 code) (same (format nil "true~%") out) (same "" err))
    (multiple-value-bind (out err code)
        (v05-cross-abi source 0 caller
          (lambda (forms) (remove '(:store-word :r15 0 :rcx) forms :test #'equal)))
      (same 99 code) (same "" out) (same "" err))))

(defun v06-abi-helper-unit (op)
  ;; These probes deliberately do not implement text semantics or collection.
  ;; They check roots at the helper boundary and return an existing argument.
  (let ((forms (append
    (list (list :label (list :helper op)))
    '((:push-rbp) (:mov-reg :rbp :rsp)
      (:load-word :rcx :r15 0) (:mov-reg :rax :rcx) (:test) (:jz :abi-helper-bad)
      (:load-word :rax :rcx 8) (:cmp-imm :rax 2) (:jnz :abi-helper-bad))
    (unless (eq op :text.length)
      '((:load-word :rax :rcx 16) (:load-frame :rdx 16) (:cmp-rax-rdx) (:jnz :abi-helper-bad)))
    (case op
      (:text.concat '((:load-word :rax :rcx 24) (:load-frame :rdx 24) (:cmp-rax-rdx) (:jnz :abi-helper-bad)))
      (:text.slice '((:load-word :rax :rcx 24) (:test) (:jnz :abi-helper-bad))))
    '((:imm-rax 99) (:mov-reg :r8 :rax) (:mov-reg :r9 :rax) (:mov-reg :r10 :rax) (:mov-reg :r11 :rax))
    (if (eq op :text.length) '((:imm-rax 1)) '((:load-frame :rax 16)))
    '((:mov-reg :rsp :rbp) (:pop-rbp) (:ret)))))
    (mognitio.object:make-code-unit :owner op :entry (list :helper op) :instructions (apply #'machine forms))))

(deftest v06-native-helper-publication-and-loop
  (let* ((source "let identity=function(s:string):string{s}; var keep=\"a\"; var i=0; loop while(i<100){let temp=keep+\"b\"; let n=temp->length(); keep=keep->slice(0,1); keep=identity(keep); i=i+1;}; true")
         (module (native-ir source)) (units nil) code)
    (replacing (mognitio.native.runtime:text-helper-units
                 (lambda (operations literal-count)
                   (declare (ignore literal-count))
                   (setf units (mapcar #'v06-abi-helper-unit operations))
                   (append units (list (mognitio.object:make-code-unit :owner :probe-failure
                     :instructions (machine '(:label :abi-helper-bad) '(:mov-edi 98) '(:mov-eax 60) '(:syscall) '(:ud2)))))))
      (setf code (mognitio.machine:lower-module module)))
    (same 3 (length units))
    (let ((path (put-bytes (fresh-path ".elf") (mognitio.elf:make-image (mognitio.amd64:encode code)))))
      (sb-posix:chmod (namestring path) #o700)
      (multiple-value-bind (out err status) (process-result (list (namestring path)))
        (same 0 status) (same (format nil "true~%") out) (same "" err)))
    ;; Production uses the real runtime, independently exercised in GC tests.
    (is (mognitio.machine:lower-module module))))

(deftest v06-native-context-pagesize
  (multiple-value-bind (out err status)
      (process-result (list "python3" "-c" "import os; print(os.sysconf('SC_PAGE_SIZE'))"))
    (same 0 status) (same "" err)
    (let ((callee (append
                  `((:label (:function 1)) (:load-word :rax :r15 16) (:imm-rcx ,(parse-integer out))
                    (:cmp) (:jnz :bad) (:load-word :rax :r15 8) (:test) (:jnz :bad)
                    (:load-word :rcx :r15 0) (:mov-reg :rax :rcx) (:test) (:jz :bad)
                    (:load-word :rax :rcx 0) (:test) (:jnz :bad)
                    (:load-word :rax :rcx 8) (:test) (:jnz :bad)
                    (:imm-rax 1) (:ret)) (v06-abi-bad))))
      (multiple-value-bind (out err code)
          (v05-cross-abi "let probe=function():bool{true}; probe()" 1 callee)
        (same 0 code) (same (format nil "true~%") out) (same "" err)))))

(deftest v06-native-frame-unsectioned-context-writes
  (dolist (op '(:load-frame :store-byte))
    (destructuring-bind (function allocation roots layout sections body)
        (first (v06-frame-capture "true"))
      (let ((index (position '(:imm-rax 1) body :test #'equal)))
        (is index)
        (is (notany (lambda (section)
                      (<= (fourth section) index
                          (1- (+ (fourth section) (length (third section)))))) sections))
        (setf (nth index body)
              (if (eq op :load-frame)
                  (list :load-frame :r15 (mognitio.frame:layout-temporary layout))
                  '(:store-byte :r15 0 :rax)))
        (signals internal-failure
          (mognitio.frame:verify-sections function allocation roots layout sections body))))))

(deftest v06-native-frame-runtime-register-writers
  (dolist (form '((:imm-reg :r15 0) (:add-reg :r15 :rax) (:sub-reg :r15 :rax)
                  (:and-imm :r15 0) (:or-imm :r15 1) (:shr-imm :r15 1)))
    (destructuring-bind (function allocation roots layout sections body) (first (v06-frame-capture "true"))
      (setf (nth (position '(:imm-rax 1) body :test #'equal) body) form)
      (signals internal-failure (mognitio.frame:verify-sections function allocation roots layout sections body)))))
