(require :asdf)
(let* ((tests (uiop:pathname-directory-pathname *load-truename*))
       (root (uiop:pathname-parent-directory-pathname tests)))
  (asdf:load-asd (merge-pathnames "mognitio.asd" root)))
(let ((*standard-output* (make-broadcast-stream)) (*error-output* (make-broadcast-stream)))
  (asdf:load-system "mognitio"))
(let* ((argv (uiop:command-line-arguments)) (mode (first argv)) (source (second argv)))
  (cond
    ((member mode '("allocation" "allocation-report") :test #'string=)
     (setf (fdefinition 'mognitio.text::allocate-bytes)
           (lambda (size) (declare (ignore size)) (error 'storage-condition))))
    ((string= mode "size")
     (setf (fdefinition 'mognitio.text:checked-size)
           (let ((original (fdefinition 'mognitio.text:checked-size)))
             (lambda (a b) (declare (ignore a b)) (funcall original mognitio.integer:+maximum+ 1)))))
    ((member mode '("compiler-report" "source-report") :test #'string=)
     (setf (fdefinition 'mognitio.frontend:lex-source)
           (lambda (input)
             (declare (ignore input))
             (if (string= mode "compiler-report") (error 'storage-condition)
                 (mognitio.diagnostics:fail 'mognitio.diagnostics:source-failure nil "Injected source failure"))))
     (setf (fdefinition 'mognitio.diagnostics:render-diagnostic)
           (lambda (&rest args) (declare (ignore args)) (error 'storage-condition))))
    ((string= mode "compiler")
     (setf (fdefinition 'mognitio.frontend:lex-source)
           (lambda (source) (declare (ignore source)) (error 'storage-condition))))
    (t (error "Unknown test fault")))
  (when (string= mode "allocation-report")
    (setf (fdefinition 'mognitio.runtime::write-chunk)
          (lambda (&rest args) (declare (ignore args)) (error 'storage-condition)))
    ;; This source's arithmetic is strictly after its failing allocation.
    (setf (fdefinition 'mognitio.integer:checked-arithmetic)
          (lambda (&rest args) (declare (ignore args)) (uiop:quit 99))))
  (uiop:quit (mognitio.driver:run-cli (list "run" source) *standard-output* *error-output*)))
