(require :asdf)
(let* ((tests (uiop:pathname-directory-pathname *load-truename*))
       (root (uiop:pathname-parent-directory-pathname tests)))
  (asdf:load-asd (merge-pathnames "mognitio.asd" root)))
(let ((*standard-output* (make-broadcast-stream)) (*error-output* (make-broadcast-stream)))
  (asdf:load-system "mognitio"))
(let* ((input (make-string 65536 :initial-element #\A))
       (source (format nil "let allocate=function(s:string):string{s+s}; let keep=allocate(~S); var current=keep; var i=0; loop while(i<9000){current=allocate(~S); i=i+1;}; if(current==keep){keep->length()==131072}else{false}" input input))
       (decoded (mognitio.source:decode-source "gc.mgn" (sb-ext:string-to-octets source :external-format :utf-8)))
       (compiled (mognitio.backend.cl:compile-program
                   (mognitio.semantic:check-program
                     (mognitio.frontend:parse-program decoded (mognitio.frontend:lex-source decoded)))))
       (original (fdefinition 'mognitio.text::allocate-text))
       (weak nil) (count 0) (bytes 0)
       (resident (sb-kernel:dynamic-usage))
       (held (funcall original 3 3 (lambda (out) (replace out #(65 0 66))))))
  (unwind-protect
       (progn
         (setf (fdefinition 'mognitio.text::allocate-text)
               (lambda (size scalars fill)
                 (let ((value (funcall original size scalars fill)))
                   (incf count) (incf bytes size)
                   (push (sb-ext:make-weak-pointer value) weak)
                   value)))
         (assert (eq :true (mognitio.backend.cl:execute-program compiled))))
    (setf (fdefinition 'mognitio.text::allocate-text) original))
  (sb-ext:gc :full t)
  (let ((dead (count-if-not #'sb-ext:weak-pointer-value weak)))
    (assert (= count 9001))
    (assert (> bytes (* 4 256 1024 1024)))
    (assert (= dead count))
    (assert (equalp #(65 0 66) (mognitio.text:text-value-octets held)))
    (format t "HOST_GC_OK heap=268435456 resident=~D allocations=~D bytes=~D dead=~D held=3~%"
            resident count bytes dead)))
