(require :asdf)
(let* ((tests (uiop:pathname-directory-pathname *load-truename*))
       (root (uiop:pathname-parent-directory-pathname tests)))
  (asdf:load-asd (merge-pathnames "mognitio.asd" root)))
(let ((*standard-output* (make-broadcast-stream)) (*error-output* (make-broadcast-stream)))
  (asdf:load-system "mognitio"))
(let* ((argv (uiop:command-line-arguments)) (mode (first argv)) (source (second argv)))
  (cond
    ((string= mode "allocation")
     (setf (fdefinition 'mognitio.text::allocate-bytes)
           (lambda (size) (declare (ignore size)) (error 'storage-condition))))
    ((string= mode "size")
     (setf (fdefinition 'mognitio.text:checked-size)
           (let ((original (fdefinition 'mognitio.text:checked-size)))
             (lambda (a b) (declare (ignore a b)) (funcall original mognitio.integer:+maximum+ 1)))))
    ((string= mode "compiler")
     (setf (fdefinition 'mognitio.frontend:lex-source)
           (lambda (source) (declare (ignore source)) (error 'storage-condition))))
    (t (error "Unknown test fault")))
  (uiop:quit (mognitio.driver:run-cli (list "run" source) *standard-output* *error-output*)))
