(in-package #:mognitio.tests)

(defun v07-instructions (module)
  (loop for f in (mognitio.ir:module-functions module) append
    (loop for b in (mognitio.ir:ir-function-blocks f) append (mognitio.ir:basic-block-instructions b))))
(defun v07-operation (module op)
  (or (find op (v07-instructions module) :key #'mognitio.ir:instruction-op) (error "Missing test operation")))

(deftest v07-checked-metadata-boundaries
  (dolist (mutate
    (list
      (lambda (c) (setf (gethash "Alias" (mognitio.semantic::value-context-names (checked-program-values c))) '(:struct 1)))
      (lambda (c) (incf (type-info-id (aref (value-context-types (checked-program-values c)) 0))))
      (lambda (c) (clrhash (mognitio.semantic::value-context-packs (checked-program-values c))))
      (lambda (c) (let ((info (aref (value-context-implementations (checked-program-values c)) 0)))
                    (setf (implementation-info-contract info) '(:interface 0))))
      (lambda (c) (maphash (lambda (n info) (declare (ignore n))
                            (when (eq (member-info-kind info) :interface-call) (setf (member-info-index info) 7)))
                          (mognitio.semantic::value-context-members (checked-program-values c))))
      (lambda (c) (maphash (lambda (n info) (declare (ignore n)) (setf (call-info-targets info) nil))
                          (mognitio.semantic::checked-program-calls c)))))
    (let ((c (check-program (parse-text
               "type U=struct{};type Alias=U;interface A{let f = function():int;}implement U against A{let f=function():int{7};}let use:function(A):int=function(a:A):int{a->f()};use(U{})==7"))))
      (verify-checked-program c) (funcall mutate c)
      (signals internal-failure (verify-checked-program c))))
  (let* ((c (check-program (parse-text "type U=struct{a:int;b:int;};U{b:2,a:1}->a==1")))
         (members (mognitio.semantic::value-context-members (checked-program-values c))))
    (maphash (lambda (n info) (declare (ignore n))
               (when (eq (member-info-kind info) :struct) (setf (member-info-index info) '(0 1)))) members)
    (signals internal-failure (verify-checked-program c))))

(deftest v07-core-value-boundaries
  (dolist (pair '((:struct.make (0 0)) (:enum.make 8) (:struct.field 9)
                  (:enum.payload ((:enum 1) 0 0)) (:interface.pack 99)
                  (:call.interface ((:interface 2) 0 (999)))))
    (let* ((module (native-ir "type U=struct{s:string;n:int;};type E=enum{A;B(U);};interface A{let f = function():string;}implement U against A{let f=function():string{this->s};}let use:function(A):string=function(a:A):string{a->f()};branch on(E::B(U{s:\"ok\",n:1})){E::A=>false,E::B(u)=>use(u)==\"ok\"}"))
           (inst (v07-operation module (first pair))))
      (setf (mognitio.ir:instruction-value inst) (second pair))
      (signals internal-failure (mognitio.ir:verify-module module))))
  (let* ((module (native-ir "type E=enum{A(int);};let a: E=E::A(1);let b: E=E::A(2);branch on(a){E::A(x)=>x==1}"))
         (constructors (remove-if-not (lambda (i) (eq :enum.make (mognitio.ir:instruction-op i))) (v07-instructions module)))
         (payload (v07-operation module :enum.payload)))
    (setf (mognitio.ir:instruction-operands payload) (list (mognitio.ir:instruction-result (second constructors))))
    (signals internal-failure (mognitio.ir:verify-module module)))
  (let* ((module (native-ir "type E=enum{A(int);};branch on(E::A(1)){E::A(x)=>x==1}"))
         (branch (find-if (lambda (b) (eq :branch (first (mognitio.ir:basic-block-terminator b)))) (entry-blocks module)))
         (term (mognitio.ir:basic-block-terminator branch)))
    (setf (fourth term) (third term))
    (signals internal-failure (mognitio.ir:verify-module module))))

(deftest v07-root-last-use-and-child-independence
  (let* ((module (native-ir "type U=struct{s:string;};type P=struct{u:U;};let p: P=P{u:U{s:\"a\"+\"b\"}};let child: U=p->u;let dead: U=U{s:\"d\"+\"e\"};child->s==\"ab\""))
         (plans (mognitio.roots:analyze-roots module)) (plan (first plans))
         (instructions (v07-instructions module))
         (parent (find '(:struct 1) instructions :key #'mognitio.ir:instruction-type :test #'equal))
         (child (v07-operation module :struct.field))
         (last (car (last (mognitio.roots:root-plan-sites plan)))))
    (is (not (member (mognitio.ir:instruction-result parent) (mognitio.roots:root-site-values last))))
    (is (member (mognitio.ir:instruction-result child) (mognitio.roots:root-site-values last)))
    (loop for site in (mognitio.roots:root-plan-sites plan)
          for inst = (nth (mognitio.roots:root-site-instruction-index site)
                         (mognitio.ir:basic-block-instructions
                           (find (mognitio.roots:root-site-block-id site) (entry-blocks module) :key #'mognitio.ir:basic-block-id)))
          when (member (mognitio.ir:instruction-op inst) '(:struct.make :enum.make :interface.pack)) do
            (is (subsetp (mognitio.ir:instruction-operands inst) (mognitio.roots:root-site-values site))))
    (let ((saved (copy-list (mognitio.roots:root-site-values last))))
      (setf (mognitio.roots:root-site-values last) (remove (mognitio.ir:instruction-result child) saved))
      (signals internal-failure (mognitio.roots:verify-roots module plans))
      (setf (mognitio.roots:root-site-values last) (sort (cons (mognitio.ir:instruction-result parent) saved) #'<))
      (signals internal-failure (mognitio.roots:verify-roots module plans)))))

(deftest v07-native-child-and-metadata-faults
  ;; Build the parent by hand, and let the real collector classify each child
  ;; before dereferencing it. Metadata addresses are static image symbols.
  (dolist (kind '(:unmapped :interior :free :fake-static :descriptor))
    (let* ((source "type U=struct{s:string;};let u: U=U{s:\"a\"+\"b\"};true")
           (caller (append (v06-raw-frame)
                     (v06-raw-allocate 8)
                     '((:store-frame -8 :rax))
                     (when (eq kind :free) '((:call (:runtime :collect))))
                     (v06-raw-allocate 8)
                     '((:store-frame -32 :rax) (:mov-reg :rdx :rax)
                       (:imm-rcx 17) (:store-word :rdx 8 :rcx)
                       (:lea-meta (:descriptor 0 0)) (:store-word :rdx 16 :rax)
                       (:imm-rcx 0) (:store-word :rdx 24 :rcx))
                     (case kind
                       (:unmapped '((:imm-rax 1)))
                       (:interior '((:load-frame :rax -8) (:add-imm :rax 8)))
                       (:free '((:load-frame :rax -8) (:add-imm :rax 40)))
                       (:fake-static '((:lea-base :rax :rbp -64) (:imm-rcx 5) (:store-word :rax 8 :rcx)))
                       (:descriptor '((:imm-rax 1) (:store-word :rdx 16 :rax))))
                     '((:store-word :rdx 32 :rax) (:call (:runtime :collect)))
                     (v06-raw-finish))))
      (let ((mognitio.native.runtime::*test-options* '(:validate t)))
        (multiple-value-bind (out err code) (v05-cross-abi source 0 caller)
          (same 3 code) (same "" out) (same "" err))))))

(deftest v07-hidden-receiver-abi
  (let ((source "type U=struct{n:int;};implement U{let f=function(a:int,v:void,b:bool):int{this->n+a};}U{n:7}->f(9,void,true)==16")
        (callee '((:label (:function 1)) (:load-word :rax :rsp 8)
                  (:load-word :rax :rax 32) (:cmp-imm :rax 7) (:jnz :bad)
                  (:load-word :rax :rsp 16) (:cmp-imm :rax 9) (:jnz :bad)
                  (:load-word :rax :rsp 24) (:test) (:jnz :bad)
                  (:load-word :rax :rsp 32) (:cmp-imm :rax 1) (:jnz :bad)
                  (:load-word :rax :r15 0) (:test) (:jz :bad)
                  (:imm-reg :r8 99) (:imm-reg :r9 99) (:imm-reg :r10 99) (:imm-reg :r11 99)
                  (:imm-rax 16) (:ret)
                  (:label :bad) (:mov-edi 99) (:mov-eax 60) (:syscall) (:ud2))))
    (multiple-value-bind (out err code) (v05-cross-abi source 1 callee)
      (same 0 code) (same (format nil "true~%") out) (same "" err))))

(deftest v07-native-static-layout-and-table-order
  (let* ((source "type U=struct{flag:bool;s:string;unit:void;};type E=enum{Empty;Pair(int,U,string);};interface I{let b = function():string;let a = function():int;}implement U against I{let a=function():int{1};let b=function():string{this->s};}true")
         (code (mognitio.machine:lower-module (native-ir source))))
    (multiple-value-bind (bytes symbols) (mognitio.amd64:encode code)
      (dolist (pair '(((:descriptor 0 0) (1 0 0 3 1 1))
                      ((:descriptor 1 0) (2 1 0 0 0))
                      ((:descriptor 1 1) (2 1 1 3 2 1 2))
                      ((:descriptor 2 0) (3 2 0 1 1 0))
                      ((:method-table 0) (0 2 2 2 1))))
        (let ((offset (mognitio.object:image-symbol-offset (gethash (first pair) symbols))))
          (same 0 (mod offset 8))
          (loop for expected in (second pair) for i from 0 do
            (same expected (image-integer bytes (+ offset (* i 8)) 8)))))))
  (dolist (forms '(((:lea-meta (:text 0)) (:label (:text 0)) (:bytes 0))
                  ((:call (:descriptor 0 0)) (:label (:descriptor 0 0)) (:bytes 0))
                  ((:jmp (:method-table 0)) (:label (:method-table 0)) (:bytes 0))))
    (signals internal-failure (mognitio.amd64:encode (apply #'machine forms)))))

(deftest v07-interface-frame-corruption
  (let* ((captures (v06-frame-capture (concatenate 'string *v07-contract-source* "render(U{s:\"ok\"})==\"ok\"")))
         (capture (find-if (lambda (entry)
                            (some (lambda (b) (find :call.interface (mognitio.ir:basic-block-instructions b) :key #'mognitio.ir:instruction-op))
                                  (mognitio.ir:ir-function-blocks (first entry)))) captures)))
    (destructuring-bind (function allocation roots layout sections body) capture
      (let* ((section (find :operation sections :key #'first)) (forms (copy-tree (third section)))
             (receiver (find '(:load-word :rcx :rax 32) forms :test #'equal)))
        (is receiver) (setf (fourth receiver) 24 (third section) forms)
        (replace body forms :start1 (fourth section))
        (signals internal-failure (mognitio.frame:verify-sections function allocation roots layout sections body))))))

(deftest v07-interface-table-faults
  (let ((source "type U=struct{};type V=struct{};interface I{let f = function():int;}implement U against I{let f=function():int{1};}implement V against I{let f=function():int{2};}let pack:function():I=function():I{U{}};let held: I=pack();let dead: V=V{};held->f()==1")
        (original (fdefinition 'mognitio.native.runtime::value-helper-units)))
    (dolist (wrong '(nil t))
      (replacing (mognitio.native.runtime::value-helper-units
                   (lambda (module)
                     (let ((units (funcall original module)))
                       (dolist (unit units)
                         (dolist (inst (mognitio.object:code-unit-instructions unit))
                           (when (and (eq (mognitio.machine:instruction-opcode inst) :lea-meta)
                                      (equal (mognitio.machine:instruction-operands inst) '((:method-table 0))))
                             (setf (mognitio.machine:instruction-opcode inst) (if wrong :lea-meta :imm-rax)
                                   (mognitio.machine:instruction-operands inst) (if wrong '((:method-table 1)) '(1)))))) units)))
        (multiple-value-bind (out err status)
            (process-result (list (namestring (v06-runtime-artifact source '(:stress t :validate t)))))
          (same 3 status) (same "" out) (same "" err))))))
