(in-package #:mognitio.tests)

(deftest v07-keywords-migration-and-construction-ast
  ;; C07-41..46,51..52. Old grammar rejection and migrated behavior are distinct.
  (dolist (word '("type" "struct" "enum" "interface" "implement" "against" "this" "branch" "when" "on" "if" "match"))
    (v03-reject (format nil "let ~A=1;true" word) "parse"))
  (dolist (word '("impl" "self" "class" "new" "case"))
    (v07-accept (format nil "let ~A:int=7;~A==7" word word)))
  (v03-reject "if(true){true}else{false}" "parse")
  (v03-reject "match(true){true=>true}" "parse")
  (v07-accept "let f:function(string):string=function(s:string):string{s+\"!\"};var n: int=0;loop while(n<3){branch when{n==1=>{n=n+1;continue;}};n=n+1;};branch when{n==3=>f(\"ok\")==\"ok!\",else=>false}")
  (dolist (text '("E::A(1)" "E::A (1,)" "E::A()" "E::A" "(E::A)(1)" "E::A(1)(2)"))
    (let* ((node (program-root (parse-text text)))
           (constructor (cond ((typep node 'enum-expression) node)
                              ((typep (call-expression-callee node) 'grouping)
                               (grouping-expression (call-expression-callee node)))
                              (t (call-expression-callee node)))))
      (is (typep constructor 'enum-expression))
      (is (<= (span-end (node-span constructor)) (length text)))
      (when (member text '("E::A(1)" "E::A (1,)") :test #'string=)
        (same 1 (length (enum-expression-arguments constructor)))
        (is (enum-expression-parenthesized-p constructor))
        (same (length text) (span-end (node-span constructor))))))
  (let* ((text "type U=struct{x:int;}; U{x:1,}->x==1") (program (parse-text text))
         (access (binary-expression-left (program-root program))))
    (is (typep access 'field-expression))
    (same "U{x:1,}->x" (subseq text (span-start (node-span access)) (span-end (node-span access))))))

(deftest v07-artifact-identity-and-standalone
  (let* ((source (concatenate 'string *v07-same-name-source* "a(U{})+b(U{})==\"ab\""))
         (input (put-text (fresh-path) source)) (output (fresh-path ".elf")))
    (multiple-value-bind (out err status) (driver-result (build-args input output))
      (same 0 status) (same "" out) (same "" err))
    (same (read-bytes output) (native-image source))
    (same (native-image source) (native-image source))
    (delete-file input)
    (multiple-value-bind (out err status)
        (process-result (list "env" "-i" "PATH=/nonexistent" (namestring output) "ignored"))
      (same 0 status) (same "" err) (same (format nil "true~%") out))))
