(in-package #:mognitio.amd64)

(defun little-endian (value width &optional signed)
  (unless (typep value (if signed `(signed-byte ,(* 8 width))
                          `(unsigned-byte ,(* 8 width))))
    (internal-error "Integer does not fit the encoded field"))
  (loop for index below width collect (ldb (byte 8 (* 8 index)) value)))

(defun register-code (name)
  (or (position name '(:rax :rcx :rdx :rbx :rsp :rbp :rsi :rdi :r8 :r9 :r10 :r11 :r12 :r13 :r14 :r15))
      (internal-error "Invalid machine register")))

(defun memory-template (opcode register base displacement)
  (let ((reg (register-code register)))
    (unless (and (typep displacement '(signed-byte 32)) (zerop (mod displacement 8)))
      (internal-error "Invalid frame displacement"))
    (append (list (logior #x48 (if (>= reg 8) 4 0)) opcode
                  (logior #x80 (ash (mod reg 8) 3) (ecase base (:rbp 5) (:rsp 4))))
            (when (eq base :rsp) (list #x24))
            (little-endian displacement 4 t))))

(defun base-memory-template (opcode register base displacement &optional (width64 t))
  (let ((reg (register-code register)) (b (register-code base)))
    (unless (typep displacement '(signed-byte 32)) (internal-error "Invalid memory displacement"))
    (append (list (logior (if width64 #x48 #x40) (if (>= reg 8) 4 0) (if (>= b 8) 1 0)))
            (if (listp opcode) opcode (list opcode))
            (list (logior #x80 (ash (mod reg 8) 3) (mod b 8)))
            (when (= (mod b 8) 4) (list #x24))
            (little-endian displacement 4 t))))

(defun instruction-template (instruction)
  ;; Returns bytes and, for PC-relative instructions, the unresolved label.
  (let ((op (mognitio.machine:instruction-opcode instruction))
        (args (mognitio.machine:instruction-operands instruction)))
    (labels ((arity (count)
               (unless (= count (length args)) (internal-error "Invalid machine operands")))
             (fixed (bytes) (arity 0) bytes)
             (immediate (prefix)
               (arity 1) (append prefix (little-endian (first args) 4)))
             (imm64 (prefix)
               (arity 1)
               (unless (typep (first args) '(signed-byte 64)) (internal-error "Invalid int64 immediate"))
               (append prefix (little-endian (ldb (byte 64 0) (first args)) 8)))
             (slot (prefix)
               (arity 1)
               (unless (and (typep (first args) '(integer 0 2147483647))
                            (zerop (mod (first args) 8))) (internal-error "Invalid stack offset"))
               (append prefix (little-endian (first args) 4)))
             (relative (prefix)
               (arity 1)
               (mognitio.object:symbol-kind (first args))
               (values (append prefix '(0 0 0 0)) (first args))))
      (case op
        (:load-word (arity 3) (base-memory-template #x8b (first args) (second args) (third args)))
        (:store-word (arity 3) (base-memory-template #x89 (third args) (first args) (second args)))
        (:load-byte (arity 3) (base-memory-template '(#x0f #xb6) (first args) (second args) (third args) nil))
        (:store-byte (arity 3) (base-memory-template #x88 (third args) (first args) (second args) nil))
        (:lea-base (arity 3) (base-memory-template #x8d (first args) (second args) (third args)))
        (:imm-reg
         (arity 2)
         (let ((reg (register-code (first args))))
           (append (list (if (>= reg 8) #x49 #x48) (+ #xb8 (mod reg 8)))
                   (little-endian (second args) 8 t))))
        ((:add-reg :sub-reg :cmp-reg)
         (arity 2)
         (let ((dst (register-code (first args))) (src (register-code (second args))))
           (list (logior #x48 (if (>= src 8) 4 0) (if (>= dst 8) 1 0))
                 (ecase op (:add-reg #x01) (:sub-reg #x29) (:cmp-reg #x39))
                 (logior #xc0 (ash (mod src 8) 3) (mod dst 8)))))
        (:shr-imm
         (arity 2)
         (let ((reg (register-code (first args))))
           (append (list (if (>= reg 8) #x49 #x48) #xc1 (+ #xe8 (mod reg 8)))
                   (little-endian (second args) 1))))
        ((:add-imm :cmp-imm :and-imm :or-imm)
         (arity 2)
         (let ((reg (register-code (first args))))
           (append (list (logior #x48 (if (>= reg 8) 1 0)) #x81
                         (logior (ecase op (:add-imm #xc0) (:cmp-imm #xf8) (:and-imm #xe0) (:or-imm #xc8)) (mod reg 8)))
                   (little-endian (second args) 4 t))))
        ((:lea-text :lea-meta) (relative '(#x48 #x8d #x05)))
        (:jb (relative '(#x0f #x82)))
        (:ja (relative '(#x0f #x87)))
        (:jbe (relative '(#x0f #x86)))
        (:jl (relative '(#x0f #x8c)))
        (:js (relative '(#x0f #x88)))
        (:div-rcx (fixed '(#x48 #xf7 #xf1)))
        (:jae (relative '(#x0f #x83)))
        (:align (arity 1) (unless (eql (first args) 8) (internal-error "Invalid image alignment")) nil)
        (:mov-reg
         (arity 2)
         (let ((dst (register-code (first args))) (src (register-code (second args))))
           (list (logior #x48 (if (>= src 8) 4 0) (if (>= dst 8) 1 0)) #x89
                 (logior #xc0 (ash (mod src 8) 3) (mod dst 8)))))
        (:load-frame (arity 2) (memory-template #x8b (first args) :rbp (second args)))
        (:store-frame (arity 2) (memory-template #x89 (second args) :rbp (first args)))
        (:store-out (arity 2)
         (unless (typep (first args) '(integer 0 *)) (internal-error "Invalid outgoing offset"))
         (memory-template #x89 (second args) :rsp (first args)))
        (:align-stack (fixed '(#x48 #x83 #xe4 #xf0)))
        (:clear-frame (fixed '(#x48 #x31 #xed)))
        (:push-rbp (fixed '(#x55)))
        (:pop-rbp (fixed '(#x5d)))
        (:ret (fixed '(#xc3)))
        (:call (relative '(#xe8)))
        (:imm-rax (imm64 '(#x48 #xb8)))
        (:imm-rcx (imm64 '(#x48 #xb9)))
        (:imm-rdx (imm64 '(#x48 #xba)))
        (:load-rax (slot '(#x48 #x8b #x84 #x24)))
        (:load-rcx (slot '(#x48 #x8b #x8c #x24)))
        (:store-rax (slot '(#x48 #x89 #x84 #x24)))
        (:push-zero (fixed '(#x6a #x00)))
        (:dec-rcx (fixed '(#x48 #xff #xc9)))
        (:test-rcx (fixed '(#x48 #x85 #xc9)))
        (:neg (fixed '(#x48 #xf7 #xd8)))
        (:add (fixed '(#x48 #x01 #xc8)))
        (:sub (fixed '(#x48 #x29 #xc8)))
        (:mul (fixed '(#x48 #x0f #xaf #xc1)))
        (:cmp (fixed '(#x48 #x39 #xc8)))
        (:cmp-rax-rdx (fixed '(#x48 #x39 #xd0)))
        (:cmp-rcx-minus-one (fixed '(#x48 #x83 #xf9 #xff)))
        (:cqo (fixed '(#x48 #x99)))
        (:idiv (fixed '(#x48 #xf7 #xf9)))
        (:mov-rax-rdx (fixed '(#x48 #x89 #xd0)))
        (:jo (relative '(#x0f #x80)))
        (:set-bool
         (arity 1)
         (let ((cc (cdr (assoc (first args) '((:eq . #x94) (:ne . #x95)
                        (:lt . #x9c) (:le . #x9e) (:gt . #x9f) (:ge . #x9d))))))
           (unless cc (internal-error "Invalid condition code"))
           (list #x0f cc #xc0 #x0f #xb6 #xc0)))
        (:mov-r8d (immediate '(#x41 #xb8)))
        (:mov-r9d (immediate '(#x41 #xb9)))
        (:mov-r10d (immediate '(#x41 #xba)))
        (:mov-edi-r8d (fixed '(#x44 #x89 #xc7)))
        (:mov-edi-r9d (fixed '(#x44 #x89 #xcf)))
        (:cmp-r9d-one (fixed '(#x41 #x83 #xf9 #x01)))
        (:dec-r10d (fixed '(#x41 #xff #xca)))
        (:label (arity 1) (relative nil) nil)
        (:bool (unless (member (first args) '(0 1)) (internal-error "Invalid bool immediate"))
               (immediate '(#x48 #xc7 #xc0)))
        (:test (fixed '(#x48 #x85 #xc0)))
        (:jz (relative '(#x0f #x84)))
        (:jnz (relative '(#x0f #x85)))
        (:jle (relative '(#x0f #x8e)))
        (:jmp (relative '(#xe9)))
        (:lea-rsi (relative '(#x48 #x8d #x35)))
        (:mov-edx (immediate '(#xba)))
        (:mov-edi (immediate '(#xbf)))
        (:mov-eax (immediate '(#xb8)))
        (:cmp-eintr (fixed '(#x48 #x83 #xf8 #xfc)))
        (:add-rsi (fixed '(#x48 #x01 #xc6)))
        (:sub-rdx (fixed '(#x48 #x29 #xc2)))
        (:xor-edi (fixed '(#x31 #xff)))
        (:syscall (fixed '(#x0f #x05)))
        (:ud2 (fixed '(#x0f #x0b)))
        (:bytes
         (unless (every (lambda (byte) (typep byte '(unsigned-byte 8))) args)
           (internal-error "Invalid machine data bytes"))
         args)
        (otherwise (internal-error "Unsupported machine opcode"))))))

(defun encode-internal (code)
  (let ((labels (make-hash-table :test #'equal)) (fixups nil)
        (chunks nil) (position 0))
    (dolist (inst code)
      (multiple-value-bind (bytes target) (instruction-template inst)
        (if (eq (mognitio.machine:instruction-opcode inst) :label)
            (let ((name (first (mognitio.machine:instruction-operands inst))))
              (when (nth-value 1 (gethash name labels))
                (internal-error "Duplicate machine label"))
              (setf (gethash name labels)
                    (mognitio.object:make-image-symbol :name name
                      :kind (mognitio.object:symbol-kind name) :offset position)))
            (progn
              (when (eq (mognitio.machine:instruction-opcode inst) :align)
                (setf bytes (make-list (mod (- position) 8) :initial-element 0)))
              (when target
                (push (mognitio.object:make-fixup :offset (+ position (- (length bytes) 4))
                        :end (+ position (length bytes)) :target target
                        :use (mognitio.machine:instruction-opcode inst)) fixups))
              (push bytes chunks)
              (incf position (length bytes))))))
    (let ((image (make-array position :element-type '(unsigned-byte 8)))
          (cursor 0))
      (dolist (chunk (nreverse chunks))
        (dolist (byte chunk) (setf (aref image cursor) byte) (incf cursor)))
      (dolist (fixup fixups)
        (let* ((target (mognitio.object:fixup-target fixup)) (symbol (gethash target labels))
               (use (mognitio.object:fixup-use fixup)))
          (unless symbol (internal-error "Unresolved machine label"))
          (when (or (and (eq use :call) (not (member (mognitio.object:image-symbol-kind symbol) '(:function :helper))))
                    (and (member use '(:call :jmp :jo :jz :jnz :jle :jb :jae :ja :jbe :jl :js))
                         (member (mognitio.object:image-symbol-kind symbol) '(:data :text :metadata))))
            (internal-error "Invalid fixup target kind"))
          (when (and (eq use :lea-text) (not (eq (mognitio.object:image-symbol-kind symbol) :text)))
            (internal-error "Text address fixup requires an object symbol"))
          (when (and (eq use :lea-meta) (not (eq (mognitio.object:image-symbol-kind symbol) :metadata)))
            (internal-error "Metadata address requires a descriptor or table"))
          (replace image (little-endian (- (mognitio.object:image-symbol-offset symbol)
                                          (mognitio.object:fixup-end fixup)) 4 t)
                   :start1 (mognitio.object:fixup-offset fixup))))
      (values image labels))))

(defun encode (code)
  (handler-case (encode-internal code)
    (internal-failure (condition) (error condition))
    (error () (internal-error "Malformed Machine IR"))))
