(in-package #:mognitio.amd64)

(defun little-endian (value width &optional signed)
  (unless (typep value (if signed `(signed-byte ,(* 8 width))
                          `(unsigned-byte ,(* 8 width))))
    (internal-error "Integer does not fit the encoded field"))
  (loop for index below width collect (ldb (byte 8 (* 8 index)) value)))

(defun instruction-template (instruction)
  ;; Returns bytes and, for PC-relative instructions, the unresolved label.
  (let ((op (mognitio.machine:instruction-opcode instruction))
        (args (mognitio.machine:instruction-operands instruction)))
    (labels ((arity (count)
               (unless (= count (length args)) (internal-error "Invalid machine operands")))
             (fixed (bytes) (arity 0) bytes)
             (immediate (prefix)
               (arity 1) (append prefix (little-endian (first args) 4)))
             (relative (prefix)
               (arity 1)
               (unless (or (keywordp (first args))
                           (and (listp (first args)) (= (length (first args)) 2)
                                (eq (caar args) :block)
                                (typep (second (first args)) '(integer 0 *))))
                 (internal-error "Invalid machine label"))
               (values (append prefix '(0 0 0 0)) (first args))))
      (case op
        (:label (arity 1) (relative nil) nil)
        (:bool (unless (member (first args) '(0 1)) (internal-error "Invalid bool immediate"))
               (immediate '(#x48 #xc7 #xc0)))
        (:test (fixed '(#x48 #x85 #xc0)))
        (:jz (relative '(#x0f #x84)))
        (:jnz (relative '(#x0f #x85)))
        (:jle (relative '(#x0f #x8e)))
        (:jmp (relative '(#xe9)))
        (:lea-rsi (relative '(#x48 #x8d #x35)))
        (:mov-edx (immediate '(#xba)))
        (:mov-edi (immediate '(#xbf)))
        (:mov-eax (immediate '(#xb8)))
        (:cmp-eintr (fixed '(#x48 #x83 #xf8 #xfc)))
        (:add-rsi (fixed '(#x48 #x01 #xc6)))
        (:sub-rdx (fixed '(#x48 #x29 #xc2)))
        (:xor-edi (fixed '(#x31 #xff)))
        (:syscall (fixed '(#x0f #x05)))
        (:ud2 (fixed '(#x0f #x0b)))
        (:bytes
         (unless (every (lambda (byte) (typep byte '(unsigned-byte 8))) args)
           (internal-error "Invalid machine data bytes"))
         args)
        (otherwise (internal-error "Unsupported machine opcode"))))))

(defun encode-internal (code)
  (let ((labels (make-hash-table :test #'equal)) (fixups nil)
        (chunks nil) (position 0))
    (dolist (inst code)
      (multiple-value-bind (bytes target) (instruction-template inst)
        (if (eq (mognitio.machine:instruction-opcode inst) :label)
            (let ((name (first (mognitio.machine:instruction-operands inst))))
              (when (nth-value 1 (gethash name labels))
                (internal-error "Duplicate machine label"))
              (setf (gethash name labels) position))
            (progn
              (when target
                (push (list (+ position (- (length bytes) 4))
                            (+ position (length bytes)) target) fixups))
              (push bytes chunks)
              (incf position (length bytes))))))
    (let ((image (make-array position :element-type '(unsigned-byte 8)))
          (cursor 0))
      (dolist (chunk (nreverse chunks))
        (dolist (byte chunk) (setf (aref image cursor) byte) (incf cursor)))
      (dolist (fixup fixups)
        (destructuring-bind (offset end target) fixup
          (multiple-value-bind (address found) (gethash target labels)
            (unless found (internal-error "Unresolved machine label"))
            (replace image (little-endian (- address end) 4 t) :start1 offset))))
      (values image labels))))

(defun encode (code)
  (handler-case (encode-internal code)
    (internal-failure (condition) (error condition))
    (error () (internal-error "Malformed Machine IR"))))
