(in-package #:mognitio.amd64)

(defun little-endian (value width &optional signed)
  (unless (typep value (if signed `(signed-byte ,(* 8 width))
                          `(unsigned-byte ,(* 8 width))))
    (internal-error "Integer does not fit the encoded field"))
  (loop for index below width collect (ldb (byte 8 (* 8 index)) value)))

(defun instruction-template (instruction)
  ;; Returns bytes and, for PC-relative instructions, the unresolved label.
  (let ((op (mognitio.machine:instruction-opcode instruction))
        (args (mognitio.machine:instruction-operands instruction)))
    (labels ((arity (count)
               (unless (= count (length args)) (internal-error "Invalid machine operands")))
             (fixed (bytes) (arity 0) bytes)
             (immediate (prefix)
               (arity 1) (append prefix (little-endian (first args) 4)))
             (imm64 (prefix)
               (arity 1)
               (unless (typep (first args) '(signed-byte 64)) (internal-error "Invalid int64 immediate"))
               (append prefix (little-endian (ldb (byte 64 0) (first args)) 8)))
             (slot (prefix)
               (arity 1)
               (unless (and (typep (first args) '(integer 0 2147483647))
                            (zerop (mod (first args) 8))) (internal-error "Invalid stack offset"))
               (append prefix (little-endian (first args) 4)))
             (relative (prefix)
               (arity 1)
               (unless (or (and (listp (first args)) (= (length (first args)) 2)
                                (eq (caar args) :data)
                                (member (second (first args)) '(:overflow :division-by-zero :remainder-by-zero)))
                           (keywordp (first args))
                           (and (listp (first args)) (= (length (first args)) 2)
                                (member (caar args) '(:block :internal))
                                (typep (second (first args)) '(integer 0 *))))
                 (internal-error "Invalid machine label"))
               (values (append prefix '(0 0 0 0)) (first args))))
      (case op
        (:imm-rax (imm64 '(#x48 #xb8)))
        (:imm-rcx (imm64 '(#x48 #xb9)))
        (:imm-rdx (imm64 '(#x48 #xba)))
        (:load-rax (slot '(#x48 #x8b #x84 #x24)))
        (:load-rcx (slot '(#x48 #x8b #x8c #x24)))
        (:store-rax (slot '(#x48 #x89 #x84 #x24)))
        (:push-zero (fixed '(#x6a #x00)))
        (:dec-rcx (fixed '(#x48 #xff #xc9)))
        (:test-rcx (fixed '(#x48 #x85 #xc9)))
        (:neg (fixed '(#x48 #xf7 #xd8)))
        (:add (fixed '(#x48 #x01 #xc8)))
        (:sub (fixed '(#x48 #x29 #xc8)))
        (:mul (fixed '(#x48 #x0f #xaf #xc1)))
        (:cmp (fixed '(#x48 #x39 #xc8)))
        (:cmp-rax-rdx (fixed '(#x48 #x39 #xd0)))
        (:cmp-rcx-minus-one (fixed '(#x48 #x83 #xf9 #xff)))
        (:cqo (fixed '(#x48 #x99)))
        (:idiv (fixed '(#x48 #xf7 #xf9)))
        (:mov-rax-rdx (fixed '(#x48 #x89 #xd0)))
        (:jo (relative '(#x0f #x80)))
        (:set-bool
         (arity 1)
         (let ((cc (cdr (assoc (first args) '((:eq . #x94) (:ne . #x95)
                        (:lt . #x9c) (:le . #x9e) (:gt . #x9f) (:ge . #x9d))))))
           (unless cc (internal-error "Invalid condition code"))
           (list #x0f cc #xc0 #x0f #xb6 #xc0)))
        (:mov-r8d (immediate '(#x41 #xb8)))
        (:mov-r9d (immediate '(#x41 #xb9)))
        (:mov-r10d (immediate '(#x41 #xba)))
        (:mov-edi-r8d (fixed '(#x44 #x89 #xc7)))
        (:mov-edi-r9d (fixed '(#x44 #x89 #xcf)))
        (:cmp-r9d-one (fixed '(#x41 #x83 #xf9 #x01)))
        (:dec-r10d (fixed '(#x41 #xff #xca)))
        (:label (arity 1) (relative nil) nil)
        (:bool (unless (member (first args) '(0 1)) (internal-error "Invalid bool immediate"))
               (immediate '(#x48 #xc7 #xc0)))
        (:test (fixed '(#x48 #x85 #xc0)))
        (:jz (relative '(#x0f #x84)))
        (:jnz (relative '(#x0f #x85)))
        (:jle (relative '(#x0f #x8e)))
        (:jmp (relative '(#xe9)))
        (:lea-rsi (relative '(#x48 #x8d #x35)))
        (:mov-edx (immediate '(#xba)))
        (:mov-edi (immediate '(#xbf)))
        (:mov-eax (immediate '(#xb8)))
        (:cmp-eintr (fixed '(#x48 #x83 #xf8 #xfc)))
        (:add-rsi (fixed '(#x48 #x01 #xc6)))
        (:sub-rdx (fixed '(#x48 #x29 #xc2)))
        (:xor-edi (fixed '(#x31 #xff)))
        (:syscall (fixed '(#x0f #x05)))
        (:ud2 (fixed '(#x0f #x0b)))
        (:bytes
         (unless (every (lambda (byte) (typep byte '(unsigned-byte 8))) args)
           (internal-error "Invalid machine data bytes"))
         args)
        (otherwise (internal-error "Unsupported machine opcode"))))))

(defun encode-internal (code)
  (let ((labels (make-hash-table :test #'equal)) (fixups nil)
        (chunks nil) (position 0))
    (dolist (inst code)
      (multiple-value-bind (bytes target) (instruction-template inst)
        (if (eq (mognitio.machine:instruction-opcode inst) :label)
            (let ((name (first (mognitio.machine:instruction-operands inst))))
              (when (nth-value 1 (gethash name labels))
                (internal-error "Duplicate machine label"))
              (setf (gethash name labels) position))
            (progn
              (when target
                (push (list (+ position (- (length bytes) 4))
                            (+ position (length bytes)) target) fixups))
              (push bytes chunks)
              (incf position (length bytes))))))
    (let ((image (make-array position :element-type '(unsigned-byte 8)))
          (cursor 0))
      (dolist (chunk (nreverse chunks))
        (dolist (byte chunk) (setf (aref image cursor) byte) (incf cursor)))
      (dolist (fixup fixups)
        (destructuring-bind (offset end target) fixup
          (multiple-value-bind (address found) (gethash target labels)
            (unless found (internal-error "Unresolved machine label"))
            (replace image (little-endian (- address end) 4 t) :start1 offset))))
      (values image labels))))

(defun encode (code)
  (handler-case (encode-internal code)
    (internal-failure (condition) (error condition))
    (error () (internal-error "Malformed Machine IR"))))
