(in-package #:mognitio.backend.cl)

(defvar *void-value* (make-symbol "VOID"))

(defstruct (compiled-program
             (:constructor %make-compiled-program
                 (function span &optional warnings-p compiler-output)))
  (function nil :read-only t) (span nil :read-only t)
  (warnings-p nil :read-only t) (compiler-output "" :read-only t))

(defun unpacked-expression-form (node checked names functions exits &optional loops)
  (labels ((form (child) (if child (expression-form child checked names functions exits loops) (list 'cl:quote *void-value*)))
           (symbol-for (child)
             (or (gethash (local-symbol-id (checked-symbol checked child)) names)
                 (internal-error "Missing host binding")))
           (ordered (children build)
             (let ((bindings nil) (args nil))
               (dolist (child children)
                 (unless (checked-normal-type checked child)
                   (return-from ordered (list 'cl:let* (nreverse bindings) (form child))))
                 (let ((name (make-symbol "ARG")))
                   (push (list name (form child)) bindings) (push name args)))
               (list 'cl:let* (nreverse bindings) (funcall build (nreverse args)))))
           (sequence-form (statements tail index)
             (if (= index (length statements)) (form tail)
                 (let ((statement (aref statements index)))
                   (unless (checked-normal-type checked statement) (return-from sequence-form (form statement)))
                   (if (typep statement 'local-binding)
                       (list 'cl:let (list (list (symbol-for statement) (form (local-binding-initializer statement))))
                             (sequence-form statements tail (1+ index)))
                       (list 'cl:progn (form statement) (sequence-form statements tail (1+ index))))))))
    (typecase node
      ((or data-declaration contract-declaration implementation-declaration struct-expression enum-expression field-expression this-expression branch-expression)
       (value-expression-form node checked names functions exits loops))
      (panic-expression
       (let ((child (panic-expression-block node)))
         (if (checked-normal-type checked child) (list 'mognitio.runtime::raise-panic (form child)) (form child))))
      (try-expression
       (let* ((child (try-expression-operand node)) (info (checked-error checked node)) (value (make-symbol "RESULT")))
         (if (null (checked-normal-type checked child)) (form child)
             (list 'cl:let (list (list value (form child)))
                   (list 'cl:case (list 'mognitio.value:tag value)
                         (list 0 (list 'mognitio.value:field value 0))
                         (list 1 (list 'cl:return-from (gethash (error-info-owner info) exits)
                                       (list 'mognitio.value:construct (list 'cl:quote (error-info-return-type info)) 1
                                             (list 'mognitio.value:field value 0))))
                         (list 'cl:otherwise (list 'mognitio.diagnostics:internal-error "Invalid Result tag")))))))
      (loop-expression
       (let* ((id (loop-info-id (checked-loop checked node))) (exit (make-symbol "BREAK")) (again (make-symbol "CONTINUE"))
              (inner (acons id (cons exit again) loops)))
         (let* ((condition (loop-expression-condition node))
                (condition-form (when condition (expression-form condition checked names functions exits inner))))
           (list 'cl:block exit
                 (append (list 'cl:tagbody again)
                         (when condition
                           (list (if (checked-normal-type checked condition)
                                     (list 'cl:unless condition-form (list 'cl:return-from exit (list 'cl:quote *void-value*)))
                                     condition-form)))
                         (when (or (null condition) (checked-normal-type checked condition))
                           (list (expression-form (loop-expression-body node) checked names functions exits inner)))
                         (when (and (or (null condition) (checked-normal-type checked condition))
                                    (checked-normal-type checked (loop-expression-body node)))
                           (list (list 'cl:go again))))))))
      (break-statement
       (let ((value (break-statement-value node)))
         (if (or (null value) (checked-normal-type checked value))
             (list 'cl:return-from (cadr (assoc (loop-info-id (checked-control checked node)) loops)) (form value))
             (form value))))
      (continue-statement
       (list 'cl:go (cddr (assoc (loop-info-id (checked-control checked node)) loops))))
      (string-literal (list 'cl:quote (mognitio.text:literal-value (string-literal-payload node))))
      (void-literal (list 'cl:quote *void-value*))
      (expression-statement (form (expression-statement-expression node)))
      (assignment (list 'cl:progn (list 'cl:setq (symbol-for node) (form (assignment-rhs node))) (list 'cl:quote *void-value*)))
      (boolean-literal (ecase (boolean-literal-value node) (:true t) (:false nil)))
      (integer-literal (checked-literal checked node))
      (concrete-function-reference (concrete-function-reference-target node))
      (function-expression (signature-id (checked-function checked node)))
      (variable-reference (or (local-symbol-static-target (checked-symbol checked node)) (symbol-for node)))
      (sequence-node (sequence-form (sequence-node-statements node) (sequence-node-terminal node) 0))
      (grouping (form (grouping-expression node)))
      (return-statement
       (let ((value (return-statement-value node)))
         (if (or (null value) (checked-normal-type checked value))
             (list 'cl:return-from (gethash (checked-return checked node) exits) (form value))
             (form value))))
      (method-call
       (if (not (checked-operation checked node))
           (value-expression-form node checked names functions exits loops)
       (ordered (cons (method-call-receiver node) (coerce (method-call-arguments node) 'list))
                (lambda (args)
                  (cons (ecase (operation-info-kind (checked-operation checked node))
                          (:text.length 'mognitio.text:text-length) (:text.slice 'mognitio.text:text-slice)) args)))))
      (call-expression
       (ordered (cons (call-expression-callee node) (coerce (call-expression-arguments node) 'list))
                (lambda (args)
                  (list* 'cl:case (first args)
                         (append (loop for id in (call-info-targets (checked-call checked node))
                                       collect (list id (cons (gethash id functions) (rest args))))
                                 (list (list 'cl:otherwise (list 'mognitio.diagnostics:internal-error "Invalid function value"))))))))
      (if-expression
       (if (null (checked-normal-type checked (if-expression-condition node)))
           (form (if-expression-condition node))
           (list 'cl:if (form (if-expression-condition node))
                   (form (if-expression-then-branch node)) (form (if-expression-else-branch node)))))
      (unary-expression
       (if (checked-literal-p checked node) (checked-literal checked node)
           (if (checked-normal-type checked (unary-expression-operand node))
               (list 'mognitio.integer:checked-arithmetic :neg (form (unary-expression-operand node)))
               (form (unary-expression-operand node)))))
      (binary-expression
       (ordered (list (binary-expression-left node) (binary-expression-right node))
         (lambda (args)
           (let ((op (token-kind (binary-expression-operator node))))
             (if (checked-operation checked node)
                 (cons (ecase (operation-info-kind (checked-operation checked node))
                         (:text.concat 'mognitio.text:text-concat) (:text.equal 'mognitio.text:text-equal)
                         (:text.not-equal 'mognitio.text:text-not-equal)) args)
                 (if (member op '(:add :sub :mul :div :rem))
                 (list* 'mognitio.integer:checked-arithmetic op args)
                 (let ((comparison
                         (cons (case op
                                 ((:eq :ne) (if (eq (checked-normal-type checked (binary-expression-left node)) :bool)
                                                'cl:eq 'cl:=))
                                 (:lt 'cl:<) (:le 'cl:<=) (:gt 'cl:>) (:ge 'cl:>=)) args)))
                   (if (eq op :ne) (list 'cl:not comparison) comparison))))))))
      (t (internal-error "Invalid checked AST")))))

(defun program-form (checked)
  (let ((names (make-hash-table)) (functions (make-hash-table)) (exits (make-hash-table))
        (program (checked-program-program checked)))
    (loop for symbol across (checked-program-bindings checked)
          do (setf (gethash (local-symbol-id symbol) names) (make-symbol "LOCAL")))
    (loop for signature across (checked-program-signatures checked) do
      (setf (gethash (signature-id signature) functions) (make-symbol "FUNCTION")
            (gethash (signature-id signature) exits) (make-symbol "RETURN")))
    (let ((definitions
            (loop for signature across (checked-program-signatures checked)
                  for declaration = (signature-declaration signature) when declaration collect
              (list (gethash (signature-id signature) functions)
                    (append (when (signature-receiver signature) (list (gethash (local-symbol-id (signature-receiver signature)) names)))
                            (map 'list (lambda (p) (gethash (local-symbol-id (checked-symbol checked p)) names))
                                 (function-expression-parameters declaration)))
                    (list 'cl:block (gethash (signature-id signature) exits)
                          (expression-form (function-expression-body declaration) checked names functions exits)))))
          (entry (expression-form (make-sequence-node :statements (program-statements program)
                                    :terminal (program-root program)) checked names functions exits)))
      (if definitions
          (list 'cl:labels definitions (list 'cl:declare (cons 'cl:notinline (mapcar #'first definitions))) entry)
          entry))))

(defun host-compile (form)
  (with-compilation-unit (:override t)
    (compile nil form)))

(defun call-isolated (span thunk &optional runtime-allowed)
  (let* ((capture (make-string-output-stream))
         (*standard-output* capture) (*error-output* capture) (*trace-output* capture)
         (*compile-verbose* nil) (*compile-print* nil))
    (handler-case (with-compilation-unit (:override t) (funcall thunk))
      (mognitio.runtime:program-runtime-failure (condition)
        (if runtime-allowed (error condition)
            (internal-error "Runtime operation evaluated during host compilation")))
      (storage-condition ()
        (fail-at span :internal "Host storage failure outside text allocation" 'internal-failure))
      (compiler-failure (condition) (error condition))
      (error ()
        (fail-at span :internal "Host compilation or execution failed" 'internal-failure)))))

(defun compile-program (checked)
  (setf checked (mognitio.semantic::prepare-runtime-program checked))
  (let* ((root (program-root (checked-program-program checked)))
         (span (node-span root)))
    (call-isolated
     span
     (lambda ()
       (multiple-value-bind (function warnings-p failure-p)
           (host-compile (list 'cl:lambda '() (program-form checked)))
         (when (or failure-p (not (compiled-function-p function)))
           (fail-at span :internal "Host compile did not produce a valid function"
                    'internal-failure))
         (%make-compiled-program function span warnings-p
                                 (get-output-stream-string *standard-output*)))))))

(defun execute-program (compiled)
  (unless (typep compiled 'compiled-program)
    (internal-error "Expected CompiledProgram"))
  (call-isolated
   (compiled-program-span compiled)
   (lambda ()
     (let ((result (funcall (compiled-program-function compiled))))
       (cond ((eq result t) :true)
             ((eq result nil) :false)
             (t (fail-at (compiled-program-span compiled) :internal
                         "Host returned a non-boolean result" 'internal-failure))))) t))
