(in-package #:mognitio.semantic)

(defstruct (value-verification (:constructor make-value-verification (checked)))
  checked (context (make-value-context))
  (members (make-hash-table :test #'eq)) (packs (make-hash-table :test #'eq))
  (reserved (make-hash-table :test #'eq)) (next-signature 1) pending)
(defun verification-ensure (value message) (unless value (internal-error message)))
(defun type-shape (info)
  (list (type-info-id info) (type-info-kind info) (type-info-name info) (type-info-fields info) (type-info-origin info) (type-info-arguments info)
        (mapcar (lambda (x) (list (variant-info-id x) (variant-info-name x) (variant-info-types x))) (type-info-variants info))
        (mapcar (lambda (x) (list (requirement-name x) (requirement-parameters x) (requirement-result x))) (type-info-methods info))))
(defun implementation-shape (info)
  (list (implementation-info-id info) (implementation-info-concrete info) (implementation-info-contract info)
        (mapcar (lambda (x) (cons (car x) (signature-id (cdr x)))) (implementation-info-methods info))))
(defun verify-value-member (state node &key kind type index variant implementation signature contract)
  (let ((info (checked-member (value-verification-checked state) node)))
    (verification-ensure
     (and (member-info-p info) (eq kind (member-info-kind info)) (equal type (member-info-type info))
          (equal index (member-info-index info)) (eql variant (member-info-variant info))
          (eq signature (member-info-signature info)) (equal contract (member-info-contract info))
          (if implementation
              (and (member-info-implementation info)
                   (= (implementation-info-id implementation) (implementation-info-id (member-info-implementation info))))
              (null (member-info-implementation info)))) "Invalid value member metadata")
    (setf (gethash node (value-verification-members state)) t) info))
(defun verify-adaptation (state node actual expected)
  (let* ((checked (value-verification-checked state)) (pack (checked-pack checked node))
         (implementation (unless (or (null actual) (equal actual expected))
                           (and (nominal-type-p expected :interface)
                                (find-implementation (value-verification-context state) actual expected)))))
    (verification-ensure
     (if implementation
         (and pack (= (implementation-info-id implementation) (implementation-info-id pack))
              (equal (implementation-info-concrete pack) actual) (equal (implementation-info-contract pack) expected))
         (and (null pack) (or (null actual) (equal actual expected)))) "Invalid interface adaptation")
    (when pack (setf (gethash node (value-verification-packs state)) t))))
(defun reserve-verified-signature (state node)
  (let* ((checked (value-verification-checked state)) (sig (checked-function checked node)))
    (unless (gethash node (value-verification-reserved state))
      (verification-ensure (and (= (signature-id sig) (value-verification-next-signature state))
                               (eq sig (aref (checked-program-signatures checked) (signature-id sig)))
                               (eq node (signature-declaration sig))) "Invalid signature declaration order")
      (incf (value-verification-next-signature state))
      (setf (gethash node (value-verification-reserved state)) t)) sig))

(defun verify-type-node (state node)
  (when (and (typep node 'data-declaration) (plusp (length (data-declaration-type-parameters node))))
    (return-from verify-type-node (verify-generic-type-node state node)))
  ;; Reconstruct declarations without consulting producer name/field tables.
  (let* ((context (value-verification-context state))
         (contract-p (typep node 'contract-declaration))
         (name (if contract-p (contract-declaration-name node) (data-declaration-name node)))
         (kind (if contract-p :interface (data-declaration-kind node)))
         (seen nil) (info nil) (type nil))
    (verification-ensure (not (gethash (token-text name) (value-context-names context))) "Duplicate verified type")
    (labels ((resolve (token) (resolve-type-token context token))
             (unique (token)
               (verification-ensure (not (member (token-text token) seen :test #'string=)) "Duplicate verified member")
               (push (token-text token) seen))
             (field-type (token)
               (let ((value (resolve token)))
                 (verification-ensure (not (nominal-type-p value :interface)) "Interface in aggregate") value)))
      (if (eq kind :alias) (setf type (resolve (data-declaration-target node)))
          (progn
            (setf info (make-type-info :id (length (value-context-types context)) :kind kind :name (token-text name)))
            (case kind
              (:struct
               (setf (type-info-fields info)
                     (loop for field across (data-declaration-members node) do (unique (named-member-name field))
                           collect (cons (token-text (named-member-name field)) (field-type (named-member-value field))))))
              (:enum
               (verification-ensure (plusp (length (data-declaration-members node))) "Empty verified enum")
               (setf (type-info-variants info)
                     (loop for variant across (data-declaration-members node) for index from 0 do (unique (named-member-name variant))
                           collect (make-variant-info :id index :name (token-text (named-member-name variant))
                                     :types (map 'list #'field-type (named-member-value variant))))))
              (:interface
               (setf (type-info-methods info)
                     (loop for method across (contract-declaration-methods node) for fn = (named-member-value method)
                           do (unique (named-member-name method))
                           collect (make-requirement :name (token-text (named-member-name method))
                                     :parameters (map 'list (lambda (p) (resolve (parameter-type p))) (function-expression-parameters fn))
                                     :result (resolve (function-expression-result-type fn))))))
              (otherwise (internal-error "Invalid declaration kind")))
            (setf (type-info-id info) (length (value-context-types context)))
            (let ((actual (value-context-types (checked-program-values (value-verification-checked state)))))
              (verification-ensure (and (< (type-info-id info) (length actual))
                                        (equal (type-shape info) (type-shape (aref actual (type-info-id info))))) "Invalid type descriptor"))
            (vector-push-extend info (value-context-types context)) (setf type (canonical-type info))))
      (setf (gethash (token-text name) (value-context-names context)) type)
      (verify-value-member state node :kind :declaration :type type))))

(defun verify-implementation-node (state node owner scopes visit)
  (let* ((context (value-verification-context state))
         (concrete (resolve-type-token context (implementation-declaration-target node)))
         (contract (when (implementation-declaration-contract node) (resolve-type-token context (implementation-declaration-contract node))))
         (existing (find-implementation context concrete contract))
         (info (or existing (make-implementation-info :id (length (value-context-implementations context)) :concrete concrete :contract contract)))
         (names nil) (pending nil))
    (verification-ensure (and (nominal-type-p concrete) (not (nominal-type-p concrete :interface))
                             (not (generic-origin-p context concrete))
                             (or (null contract) (and (nominal-type-p contract :interface) (null existing)))) "Invalid implementation target")
    (loop for method across (implementation-declaration-methods node) for fn = (local-binding-initializer method)
          for name = (token-text (local-binding-name method)) do
      (verification-ensure (and (eq :let (local-binding-mutability method))
                               (not (member name names :test #'string=))
                               (not (assoc name (implementation-info-methods info) :test #'string=))
                               (not (assoc name (type-info-fields (context-type context concrete)) :test #'string=))) "Invalid method declaration")
      (push name names)
      (let ((sig (reserve-verified-signature state fn)))
        (verification-ensure (equal (signature-method sig) (list concrete contract name)) "Invalid method identity")
        (when contract
          (let ((requirement (find name (type-info-methods (context-type context contract)) :key #'requirement-name :test #'string=)))
            (verification-ensure (and requirement (equal (requirement-parameters requirement) (signature-parameter-types sig))
                                     (equal (requirement-result requirement) (signature-result-type sig))) "Invalid contract implementation")))
        (push (cons name sig) pending)))
    (when contract (verification-ensure (= (length pending) (length (type-info-methods (context-type context contract)))) "Incomplete contract"))
    (setf (implementation-info-methods info) (append (implementation-info-methods info) (nreverse pending)))
    (unless existing (vector-push-extend info (value-context-implementations context)))
    (verify-value-member state node :kind :implementation :implementation info)
    (loop for method across (implementation-declaration-methods node) do (funcall visit (local-binding-initializer method) owner scopes))))

(defun verify-value-node (state node owner scopes visit bind-symbol)
  (let ((checked (value-verification-checked state)) (context (value-verification-context state)))
    (labels ((nt (n) (checked-normal-type checked n))
             (ex (n) (completion-exits (checked-completion checked n)))
             (targets (n) (completion-targets (checked-completion checked n)))
             (prefix (nodes)
               (let ((result nil))
                 (dolist (n nodes result) (setf result (union result (ex n) :test #'equal)) (unless (nt n) (return result)))))
             (visit (n &optional (env scopes)) (funcall visit n owner env))
             (same-type (a b) (verification-ensure (or (null a) (equal a b)) "Invalid member operand type"))
             (find-variant (type token)
               (verification-ensure (nominal-type-p type :enum) "Invalid pattern type")
               (or (find (token-text token) (type-info-variants (context-type context type)) :key #'variant-info-name :test #'string=)
                   (internal-error "Unknown verified variant"))))
      (typecase node
        ((or data-declaration contract-declaration) (verify-type-node state node) (values :void nil nil))
        (implementation-declaration (verify-implementation-node state node owner scopes visit) (values :void nil nil))
        (this-expression
         (let ((symbol (signature-receiver (aref (checked-program-signatures checked) owner))))
           (verification-ensure symbol "Invalid this owner")
           (verify-value-member state node :kind :this :type (local-symbol-type symbol) :index (local-symbol-id symbol))
           (values (local-symbol-type symbol) nil nil)))
        (struct-expression
         (let* ((type (resolve-type-token context (struct-expression-name node))) (indices nil) (nodes nil))
           (verification-ensure (nominal-type-p type :struct) "Invalid struct type")
           (let ((fields (type-info-fields (context-type context type))))
             (loop for field across (struct-expression-fields node) for value = (named-member-value field)
                   for index = (position (token-text (named-member-name field)) fields :key #'car :test #'string=) do
               (verification-ensure (and index (not (member index indices))) "Invalid field initializer")
               (visit value) (same-type (nt value) (cdr (nth index fields))) (push index indices) (push value nodes))
             (verification-ensure (= (length indices) (length fields)) "Missing checked field"))
           (setf nodes (nreverse nodes))
           (verify-value-member state node :kind :struct :type type :index (nreverse indices))
           (values (when (every #'nt nodes) type) nil (prefix nodes))))
        (enum-expression
         (let* ((type (resolve-type-token context (enum-expression-name node)))
                (variant (find-variant type (enum-expression-variant node))) (nodes (coerce (enum-expression-arguments node) 'list)))
           (verification-ensure (and (= (length nodes) (length (variant-info-types variant)))
                                    (or (variant-info-types variant) (not (enum-expression-parenthesized-p node)))) "Invalid enum arity")
           (loop for value in nodes for expected in (variant-info-types variant) do (visit value) (same-type (nt value) expected))
           (verify-value-member state node :kind :enum :type type :variant (variant-info-id variant))
           (values (when (every #'nt nodes) type) nil (prefix nodes))))
        (field-expression
         (let ((receiver (field-expression-receiver node)))
           (visit receiver)
           (let* ((type (nt receiver))
                  (fields (when (nominal-type-p type :struct) (type-info-fields (context-type context type))))
                  (index (position (token-text (field-expression-name node)) fields :key #'car :test #'string=)))
             (when type
               (verification-ensure index "Invalid checked field access")
               (verify-value-member state node :kind :field :type type :index index))
             (values (when type (cdr (nth index fields))) nil (ex receiver)))))
        (branch-expression
         (let* ((on-p (eq :on (branch-expression-mode node))) (subject (branch-expression-subject node))
                (type nil) (variants nil) (fallback nil) (types nil) (normal nil) (candidates nil) (exits nil) (reachable t))
           (when on-p
             (visit subject) (setf type (nt subject) exits (ex subject) reachable (not (null type)))
             (verification-ensure (or (null type) (nominal-type-p type :enum)) "Invalid branch subject"))
           (loop for arm across (branch-expression-arms node) for selector = (branch-arm-selector arm)
                 for value = (branch-arm-value arm) for inner = (cons (make-hash-table :test #'equal) scopes) do
             (verification-ensure (not fallback) "Invalid fallback order")
             (cond
               ((null selector) (setf fallback t))
               (on-p
                (let* ((selected (resolve-type-token context (variant-pattern-name selector)))
                       (variant (find-variant selected (variant-pattern-variant selector))))
                  (same-type type selected) (setf type selected)
                  (verification-ensure (and (not (member (variant-info-id variant) variants))
                                           (= (length (variant-pattern-bindings selector)) (length (variant-info-types variant)))) "Invalid variant pattern")
                  (push (variant-info-id variant) variants)
                  (verify-value-member state selector :kind :pattern :type type :variant (variant-info-id variant))
                  (loop for token across (or (variant-pattern-bindings selector) #()) for expected in (variant-info-types variant) do
                    (unless (string= (token-text token) "_") (funcall bind-symbol token token :pattern owner inner expected)))))
               (t
                (visit selector) (same-type (nt selector) :bool)
                (when reachable (setf exits (union exits (ex selector) :test #'equal))
                  (unless (nt selector) (setf reachable nil)))))
             (visit value inner)
             (when (nt value) (pushnew (nt value) types :test #'equal) (setf candidates (union candidates (targets value))))
             (when reachable (setf exits (union exits (ex value) :test #'equal) normal (or normal (nt value)))))
           (verification-ensure (<= (length types) 1) "Invalid branch type join")
           (if on-p
               (progn
                 (verification-ensure type "Missing enum identity")
                 (let ((count (length (type-info-variants (context-type context type)))))
                   (verification-ensure (if fallback (< (length variants) count) (= (length variants) count)) "Invalid exhaustiveness")))
               (unless fallback
                 (verification-ensure (or (null types) (equal types '(:void))) "Invalid omitted else")
                 (when reachable (setf normal :void))))
           (verify-value-member state node :kind :branch :type type)
           (values normal (when normal candidates) exits)))
        (t (internal-error "Invalid value node in CheckedProgram"))))))

(defun finish-value-verification (state)
  (let* ((expected (value-verification-context state))
         (actual (checked-program-values (value-verification-checked state))))
    (verification-ensure (and (= (length (value-context-types expected)) (length (value-context-types actual)))
                             (equal (map 'list #'implementation-shape (value-context-implementations expected))
                                    (map 'list #'implementation-shape (value-context-implementations actual)))
                             (= (hash-table-count (value-context-members actual)) (hash-table-count (value-verification-members state)))
                             (= (hash-table-count (value-context-packs actual)) (hash-table-count (value-verification-packs state))))
                         "Unexpected value metadata")
    (verification-ensure (= (hash-table-count (value-context-names expected)) (hash-table-count (value-context-names actual))) "Unexpected type alias")
    (verification-ensure (equal (map 'list #'type-shape (value-context-types expected))
                                (map 'list #'type-shape (value-context-types actual))) "Invalid concrete type substitution")
    (verification-ensure (= (hash-table-count (value-context-templates expected))
                            (hash-table-count (value-context-templates actual))) "Unexpected type template")
    (verification-ensure (= (value-context-next-template expected) (value-context-next-template actual))
                         "Invalid type template identity sequence")
    (maphash (lambda (id template)
               (let ((other (gethash id (value-context-templates actual))))
                 (verification-ensure (and (generic-template-p other)
                                            (equal (generic-template-shape template) (generic-template-shape other)))
                                      "Invalid registered type template")))
             (value-context-templates expected))
    (verification-ensure (= (hash-table-count (value-context-instances expected))
                            (hash-table-count (value-context-instances actual))) "Unexpected concrete type instance")
    (maphash (lambda (key type)
               (verification-ensure (equal type (gethash key (value-context-instances actual))) "Invalid type instance key"))
             (value-context-instances expected))
    (maphash (lambda (name type)
               (let ((other (gethash name (value-context-names actual))))
                 (verification-ensure
                  (if (generic-template-p type)
                      (and (generic-template-p other) (equal (generic-template-shape type) (generic-template-shape other)))
                      (equal type other)) "Invalid type alias")))
             (value-context-names expected))))
