(in-package #:mognitio.semantic)

(defun verify-checked-program-internal (checked)
  (unless (checked-program-p checked) (internal-error "Expected CheckedProgram"))
  (let ((signatures (checked-program-signatures checked)) (bindings (checked-program-bindings checked))
        (edges (make-hash-table)) (seen-functions (make-hash-table)) (seen-bindings (make-hash-table)))
    (labels ((ensure (ok message) (unless ok (internal-error message)))
             (nt (node) (checked-normal-type checked node))
             (targets (node) (completion-targets (checked-completion checked node)))
             (same-set (a b) (and (subsetp a b) (subsetp b a)))
             (require-type (actual expected) (ensure (or (null actual) (equal actual expected)) "Invalid checked type"))
             (lookup (token scopes)
               (loop for scope in scopes for entry = (gethash (token-text token) scope) when entry return entry))
             (bind-symbol (node token mutability owner scopes &optional type)
               (let ((symbol (checked-symbol checked node)))
                 (ensure (and (typep (local-symbol-id symbol) `(integer 0 ,(1- (length bindings))))
                              (eq symbol (aref bindings (local-symbol-id symbol)))
                              (not (gethash symbol seen-bindings)) (= owner (local-symbol-owner symbol))
                              (string= (local-symbol-name symbol) (token-text token))
                              (eq mutability (local-symbol-mutability symbol)) (not (lookup token scopes))) "Invalid checked declaration")
                 (when type (ensure (equal type (local-symbol-type symbol)) "Invalid parameter type"))
                 (setf (gethash symbol seen-bindings) t
                       (gethash (token-text token) (first scopes)) (cons symbol (not (null type))))
                 symbol))
             (reference (node token owner scopes)
               (let* ((entry (lookup token scopes)) (symbol (checked-symbol checked node)))
                 (ensure (and entry (cdr entry) (eq symbol (car entry))
                              (or (= owner (local-symbol-owner symbol)) (local-symbol-static-target symbol))) "Invalid checked reference")
                 symbol))
             (static-id (node)
               (typecase node
                 (function-expression (signature-id (checked-function checked node)))
                 (grouping (static-id (grouping-expression node)))
                 (variable-reference (local-symbol-static-target (checked-symbol checked node)))))
             (sequence-visit (statements tail owner scopes)
               (let ((reachable t))
                 (loop for child across statements do
                   (ensure reachable "Unreachable checked statement") (visit child owner scopes) (setf reachable (nt child)))
                 (when tail (ensure reachable "Unreachable checked tail") (visit tail owner scopes))
                 (values (when reachable (if tail (nt tail) :void)) (when tail (targets tail)))))
             (visit (node owner scopes &optional consumed)
               (let ((type nil) (candidate nil))
                 (typecase node
                   (void-literal (setf type :void))
                   (expression-statement
                    (let ((child (expression-statement-expression node)))
                      (visit child owner scopes) (require-type (nt child) :void) (setf type (nt child))))
                   (boolean-literal (setf type :bool))
                   (integer-literal
                    (if consumed
                        (ensure (and (gethash node (checked-program-consumed checked)) (null (nt node))) "Invalid consumed literal")
                        (progn (ensure (and (mognitio.integer:in-range-p (checked-literal checked node))
                                            (not (gethash node (checked-program-consumed checked)))) "Invalid literal") (setf type :int))))
                   (variable-reference
                    (let ((symbol (reference node (variable-reference-name node) owner scopes)))
                      (setf type (local-symbol-type symbol) candidate (local-symbol-targets symbol))))
                   (function-expression
                    (let* ((sig (checked-function checked node)) (id (signature-id sig))
                           (inner (cons (make-hash-table :test #'equal) scopes)))
                      (ensure (and (typep id `(integer 1 ,(1- (length signatures))))
                                   (eq sig (aref signatures id)) (eq node (signature-declaration sig))
                                   (not (gethash id seen-functions))) "Invalid function identity")
                      (setf (gethash id seen-functions) t)
                      (ensure (equal (signature-parameter-types sig)
                                     (map 'list (lambda (p) (token-kind (parameter-type p))) (function-expression-parameters node))) "Invalid signature parameters")
                      (ensure (eq (signature-result-type sig) (token-kind (function-expression-result-type node))) "Invalid result signature")
                      (loop for p across (function-expression-parameters node) for expected in (signature-parameter-types sig) do
                        (bind-symbol p (parameter-name p) :parameter id inner expected)
                        (ensure (equal expected (nt p)) "Invalid parameter summary"))
                      (visit (function-expression-body node) id inner)
                      (require-type (nt (function-expression-body node)) (signature-result-type sig))
                      (setf type (signature-type sig) candidate (list id))))
                   (grouping (visit (grouping-expression node) owner scopes)
                             (setf type (nt (grouping-expression node)) candidate (targets (grouping-expression node))))
                   (sequence-node
                    (multiple-value-setq (type candidate)
                      (sequence-visit (sequence-node-statements node) (sequence-node-terminal node) owner
                                      (cons (make-hash-table :test #'equal) scopes))))
                   (local-binding
                    (let* ((symbol (bind-symbol node (local-binding-name node) (local-binding-mutability node) owner scopes))
                           (child (local-binding-initializer node)))
                      (visit child owner scopes)
                      (ensure (and (nt child) (equal (local-symbol-type symbol) (nt child))
                                   (not (and (function-type-p (nt child)) (eq (local-binding-mutability node) :var)))
                                   (same-set (local-symbol-targets symbol) (targets child))
                                   (eql (local-symbol-static-target symbol) (static-id child))) "Invalid checked initializer")
                      (setf (cdr (lookup (local-binding-name node) scopes)) t type :void)))
                   (assignment
                    (let ((symbol (reference node (assignment-name node) owner scopes)) (child (assignment-rhs node)))
                      (ensure (eq (local-symbol-mutability symbol) :var) "Immutable checked assignment")
                      (visit child owner scopes) (require-type (nt child) (local-symbol-type symbol)) (setf type (when (nt child) :void))))
                   (return-statement
                    (ensure (and (plusp owner) (= owner (checked-return checked node))) "Invalid return owner")
                    (when (return-statement-value node) (visit (return-statement-value node) owner scopes))
                    (require-type (if (return-statement-value node) (nt (return-statement-value node)) :void)
                                  (signature-result-type (aref signatures owner))))
                   (call-expression
                    (visit (call-expression-callee node) owner scopes)
                    (map nil (lambda (arg) (visit arg owner scopes)) (call-expression-arguments node))
                    (let* ((callee (call-expression-callee node)) (sig (nt callee)) (info (checked-call checked node)))
                      (ensure (and (= owner (call-info-owner info)) (equal sig (call-info-type info))
                                   (same-set (targets callee) (call-info-targets info))) "Invalid call metadata")
                      (when sig
                        (ensure (and (function-type-p sig) (= (length (second sig)) (length (call-expression-arguments node)))) "Invalid call signature")
                        (loop for arg across (call-expression-arguments node) for expected in (second sig) do (require-type (nt arg) expected))
                        (when (every (lambda (arg) (nt arg)) (coerce (call-expression-arguments node) 'list)) (setf type (third sig))))
                      (dolist (id (call-info-targets info)) (push (cons id (node-span node)) (gethash owner edges)))))
                   (unary-expression
                    (let* ((child (unary-expression-operand node))
                           (minimum (and (checked-literal-p checked node) (= (checked-literal checked node) mognitio.integer:+minimum+))))
                      (ensure (eq (token-kind (unary-expression-operator node)) :sub) "Invalid unary op")
                      (visit child owner scopes minimum)
                      (when minimum (ensure (typep child 'integer-literal) "Invalid minimum operand"))
                      (require-type (nt child) :int) (when (or minimum (nt child)) (setf type :int))))
                   (binary-expression
                    (let ((a (binary-expression-left node)) (b (binary-expression-right node)) (op (token-kind (binary-expression-operator node))))
                      (visit a owner scopes) (visit b owner scopes)
                      (ensure (member op '(:add :sub :mul :div :rem :eq :ne :lt :le :gt :ge)) "Invalid binary op")
                      (if (member op '(:eq :ne))
                          (progn (ensure (and (member (nt a) '(nil :int :bool)) (member (nt b) '(nil :int :bool))) "Invalid equality")
                                 (when (nt a) (require-type (if b (nt b) :void) (nt a))))
                          (progn (require-type (nt a) :int) (require-type (nt b) :int)))
                      (when (and (nt a) (nt b)) (setf type (if (member op '(:add :sub :mul :div :rem)) :int :bool)))))
                   (if-expression
                    (let ((condition (if-expression-condition node)) (a (if-expression-then-branch node)) (b (if-expression-else-branch node)))
                      (visit condition owner scopes) (visit a owner scopes) (when b (visit b owner scopes))
                      (require-type (nt condition) :bool) (when (nt a) (require-type (if b (nt b) :void) (nt a)))
                      (when (nt condition) (setf type (or (nt a) (if b (nt b) :void)) candidate (union (targets a) (when b (targets b)))))))
                   (t (internal-error "Invalid checked AST")))
                 (ensure (and (equal type (nt node)) (same-set (if type candidate nil) (targets node))) "Invalid checked completion")
                 (ensure (member (completion-may-return (checked-completion checked node)) '(nil t)) "Invalid return summary")
                 type)))
      (ensure (and (plusp (length signatures)) (= 0 (signature-id (aref signatures 0)))
                   (null (signature-declaration (aref signatures 0))) (eq :bool (signature-result-type (aref signatures 0)))
                   (null (signature-parameter-types (aref signatures 0)))) "Invalid entry")
      (let ((program (checked-program-program checked)))
        (multiple-value-bind (type candidates)
            (sequence-visit (program-statements program) (program-root program) 0 (list (make-hash-table :test #'equal)))
          (declare (ignore candidates)) (require-type type :bool)
          (ensure (equal type (nt program)) "Invalid entry summary")))
      (ensure (= (hash-table-count seen-functions) (1- (length signatures))) "Missing function table entry")
      (ensure (= (hash-table-count seen-bindings) (length bindings)) "Missing binding table entry")
      (check-call-graph (loop for id below (length signatures) collect id) edges
                        (lambda (span) (declare (ignore span)) (internal-error "Cyclic checked calls")))))
  checked)

(defun verify-checked-program (checked)
  (handler-case (verify-checked-program-internal checked)
    (internal-failure (condition) (error condition))
    (error () (internal-error "Malformed CheckedProgram"))))
