(in-package #:mognitio.semantic)

(defun verify-checked-program-internal (checked)
  (unless (checked-program-p checked) (internal-error "Expected CheckedProgram"))
  (let ((signatures (checked-program-signatures checked)) (bindings (checked-program-bindings checked))
        (seen-operations (make-hash-table :test #'eq)) (edges (make-hash-table)) (seen-functions (make-hash-table)) (seen-bindings (make-hash-table)) (seen-loops (make-hash-table))
        (plain-breaks (make-hash-table)) (valued-breaks (make-hash-table)) (break-types (make-hash-table)) (loop-stack nil))
    (labels ((ensure (ok message) (unless ok (internal-error message)))
             (verify-operation (node kind operands parameters result)
               (let ((info (checked-operation checked node)))
                 (ensure (and (operation-info-p info) (eq kind (operation-info-kind info))
                              (equal operands (operation-info-operands info))
                              (equal parameters (operation-info-parameter-types info))
                              (eq result (operation-info-result-type info))) "Invalid checked text operation")
                 (setf (gethash node seen-operations) t)))
             (nt (node) (checked-normal-type checked node))
             (targets (node) (completion-targets (checked-completion checked node)))
             (same-set (a b) (and (subsetp a b :test #'equal) (subsetp b a :test #'equal)))
             (exits-of (node) (when node (completion-exits (checked-completion checked node))))
             (prefix-exits (nodes)
               (let ((exits nil))
                 (dolist (child nodes exits)
                   (setf exits (union exits (exits-of child) :test #'equal))
                   (unless (nt child) (return exits)))))
             (loop-exits (node)
               (let ((condition (loop-expression-condition node)) (body (loop-expression-body node)))
                 (if condition (union (exits-of condition) (when (nt condition) (exits-of body)) :test #'equal)
                     (exits-of body))))
             (derive-exits (node owner)
               ;; Separate control-flow reconstruction; producer helpers are not used.
               (typecase node
                 (function-expression nil)
                 (if-expression
                  (let ((condition (if-expression-condition node)))
                    (union (exits-of condition)
                           (when (nt condition)
                             (union (exits-of (if-expression-then-branch node))
                                    (exits-of (if-expression-else-branch node)) :test #'equal)) :test #'equal)))
                 (loop-expression
                  (let ((id (loop-info-id (checked-loop checked node))))
                    (remove-if (lambda (exit) (and (member (first exit) '(:break :continue)) (= id (second exit))))
                               (loop-exits node))))
                 (break-statement
                  (let ((child (break-statement-value node)))
                    (union (exits-of child)
                           (when (or (null child) (nt child))
                             (list (list :break (loop-info-id (checked-control checked node))
                                         (if child (nt child) :void) (when child (targets child))))) :test #'equal)))
                 (continue-statement (list (list :continue (loop-info-id (checked-control checked node)) nil nil)))
                 (return-statement
                  (let ((child (return-statement-value node)))
                    (union (exits-of child) (when (or (null child) (nt child)) (list (list :return owner nil nil))) :test #'equal)))
                 (sequence-node (prefix-exits (append (coerce (sequence-node-statements node) 'list)
                                                     (when (sequence-node-terminal node) (list (sequence-node-terminal node))))))
                 (method-call (prefix-exits (cons (method-call-receiver node) (coerce (method-call-arguments node) 'list))))
                 (call-expression (prefix-exits (cons (call-expression-callee node) (coerce (call-expression-arguments node) 'list))))
                 (binary-expression (prefix-exits (list (binary-expression-left node) (binary-expression-right node))))
                 (unary-expression (exits-of (unary-expression-operand node)))
                 (local-binding (exits-of (local-binding-initializer node)))
                 (assignment (exits-of (assignment-rhs node)))
                 (grouping (exits-of (grouping-expression node)))
                 (expression-statement (exits-of (expression-statement-expression node)))
                 (t nil)))
             (require-type (actual expected) (ensure (or (null actual) (equal actual expected)) "Invalid checked type"))
             (lookup (token scopes)
               (loop for scope in scopes for entry = (gethash (token-text token) scope) when entry return entry))
             (bind-symbol (node token mutability owner scopes &optional type)
               (let ((symbol (checked-symbol checked node)))
                 (ensure (and (typep (local-symbol-id symbol) `(integer 0 ,(1- (length bindings))))
                              (eq symbol (aref bindings (local-symbol-id symbol)))
                              (not (gethash symbol seen-bindings)) (= (local-symbol-id symbol) (hash-table-count seen-bindings))
                              (= owner (local-symbol-owner symbol))
                              (string= (local-symbol-name symbol) (token-text token))
                              (eq mutability (local-symbol-mutability symbol)) (not (lookup token scopes))) "Invalid checked declaration")
                 (when type (ensure (and (equal type (local-symbol-type symbol)) (null (local-symbol-targets symbol))
                                         (null (local-symbol-static-target symbol))) "Invalid parameter type or static binding"))
                 (setf (gethash symbol seen-bindings) t
                       (gethash (token-text token) (first scopes)) (cons symbol (not (null type))))
                 symbol))
             (reference (node token owner scopes)
               (let* ((entry (lookup token scopes)) (symbol (checked-symbol checked node)))
                 (ensure (and entry (cdr entry) (eq symbol (car entry))
                              (or (= owner (local-symbol-owner symbol)) (local-symbol-static-target symbol))) "Invalid checked reference")
                 symbol))
             (static-id (node)
               (typecase node
                 (function-expression (signature-id (checked-function checked node)))
                 (grouping (static-id (grouping-expression node)))
                 (variable-reference (local-symbol-static-target (checked-symbol checked node)))))
             (sequence-visit (statements tail owner scopes)
               (let ((reachable t))
                 (loop for child across statements do
                   (ensure reachable "Unreachable checked statement") (visit child owner scopes) (setf reachable (nt child)))
                 (when tail (ensure reachable "Unreachable checked tail") (visit tail owner scopes))
                 (values (when reachable (if tail (nt tail) :void)) (when tail (targets tail)))))
             (visit (node owner scopes &optional consumed)
               (let ((type nil) (candidate nil))
                 (typecase node
                   (loop-expression
                    (let* ((info (checked-loop checked node)) (id (loop-info-id info)) (outer loop-stack)
                           (condition (loop-expression-condition node)) (body (loop-expression-body node)))
                      (ensure (and (eql id (hash-table-count seen-loops)) (= owner (loop-info-owner info))
                                   (eq node (loop-info-node info)) (not (gethash id seen-loops))) "Invalid loop identity")
                      (setf (gethash id seen-loops) info loop-stack (cons info loop-stack))
                      (when condition (visit condition owner scopes) (require-type (nt condition) :bool))
                      (visit body owner scopes) (require-type (nt body) :void)
                      (setf loop-stack outer)
                      (let ((breaks (remove-if-not (lambda (exit) (and (eq (first exit) :break) (= id (second exit)))) (loop-exits node))))
                        (setf type (if condition (when (or (nt condition) breaks) :void) (third (first breaks)))
                              candidate (reduce (lambda (a b) (union a b)) (mapcar #'fourth breaks) :initial-value nil)))
                      (ensure (and (not (and (gethash id plain-breaks) (gethash id valued-breaks)))
                                   (<= (length (gethash id break-types)) 1)
                                   (same-set (gethash id break-types) (loop-info-types info))
                                   (equal type (loop-info-normal-type info)) (same-set candidate (loop-info-targets info))
                                   (eql (gethash id plain-breaks) (loop-info-plain info))
                                   (eql (gethash id valued-breaks) (loop-info-valued info)))
                              "Invalid loop summary")))
                   (break-statement
                    (ensure (and loop-stack (eq (checked-control checked node) (first loop-stack))) "Invalid break target")
                    (let* ((info (first loop-stack)) (id (loop-info-id info)) (child (break-statement-value node)))
                      (when child (visit child owner scopes)
                        (ensure (null (loop-expression-condition (loop-info-node info))) "Valued conditional break"))
                      (setf (gethash id (if child valued-breaks plain-breaks)) t)
                      (let ((result (if child (nt child) :void))) (when result (pushnew result (gethash id break-types) :test #'equal)))))

                   (continue-statement
                    (ensure (and loop-stack (eq (checked-control checked node) (first loop-stack))) "Invalid continue target"))
                   (string-literal
                    (let* ((payload (string-literal-payload node)) (bytes (text-payload-octets payload))
                           (text (sb-ext:octets-to-string bytes :external-format :utf-8)))
                      (ensure (and (typep bytes '(simple-array (unsigned-byte 8) (*)))
                                   (= (length text) (text-payload-scalar-count payload))
                                   (<= 0 (length bytes) mognitio.integer:+maximum+)
                                   (every (lambda (ch) (let ((n (char-code ch)))
                                                        (and (<= n #x10ffff) (not (<= #xd800 n #xdfff))))) text))
                              "Invalid text literal payload")
                      (setf type :string)))
                   (void-literal (setf type :void))
                   (expression-statement
                    (let ((child (expression-statement-expression node)))
                      (visit child owner scopes) (require-type (nt child) :void) (setf type (nt child))))
                   (boolean-literal (ensure (member (boolean-literal-value node) '(:true :false)) "Invalid boolean") (setf type :bool))
                   (integer-literal
                    (let ((magnitude (parse-integer (token-text (integer-literal-token node)) :radix 10)))
                      (if consumed
                          (ensure (and (= magnitude (expt 2 63)) (gethash node (checked-program-consumed checked))
                                       (not (checked-literal-p checked node)) (null (nt node))) "Invalid consumed literal")
                          (progn (ensure (and (<= 0 magnitude (1- (expt 2 63))) (= magnitude (checked-literal checked node))
                                              (not (gethash node (checked-program-consumed checked)))) "Invalid literal")
                                 (setf type :int)))))

                   (variable-reference
                    (let ((symbol (reference node (variable-reference-name node) owner scopes)))
                      (setf type (local-symbol-type symbol) candidate (local-symbol-targets symbol))))
                   (function-expression
                    (let* ((sig (checked-function checked node)) (id (signature-id sig))
                           (outer-loops loop-stack) (inner (cons (make-hash-table :test #'equal) scopes)))
                      (ensure (and (typep id `(integer 1 ,(1- (length signatures))))
                                   (eq sig (aref signatures id)) (eq node (signature-declaration sig))
                                   (not (gethash id seen-functions)) (= id (1+ (hash-table-count seen-functions)))) "Invalid function identity")
                      (setf (gethash id seen-functions) t loop-stack nil)
                      (ensure (equal (signature-parameter-types sig)
                                     (map 'list (lambda (p) (token-kind (parameter-type p))) (function-expression-parameters node))) "Invalid signature parameters")
                      (ensure (and (member (signature-result-type sig) '(:int :bool :void :string)) (eq (signature-result-type sig) (token-kind (function-expression-result-type node)))) "Invalid result signature")
                      (loop for p across (function-expression-parameters node) for expected in (signature-parameter-types sig) do
                        (bind-symbol p (parameter-name p) :parameter id inner expected)
                        (ensure (and (member expected '(:int :bool :void :string)) (equal expected (nt p))
                                     (null (targets p)) (null (exits-of p)) (null (completion-may-return (checked-completion checked p))))
                                "Invalid parameter summary"))
                      (visit (function-expression-body node) id inner)
                      (require-type (nt (function-expression-body node)) (signature-result-type sig))
                      (setf loop-stack outer-loops type (signature-type sig) candidate (list id))))
                   (grouping (visit (grouping-expression node) owner scopes)
                             (setf type (nt (grouping-expression node)) candidate (targets (grouping-expression node))))
                   (sequence-node
                    (multiple-value-setq (type candidate)
                      (sequence-visit (sequence-node-statements node) (sequence-node-terminal node) owner
                                      (cons (make-hash-table :test #'equal) scopes))))
                   (local-binding
                    (let* ((symbol (bind-symbol node (local-binding-name node) (local-binding-mutability node) owner scopes))
                           (child (local-binding-initializer node)))
                      (visit child owner scopes)
                      (ensure (and (nt child) (equal (local-symbol-type symbol) (nt child))
                                   (not (and (function-type-p (nt child)) (eq (local-binding-mutability node) :var)))
                                   (same-set (local-symbol-targets symbol) (targets child))
                                   (eql (local-symbol-static-target symbol) (static-id child))) "Invalid checked initializer")
                      (setf (cdr (lookup (local-binding-name node) scopes)) t type :void)))
                   (assignment
                    (let ((symbol (reference node (assignment-name node) owner scopes)) (child (assignment-rhs node)))
                      (ensure (eq (local-symbol-mutability symbol) :var) "Immutable checked assignment")
                      (visit child owner scopes) (require-type (nt child) (local-symbol-type symbol)) (setf type (when (nt child) :void))))
                   (return-statement
                    (ensure (and (plusp owner) (= owner (checked-return checked node))) "Invalid return owner")
                    (when (return-statement-value node) (visit (return-statement-value node) owner scopes))
                    (require-type (if (return-statement-value node) (nt (return-statement-value node)) :void)
                                  (signature-result-type (aref signatures owner))))
                   (method-call
                    (let* ((receiver (method-call-receiver node)) (args (coerce (method-call-arguments node) 'list))
                           (name (token-text (method-call-name node))))
                      (visit receiver owner scopes)
                      (dolist (arg args) (visit arg owner scopes))
                      (when (nt receiver)
                        (require-type (nt receiver) :string)
                        (ensure (member name '("length" "slice") :test #'string=) "Invalid method name")
                        (let* ((slice-p (string= name "slice")) (parameters (if slice-p '(:int :int) nil))
                               (result (if slice-p :string :int)))
                          (ensure (= (length parameters) (length args)) "Invalid method arity")
                          (loop for arg in args for expected in parameters do (require-type (nt arg) expected))
                          (verify-operation node (if slice-p :text.slice :text.length) (cons receiver args)
                                            (cons :string parameters) result)
                          (when (every #'nt args) (setf type result))))))
                   (call-expression
                    (visit (call-expression-callee node) owner scopes)
                    (map nil (lambda (arg) (visit arg owner scopes)) (call-expression-arguments node))
                    (let* ((callee (call-expression-callee node)) (sig (nt callee)) (info (checked-call checked node)))
                      (ensure (and (= owner (call-info-owner info)) (equal sig (call-info-type info))
                                   (same-set (targets callee) (call-info-targets info))) "Invalid call metadata")
                      (when sig
                        (ensure (and (function-type-p sig) (= (length (second sig)) (length (call-expression-arguments node)))) "Invalid call signature")
                        (loop for arg across (call-expression-arguments node) for expected in (second sig) do (require-type (nt arg) expected))
                        (when (every (lambda (arg) (nt arg)) (coerce (call-expression-arguments node) 'list)) (setf type (third sig))))
                      (dolist (id (call-info-targets info)) (push (cons id (node-span node)) (gethash owner edges)))))
                   (unary-expression
                    (let* ((child (unary-expression-operand node))
                           (minimum (and (checked-literal-p checked node) (= (checked-literal checked node) mognitio.integer:+minimum+))))
                      (ensure (eq (token-kind (unary-expression-operator node)) :sub) "Invalid unary op")
                      (ensure (or minimum (not (checked-literal-p checked node))) "Invalid unary constant")
                      (visit child owner scopes minimum)
                      (when minimum (ensure (typep child 'integer-literal) "Invalid minimum operand"))
                      (require-type (nt child) :int) (when (or minimum (nt child)) (setf type :int))))
                   (binary-expression
                    (let ((a (binary-expression-left node)) (b (binary-expression-right node)) (op (token-kind (binary-expression-operator node))))
                      (visit a owner scopes) (visit b owner scopes)
                      (ensure (member op '(:add :sub :mul :div :rem :eq :ne :lt :le :gt :ge)) "Invalid binary op")
                      (cond
                        ((member op '(:eq :ne :add))
                         (let ((allowed (if (eq op :add) '(nil :int :string) '(nil :int :bool :string))))
                           (ensure (and (member (nt a) allowed) (member (nt b) allowed)) "Invalid binary types"))
                         (when (nt a) (require-type (nt b) (nt a))))
                        (t (require-type (nt a) :int) (require-type (nt b) :int)))
                      (when (and (nt a) (nt b))
                        (setf type (if (member op '(:eq :ne :lt :le :gt :ge)) :bool (nt a)))
                        (when (eq (nt a) :string)
                          (verify-operation node (ecase op (:add :text.concat) (:eq :text.equal) (:ne :text.not-equal))
                                            (list a b) '(:string :string) type)))))
                   (if-expression
                    (let ((condition (if-expression-condition node)) (a (if-expression-then-branch node)) (b (if-expression-else-branch node)))
                      (visit condition owner scopes) (visit a owner scopes) (when b (visit b owner scopes))
                      (require-type (nt condition) :bool) (when (nt a) (require-type (if b (nt b) :void) (nt a)))
                      (when (nt condition) (setf type (or (nt a) (if b (nt b) :void)) candidate (union (targets a) (when b (targets b)))))))
                   (t (internal-error "Invalid checked AST")))
                 (ensure (and (equal type (nt node)) (same-set (if type candidate nil) (targets node))) "Invalid checked completion")
                 (ensure (if (function-type-p type)
                             (and candidate (every (lambda (id)
                                                     (and (typep id `(integer 1 ,(1- (length signatures))))
                                                          (equal type (signature-type (aref signatures id))))) candidate))
                             (null candidate)) "Invalid function candidates")
                 (let* ((expected (derive-exits node owner)) (summary (checked-completion checked node)))
                   (ensure (same-set expected (completion-exits summary)) "Invalid checked exits")
                   (ensure (eq (not (null (find :return expected :key #'first))) (completion-may-return summary)) "Invalid return summary"))
                 type)))
      (ensure (and (plusp (length signatures)) (= 0 (signature-id (aref signatures 0)))
                   (null (signature-declaration (aref signatures 0))) (eq :bool (signature-result-type (aref signatures 0)))
                   (null (signature-parameter-types (aref signatures 0)))) "Invalid entry")
      (let ((program (checked-program-program checked)))
        (multiple-value-bind (type candidates)
            (sequence-visit (program-statements program) (program-root program) 0 (list (make-hash-table :test #'equal)))
          (require-type type :bool)
          (ensure (null candidates) "Invalid entry candidates")
          (ensure (and (equal type (nt program)) (null (targets program)) (null (exits-of program))
                       (null (completion-may-return (checked-completion checked program)))) "Invalid entry summary")))
      (ensure (= (hash-table-count seen-operations) (hash-table-count (checked-program-operations checked)))
              "Unexpected checked operation entry")
      (ensure (= (hash-table-count seen-functions) (1- (length signatures))) "Missing function table entry")
      (ensure (= (hash-table-count seen-loops) (hash-table-count (checked-program-loops checked))) "Missing loop entry")
      (ensure (= (hash-table-count seen-bindings) (length bindings)) "Missing binding table entry")
      (check-call-graph (loop for id below (length signatures) collect id) edges
                        (lambda (span) (declare (ignore span)) (internal-error "Cyclic checked calls")))))
  checked)

(defun verify-checked-program (checked)
  (handler-case (verify-checked-program-internal checked)
    (internal-failure (condition) (error condition))
    (error () (internal-error "Malformed CheckedProgram"))))
