(in-package #:mognitio.driver)

(defun invocation-error ()
  (fail 'usage-or-io-failure nil
        "Expected run <source.mgn> or build --target linux/amd64 --output <artifact> <source.mgn>"))

(defun parse-invocation (argv)
  (unless (and (listp argv) (every #'stringp argv)) (invocation-error))
  (let ((command (first argv)) (source nil) (output nil))
    (cond
      ((and (equal command "run") (= (length argv) 2))
       (setf source (second argv)))
      ((and (equal command "build") (= (length argv) 6))
       (let ((options (subseq argv 1 5)))
         (unless (or (and (equal (first options) "--target")
                          (equal (third options) "--output"))
                     (and (equal (first options) "--output")
                          (equal (third options) "--target")))
           (invocation-error))
         (let ((target (if (equal (first options) "--target")
                           (second options) (fourth options))))
           (unless (equal target "linux/amd64") (invocation-error)))
         (setf output (if (equal (first options) "--output")
                          (second options) (fourth options)))
         (unless (plusp (length output)) (invocation-error))
         (setf source (sixth argv))))
      (t (invocation-error)))
    (unless (and (>= (length source) 4)
                 (string= source ".mgn" :start1 (- (length source) 4)))
      (fail 'usage-or-io-failure nil "Source path must end with lowercase .mgn"))
    (values command source output
            (when (string= command "build") (mognitio.target:linux-amd64)))))

(defun checked-source (path)
  (let* ((source (read-source path))
         (tokens (lex-source source))
         (program (parse-program source tokens)))
    (check-program program)))

(defun run-pipeline (argv stdout)
  (multiple-value-bind (command source output target) (parse-invocation argv)
    (cond
      ((string= command "run")
       (let* ((checked (checked-source source))
              (compiled (compile-program checked))
              (result (execute-program compiled)))
         (write-line (ecase result (:true "true") (:false "false")) stdout)
         (finish-output stdout)))
      (t
       (mognitio.artifact:validate-paths source output)
       (let* ((checked (checked-source source))
              (image (mognitio.backend.native:compile-program checked target)))
         (mognitio.artifact:publish-image image source output)))))
  0)

(defun run-cli (argv stdout stderr)
  (labels ((report-failure (diagnostic code)
             ;; A broken diagnostic stream must not cause recursive reporting.
             (handler-case (progn (render-diagnostic diagnostic stderr) code)
               (error () 3))))
    (handler-case (run-pipeline argv stdout)
      (source-failure (condition)
        (report-failure (failure-diagnostic condition) 1))
      (usage-or-io-failure (condition)
        (report-failure (failure-diagnostic condition) 2))
      (internal-failure (condition)
        (report-failure (failure-diagnostic condition) 3))
      (error ()
        (report-failure (make-diagnostic :phase :internal
                                         :message "Unexpected compiler failure") 3)))))
