(in-package #:mognitio.driver)

(defun run-pipeline (argv stdout)
  (unless (and (= (length argv) 2) (string= (first argv) "run")
               (stringp (second argv)) (plusp (length (second argv))))
    (fail 'usage-or-io-failure nil "Expected run <source.mgn>"))
  (let* ((source (read-source (second argv)))
         (tokens (lex-source source))
         (program (parse-program source tokens))
         (checked (check-program program))
         (compiled (compile-program checked))
         (result (execute-program compiled)))
    (write-line (ecase result (:true "true") (:false "false")) stdout)
    (finish-output stdout))
  0)

(defun run-cli (argv stdout stderr)
  (labels ((report-failure (diagnostic code)
             ;; A broken diagnostic stream must not cause recursive reporting.
             (handler-case (progn (render-diagnostic diagnostic stderr) code)
               (error () 3))))
    (handler-case (run-pipeline argv stdout)
      (source-failure (condition)
        (report-failure (failure-diagnostic condition) 1))
      (usage-or-io-failure (condition)
        (report-failure (failure-diagnostic condition) 2))
      (internal-failure (condition)
        (report-failure (failure-diagnostic condition) 3))
      (error ()
        (report-failure (make-diagnostic :phase :internal
                                         :message "Unexpected compiler failure") 3)))))
