(in-package #:mognitio.elf)

(defconstant +image-base+ #x400000)
(defconstant +code-offset+ #x80)

(defun image-size (code-size)
  (unless (typep code-size '(integer 1 *))
    (internal-error "Invalid ELF payload size"))
  (let ((size (+ +code-offset+ code-size)))
    (mognitio.amd64:little-endian (+ +image-base+ size) 8)
    size))

(defun make-image (code)
  (unless (and (typep code '(vector (unsigned-byte 8))) (plusp (length code)))
    (internal-error "ELF payload must contain machine code"))
  (let* ((size (image-size (length code)))
         (image (make-array size :element-type '(unsigned-byte 8) :initial-element 0)))
    (labels ((field (offset value width)
               (replace image (mognitio.amd64:little-endian value width) :start1 offset)))
      (mognitio.amd64:little-endian (+ +image-base+ size) 8)
      (replace image '(127 69 76 70 2 1 1 0))
      (field 16 2 2) (field 18 62 2) (field 20 1 4)
      (field 24 (+ +image-base+ +code-offset+) 8) (field 32 64 8)
      (field 52 64 2) (field 54 56 2) (field 56 1 2)
      (field 64 1 4) (field 68 5 4)
      (field 80 +image-base+ 8) (field 88 +image-base+ 8)
      (field 96 size 8) (field 104 size 8) (field 112 #x1000 8)
      (replace image code :start1 +code-offset+)
      image)))
