(in-package #:mognitio.integer)

(defconstant +minimum+ (- (expt 2 63)))
(defconstant +maximum+ (1- (expt 2 63)))
(defun in-range-p (value) (typep value '(signed-byte 64)))
(defun decimal-magnitude (text &optional negative)
  (let* ((digits (string-left-trim "0" text))
         (limit (write-to-string (if negative (- +minimum+) +maximum+))))
    (when (or (> (length digits) (length limit))
              (and (= (length digits) (length limit)) (string> digits limit)))
      (return-from decimal-magnitude (values nil nil)))
    (values (if (zerop (length digits)) 0 (parse-integer digits :radix 10)) t)))
(declaim (notinline checked-arithmetic))
(defun checked-arithmetic (op a &optional b)
  (unless (and (in-range-p a) (or (eq op :neg) (in-range-p b)))
    (mognitio.diagnostics:internal-error "Invalid integer operand"))
  (when (member op '(:div :rem))
    (when (zerop b)
      (mognitio.runtime:runtime-error (if (eq op :div) :division-by-zero :remainder-by-zero)))
    (when (and (= a +minimum+) (= b -1))
      (mognitio.runtime:runtime-error :overflow)))
  (let ((result (ecase op
                  (:neg (- a)) (:add (+ a b)) (:sub (- a b)) (:mul (* a b))
                  (:div (truncate a b)) (:rem (nth-value 1 (truncate a b))))))
    (unless (in-range-p result) (mognitio.runtime:runtime-error :overflow))
    result))
