(in-package #:mognitio.ir)

(defun lower-error-node (node checked block env lower emit new-block)
  (let* ((panic (typep node 'panic-expression)) (span (node-span node))
         (operand (if panic (panic-expression-block node) (try-expression-operand node))))
    (multiple-value-bind (value end updated) (funcall lower operand block env)
      (unless end (return-from lower-error-node (values nil nil nil)))
      (when panic
        (setf (basic-block-terminator end) (list :panic value))
        (return-from lower-error-node (values nil nil nil)))
      (let* ((info (checked-error checked node)) (input (error-info-operand-type info))
             (ok (funcall new-block span)) (check-error (funcall new-block span))
             (err (funcall new-block span)) (invalid (funcall new-block span))
             (tag (funcall emit end :int :enum.tag span :operands (list value)))
             (zero (funcall emit end :int :constant span :value 0))
             (is-ok (funcall emit end :bool :eq span :operands (list tag zero))))
        (setf (basic-block-terminator end) (list :branch is-ok (basic-block-id ok) (basic-block-id check-error)))
        ;; Each payload load has its own dominating positive variant guard.
        (let* ((one (funcall emit check-error :int :constant span :value 1))
               (is-err (funcall emit check-error :bool :eq span :operands (list tag one)))
               (error-type (second (mognitio.semantic::type-info-arguments (context-type (checked-program-values checked) input))))
               (payload (funcall emit err error-type :enum.payload span :value (list input 1 0) :operands (list value)))
               (returned (funcall emit err (error-info-return-type info) :enum.make span :value 1 :operands (list payload))))
          (setf (basic-block-terminator check-error) (list :branch is-err (basic-block-id err) (basic-block-id invalid))
                (basic-block-terminator invalid) (list :trap)
                (basic-block-terminator err) (list :return returned)))
        (values (funcall emit ok (error-info-result-type info) :enum.payload span :value (list input 0 0) :operands (list value))
                ok updated)))))
