(in-package #:mognitio.ir)

(defparameter *value-operations* '(:struct.make :enum.make :struct.field :enum.tag :enum.payload :interface.pack :call.interface))

(defun verify-core-types (context functions)
  (let ((types (value-context-types context)))
    (labels ((valid (type &optional bound)
               (declare (ignore bound))
               (and (not (mognitio.semantic::symbolic-type-p type)) (valid-value-type-p type)
                    (or (not (nominal-type-p type))
                        (and (< (second type) (length types))
                             (equal type (canonical-type (aref types (second type))))))))
             (data (type bound) (and (valid type bound) (not (nominal-type-p type :interface)))))
      (loop for info across types for id from 0 do
        (unless (and (= id (type-info-id info)) (member (type-info-kind info) '(:struct :enum :interface))) (internal-error "Invalid Core type identity"))
        (ecase (type-info-kind info)
          (:struct
           (let ((fields (type-info-fields info)))
             (unless (and (null (type-info-variants info)) (null (type-info-methods info))
                          (= (length fields) (length (remove-duplicates fields :key #'car :test #'string=)))
                          (every (lambda (x) (data (cdr x) id)) fields)) (internal-error "Invalid Core struct"))))
          (:enum
           (let ((variants (type-info-variants info)))
             (unless (and variants (null (type-info-fields info)) (null (type-info-methods info))
                          (= (length variants) (length (remove-duplicates variants :key #'variant-info-name :test #'string=))))
               (internal-error "Invalid Core enum"))
             (loop for variant in variants for index from 0 do
               (unless (and (= index (variant-info-id variant)) (every (lambda (x) (data x id)) (variant-info-types variant)))
                 (internal-error "Invalid Core payload")))))
          (:interface
           (let ((methods (type-info-methods info)))
             (unless (and (null (type-info-fields info)) (null (type-info-variants info))
                          (= (length methods) (length (remove-duplicates methods :key #'requirement-name :test #'string=)))
                          (every (lambda (x) (and (valid (requirement-result x) id)
                                                 (every (lambda (t1) (valid t1 id)) (requirement-parameters x)))) methods))
               (internal-error "Invalid Core interface"))))))
      ;; Runtime IDs follow canonical keys, not dependency order. Validate the
      ;; complete graph independently instead of assuming every edge points back.
      (let ((edges (make-hash-table)))
        (loop for info across types for id from 0 do
          (dolist (type (append (mapcar #'cdr (type-info-fields info))
                               (mapcan (lambda (variant) (copy-list (variant-info-types variant))) (type-info-variants info))
                               (mapcan (lambda (method) (cons (requirement-result method) (copy-list (requirement-parameters method)))) (type-info-methods info))))
            (when (nominal-type-p type) (push (cons (second type) nil) (gethash id edges)))))
        (check-call-graph (loop for id below (length types) collect id) edges
                          (lambda (span) (declare (ignore span)) (internal-error "Recursive Core type graph"))))
      (let ((pairs nil))
        (loop for implementation across (value-context-implementations context) for id from 0
              for concrete = (implementation-info-concrete implementation) for contract = (implementation-info-contract implementation)
              for methods = (implementation-info-methods implementation) do
          (unless (and (= id (implementation-info-id implementation)) (valid concrete) (nominal-type-p concrete)
                       (not (nominal-type-p concrete :interface))
                       (or (null contract) (and (valid contract) (nominal-type-p contract :interface)))
                       (not (member (list concrete contract) pairs :test #'equal))
                       (= (length methods) (length (remove-duplicates methods :key #'car :test #'string=))))
            (internal-error "Invalid Core implementation"))
          (push (list concrete contract) pairs)
          (when contract
            (unless (= (length methods) (length (type-info-methods (context-type context contract)))) (internal-error "Incomplete Core table")))
          (dolist (pair methods)
            (let* ((sig (cdr pair)) (callee (gethash (signature-id sig) functions))
                   (requirement (when contract (find (car pair) (type-info-methods (context-type context contract)) :key #'requirement-name :test #'string=))))
              (unless (and callee (equal (ir-function-method callee) (list concrete contract (car pair)))
                           (equal (ir-function-parameter-types callee) (cons concrete (signature-parameter-types sig)))
                           (equal (ir-function-result-type callee) (signature-result-type sig))
                           (not (assoc (car pair) (type-info-fields (context-type context concrete)) :test #'string=))
                           (or (null contract) (and requirement (equal (rest (ir-function-parameter-types callee)) (requirement-parameters requirement))
                                                    (equal (ir-function-result-type callee) (requirement-result requirement)))))
                (internal-error "Invalid Core method signature"))))))
      (maphash (lambda (id function)
                 (declare (ignore id))
                 (unless (and (valid (ir-function-result-type function)) (every #'valid (ir-function-parameter-types function)))
                   (internal-error "Unknown Core signature type"))) functions))))

(defun verify-value-instruction (instruction types context functions id pos defs blocks dom edges caller)
  (declare (ignore pos))
  (let ((op (instruction-op instruction)) (data (instruction-value instruction))
        (result (instruction-type instruction)) (operands (instruction-operands instruction)))
    (labels ((type-info (type) (context-type context type))
             (defined-instruction (value)
               (let ((definition (gethash value defs)))
                 (when (and definition (>= (second definition) 0))
                   (nth (second definition) (basic-block-instructions (gethash (first definition) blocks))))))
             (guarded (subject variant)
               (loop for block being the hash-values of blocks for term = (basic-block-terminator block)
                     thereis
                 (and (eq :branch (first term)) (not (eql (third term) (fourth term)))
                      (member (third term) (gethash id dom))
                      (equal (loop for predecessor being the hash-values of blocks
                                   when (member (third term) (successors predecessor))
                                   collect (basic-block-id predecessor))
                             (list (basic-block-id block)))
                      (let ((comparison (defined-instruction (second term))))
                        (and comparison (eq :eq (instruction-op comparison))
                             (loop for pair in (list (instruction-operands comparison) (reverse (instruction-operands comparison)))
                                   thereis
                               (let ((tag (defined-instruction (first pair))) (constant (defined-instruction (second pair))))
                                 (and tag constant (eq :enum.tag (instruction-op tag)) (equal (list subject) (instruction-operands tag))
                                      (eq :constant (instruction-op constant)) (eql variant (instruction-value constant)))))))))))
      (case op
        (:struct.make
         (and (nominal-type-p result :struct)
              (let ((fields (type-info-fields (type-info result))))
                (and (= (length types) (length fields) (length data))
                     (equal (sort (copy-list data) #'<) (loop for n below (length fields) collect n))
                     (equal types (mapcar (lambda (index) (cdr (nth index fields))) data))))))
        (:enum.make
         (and (nominal-type-p result :enum) (typep data '(integer 0 *))
              (let ((variant (nth data (type-info-variants (type-info result))))) (and variant (equal types (variant-info-types variant))))))
        (:struct.field
         (and (= 1 (length types)) (nominal-type-p (first types) :struct) (typep data '(integer 0 *))
              (let ((field (nth data (type-info-fields (type-info (first types)))))) (and field (equal result (cdr field))))))
        (:enum.tag (and (null data) (= 1 (length types)) (nominal-type-p (first types) :enum) (eq result :int)))
        (:enum.payload
         (and (= 1 (length types)) (= 3 (length data)) (equal (first types) (first data)) (nominal-type-p (first data) :enum)
              (typep (second data) '(integer 0 *)) (typep (third data) '(integer 0 *))
              (let* ((variant (nth (second data) (type-info-variants (type-info (first data)))))
                     (slot (when variant (nth (third data) (variant-info-types variant)))))
                (and slot (equal result slot) (guarded (first operands) (second data))))))
        (:interface.pack
         (and (= 1 (length types)) (typep data '(integer 0 *)) (< data (length (value-context-implementations context)))
              (let ((implementation (aref (value-context-implementations context) data)))
                (and (equal (first types) (implementation-info-concrete implementation))
                     (equal result (implementation-info-contract implementation)) (nominal-type-p result :interface)))))
        (:call.interface
         (and (= 3 (length data)) (equal (first types) (first data)) (nominal-type-p (first data) :interface)
              (typep (second data) '(integer 0 *))
              (let* ((requirement (nth (second data) (type-info-methods (type-info (first data)))))
                     (targets (when requirement
                                (loop for implementation across (value-context-implementations context)
                                      when (equal (first data) (implementation-info-contract implementation))
                                        collect (signature-id (cdr (assoc (requirement-name requirement) (implementation-info-methods implementation) :test #'string=)))))))
                (and requirement (equal (rest types) (requirement-parameters requirement)) (equal result (requirement-result requirement))
                     (= (length targets) (length (third data))) (subsetp targets (third data)) (subsetp (third data) targets)
                     (every (lambda (target) (push (cons target (instruction-span instruction)) (gethash caller edges)) (gethash target functions)) targets)))))
        (otherwise nil)))))
