(in-package #:mognitio.ir)

(defstruct instruction result (type :bool) op value operands span)
(defstruct basic-block id parameters instructions terminator span)
(defstruct ir-function id parameter-types (result-type :bool) blocks entry span)
(defstruct module functions (entry 0) span)
(defparameter *operations*
  '((:constant 0 :literal nil) (:neg 1 :int t) (:add 2 :int t)
    (:sub 2 :int t) (:mul 2 :int t) (:div 2 :int t) (:rem 2 :int t)
    (:eq 2 :equal nil) (:ne 2 :equal nil)
    (:lt 2 :comparison nil) (:le 2 :comparison nil)
    (:gt 2 :comparison nil) (:ge 2 :comparison nil)))

(defun lower-function (checked signature)
  (unless (typep checked 'checked-program) (internal-error "Expected CheckedProgram"))
  (let ((blocks nil) (next-block 0) (next-value 0)
        (program (checked-program-program checked)) (declaration (signature-declaration signature)))
    (labels ((new-block (span)
               (let ((b (make-basic-block :id next-block :span span)))
                 (incf next-block) (push b blocks) b))
             (new-value () (prog1 next-value (incf next-value)))
             (symbol-id (node) (local-symbol-id (checked-symbol checked node)))
             (value-for (id env)
               (let ((pair (assoc id env)))
                 (unless pair (internal-error "Missing SSA binding")) (cdr pair)))
             (emit-value (block type op span &key value operands)
               (let ((id (new-value)))
                 (push (make-instruction :result id :type type :op op :span span
                                         :value value :operands operands)
                       (basic-block-instructions block)) id))
             (sequence-lower (statements tail block env scoped)
               (let ((visible (mapcar #'car env)))
                 (loop for statement across statements do
                   (multiple-value-bind (v end updated)
                       (lower (etypecase statement
                                (local-binding (local-binding-initializer statement))
                                (assignment (assignment-rhs statement))) block env)
                     (unless end (return-from sequence-lower (values nil nil nil)))
                     (setf block end env (acons (symbol-id statement) v updated))))
                 (multiple-value-bind (v end updated) (lower tail block env)
                   (values v end (if scoped
                                     (remove-if-not (lambda (pair) (member (car pair) visible)) updated)
                                     updated)))))
             (lower (node block env)
               (unless block (return-from lower (values nil nil nil)))
               (typecase node
                 (return-statement
                  (unless (= (checked-return checked node) (signature-id signature))
                    (internal-error "Return owner mismatch"))
                  (multiple-value-bind (value end updated) (lower (return-statement-value node) block env)
                    (declare (ignore updated))
                    (when end (setf (basic-block-terminator end) (list :return value)))
                    (values nil nil nil)))
                 (call-expression
                  (let ((arguments nil))
                    (loop for arg across (call-expression-arguments node) do
                      (multiple-value-bind (value end updated) (lower arg block env)
                        (unless end (return-from lower (values nil nil nil)))
                        (push value arguments) (setf block end env updated)))
                    (values (emit-value block (checked-normal-type checked node) :call (node-span node)
                              :value (signature-id (checked-call checked node)) :operands (nreverse arguments)) block env)))
                 (boolean-literal
                  (values (emit-value block :bool :constant (node-span node)
                             :value (ecase (boolean-literal-value node) (:true 1) (:false 0))) block env))
                 (integer-literal
                  (values (emit-value block :int :constant (node-span node)
                                      :value (checked-literal checked node)) block env))
                 (variable-reference (values (value-for (symbol-id node) env) block env))
                 (grouping (lower (grouping-expression node) block env))
                 (sequence-node
                  (sequence-lower (sequence-node-statements node) (sequence-node-terminal node) block env t))
                 (unary-expression
                  (if (checked-literal-p checked node)
                      (values (emit-value block :int :constant (node-span node)
                                          :value (checked-literal checked node)) block env)
                      (multiple-value-bind (v end updated) (lower (unary-expression-operand node) block env)
                        (unless end (return-from lower (values nil nil nil)))
                        (values (emit-value end :int :neg (node-span node) :operands (list v)) end updated))))
                 (binary-expression
                  (multiple-value-bind (a a-end a-env) (lower (binary-expression-left node) block env)
                    (unless a-end (return-from lower (values nil nil nil)))
                    (multiple-value-bind (b b-end b-env) (lower (binary-expression-right node) a-end a-env)
                      (unless b-end (return-from lower (values nil nil nil)))
                      (values (emit-value b-end (checked-normal-type checked node)
                                (token-kind (binary-expression-operator node)) (node-span node)
                                :operands (list a b)) b-end b-env))))
                 (if-expression
                  (multiple-value-bind (condition condition-end condition-env)
                      (lower (if-expression-condition node) block env)
                    (unless condition-end (return-from lower (values nil nil nil)))
                    (let ((then (new-block (node-span node))) (else (new-block (node-span node))))
                      (setf (basic-block-terminator condition-end)
                            (list :branch condition (basic-block-id then) (basic-block-id else)))
                      (multiple-value-bind (a a-end a-env)
                          (lower (if-expression-then-branch node) then condition-env)
                        (multiple-value-bind (b b-end b-env)
                            (lower (if-expression-else-branch node) else condition-env)
                          (cond ((and (null a-end) (null b-end)) (return-from lower (values nil nil nil)))
                                ((null a-end) (return-from lower (values b b-end b-env)))
                                ((null b-end) (return-from lower (values a a-end a-env))))
                          (let* ((join (new-block (node-span node))) (result (new-value))
                                 (params (list (cons result (checked-normal-type checked node))))
                                 (args-a (list a)) (args-b (list b)) (merged condition-env))
                            (dolist (id (sort (remove-duplicates (mapcar #'car condition-env)) #'<))
                              (let ((va (value-for id a-env)) (vb (value-for id b-env)))
                                ;; Equal incoming IDs can still replace the pre-branch value.
                                (when (and (= va vb) (/= va (value-for id condition-env)))
                                  (setf merged (acons id va merged)))
                                (unless (= va vb)
                                  (let ((parameter (new-value))
                                        (symbol (aref (checked-program-bindings checked) id)))
                                    (unless (eq (local-symbol-mutability symbol) :var)
                                      (internal-error "Immutable binding changed during lowering"))
                                    (push (cons parameter (local-symbol-type symbol)) params)
                                    (push va args-a) (push vb args-b)
                                    (setf merged (acons id parameter merged))))))
                            (setf (basic-block-parameters join) (nreverse params)
                                  (basic-block-terminator a-end) (list :jump (basic-block-id join) (nreverse args-a))
                                  (basic-block-terminator b-end) (list :jump (basic-block-id join) (nreverse args-b)))
                            (values result join merged)))))))
                 (t (internal-error "Invalid checked node")))))
      (let* ((span (if declaration (node-span declaration) (node-span (program-root program))))
             (entry (new-block span)) (env nil))
        (when declaration
          (loop for p across (function-declaration-parameters declaration)
                for type in (signature-parameter-types signature) for id = (new-value) do
            (push (cons id type) (basic-block-parameters entry))
            (push (cons (symbol-id p) id) env))
          (setf (basic-block-parameters entry) (nreverse (basic-block-parameters entry))))
        (multiple-value-bind (value end updated)
            (if declaration (lower (function-declaration-body declaration) entry env)
                (sequence-lower (program-statements program) (program-root program) entry nil nil))
          (declare (ignore updated))
          (when end (setf (basic-block-terminator end) (list :return value))))
        (dolist (block blocks)
          (setf (basic-block-instructions block) (nreverse (basic-block-instructions block))))
        (make-ir-function :id (signature-id signature) :parameter-types (signature-parameter-types signature)
                          :result-type (signature-result-type signature)
                          :entry (basic-block-id entry) :blocks (nreverse blocks) :span span)))))

(defun lower-program (checked)
  (verify-checked-program checked)
  (make-module :functions (map 'list (lambda (signature) (lower-function checked signature))
                               (checked-program-signatures checked))
               :span (node-span (program-root (checked-program-program checked)))))

(defun successors (block)
  (let ((term (basic-block-terminator block)))
    (case (first term)
      (:branch (list (third term) (fourth term)))
      (:jump (list (second term))) (:return nil)
      (otherwise (internal-error "Invalid SSA terminator")))))

(defun verify-function (function functions edges)
  (let ((blocks (make-hash-table)) (defs (make-hash-table)) (pred (make-hash-table))
        (dom (make-hash-table)) (colors (make-hash-table)) (order nil))
    (labels ((require-ir (v message) (unless v (internal-error message)))
             (define-value (v block pos type)
               (require-ir (and (typep v '(integer 0 *)) (not (gethash v defs))
                                (member type '(:bool :int))) "Invalid SSA definition")
               (setf (gethash v defs) (list block pos type)))
             (visit (id)
               (let ((stack (list id)))
                 (loop while stack for current = (pop stack) do
                   (unless (gethash current colors)
                     (setf (gethash current colors) t)
                     (push current order)
                     (dolist (next (reverse (successors (gethash current blocks))))
                       (push next stack))))))
             (check-use (v block pos)
               (let ((d (gethash v defs)))
                 (require-ir (and d (if (= (first d) block) (< (second d) pos)
                                        (member (first d) (gethash block dom))))
                             "Undefined or non-dominating value")
                 (third d))))
      (require-ir (and (ir-function-p function) (ir-function-blocks function)) "Invalid SSA module")
      (dolist (b (ir-function-blocks function))
        (let ((id (basic-block-id b)))
          (require-ir (and (typep id '(integer 0 *)) (not (gethash id blocks))) "Invalid block ID")
          (setf (gethash id blocks) b)
          (dolist (p (basic-block-parameters b)) (define-value (car p) id -1 (cdr p)))
          (loop for i in (basic-block-instructions b) for pos from 0 do
            (define-value (instruction-result i) id pos (instruction-type i)))))
      (require-ir (and (gethash (ir-function-entry function) blocks)
                       (equal (mapcar #'cdr (basic-block-parameters (gethash (ir-function-entry function) blocks)))
                              (ir-function-parameter-types function)))
                  "Invalid entry")
      (dolist (b (ir-function-blocks function))
        (let ((term (basic-block-terminator b)))
          (require-ir (case (first term) (:branch (= (length term) 4))
                        (:jump (= (length term) 3)) (:return (= (length term) 2))) "Invalid terminator")
          (dolist (next (successors b))
            (require-ir (gethash next blocks) "Missing successor")
            (pushnew (basic-block-id b) (gethash next pred)))))
      (visit (ir-function-entry function))
      (require-ir (= (length order) (hash-table-count blocks)) "Unreachable block")
      (require-ir (null (gethash (ir-function-entry function) pred)) "Entry has predecessors")
      (dolist (id order)
        (setf (gethash id dom) (if (= id (ir-function-entry function)) (list id) (copy-list order))))
      (loop with changed = t while changed do
        (setf changed nil)
        (dolist (id order)
          (unless (= id (ir-function-entry function))
            (let ((next (adjoin id (reduce #'intersection
                                  (mapcar (lambda (p) (gethash p dom)) (gethash id pred))))))
              (unless (and (subsetp next (gethash id dom)) (subsetp (gethash id dom) next))
                (setf (gethash id dom) next changed t))))))
      (dolist (b (ir-function-blocks function))
        (let ((id (basic-block-id b)) (pos 0))
          (dolist (i (basic-block-instructions b))
            (let* ((schema (if (eq (instruction-op i) :call) '(:call nil :call t)
                               (assoc (instruction-op i) *operations*)))
                   (operands (instruction-operands i))
                   (types (mapcar (lambda (v) (check-use v id pos)) operands))
                   (result (instruction-type i)))
              (require-ir (and schema (or (eq (third schema) :call) (= (length operands) (second schema)))) "Invalid operation arity")
              (require-ir
               (case (third schema)
                 (:call
                  (let ((callee (gethash (instruction-value i) functions)))
                    (push (cons (instruction-value i) (instruction-span i)) (gethash (ir-function-id function) edges))
                    (and callee (not (zerop (ir-function-id callee)))
                         (equal types (ir-function-parameter-types callee))
                         (eq result (ir-function-result-type callee)))))
                 (:literal (if (eq result :bool) (member (instruction-value i) '(0 1))
                               (mognitio.integer:in-range-p (instruction-value i))))
                 (:int (and (eq result :int) (every (lambda (x) (eq x :int)) types)))
                 (:equal (and (eq result :bool) (eq (first types) (second types))))
                 (:comparison (and (eq result :bool) (every (lambda (x) (eq x :int)) types))))
               "Invalid operation types or literal"))
            (incf pos))
          (let ((term (basic-block-terminator b)))
            (ecase (first term)
              (:branch
               (require-ir (eq (check-use (second term) id pos) :bool) "Non-bool branch")
               (dolist (next (rest (rest term)))
                 (require-ir (null (basic-block-parameters (gethash next blocks))) "Branch arguments missing")))
              (:jump
               (let ((params (basic-block-parameters (gethash (second term) blocks))) (args (third term)))
                 (require-ir (= (length params) (length args)) "Wrong jump arity")
                 (loop for p in params for a in args do
                   (require-ir (eq (cdr p) (check-use a id pos)) "Wrong jump argument type"))))
              (:return (require-ir (eq (check-use (second term) id pos) (ir-function-result-type function)) "Wrong return type"))))))
      function)))

(defun verify-module-internal (module)
  (unless (and (module-p module) (module-functions module) (eql (module-entry module) 0))
    (internal-error "Invalid SSA module"))
  (let ((ids (make-hash-table)) (edges (make-hash-table)))
    (dolist (function (module-functions module))
      (let ((id (ir-function-id function)))
        (unless (and (typep id '(integer 0 *)) (not (gethash id ids))
                     (member (ir-function-result-type function) '(:bool :int))
                     (every (lambda (x) (member x '(:bool :int))) (ir-function-parameter-types function)))
          (internal-error "Invalid function signature"))
        (setf (gethash id ids) function)))
    (dolist (function (module-functions module)) (verify-function function ids edges))
    (check-call-graph (mapcar #'ir-function-id (module-functions module)) edges
                      (lambda (span) (declare (ignore span)) (internal-error "Cyclic IR calls")))
    (let ((entry (gethash 0 ids)))
      (unless (and entry (null (ir-function-parameter-types entry))
                   (eq (ir-function-result-type entry) :bool))
        (internal-error "Invalid entry signature"))))
  module)

(defun verify-module (module)
  (handler-case (verify-module-internal module)
    (internal-failure (c) (error c))
    (error () (internal-error "Malformed SSA module"))))
