(in-package #:mognitio.ir)

(defstruct (instruction (:constructor %make-instruction))
  result (type :bool) op value operands span effects)

(defun operation-effects (op)
  (case op
    ((:call :call.value :call.interface :struct.make :enum.make :interface.pack :text.concat :text.slice) '(:may-allocate :may-fail :call-barrier))
    ((:text.length :text.equal :text.not-equal) '(:call-barrier))
    ((:neg :add :sub :mul :div :rem) '(:may-fail))))

(defun make-instruction (&key result (type :bool) op value operands span
                             (effects (operation-effects op)))
  (%make-instruction :result result :type type :op op :value value
                     :operands operands :span span :effects (copy-list effects)))
(defstruct basic-block id parameters instructions terminator span)
(defstruct ir-function id parameter-types (result-type :bool) blocks entry span method)
(defstruct module functions (entry 0) span (values (mognitio.semantic::make-value-context)) (literal-pool (vector (make-text-payload :octets (make-array 0 :element-type '(unsigned-byte 8)) :scalar-count 0))))
(defparameter *value-operations* '(:struct.make :enum.make :struct.field :enum.tag :enum.payload :interface.pack :call.interface))
(defparameter *operations*
  '((:constant 0 :literal nil) (:function 0 :function nil) (:neg 1 :int t) (:add 2 :int t)
    (:sub 2 :int t) (:mul 2 :int t) (:div 2 :int t) (:rem 2 :int t)
    (:eq 2 :equal nil) (:ne 2 :equal nil)
    (:lt 2 :comparison nil) (:le 2 :comparison nil)
    (:gt 2 :comparison nil) (:ge 2 :comparison nil)
    (:const.text 0 :text-literal nil) (:text.length 1 :text-length nil)
    (:text.equal 2 :text-equality nil) (:text.not-equal 2 :text-equality nil)
    (:text.concat 2 :text-concat t) (:text.slice 3 :text-slice t)))

(defun lower-function (checked signature intern-text)
  (unless (typep checked 'checked-program) (internal-error "Expected CheckedProgram"))
  (let ((contexts nil) (blocks nil) (next-block 0) (next-value 0)
        (program (checked-program-program checked)) (declaration (signature-declaration signature)))
    (labels ((new-block (span)
               (let ((b (make-basic-block :id next-block :span span)))
                 (incf next-block) (push b blocks) b))
             (new-value () (prog1 next-value (incf next-value)))
             (symbol-id (node) (local-symbol-id (checked-symbol checked node)))
             (value-for (id env)
               (let ((pair (assoc id env)))
                 (unless pair (internal-error "Missing SSA binding")) (cdr pair)))
             (emit-value (block type op span &key value operands)
               (let ((id (new-value)))
                 (push (make-instruction :result id :type type :op op :span span
                                         :value value :operands operands)
                       (basic-block-instructions block)) id))
             (sequence-lower (statements tail block env scoped)
               (let ((visible (mapcar #'car env)))
                 (loop for statement across statements do
                   (multiple-value-bind (v end updated) (lower statement block env)
                     (declare (ignore v))
                     (unless end (return-from sequence-lower (values nil nil nil)))
                     (setf block end env updated)))
                 (multiple-value-bind (v end updated)
                     (if tail (lower tail block env)
                         (values (emit-value block :void :constant (basic-block-span block) :value 0) block env))
                   (values v end (if scoped (remove-if-not (lambda (pair) (member (car pair) visible)) updated) updated)))))
             (jump-context (context end env &optional result)
               (let ((target (if result (third context) (second context))))
                 (unless target (internal-error "Missing loop exit"))
                 (setf (basic-block-terminator end)
                       (list :jump (basic-block-id target)
                             (append (when result (list result))
                                     (mapcar (lambda (id) (value-for id env)) (fourth context)))))))
             (lower (node block env)
               (multiple-value-bind (result end updated) (lower-raw node block env)
                 (let ((pack (checked-pack checked node)))
                   (when (and end pack)
                     (setf result (emit-value end (implementation-info-contract pack) :interface.pack (node-span node)
                                             :value (implementation-info-id pack) :operands (list result))))
                   (values result end updated))))
             (lower-raw (node block env)
               (unless block (return-from lower-raw (values nil nil nil)))
               (typecase node
                 ((or data-declaration contract-declaration implementation-declaration struct-expression enum-expression
                      field-expression this-expression branch-expression)
                  (lower-value-node node checked block env #'lower #'emit-value #'new-block #'new-value))
                 (loop-expression
                  (let* ((info (checked-loop checked node))
                         (ids (sort (remove-duplicates
                                (remove-if-not (lambda (id) (eq :var (local-symbol-mutability
                                                                  (aref (checked-program-bindings checked) id))))
                                               (mapcar #'car env))) #'<))
                         (header (new-block (node-span node)))
                         (exit (when (checked-normal-type checked node) (new-block (node-span node))))
                         (result (when exit (new-value)))
                         (header-env env) (exit-env env)
                         (context (list (loop-info-id info) header exit ids result)))
                    (dolist (id ids)
                      (let* ((type (local-symbol-type (aref (checked-program-bindings checked) id)))
                             (parameter (new-value)))
                        (setf (basic-block-parameters header) (append (basic-block-parameters header) (list (cons parameter type)))
                              header-env (acons id parameter header-env))))
                    (when exit
                      (setf (basic-block-parameters exit) (list (cons result (checked-normal-type checked node))))
                      (dolist (id ids)
                        (let ((parameter (new-value)) (type (local-symbol-type (aref (checked-program-bindings checked) id))))
                          (setf (basic-block-parameters exit) (append (basic-block-parameters exit) (list (cons parameter type)))
                                exit-env (acons id parameter exit-env)))))
                    (jump-context context block env)
                    (push context contexts)
                    (let ((body-start header) (body-env header-env))
                      (when (loop-expression-condition node)
                        (multiple-value-bind (condition end updated) (lower (loop-expression-condition node) header header-env)
                          (setf body-start nil)
                          (when end
                            (let ((yes (new-block (node-span node))) (no (new-block (node-span node))))
                              (setf (basic-block-terminator end) (list :branch condition (basic-block-id yes) (basic-block-id no))
                                    body-start yes body-env updated)
                              (jump-context context no updated (emit-value no :void :constant (node-span node) :value 0))))))
                      (when body-start
                        (multiple-value-bind (value end updated) (lower (loop-expression-body node) body-start body-env)
                          (declare (ignore value)) (when end (jump-context context end updated)))))
                    (pop contexts)
                    (if exit (values result exit exit-env) (values nil nil nil))))
                 (break-statement
                  (let ((context (assoc (loop-info-id (checked-control checked node)) contexts)))
                    (multiple-value-bind (value end updated)
                        (if (break-statement-value node) (lower (break-statement-value node) block env)
                            (values (emit-value block :void :constant (node-span node) :value 0) block env))
                      (when end (jump-context context end updated value))
                      (values nil nil nil))))
                 (continue-statement
                  (jump-context (assoc (loop-info-id (checked-control checked node)) contexts) block env)
                  (values nil nil nil))
                 (void-literal (values (emit-value block :void :constant (node-span node) :value 0) block env))
                 (expression-statement (lower (expression-statement-expression node) block env))
                 ((or local-binding assignment)
                  (multiple-value-bind (value end updated)
                      (lower (etypecase node (local-binding (local-binding-initializer node)) (assignment (assignment-rhs node))) block env)
                    (values nil end (when end (acons (symbol-id node) value updated)))))
                 (return-statement
                  (unless (= (checked-return checked node) (signature-id signature))
                    (internal-error "Return owner mismatch"))
                  (multiple-value-bind (value end updated) (if (return-statement-value node) (lower (return-statement-value node) block env)
                        (values (emit-value block :void :constant (node-span node) :value 0) block env))
                    (declare (ignore updated))
                    (when end (setf (basic-block-terminator end) (list :return value)))
                    (values nil nil nil)))
                 (call-expression
                  (let ((arguments nil))
                    (dolist (arg (cons (call-expression-callee node) (coerce (call-expression-arguments node) 'list)))
                      (multiple-value-bind (value end updated) (lower arg block env)
                        (unless end (return-from lower-raw (values nil nil nil)))
                        (push value arguments) (setf block end env updated)))
                    (let ((info (checked-call checked node)))
                      (values (emit-value block (checked-normal-type checked node) :call.value (node-span node)
                                :value (list (call-info-type info) (call-info-targets info))
                                :operands (nreverse arguments)) block env))))
                 (method-call
                  (when (not (checked-operation checked node))
                    (return-from lower-raw (lower-value-node node checked block env #'lower #'emit-value #'new-block #'new-value)))
                  (let ((operands nil))
                    (dolist (child (cons (method-call-receiver node) (coerce (method-call-arguments node) 'list)))
                      (multiple-value-bind (value end updated) (lower child block env)
                        (unless end (return-from lower-raw (values nil nil nil)))
                        (push value operands) (setf block end env updated)))
                    (values (emit-value block (checked-normal-type checked node)
                              (operation-info-kind (checked-operation checked node)) (node-span node)
                              :operands (nreverse operands)) block env)))
                 (string-literal
                  (values (emit-value block :string :const.text (node-span node)
                                      :value (funcall intern-text (string-literal-payload node))) block env))
                 ((or function-expression concrete-function-reference)
                  (values (emit-value block (checked-normal-type checked node) :function (node-span node)
                                      :value (signature-id (checked-function checked node))) block env))
                 (boolean-literal
                  (values (emit-value block :bool :constant (node-span node)
                             :value (ecase (boolean-literal-value node) (:true 1) (:false 0))) block env))
                 (integer-literal
                  (values (emit-value block :int :constant (node-span node)
                                      :value (checked-literal checked node)) block env))
                 (variable-reference
                  (let ((symbol (checked-symbol checked node)))
                    (values (if (= (local-symbol-owner symbol) (signature-id signature))
                                (value-for (symbol-id node) env)
                                (emit-value block (local-symbol-type symbol) :function (node-span node)
                                            :value (local-symbol-static-target symbol))) block env)))
                 (grouping (lower (grouping-expression node) block env))
                 (sequence-node
                  (sequence-lower (sequence-node-statements node) (sequence-node-terminal node) block env t))
                 (unary-expression
                  (if (checked-literal-p checked node)
                      (values (emit-value block :int :constant (node-span node)
                                          :value (checked-literal checked node)) block env)
                      (multiple-value-bind (v end updated) (lower (unary-expression-operand node) block env)
                        (unless end (return-from lower-raw (values nil nil nil)))
                        (values (emit-value end :int :neg (node-span node) :operands (list v)) end updated))))
                 (binary-expression
                  (multiple-value-bind (a a-end a-env) (lower (binary-expression-left node) block env)
                    (unless a-end (return-from lower-raw (values nil nil nil)))
                    (multiple-value-bind (b b-end b-env) (lower (binary-expression-right node) a-end a-env)
                      (unless b-end (return-from lower-raw (values nil nil nil)))
                      (values (emit-value b-end (checked-normal-type checked node)
                                (let ((info (checked-operation checked node)))
                                  (if info (operation-info-kind info) (token-kind (binary-expression-operator node))))
                                (node-span node)
                                :operands (list a b)) b-end b-env))))
                 (if-expression
                  (multiple-value-bind (condition condition-end condition-env)
                      (lower (if-expression-condition node) block env)
                    (unless condition-end (return-from lower-raw (values nil nil nil)))
                    (let ((then (new-block (node-span node))) (else (new-block (node-span node))))
                      (setf (basic-block-terminator condition-end)
                            (list :branch condition (basic-block-id then) (basic-block-id else)))
                      (multiple-value-bind (a a-end a-env)
                          (lower (if-expression-then-branch node) then condition-env)
                        (multiple-value-bind (b b-end b-env)
                            (if (if-expression-else-branch node) (lower (if-expression-else-branch node) else condition-env)
                              (values (emit-value else :void :constant (node-span node) :value 0) else condition-env))
                          (cond ((and (null a-end) (null b-end)) (return-from lower-raw (values nil nil nil)))
                                ((null a-end) (return-from lower-raw (values b b-end b-env)))
                                ((null b-end) (return-from lower-raw (values a a-end a-env))))
                          (let* ((join (new-block (node-span node))) (result (new-value))
                                 (params (list (cons result (checked-normal-type checked node))))
                                 (args-a (list a)) (args-b (list b)) (merged condition-env))
                            (dolist (id (sort (remove-duplicates (mapcar #'car condition-env)) #'<))
                              (let ((va (value-for id a-env)) (vb (value-for id b-env)))
                                ;; Equal incoming IDs can still replace the pre-branch value.
                                (when (and (= va vb) (/= va (value-for id condition-env)))
                                  (setf merged (acons id va merged)))
                                (unless (= va vb)
                                  (let ((parameter (new-value))
                                        (symbol (aref (checked-program-bindings checked) id)))
                                    (unless (eq (local-symbol-mutability symbol) :var)
                                      (internal-error "Immutable binding changed during lowering"))
                                    (push (cons parameter (local-symbol-type symbol)) params)
                                    (push va args-a) (push vb args-b)
                                    (setf merged (acons id parameter merged))))))
                            (setf (basic-block-parameters join) (nreverse params)
                                  (basic-block-terminator a-end) (list :jump (basic-block-id join) (nreverse args-a))
                                  (basic-block-terminator b-end) (list :jump (basic-block-id join) (nreverse args-b)))
                            (values result join merged)))))))
                 (t (internal-error "Invalid checked node")))))
      (let* ((span (if declaration (node-span declaration) (node-span (program-root program))))
             (entry (new-block span)) (env nil))
        (when declaration
          (when (signature-receiver signature)
            (let ((id (new-value)) (symbol (signature-receiver signature)))
              (push (cons id (local-symbol-type symbol)) (basic-block-parameters entry))
              (push (cons (local-symbol-id symbol) id) env)))
          (loop for p across (function-expression-parameters declaration)
                for type in (signature-parameter-types signature) for id = (new-value) do
            (push (cons id type) (basic-block-parameters entry))
            (push (cons (symbol-id p) id) env))
          (setf (basic-block-parameters entry) (nreverse (basic-block-parameters entry))))
        (multiple-value-bind (value end updated)
            (if declaration (lower (function-expression-body declaration) entry env)
                (sequence-lower (program-statements program) (program-root program) entry nil nil))
          (declare (ignore updated))
          (when end (setf (basic-block-terminator end) (list :return value))))
        (dolist (block blocks)
          (setf (basic-block-instructions block) (nreverse (basic-block-instructions block))))
        (make-ir-function :id (signature-id signature) :parameter-types (signature-runtime-types signature) :method (signature-method signature)
                          :result-type (signature-result-type signature)
                          :entry (basic-block-id entry) :blocks (nreverse blocks) :span span)))))

(defun lower-program (checked)
  (setf checked (mognitio.semantic::prepare-runtime-program checked))
  (let ((pool (make-array 0 :adjustable t :fill-pointer 0))
        (ids (make-hash-table :test #'equalp)))
    (labels ((register (payload)
               (let ((bytes (text-payload-octets payload)))
                 (unless (nth-value 1 (gethash bytes ids))
                   (setf (gethash bytes ids)
                         (vector-push-extend
                          (make-text-payload :octets (copy-seq bytes)
                                             :scalar-count (text-payload-scalar-count payload)) pool)))))
             (literal-id (payload)
               (multiple-value-bind (id found) (gethash (text-payload-octets payload) ids)
                 (unless found (internal-error "Unregistered text literal")) id)))
      (register (make-text-payload :octets (make-array 0 :element-type '(unsigned-byte 8)) :scalar-count 0))
      (dolist (node (checked-string-literals checked)) (register (string-literal-payload node)))
      (make-module :functions (map 'list (lambda (signature) (lower-function checked signature #'literal-id))
                                    (checked-program-signatures checked))
                   :literal-pool (coerce pool 'simple-vector) :values (checked-program-values checked)
                   :span (node-span (program-root (checked-program-program checked)))))))

(defun successors (block)
  (let ((term (basic-block-terminator block)))
    (case (first term)
      (:branch (list (third term) (fourth term)))
      (:jump (list (second term))) ((:return :trap) nil)
      (otherwise (internal-error "Invalid SSA terminator")))))

(defun verify-function (function functions edges pool context)
  (let ((blocks (make-hash-table)) (defs (make-hash-table)) (pred (make-hash-table))
        (candidates (make-hash-table)) (dom (make-hash-table)) (colors (make-hash-table)) (order nil))
    (labels ((require-ir (v message) (unless v (internal-error message)))
             (define-value (v block pos type)
               (require-ir (and (typep v '(integer 0 *)) (not (gethash v defs))
                                (or (valid-value-type-p type) (function-type-p type))) "Invalid SSA definition")
               (setf (gethash v defs) (list block pos type)))
             (visit (id)
               (let ((stack (list id)))
                 (loop while stack for current = (pop stack) do
                   (unless (gethash current colors)
                     (setf (gethash current colors) t)
                     (push current order)
                     (dolist (next (reverse (successors (gethash current blocks))))
                       (push next stack))))))
             (check-use (v block pos)
               (let ((d (gethash v defs)))
                 (require-ir (and d (if (= (first d) block) (< (second d) pos)
                                        (member (first d) (gethash block dom))))
                             "Undefined or non-dominating value")
                 (third d))))
      (require-ir (and (ir-function-p function) (ir-function-blocks function)) "Invalid SSA module")
      (dolist (b (ir-function-blocks function))
        (let ((id (basic-block-id b)))
          (require-ir (and (typep id '(integer 0 *)) (not (gethash id blocks))) "Invalid block ID")
          (setf (gethash id blocks) b)
          (dolist (p (basic-block-parameters b)) (define-value (car p) id -1 (cdr p)))
          (loop for i in (basic-block-instructions b) for pos from 0 do
            (define-value (instruction-result i) id pos (instruction-type i)))))
      (require-ir (and (gethash (ir-function-entry function) blocks)
                       (equal (mapcar #'cdr (basic-block-parameters (gethash (ir-function-entry function) blocks)))
                              (ir-function-parameter-types function)))
                  "Invalid entry")
      (dolist (b (ir-function-blocks function))
        (let ((term (basic-block-terminator b)))
          (require-ir (case (first term) (:branch (= (length term) 4))
                        (:jump (= (length term) 3)) (:return (= (length term) 2)) (:trap (= (length term) 1))) "Invalid terminator")
          (dolist (next (successors b))
            (require-ir (gethash next blocks) "Missing successor")
            (pushnew (basic-block-id b) (gethash next pred)))))
      (visit (ir-function-entry function))
      (require-ir (= (length order) (hash-table-count blocks)) "Unreachable block")
      (require-ir (null (gethash (ir-function-entry function) pred)) "Entry has predecessors")
      (dolist (id order)
        (setf (gethash id dom) (if (= id (ir-function-entry function)) (list id) (copy-list order))))
      (loop with changed = t while changed do
        (setf changed nil)
        (dolist (id order)
          (unless (= id (ir-function-entry function))
            (let ((next (adjoin id (reduce #'intersection
                                  (mapcar (lambda (p) (gethash p dom)) (gethash id pred))))))
              (unless (and (subsetp next (gethash id dom)) (subsetp (gethash id dom) next))
                (setf (gethash id dom) next changed t))))))
      ;; Least fixed point: all values start empty, constants seed singletons.
      ;; Call annotations never seed this independent analysis.
      (dolist (b (ir-function-blocks function))
        (dolist (i (basic-block-instructions b))
          (when (eq (instruction-op i) :function)
            (setf (gethash (instruction-result i) candidates) (list (instruction-value i))))))
      (loop with changed = t while changed do
        (setf changed nil)
        (dolist (b (sort (copy-list (ir-function-blocks function)) #'< :key #'basic-block-id))
          (let ((term (basic-block-terminator b)))
            (when (eq (first term) :jump)
              (loop for p in (basic-block-parameters (gethash (second term) blocks))
                    for arg in (third term) when (function-type-p (cdr p)) do
                (let* ((old (gethash (car p) candidates))
                       (next (union old (gethash arg candidates))))
                  (unless (subsetp next old)
                    (setf (gethash (car p) candidates) next changed t))))))))
      (maphash (lambda (id definition)
                 (when (function-type-p (third definition))
                   (require-ir (gethash id candidates) "Empty function candidate set"))) defs)
      (dolist (b (ir-function-blocks function))
        (let ((id (basic-block-id b)) (pos 0))
          (dolist (i (basic-block-instructions b))
            (let* ((schema (cond ((member (instruction-op i) *value-operations*) (list (instruction-op i) nil :value t))
                                 ((member (instruction-op i) '(:call :call.value)) (list (instruction-op i) nil (instruction-op i) t))
                                 (t (assoc (instruction-op i) *operations*))))
                   (operands (instruction-operands i))
                   (types (mapcar (lambda (v) (check-use v id pos)) operands))
                   (result (instruction-type i)))
              (require-ir (and schema (or (member (third schema) '(:call :call.value :value)) (= (length operands) (second schema)))) "Invalid operation arity")
              (require-ir (equal (instruction-effects i) (operation-effects (instruction-op i)))
                          "Invalid operation effects")
              (require-ir
               (case (third schema)
                 (:value (verify-value-instruction i types context functions id pos defs blocks dom edges (ir-function-id function)))
                 (:call
                  (let ((callee (gethash (instruction-value i) functions)))
                    (push (cons (instruction-value i) (instruction-span i)) (gethash (ir-function-id function) edges))
                    (and callee (not (zerop (ir-function-id callee)))
                         (equal types (ir-function-parameter-types callee))
                         (equal result (ir-function-result-type callee)))))
                 (:function
                  (let ((target (gethash (instruction-value i) functions)))
                    (and target (plusp (ir-function-id target)) (null (ir-function-method target))
                         (equal result (list :function (ir-function-parameter-types target) (ir-function-result-type target))))))
                 (:call.value
                  (let ((type (first (instruction-value i))) (targets (second (instruction-value i)))
                        (actual (gethash (first operands) candidates)))
                    (and (function-type-p type) (equal (first types) type)
                         (equal (rest types) (second type)) (equal result (third type))
                         actual (= (length targets) (length (remove-duplicates targets)))
                         (subsetp targets actual) (subsetp actual targets)
                         (every (lambda (target)
                                  (let ((callee (gethash target functions)))
                                    (push (cons target (instruction-span i)) (gethash (ir-function-id function) edges))
                                    (and callee (plusp target)
                                         (equal (second type) (ir-function-parameter-types callee))
                                         (equal (third type) (ir-function-result-type callee))))) targets))))
                 (:literal (if (eq result :void) (eql (instruction-value i) 0) (if (eq result :bool) (member (instruction-value i) '(0 1))
                               (and (eq result :int) (mognitio.integer:in-range-p (instruction-value i))))))
                 (:text-literal (and (eq result :string)
                                     (typep (instruction-value i) '(integer 0 *))
                                     (< (instruction-value i) (length pool))))
                 (:text-length (and (eq result :int) (equal types '(:string))))
                 (:text-equality (and (eq result :bool) (equal types '(:string :string))))
                 (:text-concat (and (eq result :string) (equal types '(:string :string))))
                 (:text-slice (and (eq result :string) (equal types '(:string :int :int))))
                 (:int (and (eq result :int) (every (lambda (x) (eq x :int)) types)))
                 (:equal (and (eq result :bool) (member (first types) '(:int :bool)) (eq (first types) (second types))))
                 (:comparison (and (eq result :bool) (every (lambda (x) (eq x :int)) types))))
               "Invalid operation types or literal"))
            (incf pos))
          (let ((term (basic-block-terminator b)))
            (ecase (first term)
              (:branch
               (require-ir (eq (check-use (second term) id pos) :bool) "Non-bool branch")
               (dolist (next (rest (rest term)))
                 (require-ir (null (basic-block-parameters (gethash next blocks))) "Branch arguments missing")))
              (:jump
               (let ((params (basic-block-parameters (gethash (second term) blocks))) (args (third term)))
                 (require-ir (= (length params) (length args)) "Wrong jump arity")
                 (loop for p in params for a in args do
                   (require-ir (equal (cdr p) (check-use a id pos)) "Wrong jump argument type"))))
              (:trap nil)
              (:return (require-ir (equal (check-use (second term) id pos) (ir-function-result-type function)) "Wrong return type"))))))
      function)))

(defun verify-module-internal (module)
  (unless (and (module-p module) (module-functions module) (eql (module-entry module) 0))
    (internal-error "Invalid SSA module"))
  (unless (and (vectorp (module-literal-pool module)) (plusp (length (module-literal-pool module)))) (internal-error "Invalid text literal pool"))
  (loop for payload across (module-literal-pool module) do
    (let* ((bytes (text-payload-octets payload))
           (text (sb-ext:octets-to-string bytes :external-format :utf-8)))
      (unless (and (typep bytes '(simple-array (unsigned-byte 8) (*)))
                   (typep (text-payload-scalar-count payload) '(integer 0 *))
                   (= (length text) (text-payload-scalar-count payload))
                   (<= (length bytes) mognitio.integer:+maximum+)
                   (equalp bytes (sb-ext:string-to-octets text :external-format :utf-8))
                   (every (lambda (ch) (let ((n (char-code ch)))
                                        (and (<= n #x10ffff) (not (<= #xd800 n #xdfff))))) text))
        (internal-error "Invalid Core text literal payload"))))
  (unless (zerop (length (text-payload-octets (aref (module-literal-pool module) 0))))
    (internal-error "Literal pool zero must be empty"))
  (let ((seen (make-hash-table :test #'equalp)))
    (loop for p across (module-literal-pool module) for bytes = (text-payload-octets p) do
      (when (gethash bytes seen) (internal-error "Duplicate text literal payload"))
      (setf (gethash bytes seen) t)))
  (let ((ids (make-hash-table)) (edges (make-hash-table)))
    (dolist (function (module-functions module))
      (let ((id (ir-function-id function)))
        (unless (and (typep id '(integer 0 *)) (not (gethash id ids))
                     (valid-value-type-p (ir-function-result-type function))
                     (every #'valid-value-type-p (ir-function-parameter-types function)))
          (internal-error "Invalid function signature"))
        (setf (gethash id ids) function)))
    (verify-core-types (module-values module) ids)
    (dolist (function (module-functions module)) (verify-function function ids edges (module-literal-pool module) (module-values module)))
    (check-call-graph (mapcar #'ir-function-id (module-functions module)) edges
                      (lambda (span) (declare (ignore span)) (internal-error "Cyclic IR calls")))
    (let ((entry (gethash 0 ids)))
      (unless (and entry (null (ir-function-parameter-types entry))
                   (eq (ir-function-result-type entry) :bool))
        (internal-error "Invalid entry signature"))))
  module)

(defun verify-module (module)
  (handler-case (verify-module-internal module)
    (internal-failure (c) (error c))
    (error () (internal-error "Malformed SSA module"))))
