(in-package #:mognitio.ir)

(defstruct instruction result (type :bool) op value operands span)
(defstruct basic-block id parameters instructions terminator span)
(defstruct module blocks entry span)
(defparameter *operations*
  '((:constant 0 :literal nil) (:neg 1 :int t) (:add 2 :int t)
    (:sub 2 :int t) (:mul 2 :int t) (:div 2 :int t) (:rem 2 :int t)
    (:eq 2 :equal nil) (:ne 2 :equal nil)
    (:lt 2 :comparison nil) (:le 2 :comparison nil)
    (:gt 2 :comparison nil) (:ge 2 :comparison nil)))

(defun lower-program (checked)
  (unless (typep checked 'checked-program) (internal-error "Expected CheckedProgram"))
  (let ((blocks nil) (next-block 0) (next-value 0)
        (program (checked-program-program checked)))
    (labels ((new-block (span)
               (let ((b (make-basic-block :id next-block :span span)))
                 (incf next-block) (push b blocks) b))
             (new-value () (prog1 next-value (incf next-value)))
             (symbol-id (node) (local-symbol-id (checked-symbol checked node)))
             (value-for (id env)
               (let ((pair (assoc id env)))
                 (unless pair (internal-error "Missing SSA binding")) (cdr pair)))
             (emit-value (block type op span &key value operands)
               (let ((id (new-value)))
                 (push (make-instruction :result id :type type :op op :span span
                                         :value value :operands operands)
                       (basic-block-instructions block)) id))
             (sequence-lower (statements tail block env scoped)
               (let ((visible (mapcar #'car env)))
                 (loop for statement across statements do
                   (multiple-value-bind (v end updated)
                       (lower (etypecase statement
                                (local-binding (local-binding-initializer statement))
                                (assignment (assignment-rhs statement))) block env)
                     (setf block end env (acons (symbol-id statement) v updated))))
                 (multiple-value-bind (v end updated) (lower tail block env)
                   (values v end (if scoped
                                     (remove-if-not (lambda (pair) (member (car pair) visible)) updated)
                                     updated)))))
             (lower (node block env)
               (typecase node
                 (boolean-literal
                  (values (emit-value block :bool :constant (node-span node)
                             :value (ecase (boolean-literal-value node) (:true 1) (:false 0))) block env))
                 (integer-literal
                  (values (emit-value block :int :constant (node-span node)
                                      :value (checked-literal checked node)) block env))
                 (variable-reference (values (value-for (symbol-id node) env) block env))
                 (grouping (lower (grouping-expression node) block env))
                 (sequence-node
                  (sequence-lower (sequence-node-statements node) (sequence-node-tail node) block env t))
                 (unary-expression
                  (if (checked-literal-p checked node)
                      (values (emit-value block :int :constant (node-span node)
                                          :value (checked-literal checked node)) block env)
                      (multiple-value-bind (v end updated) (lower (unary-expression-operand node) block env)
                        (values (emit-value end :int :neg (node-span node) :operands (list v)) end updated))))
                 (binary-expression
                  (multiple-value-bind (a a-end a-env) (lower (binary-expression-left node) block env)
                    (multiple-value-bind (b b-end b-env) (lower (binary-expression-right node) a-end a-env)
                      (values (emit-value b-end (checked-type checked node)
                                (token-kind (binary-expression-operator node)) (node-span node)
                                :operands (list a b)) b-end b-env))))
                 (if-expression
                  (multiple-value-bind (condition condition-end condition-env)
                      (lower (if-expression-condition node) block env)
                    (let ((then (new-block (node-span node))) (else (new-block (node-span node))))
                      (setf (basic-block-terminator condition-end)
                            (list :branch condition (basic-block-id then) (basic-block-id else)))
                      (multiple-value-bind (a a-end a-env)
                          (lower (if-expression-then-branch node) then condition-env)
                        (multiple-value-bind (b b-end b-env)
                            (lower (if-expression-else-branch node) else condition-env)
                          (let* ((join (new-block (node-span node))) (result (new-value))
                                 (params (list (cons result (checked-type checked node))))
                                 (args-a (list a)) (args-b (list b)) (merged condition-env))
                            (dolist (id (sort (remove-duplicates (mapcar #'car condition-env)) #'<))
                              (let ((va (value-for id a-env)) (vb (value-for id b-env)))
                                (unless (= va vb)
                                  (let ((parameter (new-value))
                                        (symbol (aref (checked-program-bindings checked) id)))
                                    (unless (eq (local-symbol-mutability symbol) :var)
                                      (internal-error "Immutable binding changed during lowering"))
                                    (push (cons parameter (local-symbol-type symbol)) params)
                                    (push va args-a) (push vb args-b)
                                    (setf merged (acons id parameter merged))))))
                            (setf (basic-block-parameters join) (nreverse params)
                                  (basic-block-terminator a-end) (list :jump (basic-block-id join) (nreverse args-a))
                                  (basic-block-terminator b-end) (list :jump (basic-block-id join) (nreverse args-b)))
                            (values result join merged)))))))
                 (t (internal-error "Invalid checked node")))))
      (let ((entry (new-block (node-span (program-root program)))))
        (multiple-value-bind (value end env)
            (sequence-lower (program-statements program) (program-root program) entry nil nil)
          (declare (ignore env))
          (setf (basic-block-terminator end) (list :return value)))
        (dolist (block blocks)
          (setf (basic-block-instructions block) (nreverse (basic-block-instructions block))))
        (make-module :entry (basic-block-id entry) :blocks (nreverse blocks)
                     :span (node-span (program-root program)))))))

(defun successors (block)
  (let ((term (basic-block-terminator block)))
    (case (first term)
      (:branch (list (third term) (fourth term)))
      (:jump (list (second term))) (:return nil)
      (otherwise (internal-error "Invalid SSA terminator")))))

(defun verify-module-internal (module)
  (let ((blocks (make-hash-table)) (defs (make-hash-table)) (pred (make-hash-table))
        (dom (make-hash-table)) (colors (make-hash-table)) (order nil))
    (labels ((require-ir (v message) (unless v (internal-error message)))
             (define-value (v block pos type)
               (require-ir (and (typep v '(integer 0 *)) (not (gethash v defs))
                                (member type '(:bool :int))) "Invalid SSA definition")
               (setf (gethash v defs) (list block pos type)))
             (visit (id)
               (case (gethash id colors)
                 (:gray (internal-error "Cyclic SSA"))
                 (:black nil)
                 (t (setf (gethash id colors) :gray)
                    (dolist (next (successors (gethash id blocks))) (visit next))
                    (setf (gethash id colors) :black) (push id order))))
             (check-use (v block pos)
               (let ((d (gethash v defs)))
                 (require-ir (and d (if (= (first d) block) (< (second d) pos)
                                        (member (first d) (gethash block dom))))
                             "Undefined or non-dominating value")
                 (third d))))
      (require-ir (and (module-p module) (module-blocks module)) "Invalid SSA module")
      (dolist (b (module-blocks module))
        (let ((id (basic-block-id b)))
          (require-ir (and (typep id '(integer 0 *)) (not (gethash id blocks))) "Invalid block ID")
          (setf (gethash id blocks) b)
          (dolist (p (basic-block-parameters b)) (define-value (car p) id -1 (cdr p)))
          (loop for i in (basic-block-instructions b) for pos from 0 do
            (define-value (instruction-result i) id pos (instruction-type i)))))
      (require-ir (and (gethash (module-entry module) blocks)
                       (null (basic-block-parameters (gethash (module-entry module) blocks))))
                  "Invalid entry")
      (dolist (b (module-blocks module))
        (let ((term (basic-block-terminator b)))
          (require-ir (case (first term) (:branch (= (length term) 4))
                        (:jump (= (length term) 3)) (:return (= (length term) 2))) "Invalid terminator")
          (dolist (next (successors b))
            (require-ir (gethash next blocks) "Missing successor")
            (pushnew (basic-block-id b) (gethash next pred)))))
      (visit (module-entry module))
      (require-ir (= (length order) (hash-table-count blocks)) "Unreachable block")
      (dolist (id order)
        (setf (gethash id dom)
              (cons id (when (gethash id pred)
                         (reduce (lambda (a b) (intersection a b))
                                 (mapcar (lambda (p) (gethash p dom)) (gethash id pred)))))))
      (dolist (b (module-blocks module))
        (let ((id (basic-block-id b)) (pos 0))
          (dolist (i (basic-block-instructions b))
            (let* ((schema (assoc (instruction-op i) *operations*))
                   (operands (instruction-operands i))
                   (types (mapcar (lambda (v) (check-use v id pos)) operands))
                   (result (instruction-type i)))
              (require-ir (and schema (= (length operands) (second schema))) "Invalid operation arity")
              (require-ir
               (case (third schema)
                 (:literal (if (eq result :bool) (member (instruction-value i) '(0 1))
                               (mognitio.integer:in-range-p (instruction-value i))))
                 (:int (and (eq result :int) (every (lambda (x) (eq x :int)) types)))
                 (:equal (and (eq result :bool) (eq (first types) (second types))))
                 (:comparison (and (eq result :bool) (every (lambda (x) (eq x :int)) types))))
               "Invalid operation types or literal"))
            (incf pos))
          (let ((term (basic-block-terminator b)))
            (ecase (first term)
              (:branch
               (require-ir (eq (check-use (second term) id pos) :bool) "Non-bool branch")
               (dolist (next (rest (rest term)))
                 (require-ir (null (basic-block-parameters (gethash next blocks))) "Branch arguments missing")))
              (:jump
               (let ((params (basic-block-parameters (gethash (second term) blocks))) (args (third term)))
                 (require-ir (= (length params) (length args)) "Wrong jump arity")
                 (loop for p in params for a in args do
                   (require-ir (eq (cdr p) (check-use a id pos)) "Wrong jump argument type"))))
              (:return (require-ir (eq (check-use (second term) id pos) :bool) "Non-bool return"))))))
      module)))
(defun verify-module (module)
  (handler-case (verify-module-internal module)
    (internal-failure (c) (error c))
    (error () (internal-error "Malformed SSA module"))))
