(in-package #:mognitio.frontend)

(defun ascii-letter-p (ch)
  (or (char<= #\A ch #\Z) (char<= #\a ch #\z)))
(defun ascii-digit-p (ch) (char<= #\0 ch #\9))
(defun word-start-p (ch) (or (ascii-letter-p ch) (char= ch #\_)))
(defparameter *keywords*
  '(("true" . :true) ("false" . :false) ("if" . :if) ("else" . :else)
    ("let" . :let) ("var" . :var)
    ("void" . :void) ("function" . :function) ("return" . :return) ("int" . :int) ("bool" . :bool)))
(defparameter *operators*
  '(("==" . :eq) ("!=" . :ne) ("<=" . :le) (">=" . :ge)
    ("=" . :assign) ("+" . :add) ("-" . :sub) ("*" . :mul)
    ("/" . :div) ("%" . :rem) ("<" . :lt) (">" . :gt)
    ("(" . :left-paren) (")" . :right-paren)
    ("{" . :left-brace) ("}" . :right-brace) (";" . :semicolon) ("," . :comma) (":" . :colon)))
(defun lex-source (source)
  (let ((text (source-text source)) (cursor 0)
        (tokens (make-array 0 :adjustable t :fill-pointer 0)))
    (labels ((emit (kind start)
               (vector-push-extend
                (make-token :kind kind :span (make-span source start cursor)) tokens)))
      (loop while (< cursor (length text)) for ch = (char text cursor) do
        (cond
          ((find ch '(#\Space #\Tab #\Newline #\Return)) (incf cursor))
          ((word-start-p ch)
           (let ((start cursor))
             (loop while (and (< cursor (length text))
                              (or (word-start-p (char text cursor))
                                  (ascii-digit-p (char text cursor))))
                   do (incf cursor))
             (emit (or (cdr (assoc (subseq text start cursor) *keywords* :test #'string=))
                       :identifier) start)))
          ((ascii-digit-p ch)
           (let ((start cursor))
             (loop while (and (< cursor (length text)) (ascii-digit-p (char text cursor)))
                   do (incf cursor))
             (when (and (< cursor (length text)) (word-start-p (char text cursor)))
               (fail-at (make-span source start (1+ cursor)) :lex "Invalid decimal boundary"))
             (emit :integer start)))
          (t
           (let ((entry (find-if
                         (lambda (pair)
                           (let ((end (+ cursor (length (car pair)))))
                             (and (<= end (length text))
                                  (string= (car pair) text :start2 cursor :end2 end))))
                         *operators*))
                 (start cursor))
             (unless entry
               (fail-at (make-span source cursor (1+ cursor)) :lex "Undefined character"))
             (incf cursor (length (car entry)))
             (emit (cdr entry) start)))))
      (emit :eof cursor))
    tokens))
