(in-package #:mognitio.frontend)

(defun ascii-letter-p (ch)
  (or (char<= #\A ch #\Z) (char<= #\a ch #\z)))
(defun ascii-digit-p (ch) (char<= #\0 ch #\9))
(defun word-start-p (ch) (or (ascii-letter-p ch) (char= ch #\_)))
(defparameter *keywords*
  '(("true" . :true) ("false" . :false) ("if" . :if) ("else" . :else)
    ("let" . :let) ("var" . :var)
    ("type" . :type) ("struct" . :struct) ("enum" . :enum) ("interface" . :interface)
    ("implement" . :implement) ("against" . :against) ("this" . :this)
    ("branch" . :branch) ("when" . :when) ("on" . :on) ("match" . :match)
    ("while" . :while) ("loop" . :loop) ("break" . :break) ("continue" . :continue) ("string" . :string) ("void" . :void) ("function" . :function) ("return" . :return) ("int" . :int) ("bool" . :bool)))
(defparameter *operators*
  '(("::" . :scope) ("=>" . :fat-arrow) ("->" . :arrow) ("==" . :eq) ("!=" . :ne) ("<=" . :le) (">=" . :ge)
    ("=" . :assign) ("+" . :add) ("-" . :sub) ("*" . :mul)
    ("/" . :div) ("%" . :rem) ("<" . :lt) (">" . :gt)
    ("(" . :left-paren) (")" . :right-paren)
    ("{" . :left-brace) ("}" . :right-brace) (";" . :semicolon) ("," . :comma) (":" . :colon)))
(defun lex-source (source)
  (let ((text (source-text source)) (cursor 0)
        (tokens (make-array 0 :adjustable t :fill-pointer 0)))
    (labels ((emit (kind start &optional payload)
               (vector-push-extend
                (make-token :kind kind :span (make-span source start cursor) :payload payload) tokens))
             (scan-string ()
               (let ((start cursor) (chars (make-array 0 :element-type 'character :adjustable t :fill-pointer 0)))
                 (incf cursor)
                 (loop
                   (when (= cursor (length text))
                     (fail-at (make-span source start (1+ start)) :lex "Unterminated string literal"))
                   (let ((ch (char text cursor)) (at cursor))
                     (incf cursor)
                     (cond
                       ((char= ch #\") (return))
                       ((char= ch #\\)
                        (when (= cursor (length text))
                          (fail-at (make-span source start (1+ start)) :lex "Unterminated string literal"))
                        (let* ((escape (char text cursor))
                               (value (case escape
                                        (#\" #\") (#\\ #\\) (#\n #\Newline)
                                        (#\r #\Return) (#\t #\Tab) (#\0 (code-char 0)))))
                          (unless value (fail-at (make-span source at (1+ cursor)) :lex "Invalid string escape"))
                          (incf cursor) (vector-push-extend value chars)))
                       ((or (< (char-code ch) 32) (= (char-code ch) 127))
                        (fail-at (make-span source at cursor) :lex "Raw control in string literal"))
                       (t (vector-push-extend ch chars)))))
                 (emit :string-literal start
                       (make-text-payload :octets (sb-ext:string-to-octets chars :external-format :utf-8)
                                          :scalar-count (length chars))))))
      (loop while (< cursor (length text)) for ch = (char text cursor) do
        (cond
          ((find ch '(#\Space #\Tab #\Newline #\Return)) (incf cursor))
          ((char= ch #\") (scan-string))
          ((word-start-p ch)
           (let ((start cursor))
             (loop while (and (< cursor (length text))
                              (or (word-start-p (char text cursor))
                                  (ascii-digit-p (char text cursor))))
                   do (incf cursor))
             (emit (or (cdr (assoc (subseq text start cursor) *keywords* :test #'string=))
                       :identifier) start)))
          ((ascii-digit-p ch)
           (let ((start cursor))
             (loop while (and (< cursor (length text)) (ascii-digit-p (char text cursor)))
                   do (incf cursor))
             (when (and (< cursor (length text)) (word-start-p (char text cursor)))
               (fail-at (make-span source start (1+ cursor)) :lex "Invalid decimal boundary"))
             (emit :integer start)))
          (t
           (let ((entry (find-if
                         (lambda (pair)
                           (let ((end (+ cursor (length (car pair)))))
                             (and (<= end (length text))
                                  (string= (car pair) text :start2 cursor :end2 end))))
                         *operators*))
                 (start cursor))
             (unless entry
               (fail-at (make-span source cursor (1+ cursor)) :lex "Undefined character"))
             (incf cursor (length (car entry)))
             (emit (cdr entry) start)))))
      (emit :eof cursor))
    tokens))
