(in-package #:mognitio.machine)

(defstruct instruction opcode operands span)

(defun lower-module (module)
  (mognitio.ir:verify-module module)
  (let ((code nil))
    (labels ((emit (span opcode &rest operands)
               (push (make-instruction :opcode opcode :operands operands :span span) code))
             (label-id (id) (list :block id)))
      (let ((blocks (mognitio.ir:module-blocks module)))
        (unless (= (mognitio.ir:module-entry module)
                   (mognitio.ir:basic-block-id (first blocks)))
          (internal-error "Machine lowering requires the entry block first"))
        (dolist (block blocks)
          (let ((span (mognitio.ir:basic-block-span block))
                (accumulator (first (mognitio.ir:basic-block-parameters block))))
            (emit span :label (label-id (mognitio.ir:basic-block-id block)))
            (dolist (inst (mognitio.ir:basic-block-instructions block))
              (emit (mognitio.ir:instruction-span inst) :bool
                    (mognitio.ir:instruction-value inst))
              (setf accumulator (mognitio.ir:instruction-result inst)))
            (let* ((term (mognitio.ir:basic-block-terminator block))
                   (value (if (eq (first term) :jump) (third term) (second term))))
              (unless (eql value accumulator)
                (internal-error "SSA value requires an unsupported register assignment"))
              (ecase (first term)
                (:branch
                 (emit span :test)
                 (emit span :jz (label-id (fourth term)))
                 (emit span :jmp (label-id (third term))))
                (:jump (emit span :jmp (label-id (second term))))
                (:return (emit span :jmp :print)))))))
      (let ((span (mognitio.ir:module-span module)))
        (dolist (form '((:label :print) (:test) (:jz :false)
                        (:lea-rsi :true-data) (:mov-edx 5) (:jmp :write-setup)
                        (:label :false) (:lea-rsi :false-data) (:mov-edx 6)
                        (:label :write-setup) (:mov-edi 1)
                        (:label :write-loop) (:mov-eax 1) (:syscall)
                        (:cmp-eintr) (:jz :write-loop) (:test) (:jle :write-error)
                        (:add-rsi) (:sub-rdx) (:jnz :write-loop)
                        (:xor-edi) (:jmp :exit)
                        (:label :write-error) (:mov-edi 1)
                        (:label :exit) (:mov-eax 60) (:syscall) (:ud2)
                        (:label :true-data) (:bytes 116 114 117 101 10)
                        (:label :false-data) (:bytes 102 97 108 115 101 10)))
          (apply #'emit span (first form) (rest form))))
      (nreverse code))))
