(in-package #:mognitio.machine)

(defstruct instruction opcode operands span)
(defun lower-module (module)
  (mognitio.ir:verify-module module)
  (let ((function nil) (allocation nil) (homes nil) (temporary nil)
        (code nil) (units nil) (block-map (make-hash-table))
        (serial 0) (span (mognitio.ir:module-span module)))
    (labels ((emit (opcode &rest operands)
               (push (make-instruction :opcode opcode :operands operands :span span) code))
             (finish-unit (owner entry)
               (push (mognitio.object:make-code-unit :owner owner :entry entry :instructions (nreverse code)) units)
               (setf code nil))
             (label-id (id) (list :block (mognitio.ir:ir-function-id function) id))
             (fresh-label () (list :internal (mognitio.ir:ir-function-id function) (incf serial)))
             (home (id)
               (multiple-value-bind (offset found) (gethash id homes)
                 (unless found (internal-error "Missing value home")) offset))
             (read-location (location reg)
               (if (integerp location) (emit :load-frame reg location)
                   (unless (eq location reg) (emit :mov-reg reg location))))
             (write-location (location reg)
               (if (integerp location) (emit :store-frame location reg)
                   (unless (eq location reg) (emit :mov-reg location reg))))
             (load-value (id &optional (reg :rax)) (read-location (home id) reg))
             (arithmetic (inst)
               (let ((op (mognitio.ir:instruction-op inst)))
                 (case op
                   ((:neg :add :sub :mul) (emit op) (emit :jo :overflow))
                   ((:div :rem)
                    (emit :test-rcx) (emit :jz (if (eq op :div) :division-by-zero :remainder-by-zero))
                    (let ((safe (fresh-label)))
                      (emit :cmp-rcx-minus-one) (emit :jnz safe)
                      (emit :imm-rdx mognitio.integer:+minimum+) (emit :cmp-rax-rdx)
                      (emit :jz :overflow) (emit :label safe)
                      (emit :cqo) (emit :idiv))
                    (when (eq op :rem) (emit :mov-rax-rdx)))
                   ((:eq :ne :lt :le :gt :ge) (emit :cmp) (emit :set-bool op))
                   (otherwise (internal-error "Unsupported SSA operation")))))
             (runtime ()
               (dolist (form '((:label :print) (:test) (:jz :false)
                              (:lea-rsi (:data :true)) (:mov-edx 5) (:jmp :normal-setup)
                              (:label :false) (:lea-rsi (:data :false)) (:mov-edx 6)
                              (:label :normal-setup) (:mov-edi 1) (:mov-r8d 0) (:mov-r9d 1)
                              (:jmp :write-setup)))
                 (apply #'emit form))
               (dolist (kind '(:overflow :division-by-zero :remainder-by-zero))
                 (emit :label kind)
                 (emit :lea-rsi (list :data kind))
                 (emit :mov-edx (length (mognitio.runtime:failure-octets kind)))
                 (emit :mov-edi 2)
                 (emit :mov-r8d (mognitio.runtime:failure-status kind))
                 (emit :mov-r9d (mognitio.runtime:failure-status kind))
                 (emit :jmp :write-setup))
               (emit :label :write-setup) (emit :mov-r10d mognitio.runtime:+retry-budget+)
               (dolist (form '((:label :write-loop) (:mov-eax 1) (:syscall)
                              (:cmp-eintr) (:jz :write-interrupted)
                              (:test) (:jle :write-error) (:add-rsi) (:sub-rdx)))
                 (apply #'emit form))
               (emit :mov-r10d mognitio.runtime:+retry-budget+)
               (dolist (form '((:jnz :write-loop) (:mov-edi-r8d) (:jmp :exit)
                              (:label :write-interrupted) (:cmp-r9d-one) (:jz :write-loop)
                              (:dec-r10d) (:jnz :write-loop)
                              (:label :write-error) (:mov-edi-r9d)
                              (:label :exit) (:mov-eax 60) (:syscall) (:ud2)
                              (:label (:data :true)) (:bytes 116 114 117 101 10)
                              (:label (:data :false)) (:bytes 102 97 108 115 101 10)))
                 (apply #'emit form))
               (dolist (kind '(:overflow :division-by-zero :remainder-by-zero))
                 (emit :label (list :data kind))
                 (apply #'emit :bytes (coerce (mognitio.runtime:failure-octets kind) 'list)))))
      (emit :align-stack) (emit :clear-frame) (emit :call '(:function 0)) (emit :jmp :print)
      (finish-unit :entry-stub nil)
      (dolist (current (mognitio.ir:module-functions module))
        (setf function current allocation (mognitio.regalloc:allocate-function current)
              homes (mognitio.regalloc:allocation-locations allocation)
              temporary (- (* 8 (1+ (mognitio.regalloc:allocation-spill-count allocation))))
              serial 0 span (mognitio.ir:ir-function-span current))
        (clrhash block-map)
        (dolist (b (mognitio.ir:ir-function-blocks function))
          (setf (gethash (mognitio.ir:basic-block-id b) block-map) b))
        (emit :label (list :function (mognitio.ir:ir-function-id function)))
        (emit :push-rbp) (emit :mov-reg :rbp :rsp)
        (let* ((arity (loop for b in (mognitio.ir:ir-function-blocks function)
                            maximize (loop for i in (mognitio.ir:basic-block-instructions b)
                              when (member (mognitio.ir:instruction-op i) '(:call :call.value))
                              maximize (- (length (mognitio.ir:instruction-operands i))
                                          (if (eq (mognitio.ir:instruction-op i) :call.value) 1 0)) into maximum
                              finally (return (or maximum 0)))))
               (frame (* 16 (ceiling (+ (* 8 arity) (- temporary)) 16)))
               (loop-label (fresh-label)))
          (unless (typep frame '(signed-byte 32)) (internal-error "Frame size exceeds encoding"))
          (emit :imm-rcx (/ frame 8)) (emit :label loop-label)
          (emit :push-zero) (emit :dec-rcx) (emit :jnz loop-label))
        (loop for parameter in (mognitio.ir:basic-block-parameters
                                (gethash (mognitio.ir:ir-function-entry function) block-map))
              for offset from 16 by 8 do
          (emit :load-frame :rax offset) (write-location (home (car parameter)) :rax))
        (emit :jmp (label-id (mognitio.ir:ir-function-entry function)))
      (dolist (block (mognitio.regalloc:allocation-order allocation))
        (setf span (mognitio.ir:basic-block-span block))
        (emit :label (label-id (mognitio.ir:basic-block-id block)))
        (dolist (inst (mognitio.ir:basic-block-instructions block))
          (setf span (mognitio.ir:instruction-span inst))
          (case (mognitio.ir:instruction-op inst)
            ((:constant :function) (emit :imm-rax (mognitio.ir:instruction-value inst)))
            (:call
             (loop for argument in (mognitio.ir:instruction-operands inst) for offset from 0 by 8 do
               (load-value argument) (emit :store-out offset :rax))
             (emit :call (list :function (mognitio.ir:instruction-value inst))))
            (:call.value
             (loop for argument in (rest (mognitio.ir:instruction-operands inst)) for offset from 0 by 8 do
               (load-value argument) (emit :store-out offset :rax))
             (let ((done (fresh-label)) (targets (second (mognitio.ir:instruction-value inst))))
               (load-value (first (mognitio.ir:instruction-operands inst)))
               (loop for tail on targets for id = (car tail) do
                 (let ((next (fresh-label)))
                   (when (cdr tail) (emit :imm-rcx id) (emit :cmp) (emit :jnz next))
                   (emit :call (list :function id)) (emit :jmp done) (emit :label next)))
               (emit :label done)))
            (otherwise
             (load-value (first (mognitio.ir:instruction-operands inst)))
             (when (second (mognitio.ir:instruction-operands inst))
               (load-value (second (mognitio.ir:instruction-operands inst)) :rcx))
             (arithmetic inst)))
          (write-location (home (mognitio.ir:instruction-result inst)) :rax))
        (let ((term (mognitio.ir:basic-block-terminator block)))
          (ecase (first term)
            (:branch (load-value (second term)) (emit :test)
                     (emit :jz (label-id (fourth term))) (emit :jmp (label-id (third term))))
            (:jump
             (let ((params (mognitio.ir:basic-block-parameters (gethash (second term) block-map)))
                   (args (third term)))
               (dolist (move (mognitio.regalloc:parallel-copies
                              (loop for p in params for a in args collect (cons (home (car p)) (home a))) temporary))
                 (read-location (cdr move) :rax) (write-location (car move) :rax)))
             (emit :jmp (label-id (second term))))
            (:return (load-value (second term)) (emit :jmp (list :internal (mognitio.ir:ir-function-id function) 0))))))
        (emit :label (list :internal (mognitio.ir:ir-function-id function) 0))
        (emit :mov-reg :rsp :rbp) (emit :pop-rbp) (emit :ret)
        (finish-unit (mognitio.ir:ir-function-id function) (list :function (mognitio.ir:ir-function-id function))))
      (runtime)
      (finish-unit :runtime :print)
      (mognitio.object:layout-units (nreverse units)))))
