(in-package #:mognitio.native.runtime)

(defun validate-root-unit ()
  ;; Test/debug only: require an exact allocated block start in a known arena.
  ;; The caller has already skipped zero and static object pointers.
  (runtime-unit :validate
    '((:load-word :rdx :rsp 8) (:load-word :r8 :r15 8)
      (:label :arena) (:cmp-imm :r8 0) (:jz :bad)
      (:load-word :r10 :r8 8) (:add-reg :r10 :r8) (:lea-base :r9 :r8 32)
      (:label :block) (:cmp-reg :r9 :r10) (:jz :next) (:ja :bad)
      (:load-word :rax :r9 0) (:cmp-imm :rax 32) (:jb :bad)
      (:mov-reg :rcx :rax) (:and-imm :rcx 7) (:test-rcx) (:jnz :bad)
      (:mov-reg :rcx :r9) (:add-reg :rcx :rax) (:jb :bad)
      (:cmp-reg :rcx :r10) (:ja :bad)
      (:cmp-reg :r9 :rdx) (:jz :found) (:mov-reg :r9 :rcx) (:jmp :block)
      (:label :next) (:load-word :r8 :r8 0) (:jmp :arena)
      (:label :found) (:load-word :rax :r9 8) (:and-imm :rax -3)
      (:cmp-imm :rax 1) (:jnz :bad) (:ret)
      (:label :bad) (:mov-edi 3) (:mov-eax 60) (:syscall) (:ud2))))

(defun watch-reclamation ()
  (when (option :trace)
    `((:load-word :rax :r15 ,+watch-state+) (:cmp-imm :rax 1) (:jnz :watch-done)
      (:load-word :rax :r15 ,+watch-pointer+) (:cmp-reg :rax :r9) (:jnz :watch-done)
      (:imm-rax 2) (:store-word :r15 ,+watch-state+ :rax)
      (:store-word :r15 ,(+ +trace+ 24) :rax) (:store-word :r15 ,(+ +trace+ 32) :r9)
      (:load-word :rax :r9 0) (:store-word :r15 ,(+ +trace+ 40) :rax)
      (:label :watch-done))))

(defun collect-unit ()
  (runtime-unit :collect
    (append (helper-frame 8) (bump +collections+)
      `((:load-word :rax :r15 ,+root-head+) (:store-frame -8 :rax)
        (:label :frame) (:load-frame :rax -8) (:test) (:jz :sweep)
        (:load-word :rcx :rax 8) (:store-frame -16 :rcx)
        (:mov-reg :rax :rcx) (:add-imm :rax 2) (:imm-rcx 8) (:mul)
        (:load-frame :rdx -48) (:add-reg :rdx :rax) (:store-frame -48 :rdx)
        (:load-frame :rax -8) (:add-imm :rax 16) (:store-frame -24 :rax)
        (:label :slot) (:load-frame :rcx -16) (:test-rcx) (:jz :next-frame)
        (:load-frame :rdx -24) (:load-word :rax :rdx 0) (:test) (:jz :next-slot)
        (:load-word :rcx :rax 8) (:and-imm :rcx 4) (:test-rcx) (:jnz :next-slot)
        (:store-frame -32 :rax) (:store-out 0 :rax))
      (when (option :validate) '((:call (:runtime :validate))))
      '((:load-frame :rdx -32) (:imm-rax 3) (:store-word :rdx 8 :rax)
        (:label :next-slot) (:load-frame :rax -24) (:add-imm :rax 8) (:store-frame -24 :rax)
        (:load-frame :rcx -16) (:dec-rcx) (:store-frame -16 :rcx) (:jmp :slot)
        (:label :next-frame) (:load-frame :rax -8) (:load-word :rax :rax 0)
        (:store-frame -8 :rax) (:jmp :frame)
        (:label :sweep))
      (unless (eq (option :mutation) :no-sweep)
        (append
          `((:load-word :r8 :r15 ,+arena-head+)
            (:label :arena) (:cmp-imm :r8 0) (:jz :done)
            (:load-word :r10 :r8 8) (:add-reg :r10 :r8) (:lea-base :r9 :r8 32)
            (:imm-reg :rsi 0)
            (:label :block) (:cmp-reg :r9 :r10) (:jae :next-arena)
            (:load-word :rax :r9 8) (:test) (:jz :free)
            (:and-imm :rax 2) (:test) (:jnz :live))
          (when (eq (option :mutation) :all-mark) '((:jmp :live)))
          (bump +reclaimed-count+)
          '((:load-word :rdx :r9 0)) (bump +reclaimed-bytes+ :rdx)
          (watch-reclamation)
          '((:imm-rax 0) (:store-word :r9 8 :rax)
            (:label :free) (:cmp-imm :rsi 0) (:jz :first-free)
            (:load-word :rax :rsi 0) (:load-word :rdx :r9 0) (:add-reg :rax :rdx)
            (:store-word :rsi 0 :rax) (:jmp :advance)
            (:label :first-free) (:mov-reg :rsi :r9) (:jmp :advance)
            (:label :live) (:imm-rax 1) (:store-word :r9 8 :rax) (:imm-reg :rsi 0)
            (:load-word :rax :r9 0) (:load-frame :rdx -40) (:add-reg :rdx :rax) (:store-frame -40 :rdx)
            (:label :advance) (:load-word :rax :r9 0) (:add-reg :r9 :rax) (:jmp :block)
            (:label :next-arena) (:load-word :r8 :r8 0) (:jmp :arena))))
      `((:label :done) (:load-frame :rax -40) (:load-word :rdx :r15 ,+peak-live+)
        (:cmp-rax-rdx) (:jbe :roots-peak) (:store-word :r15 ,+peak-live+ :rax)
        (:label :roots-peak) (:load-frame :rax -48) (:load-word :rdx :r15 ,+peak-roots+)
        (:cmp-rax-rdx) (:jbe :finish) (:store-word :r15 ,+peak-roots+ :rax)
        (:label :finish) (:imm-rax 0)) (helper-return))))
