(in-package #:mognitio.native.runtime)

(defun panic-helper-unit ()
  ;; Private ABI: message in argument slot zero; no allocation or normal return.
  ;; Syscalls clobber RCX/R11, so message, segment and retry state live in frame.
  (runtime-unit :panic
    (append (helper-frame 6)
      '((:load-frame :rax 16) (:store-frame -8 :rax)
        (:imm-rax 0) (:store-frame -32 :rax)
        (:lea-rsi :prefix) (:mov-edx 16)
        (:label :setup) (:store-frame -16 :rsi) (:store-frame -24 :rdx)
        (:imm-rax 16) (:store-frame -40 :rax)
        (:label :write-loop) (:load-frame :rsi -16) (:load-frame :rdx -24)
        (:mov-reg :rax :rdx) (:test) (:jz :segment-done)
        (:mov-edi 2) (:mov-eax 1) (:syscall) (:cmp-eintr) (:jz :interrupted)
        (:test) (:jle :exit)
        (:load-frame :rsi -16) (:add-rsi) (:store-frame -16 :rsi)
        (:load-frame :rdx -24) (:sub-rdx) (:store-frame -24 :rdx)
        (:imm-rax 16) (:store-frame -40 :rax) (:jmp :write-loop)
        (:label :interrupted) (:load-frame :rax -40) (:add-imm :rax -1)
        (:store-frame -40 :rax) (:test) (:jle :exit) (:jmp :write-loop)
        (:label :segment-done) (:load-frame :rax -32) (:test) (:jz :message)
        (:add-imm :rax -1) (:test) (:jz :newline) (:jmp :exit)
        (:label :message) (:imm-rax 1) (:store-frame -32 :rax)
        (:load-frame :rax -8) (:load-word :rdx :rax 16) (:lea-base :rsi :rax 32) (:jmp :setup)
        (:label :newline) (:imm-rax 2) (:store-frame -32 :rax)
        (:lea-rsi :newline-data) (:mov-edx 1) (:jmp :setup)
        (:label :exit) (:mov-edi 4) (:mov-eax 60) (:syscall) (:ud2)
        (:label :prefix))
      (list (cons :bytes (coerce mognitio.runtime::*panic-prefix* 'list)))
      '((:label :newline-data) (:bytes 10))) :helper))
