(in-package #:mognitio.frame)

(defstruct layout size temporary root-offset capacity arity)
(defun max-arity (function)
  (loop for b in (mognitio.ir:ir-function-blocks function) maximize
    (loop for i in (mognitio.ir:basic-block-instructions b)
          when (member (mognitio.ir:instruction-op i)
                       '(:call :call.value :text.length :text.equal :text.not-equal :text.concat :text.slice))
          maximize (- (length (mognitio.ir:instruction-operands i))
                      (if (eq (mognitio.ir:instruction-op i) :call.value) 1 0)) into size
          finally (return (or size 0)))))
(defun plan-frame (function allocation roots)
  (let* ((temporary (- (* 8 (1+ (mognitio.regalloc:allocation-spill-count allocation)))))
         (capacity (mognitio.roots:root-plan-capacity roots))
         (header (- temporary (* 8 (+ capacity 2))))
         (arity (max-arity function))
         (layout (make-layout :temporary temporary :root-offset header :capacity capacity :arity arity
                              :size (* 16 (ceiling (+ (- header) (* 8 arity)) 16)))))
    (verify-layout function allocation roots layout) layout))

(defun verify-layout (function allocation roots layout)
  (let ((ranges nil) (size (layout-size layout)))
    (unless (and (typep size '(integer 16 2147483647)) (zerop (mod size 16))
                 (eql (layout-capacity layout) (mognitio.roots:root-plan-capacity roots))
                 (eql (layout-arity layout) (max-arity function)))
      (internal-error "Invalid native frame capacity"))
    (labels ((range (start count)
               (unless (and (integerp start) (zerop (mod start 8))
                            (<= (- size) start (+ start count) 0))
                 (internal-error "Native frame range is out of bounds"))
               (when (plusp count)
                 (dolist (other ranges)
                   (when (and (< start (cdr other)) (< (car other) (+ start count)))
                     (internal-error "Native frame regions overlap")))
                 (push (cons start (+ start count)) ranges))))
      (range (- (* 8 (mognitio.regalloc:allocation-spill-count allocation)))
             (* 8 (mognitio.regalloc:allocation-spill-count allocation)))
      (range (layout-temporary layout) 8)
      (range (layout-root-offset layout) (* 8 (+ 2 (layout-capacity layout))))
      (range (- size) (* 8 (layout-arity layout)))))
  layout)

(defun verify-sections-internal (function allocation roots layout sections body)
  ;; Sections are actual emitted instructions. Reconstruct required frame
  ;; transitions and root stores from the independently checked root plan.
  (verify-layout function allocation roots layout)
  (let* ((header (layout-root-offset layout)) (capacity (layout-capacity layout))
         (sites (copy-list (mognitio.roots:root-plan-sites roots))) (reserved nil) (linked nil) (unlinked nil)
         (homes (mognitio.regalloc:allocation-locations allocation))
         (operations nil) (calls nil) (link-end nil) (unlink-start nil))
    (dolist (section sections)
      (destructuring-bind (kind key forms start) section
        (unless (and (typep start '(integer 0 *))
                     (<= (+ start (length forms)) (length body))
                     (equal forms (subseq body start (+ start (length forms)))))
          (internal-error "Frame evidence does not match emitted instructions"))
        (case kind
          (:reserve
           (unless (and (not reserved) (= start 3) (= (length forms) 5)
                        (equal (subseq body 0 3) `((:label (:function ,(mognitio.ir:ir-function-id function)))
                                                  (:push-rbp) (:mov-reg :rbp :rsp)))
                        (equal (first forms) (list :imm-rcx (/ (layout-size layout) 8)))
                        (eq (first (second forms)) :label)
                        (equal (third forms) '(:push-zero)) (equal (fourth forms) '(:dec-rcx))
                        (equal (fifth forms) (list :jnz (second (second forms)))))
             (internal-error "Incorrect frame allocation or stack probe"))
           (setf reserved t))
          (:link
           (unless (and reserved (= start 8)) (internal-error "Root link before frame initialization"))
           (when linked (internal-error "Duplicate root frame link"))
           (unless (equal forms `((:load-word :rax :r15 0) (:store-frame ,header :rax)
                                 (:imm-rax ,capacity) (:store-frame ,(+ header 8) :rax)
                                 (:lea-base :rax :rbp ,header) (:store-word :r15 0 :rax)))
             (internal-error "Incorrect root frame link"))
           (setf linked t link-end (+ start (length forms))))
          (:unlink
           (unless (and linked (not unlinked)
                        (equal forms `((:load-frame :rcx ,header) (:store-word :r15 0 :rcx))))
             (internal-error "Incorrect root frame unlink or return clobber"))
           (setf unlinked t unlink-start start))
          (:publish
           (let* ((site (find key sites :test #'equal
                             :key (lambda (s) (list (mognitio.roots:root-site-block-id s)
                                                    (mognitio.roots:root-site-instruction-index s)))))
                  (pending (copy-tree forms)))
             (unless (and linked (not unlinked) site (equal (pop pending) '(:imm-rax 0)))
               (internal-error "Invalid root publication site"))
             (dotimes (slot capacity)
               (unless (equal (pop pending) (list :store-frame (+ header 16 (* slot 8)) :rax))
                 (internal-error "Root slots not cleared before publication")))
             (loop for value in (mognitio.roots:root-site-values site) for slot from 0
                   for home = (gethash value homes) do
               (unless (and (equal (pop pending) (if (integerp home) (list :load-frame :rax home)
                                                     (list :mov-reg :rax home)))
                            (equal (pop pending) (list :store-frame (+ header 16 (* slot 8)) :rax)))
                 (internal-error "Incorrect root value home or slot")))
             (when pending (internal-error "Unexpected instruction in root snapshot"))
             (setf sites (remove site sites))))
          (:operation
           (when (member key operations :test #'equal) (internal-error "Duplicate call section"))
           (push key operations)
           (let* ((block (find (first key) (mognitio.ir:ir-function-blocks function) :key #'mognitio.ir:basic-block-id))
                  (inst (nth (second key) (mognitio.ir:basic-block-instructions block)))
                  (op (mognitio.ir:instruction-op inst))
                  (publication (find key sections :key #'second :test #'equal))
                  (prefix (when (eq (first publication) :publish) (third publication)))
                  (pending (copy-list forms)))
             (unless (and linked (not unlinked)
                          (member op '(:call :call.value :text.length :text.equal :text.not-equal :text.concat :text.slice)))
               (internal-error "Invalid native call section"))
             (when (member :may-allocate (mognitio.ir:instruction-effects inst))
               (unless (and prefix (equal prefix (subseq pending 0 (length prefix))))
                 (internal-error "Call precedes root publication"))
               (setf pending (nthcdr (length prefix) pending)))
             (loop for argument in (if (eq op :call.value) (rest (mognitio.ir:instruction-operands inst))
                                       (mognitio.ir:instruction-operands inst))
                   for offset from 0 by 8 for home = (gethash argument homes) do
               (unless (and (equal (pop pending) (if (integerp home) (list :load-frame :rax home) (list :mov-reg :rax home)))
                            (equal (pop pending) (list :store-out offset :rax)))
                 (internal-error "Wrong native argument placement")))
             (let ((actual-targets (loop for form in pending when (eq (first form) :call) collect (second form)))
                   (expected-targets (case op
                                       (:call (list (list :function (mognitio.ir:instruction-value inst))))
                                       (:call.value (mapcar (lambda (id) (list :function id)) (second (mognitio.ir:instruction-value inst))))
                                       (otherwise (list (list :helper op))))))
               (unless (equal actual-targets expected-targets) (internal-error "Unexpected native call target")))
             (loop for form in forms for index from start when (eq (first form) :call) do (push index calls))))
          (otherwise (internal-error "Invalid frame section")))))
    (let ((expected (loop for block in (mognitio.ir:ir-function-blocks function) append
                      (loop for i in (mognitio.ir:basic-block-instructions block) for n from 0
                            when (member (mognitio.ir:instruction-op i)
                                         '(:call :call.value :text.length :text.equal :text.not-equal :text.concat :text.slice))
                            collect (list (mognitio.ir:basic-block-id block) n)))))
      (unless (and (subsetp expected operations :test #'equal) (subsetp operations expected :test #'equal))
        (internal-error "Missing native call sections")))
    (unless (equal (sort calls #'<) (loop for form in body for index from 0 when (eq (first form) :call) collect index))
      (internal-error "Call outside a verified operation"))
    (unless (and link-end unlink-start (< link-end unlink-start)
                 (every (lambda (index) (< link-end index unlink-start)) calls)
                 (equal (subseq body (+ unlink-start 2)) '((:mov-reg :rsp :rbp) (:pop-rbp) (:ret))))
      (internal-error "Unsafe root frame lifetime or return handoff"))
    (loop for form in body for index from 0 do
      (when (and (member (first form) '(:mov-reg :load-word :load-byte :lea-base :add-imm))
                 (eq (second form) :r15)) (internal-error "Function clobbers runtime context register"))
      (when (and (eq (first form) :store-word) (eq (second form) :r15)
                 (not (member index (list (1- link-end) (1+ unlink-start)))))
        (internal-error "Unexpected runtime context write")))
    (unless (and reserved linked unlinked (null sites)) (internal-error "Missing frame transition or root snapshot")))
  sections)

(defun verify-sections (function allocation roots layout sections body)
  (handler-case (verify-sections-internal function allocation roots layout sections body)
    (internal-failure (condition) (error condition))
    (error () (internal-error "Malformed native frame evidence"))))
