(in-package #:mognitio.native.runtime)

(defun descriptors (context)
  (when context
    (loop for info across (mognitio.semantic:value-context-types context) append
      (let ((id (mognitio.semantic:type-info-id info)))
        (labels ((row (kind variant types)
                   (list (list :descriptor id variant) kind id variant (length types)
                         (loop for type in types for index from 0
                               when (mognitio.semantic:reference-type-p type) collect index))))
          (ecase (mognitio.semantic:type-info-kind info)
            (:struct (list (row 1 0 (mapcar #'cdr (mognitio.semantic:type-info-fields info)))))
            (:enum (loop for variant in (mognitio.semantic:type-info-variants info)
                         collect (row 2 (mognitio.semantic:variant-info-id variant)
                                      (mognitio.semantic:variant-info-types variant))))
            (:interface (list (row 3 0 '(:string))))))))))

(defun metadata-unit (context)
  (let ((forms nil))
    (labels ((record (name words)
               (setf forms (append forms (list '(:align 8) (list :label name)
                 (cons :bytes (loop for word in words append (mognitio.amd64:little-endian word 8))))))))
      (dolist (row (descriptors context))
        (destructuring-bind (name kind id variant count refs) row
          (record name (append (list kind id variant count (length refs)) refs))))
      (loop for impl across (mognitio.semantic:value-context-implementations context)
            for contract = (mognitio.semantic:implementation-info-contract impl) when contract do
        (let ((ids (loop for req in (mognitio.semantic:type-info-methods (mognitio.semantic:context-type context contract))
                         collect (mognitio.semantic:signature-id
                           (cdr (assoc (mognitio.semantic:requirement-name req)
                                       (mognitio.semantic:implementation-info-methods impl) :test #'string=))))))
          (record (list :method-table (mognitio.semantic:implementation-info-id impl))
                  (append (list (second (mognitio.semantic:implementation-info-concrete impl))
                                (second contract) (length ids)) ids)))))
    (mognitio.object:make-code-unit :owner :metadata :instructions
      (loop for form in forms collect (mognitio.machine:make-instruction :opcode (first form) :operands (rest form))))))

(defun value-helper-name (inst)
  (list :helper (list (mognitio.ir:instruction-op inst) (mognitio.ir:instruction-type inst)
                      (mognitio.ir:instruction-value inst))))

(defun value-helper-units (module)
  (let ((seen nil) (units nil) (context (mognitio.ir:module-values module)))
    (dolist (function (mognitio.ir:module-functions module))
      (dolist (block (mognitio.ir:ir-function-blocks function))
        (dolist (inst (mognitio.ir:basic-block-instructions block))
          (when (member (mognitio.ir:instruction-op inst) '(:struct.make :enum.make :interface.pack))
            (let* ((name (value-helper-name inst)) (op (mognitio.ir:instruction-op inst))
                   (type (mognitio.ir:instruction-type inst)) (data (mognitio.ir:instruction-value inst))
                   (count (length (mognitio.ir:instruction-operands inst)))
                   (variant (if (eq op :enum.make) data 0))
                   (kind (ecase op (:struct.make 1) (:enum.make 2) (:interface.pack 3))))
              (unless (member name seen :test #'equal)
                (push name seen)
                (when (eq op :interface.pack)
                  (unless (aref (mognitio.semantic:value-context-implementations context) data)
                    (internal-error "Missing interface implementation")))
                (push (runtime-unit (second name)
                  (append (helper-frame 2)
                    `((:imm-rax ,(* 8 (max 1 count))) (:store-out 0 :rax) (:call (:runtime :allocate-block))
                      (:mov-reg :rdx :rax) (:imm-rcx ,(1+ (* kind 16))) (:store-word :rdx 8 :rcx)
                      (:lea-meta (:descriptor ,(second type) ,variant)) (:store-word :rdx 16 :rax))
                    (if (eq op :interface.pack)
                        `((:lea-meta (:method-table ,data)) (:store-word :rdx 24 :rax))
                        `((:imm-rax ,variant) (:store-word :rdx 24 :rax)))
                    (loop for i below count for slot = (if (eq op :struct.make) (nth i data) i) append
                      `((:load-frame :rax ,(+ 16 (* i 8))) (:store-word :rdx ,(+ 32 (* slot 8)) :rax)))
                    '((:mov-reg :rax :rdx)) (helper-return)) :helper) units)))))))
    (nreverse units)))

(defun trace-forms (context)
  ;; Scan marked, unscanned objects to a fixed point without allocating a work
  ;; list. Local slots preserve the traversal across exact-pointer validation.
  (append
    '((:label :trace-pass) (:load-frame :rax -120) (:add-imm :rax 1) (:store-frame -120 :rax)
      (:imm-rax 0) (:store-frame -104 :rax)
      (:load-word :rax :r15 8) (:store-frame -56 :rax)
      (:label :trace-arena) (:load-frame :rax -56) (:test) (:jz :trace-pass-end)
      (:load-word :rdx :rax 8) (:add-reg :rdx :rax) (:store-frame -72 :rdx)
      (:add-imm :rax 32) (:store-frame -64 :rax)
      (:label :trace-block) (:load-frame :rdx -64) (:load-frame :rcx -72)
      (:cmp-reg :rdx :rcx) (:jae :trace-next-arena)
      (:load-word :rax :rdx 8) (:mov-reg :rcx :rax) (:and-imm :rcx 11)
      (:cmp-imm :rcx 3) (:jnz :trace-next-block)
      (:or-imm :rax 8) (:store-word :rdx 8 :rax)
      (:imm-rcx 1) (:store-frame -104 :rcx)
      (:and-imm :rax 48) (:test) (:jz :trace-next-block)
      (:load-word :rcx :rdx 16) (:store-frame -80 :rcx))
    ;; Even optimized builds classify descriptors before reading their fields.
    (loop for row in (descriptors context) for serial from 0 append
      (destructuring-bind (name kind id variant count refs) row
        (declare (ignore id refs))
        (let ((next (intern (format nil "DESC-~D" serial) :keyword)))
          (append
            `((:lea-meta ,name) (:cmp-reg :rax :rcx) (:jnz ,next)
              (:load-word :rax :rdx 8) (:and-imm :rax 48) (:cmp-imm :rax ,(* kind 16)) (:jnz :bad)
              (:load-word :rax :rdx 0) (:cmp-imm :rax ,(+ 32 (* 8 (max 1 count)))) (:jb :bad))
            (if (= kind 3)
                (let ((matches (loop for impl across (mognitio.semantic:value-context-implementations context)
                                     when (equal (mognitio.semantic:implementation-info-contract impl) (list :interface (second name))) collect impl)))
                  (append '((:load-word :rcx :rdx 24))
                    (loop for impl in matches for table-id = (mognitio.semantic:implementation-info-id impl)
                          for next-table = (intern (format nil "DESC-~D-TABLE-~D" serial table-id) :keyword) append
                      (append
                        `((:lea-meta (:method-table ,table-id)) (:cmp-reg :rax :rcx) (:jnz ,next-table))
                        (when (option :validate)
                          '((:load-word :rax :rdx 32) (:store-out 0 :rax) (:call (:runtime :validate))
                            (:cmp-imm :rax 5) (:jz :bad) (:load-frame :rdx -64)))
                        '((:load-word :rax :rdx 32) (:load-word :rcx :rax 16))
                        (loop for concrete-row in (descriptors context)
                              when (= (third concrete-row) (second (mognitio.semantic:implementation-info-concrete impl))) append
                          `((:lea-meta ,(first concrete-row)) (:cmp-reg :rax :rcx) (:jz :trace-refs)))
                        `((:jmp :bad) (:label ,next-table))))
                    '((:jmp :bad))))
                `((:load-word :rax :rdx 24) (:cmp-imm :rax ,variant) (:jnz :bad) (:jmp :trace-refs)))
            `((:label ,next))))))
    '((:jmp :bad)
      (:label :trace-refs) (:load-frame :rax -80) (:load-word :rcx :rax 32)
      (:store-frame -88 :rcx) (:add-imm :rax 40) (:store-frame -96 :rax)
      (:label :trace-ref) (:load-frame :rcx -88) (:test-rcx) (:jz :trace-next-block)
      (:load-frame :rax -96) (:load-word :rax :rax 0) (:imm-rcx 8) (:mul)
      (:load-frame :rdx -64) (:add-reg :rdx :rax) (:load-word :rax :rdx 32)
      (:store-frame -112 :rax) (:store-out 0 :rax))
    (if (option :validate)
        '((:call (:runtime :validate)) (:cmp-imm :rax 5) (:jz :trace-next-ref))
        '((:load-word :rcx :rax 8) (:and-imm :rcx 4) (:test-rcx) (:jnz :trace-next-ref)))
    (unless (eq (option :mutation) :no-trace)
      '((:load-frame :rdx -112) (:load-word :rax :rdx 8) (:or-imm :rax 2) (:store-word :rdx 8 :rax)))
    '((:label :trace-next-ref) (:load-frame :rax -96) (:add-imm :rax 8) (:store-frame -96 :rax)
      (:load-frame :rcx -88) (:dec-rcx) (:store-frame -88 :rcx) (:jmp :trace-ref)
      (:label :trace-next-block) (:load-frame :rdx -64) (:load-word :rax :rdx 0)
      (:add-reg :rdx :rax) (:store-frame -64 :rdx) (:jmp :trace-block)
      (:label :trace-next-arena) (:load-frame :rax -56) (:load-word :rax :rax 0)
      (:store-frame -56 :rax) (:jmp :trace-arena)
      (:label :trace-pass-end) (:load-frame :rax -104) (:test) (:jnz :trace-pass)
      (:load-frame :rax -120) (:load-word :rcx :r15 200) (:cmp) (:jbe :trace-counted)
      (:store-word :r15 200 :rax) (:label :trace-counted) (:jmp :sweep)
      (:label :bad) (:mov-edi 3) (:mov-eax 60) (:syscall) (:ud2))))
