(in-package #:mognitio.object)

;; These records describe only the in-memory image owned by this compiler.
(defstruct code-unit owner instructions entry)
(defstruct image-symbol name kind offset)
(defstruct fixup offset end target (kind :pc-rel32) use)

(defun symbol-kind (name)
  (cond
    ((keywordp name) :code)
    ((and (listp name) (= (length name) 2) (eq (first name) :text)
          (typep (second name) '(integer 0 *))) :text)
    ((and (listp name) (= (length name) 2) (eq (first name) :runtime)
          (member (second name) '(:allocate :allocate-block :collect :find-free :physical-size :sum :validate))) :helper)
    ((and (listp name) (= (length name) 2) (eq (first name) :helper)
          (consp (second name)) (member (first (second name)) '(:struct.make :enum.make :interface.pack))) :helper)
    ((and (listp name) (member (first name) '(:descriptor :method-table))
          (member (length name) '(2 3))
          (every (lambda (id) (typep id '(integer 0 *))) (rest name))) :metadata)
    ((and (listp name) (= (length name) 2) (eq (first name) :helper)
          (member (second name) '(:text.length :text.equal :text.not-equal :text.concat :text.slice))) :helper)
    ((and (listp name)
          (case (first name)
            (:function (and (= 2 (length name)) (typep (second name) '(integer 0 *))))
            ((:block :internal)
             (and (member (length name) '(2 3))
                  (every (lambda (id) (typep id '(integer 0 *))) (rest name))))))
     (if (eq (first name) :function) :function :code))
    ((and (listp name) (= 2 (length name)) (eq (first name) :data)
          (member (second name) '(:true :false :overflow :division-by-zero :remainder-by-zero :string-index-out-of-bounds :string-size-overflow :allocation-failed))) :data)
    (t (internal-error "Invalid image symbol"))))

(defun layout-units (units)
  (loop for unit in units append (code-unit-instructions unit)))
