(in-package #:mognitio.frontend)

(defun parse-program (source tokens)
  (loop for index from 1 below (length tokens) do
    (when (and (eq (token-kind (aref tokens (1- index))) :sub) (eq (token-kind (aref tokens index)) :sub))
      (fail-at (token-span (aref tokens index)) :parse "Consecutive minus requires grouping")))
  (let ((cursor 0))
    (labels ((peek (&optional (ahead 0))
               (when (>= (+ cursor ahead) (length tokens)) (internal-error "Missing EOF"))
               (aref tokens (+ cursor ahead)))
             (kind () (token-kind (peek)))
             (take () (prog1 (peek) (incf cursor)))
             (expect (expected)
               (unless (eq expected (kind))
                 (fail-at (token-span (peek)) :parse
                          (format nil "Expected ~A" (string-downcase expected))))
               (take))
             (cover (start end) (make-span source start end))
             (start-of (node) (span-start (node-span node)))
             (end-of (node) (span-end (node-span node)))
             (sequence-body (end-kind)
               (let ((statements nil) (start (span-start (token-span (peek)))))
                 (labels ((finish (tail)
                            (let ((close (expect end-kind)))
                              (make-sequence-node :statements (coerce (nreverse statements) 'vector)
                                :terminal tail :span (cover start (span-end (token-span close)))))))
                   (loop
                     (cond
                       ((eq (kind) end-kind)
                        (when (eq end-kind :eof) (fail-at (token-span (peek)) :parse "Program requires a tail expression"))
                        (return (finish nil)))
                       ((member (kind) '(:let :var))
                        (let* ((mut (take)) (name (expect :identifier)) (equal (expect :assign))
                               (init (expression)) (close (expect :semicolon)))
                          (declare (ignore equal))
                          (push (make-local-binding :mutability (token-kind mut) :name name :initializer init
                                  :span (cover (span-start (token-span mut)) (span-end (token-span close)))) statements)))
                       ((and (eq (kind) :identifier) (eq (token-kind (peek 1)) :assign))
                        (let* ((name (take)) (equal (expect :assign)) (rhs (expression)) (close (expect :semicolon)))
                          (declare (ignore equal))
                          (push (make-assignment :name name :rhs rhs
                                  :span (cover (span-start (token-span name)) (span-end (token-span close)))) statements)))
                       ((member (kind) '(:break :continue))
                        (let* ((keyword (take))
                               (value (when (and (eq (token-kind keyword) :break) (not (eq (kind) :semicolon))) (expression)))
                               (close (expect :semicolon))
                               (span (cover (span-start (token-span keyword)) (span-end (token-span close)))))
                          (push (if (eq (token-kind keyword) :break) (make-break-statement :span span :value value)
                                    (make-continue-statement :span span)) statements)))
                       ((eq (kind) :return)
                        (let* ((keyword (take)) (value (unless (eq (kind) :semicolon) (expression)))
                               (close (expect :semicolon)))
                          (push (make-return-statement :keyword keyword :value value
                                  :span (cover (span-start (token-span keyword)) (span-end (token-span close)))) statements)))
                       (t (let ((node (expression)))
                            (if (eq (kind) :semicolon)
                                (let ((close (take)))
                                  (push (make-expression-statement :expression node
                                          :span (cover (start-of node) (span-end (token-span close)))) statements))
                                (return (finish node))))))))))
             (comma-list (reader)
               (let ((items nil))
                 (unless (eq (kind) :right-paren)
                   (push (funcall reader) items)
                   (loop while (eq (kind) :comma) do (take) (push (funcall reader) items)))
                 (coerce (nreverse items) 'vector)))
             (type-name ()
               (unless (member (kind) '(:bool :int :void :string))
                 (fail-at (token-span (peek)) :parse "Expected bool, int, void or string"))
               (take))
             (parameter-node ()
               (let ((name (expect :identifier)))
                 (expect :colon)
                 (let ((type (type-name)))
                   (make-parameter :type type :name name
                     :span (cover (span-start (token-span name)) (span-end (token-span type)))))))
             (function-node ()
               (let ((keyword (expect :function)))
                 (expect :left-paren)
                 (let ((parameters (comma-list #'parameter-node)))
                   (expect :right-paren) (expect :colon)
                   (let* ((type (type-name)) (body (body-block)))
                     (make-function-expression :parameters parameters :result-type type :body body
                       :span (cover (span-start (token-span keyword)) (end-of body)))))))
             (body-block ()
               (let* ((open (expect :left-brace)) (body (sequence-body :right-brace)))
                 (make-sequence-node :statements (sequence-node-statements body) :terminal (sequence-node-terminal body)
                   :span (cover (span-start (token-span open)) (end-of body)))))
             (primary ()
               (let ((token (peek)))
                 (case (kind)
                   ((:true :false) (take) (make-boolean-literal :value (token-kind token)
                                                             :span (token-span token)))
                   (:loop (take)
                    (let ((condition (when (eq (kind) :while)
                                       (take) (expect :left-paren)
                                       (prog1 (expression) (expect :right-paren)))))
                      (let ((body (body-block)))
                        (make-loop-expression :body body :condition condition
                          :span (cover (span-start (token-span token)) (end-of body))))))
                   (:string-literal (take) (make-string-literal :payload (token-payload token) :span (token-span token)))
                   (:void (take) (make-void-literal :span (token-span token)))
                   (:left-brace (body-block))
                   (:integer (take) (make-integer-literal :token token :span (token-span token)))
                   (:identifier (take) (make-variable-reference :name token :span (token-span token)))
                   (:function (function-node))
                   (:left-paren
                    (take)
                    (let* ((child (expression)) (close (expect :right-paren)))
                      (make-grouping :expression child
                        :span (cover (span-start (token-span token)) (span-end (token-span close))))))
                   (:if
                    (take) (expect :left-paren)
                    (let ((condition (expression)))
                      (expect :right-paren)
                      (let ((then (body-block)))
                        (let ((else (when (eq (kind) :else) (take) (body-block))))
                          (make-if-expression :condition condition :then-branch then :else-branch else
                            :span (cover (span-start (token-span token)) (end-of (or else then))))))))
                   (otherwise (fail-at (token-span token) :parse "Expected expression")))))
             (postfix ()
               (let ((callee (primary)))
                 (loop while (member (kind) '(:left-paren :arrow)) do
                   (let ((method (when (eq (kind) :arrow) (take) (expect :identifier))))
                     (expect :left-paren)
                     (let* ((args (comma-list #'expression)) (close (expect :right-paren))
                            (span (cover (start-of callee) (span-end (token-span close)))))
                       (setf callee (if method
                                       (make-method-call :receiver callee :name method :arguments args :span span)
                                       (make-call-expression :callee callee :arguments args :span span))))))
                 callee))
             (unary ()
               (if (eq (kind) :sub)
                   (let* ((op (take)) (child (unary)))
                     (make-unary-expression :operator op :operand child
                       :span (cover (span-start (token-span op)) (end-of child))))
                   (postfix)))
             (binary-level (child-fn operators &optional single)
               (let ((left (funcall child-fn)))
                 (loop while (member (kind) operators) do
                   (let* ((op (take)) (right (funcall child-fn)))
                     (setf left (make-binary-expression :operator op :left left :right right
                                  :span (cover (start-of left) (end-of right)))))
                   (when single (return)))
                 left))
             (product () (binary-level #'unary '(:mul :div :rem)))
             (sum () (binary-level #'product '(:add :sub)))
             (comparison () (binary-level #'sum '(:lt :le :gt :ge) t))
             (expression () (binary-level #'comparison '(:eq :ne) t)))
      (let ((body (sequence-body :eof)))
        (unless (= cursor (length tokens)) (internal-error "Tokens after EOF"))
        (make-program :source source :root (sequence-node-terminal body)
                      :statements (sequence-node-statements body))))))
