(in-package #:mognitio.frontend)

;; Declaration and branch parsing shares the main parser's cursor through
;; lexical callbacks, keeping token consumption in one place.
(defun parse-value-form (mode peek take expect expression block type-name comma-list function-reader binding-reader type-parameters expression-name)
  (declare (ignore block))
  (labels ((kind () (token-kind (funcall peek)))
           (get-token (k) (funcall expect k))
           (start (x) (span-start (if (typep x 'token) (token-span x) (node-span x))))
           (end (x) (span-end (if (typep x 'token) (token-span x) (node-span x))))
           (span (a b) (make-span (span-source (if (typep a 'token) (token-span a) (node-span a))) (start a) (end b)))
           (pattern ()
             (let ((name (funcall type-name)))
               (unless (eq (token-kind name) :identifier) (fail-at (token-span name) :parse "Expected pattern type"))
               (get-token :scope)
               (let* ((variant (get-token :identifier)) (last variant) (bindings nil))
                 (when (eq (kind) :left-paren)
                   (funcall take)
                   (setf bindings (funcall comma-list (lambda () (get-token :identifier)) :right-paren nil)
                         last (get-token :right-paren)))
                 (make-variant-pattern :name name :variant variant :bindings bindings :span (span name last)))))
           (member-value ()
             (let ((name (get-token :identifier)))
               (get-token :colon)
               (let ((value (funcall expression)))
                 (make-named-member :name name :value value :span (span name value))))))
    (ecase mode
      (:type
       (let* ((keyword (get-token :type)) (name (get-token :identifier)) (types (funcall type-parameters)))
         (get-token :assign)
         (let ((tag (kind)) (members nil) (target nil))
           (if (member tag '(:struct :enum))
               (progn
                 (funcall take) (get-token :left-brace)
                 (loop until (eq (kind) :right-brace) do
                   (let ((member (get-token :identifier)) (value nil))
                     (if (eq tag :struct)
                         (progn (get-token :colon) (setf value (funcall type-name)))
                         (when (eq (kind) :left-paren)
                           (funcall take) (setf value (funcall comma-list type-name :right-paren nil)) (get-token :right-paren)))
                     (push (make-named-member :name member :value value :span (span member (get-token :semicolon))) members)))
                 (when (and (eq tag :enum) (null members)) (fail-at (token-span (funcall peek)) :parse "Empty enum"))
                 (get-token :right-brace))
               (setf tag :alias target (funcall type-name)))
           (make-data-declaration :name name :kind tag :target target :type-parameters types :members (coerce (nreverse members) 'vector)
             :span (span keyword (get-token :semicolon))))))
      (:interface
       (let ((keyword (get-token :interface)) (name (get-token :identifier)) (methods nil))
         (get-token :left-brace)
         (loop until (eq (kind) :right-brace) do
           (let ((binding (get-token :let)) (method (get-token :identifier)))
             (get-token :assign)
             ;; This is a requirement, not an evaluated local initializer.
             (let ((signature (funcall function-reader t)))
               (push (make-named-member :name method :value signature :span (span binding signature)) methods))))
         (make-contract-declaration :name name :methods (coerce (nreverse methods) 'vector)
           :span (span keyword (get-token :right-brace)))))
      (:implement
       (let* ((keyword (get-token :implement)) (target (get-token :identifier))
              (contract (when (eq (kind) :against) (funcall take) (get-token :identifier))) (methods nil))
         (get-token :left-brace)
         (loop until (eq (kind) :right-brace) do
           (unless (eq (kind) :let) (fail-at (token-span (funcall peek)) :parse "Expected method binding"))
           (let ((method (funcall binding-reader)))
             (unless (typep (local-binding-initializer method) 'function-expression)
               (fail-at (node-span method) :parse "Method requires a function expression"))
             (when (plusp (length (function-expression-type-parameters (local-binding-initializer method))))
               (fail-at (node-span method) :parse "Generic method is not supported"))
             (push method methods)))
         (make-implementation-declaration :target target :contract contract :methods (coerce (nreverse methods) 'vector)
           :span (span keyword (get-token :right-brace)))))
      (:branch
       (let ((keyword (get-token :branch)) (tag (kind)) (subject nil))
         (unless (member tag '(:when :on)) (fail-at (token-span (funcall peek)) :parse "Expected branch mode"))
         (funcall take)
         (when (eq tag :on) (get-token :left-paren) (setf subject (funcall expression)) (get-token :right-paren))
         (get-token :left-brace)
         (let ((arms (funcall comma-list
                       (lambda ()
                         (let* ((first (funcall peek))
                                (selector (if (eq (kind) :else) (progn (funcall take) nil)
                                              (if (eq tag :when) (funcall expression) (pattern)))))
                           (get-token :fat-arrow)
                           (let ((value (funcall expression)))
                             (make-branch-arm :selector selector :value value :span (span first value))))) :right-brace nil)))
           (make-branch-expression :mode tag :subject subject :arms arms :span (span keyword (get-token :right-brace))))))
      (:identifier
       (let ((name (funcall expression-name)))
         (case (kind)
           (:left-paren
            (if (typep name 'type-syntax)
                (progn (funcall take)
                  (let* ((args (funcall comma-list expression)) (close (get-token :right-paren)))
                    (make-call-expression :callee (make-variable-reference :name (type-syntax-name name)
                                                    :span (token-span (type-syntax-name name)))
                      :type-arguments (type-syntax-arguments name) :arguments args :span (span name close))))
                (make-variable-reference :name name :span (token-span name))))
           (:scope
            (funcall take)
            (let* ((variant (get-token :identifier)) (last variant) (parens (eq (kind) :left-paren)) (arguments #()))
              (when parens
                (funcall take) (setf arguments (funcall comma-list expression) last (get-token :right-paren)))
              (make-enum-expression :name name :variant variant :arguments arguments :parenthesized-p parens :span (span name last))))
           (:left-brace
            (funcall take)
            (let ((fields (funcall comma-list #'member-value :right-brace)))
              (make-struct-expression :name name :fields fields :span (span name (get-token :right-brace)))))
           (otherwise (make-variable-reference :name name :span (token-span name)))))))))
