(in-package #:mognitio.frontend)

(defun parse-program (source tokens)
  (let ((cursor 0))
    (labels ((peek (&optional (ahead 0))
               (when (>= (+ cursor ahead) (length tokens)) (internal-error "Missing EOF"))
               (aref tokens (+ cursor ahead)))
             (kind () (token-kind (peek)))
             (take () (prog1 (peek) (incf cursor)))
             (expect (expected)
               (unless (eq expected (kind))
                 (fail-at (token-span (peek)) :parse
                          (format nil "Expected ~A" (string-downcase expected))))
               (take))
             (cover (start end) (make-span source start end))
             (start-of (node) (span-start (node-span node)))
             (end-of (node) (span-end (node-span node)))
             (sequence-body (end-kind)
               (let ((statements nil) (start (span-start (token-span (peek)))))
                 (loop
                   (cond
                     ((member (kind) '(:let :var))
                      (let* ((mut (take)) (name (expect :identifier))
                             (equal (expect :assign)) (init (expression))
                             (close (expect :semicolon)))
                        (declare (ignore equal))
                        (push (make-local-binding :mutability (token-kind mut)
                                :name name :initializer init
                                :span (cover (span-start (token-span mut))
                                             (span-end (token-span close)))) statements)))
                     ((and (eq (kind) :identifier) (eq (token-kind (peek 1)) :assign))
                      (let* ((name (take)) (equal (expect :assign)) (rhs (expression))
                             (close (expect :semicolon)))
                        (declare (ignore equal))
                        (push (make-assignment :name name :rhs rhs
                                :span (cover (span-start (token-span name))
                                             (span-end (token-span close)))) statements)))
                     (t (let* ((tail (if (and (eq end-kind :right-brace) (eq (kind) :return))
                                         (let* ((keyword (take)) (value (expression))
                                                (close (expect :semicolon)))
                                           (make-return-statement :keyword keyword :value value
                                             :span (cover (span-start (token-span keyword))
                                                          (span-end (token-span close)))))
                                         (expression)))
                                (close (expect end-kind)))
                          (return (make-sequence-node :statements (coerce (nreverse statements) 'vector)
                                     :terminal tail :span (cover start (span-end (token-span close)))))))))))
             (comma-list (reader)
               (let ((items nil))
                 (unless (eq (kind) :right-paren)
                   (push (funcall reader) items)
                   (loop while (eq (kind) :comma) do (take) (push (funcall reader) items)))
                 (coerce (nreverse items) 'vector)))
             (type-name ()
               (unless (member (kind) '(:bool :int))
                 (fail-at (token-span (peek)) :parse "Expected bool or int"))
               (take))
             (parameter-node ()
               (let ((name (expect :identifier)))
                 (expect :colon)
                 (let ((type (type-name)))
                   (make-parameter :type type :name name
                     :span (cover (span-start (token-span name)) (span-end (token-span type)))))))
             (function-node ()
               (let ((keyword (expect :function)))
                 (expect :left-paren)
                 (let ((parameters (comma-list #'parameter-node)))
                   (expect :right-paren) (expect :colon)
                   (let* ((type (type-name)) (body (body-block)))
                     (make-function-expression :parameters parameters :result-type type :body body
                       :span (cover (span-start (token-span keyword)) (end-of body)))))))
             (body-block () (expect :left-brace) (sequence-body :right-brace))
             (primary ()
               (let ((token (peek)))
                 (case (kind)
                   ((:true :false) (take) (make-boolean-literal :value (token-kind token)
                                                             :span (token-span token)))
                   (:integer (take) (make-integer-literal :token token :span (token-span token)))
                   (:identifier (take) (make-variable-reference :name token :span (token-span token)))
                   (:function (function-node))
                   (:left-paren
                    (take)
                    (let* ((child (expression)) (close (expect :right-paren)))
                      (make-grouping :expression child
                        :span (cover (span-start (token-span token)) (span-end (token-span close))))))
                   (:if
                    (take) (expect :left-paren)
                    (let ((condition (expression)))
                      (expect :right-paren)
                      (let ((then (body-block)))
                        (expect :else)
                        (let ((else (body-block)))
                          (make-if-expression :condition condition :then-branch then :else-branch else
                            :span (cover (span-start (token-span token)) (end-of else)))))))
                   (otherwise (fail-at (token-span token) :parse "Expected expression")))))
             (postfix ()
               (let ((callee (primary)))
                 (loop while (eq (kind) :left-paren) do
                   (take)
                   (let* ((args (comma-list #'expression)) (close (expect :right-paren)))
                     (setf callee (make-call-expression :callee callee :arguments args
                                   :span (cover (start-of callee) (span-end (token-span close)))))))
                 callee))
             (unary ()
               (if (eq (kind) :sub)
                   (let* ((op (take)) (child (unary)))
                     (make-unary-expression :operator op :operand child
                       :span (cover (span-start (token-span op)) (end-of child))))
                   (postfix)))
             (binary-level (child-fn operators &optional single)
               (let ((left (funcall child-fn)))
                 (loop while (member (kind) operators) do
                   (let* ((op (take)) (right (funcall child-fn)))
                     (setf left (make-binary-expression :operator op :left left :right right
                                  :span (cover (start-of left) (end-of right)))))
                   (when single (return)))
                 left))
             (product () (binary-level #'unary '(:mul :div :rem)))
             (sum () (binary-level #'product '(:add :sub)))
             (comparison () (binary-level #'sum '(:lt :le :gt :ge) t))
             (expression () (binary-level #'comparison '(:eq :ne) t)))
      (let ((body (sequence-body :eof)))
        (unless (= cursor (length tokens)) (internal-error "Tokens after EOF"))
        (make-program :source source :root (sequence-node-terminal body)
                      :statements (sequence-node-statements body))))))
