(in-package #:mognitio.frontend)

(defun parse-program (source tokens)
  (let ((cursor 0))
    (labels ((peek ()
               (when (>= cursor (length tokens))
                 (internal-error "Missing EOF token"))
               (aref tokens cursor))
             (expect (kind)
               (let ((token (peek)))
                 (unless (eq kind (token-kind token))
                   (fail-at (token-span token) :parse
                            (format nil "Expected ~A" (string-downcase kind))))
                 (incf cursor)
                 token))
             (expression ()
               (let ((token (peek)))
                 (case (token-kind token)
                   ((:true :false)
                    (incf cursor)
                    (make-boolean-literal :value (token-kind token)
                                          :span (token-span token)))
                   (:if (conditional))
                   (otherwise (fail-at (token-span token) :parse "Expected expression")))))
             (parse-block ()
               (expect :left-brace)
               (let* ((node (expression)) (close (expect :right-brace)))
                 (values node (span-end (token-span close)))))
             (conditional ()
               (let ((start (span-start (token-span (expect :if)))))
                 (expect :left-paren)
                 (let ((condition (expression)))
                   (expect :right-paren)
                   (let ((then (parse-block)))
                     (expect :else)
                     (multiple-value-bind (else end) (parse-block)
                       (make-if-expression :condition condition
                                           :then-branch then :else-branch else
                                           :span (make-span source start end))))))))
      (let ((root (expression)))
        (expect :eof)
        (unless (= cursor (length tokens)) (internal-error "Tokens after EOF"))
        (make-program :source source :root root)))))
