(in-package #:mognitio.regalloc)

(defparameter +registers+ '(:r8 :r9 :r10 :r11))
(defstruct interval id start end)
(defstruct allocation locations intervals barriers spill-count order function)

(defun block-order (function)
  ;; Iterative postorder, with stable then/else successor order.
  (let ((blocks (make-hash-table)) (seen (make-hash-table)) (order nil)
        (stack (list (cons (mognitio.ir:ir-function-entry function) nil))))
    (dolist (b (mognitio.ir:ir-function-blocks function))
      (setf (gethash (mognitio.ir:basic-block-id b) blocks) b))
    (loop while stack do
      (destructuring-bind (id . finish) (pop stack)
        (cond (finish (push (gethash id blocks) order))
              ((not (gethash id seen))
               (setf (gethash id seen) t)
               (push (cons id t) stack)
               (dolist (next (reverse (mognitio.ir:successors (gethash id blocks))))
                 (push (cons next nil) stack))))))
    order))

(defun terminator-uses (block)
  (let ((term (mognitio.ir:basic-block-terminator block)))
    (ecase (first term) ((:return :branch) (list (second term))) (:jump (third term)) (:trap nil))))

(defun set-equal (a b) (and (subsetp a b) (subsetp b a)))

(defun live-intervals (function)
  (let ((table (make-hash-table)) (position 0) (barriers nil)
        (starts (make-hash-table)) (ends (make-hash-table))
        (uses (make-hash-table)) (defs (make-hash-table))
        (live-in (make-hash-table)) (live-out (make-hash-table))
        (order (block-order function)))
    (labels ((touch (id pos)
               (let ((i (gethash id table)))
                 (unless i (internal-error "Undefined allocation value"))
                 (setf (interval-start i) (min pos (interval-start i))
                       (interval-end i) (max pos (interval-end i))))))
      ;; Collect every definition before visiting any edge use.
      (dolist (block order)
        (setf (gethash (mognitio.ir:basic-block-id block) starts) position)
        (dolist (p (mognitio.ir:basic-block-parameters block))
          (setf (gethash (car p) table) (make-interval :id (car p) :start position :end position)))
        (incf position)
        (dolist (i (mognitio.ir:basic-block-instructions block))
          (when (member (mognitio.ir:instruction-op i)
                        '(:call :call.value :text.length :text.equal :text.not-equal :text.concat :text.slice :struct.make :enum.make :interface.pack :call.interface))
            (push (1+ position) barriers))
          (let ((id (mognitio.ir:instruction-result i)))
            (setf (gethash id table) (make-interval :id id :start (+ position 2) :end (+ position 2))))
          (incf position 3))
        (setf (gethash (mognitio.ir:basic-block-id block) ends) position)
        (incf position))
      (dolist (block order)
        (let* ((id (mognitio.ir:basic-block-id block))
               (defined (mapcar #'car (mognitio.ir:basic-block-parameters block))) (used nil)
               (pos (1+ (gethash id starts))))
          (flet ((record-use (value)
                   (touch value pos)
                   (unless (member value defined) (pushnew value used))))
            (dolist (i (mognitio.ir:basic-block-instructions block))
              (mapc #'record-use (mognitio.ir:instruction-operands i))
              (push (mognitio.ir:instruction-result i) defined) (incf pos 3))
            (mapc #'record-use (terminator-uses block)))
          (setf (gethash id defs) defined (gethash id uses) used)))
      (loop with changed = t while changed do
        (setf changed nil)
        (dolist (block (reverse order))
          (let* ((id (mognitio.ir:basic-block-id block))
                 (out (reduce #'union (mapcar (lambda (next) (gethash next live-in))
                                             (mognitio.ir:successors block)) :initial-value nil))
                 (in (union (gethash id uses) (set-difference out (gethash id defs)))))
            (unless (and (set-equal in (gethash id live-in)) (set-equal out (gethash id live-out)))
              (setf (gethash id live-in) in (gethash id live-out) out changed t)))))
      (dolist (block order)
        (let ((id (mognitio.ir:basic-block-id block)))
          (dolist (v (gethash id live-in)) (touch v (gethash id starts)))
          (dolist (v (gethash id live-out)) (touch v (gethash id ends)))))
      (values (sort (loop for i being the hash-values of table collect i)
                    (lambda (a b) (or (< (interval-start a) (interval-start b))
                                     (and (= (interval-start a) (interval-start b)) (< (interval-id a) (interval-id b))))))
              (nreverse barriers) order))))

(defun verify-live-coverage (allocation)
  ;; A separate instruction-level backwards analysis; it does not consume the
  ;; producer's block use/def, live sets, or interval endpoints as evidence.
  (let ((events (make-hash-table)) (starts (make-hash-table)) (lasts (make-hash-table))
        (before (make-hash-table)) (after (make-hash-table))
        (intervals (make-hash-table)) (position 0)
        (order (block-order (allocation-function allocation))))
    (dolist (i (allocation-intervals allocation)) (setf (gethash (interval-id i) intervals) i))
    (labels ((event (use def &optional barrier)
               (setf (gethash position events) (list (remove-duplicates use) (remove-duplicates def) (list (1+ position)) barrier))
               (incf position))
             (cover (id pos)
               (let ((i (gethash id intervals)))
                 (unless (and i (<= (interval-start i) pos (interval-end i)))
                   (internal-error "Interval omits a live position")))))
      (dolist (block order)
        (let ((id (mognitio.ir:basic-block-id block)))
          (setf (gethash id starts) position)
          (event nil (mapcar #'car (mognitio.ir:basic-block-parameters block)))
          (dolist (inst (mognitio.ir:basic-block-instructions block))
            (event (mognitio.ir:instruction-operands inst) nil)
            (event nil nil (member (mognitio.ir:instruction-op inst)
                                   '(:call :call.value :text.length :text.equal :text.not-equal :text.concat :text.slice :struct.make :enum.make :interface.pack :call.interface)))
            (event nil (list (mognitio.ir:instruction-result inst))))
          (setf (gethash id lasts) position)
          (event (terminator-uses block) nil)))
      (dolist (block order)
        (setf (third (gethash (gethash (mognitio.ir:basic-block-id block) lasts) events))
              (mapcar (lambda (id) (gethash id starts)) (mognitio.ir:successors block))))
      (loop with changed = t while changed do
        (setf changed nil)
        (loop for pos downfrom (1- position) to 0 for e = (gethash pos events) do
          (let* ((out (reduce #'union (mapcar (lambda (next) (gethash next before)) (third e)) :initial-value nil))
                 (in (union (first e) (set-difference out (second e)))))
            (unless (and (set-equal in (gethash pos before)) (set-equal out (gethash pos after)))
              (setf (gethash pos before) in (gethash pos after) out changed t)))))
      (loop for pos below position for e = (gethash pos events) do
        (let ((live (union (gethash pos before) (union (gethash pos after) (second e)))))
          (dolist (id live) (cover id pos))
          (loop for tail on live for a = (first tail) for location = (gethash a (allocation-locations allocation)) do
            (when (member location +registers+)
              (dolist (b (rest tail))
                (when (eql location (gethash b (allocation-locations allocation)))
                  (internal-error (format nil "Simultaneously live values ~D/~D share ~S at ~D" a b location pos))))))
          (when (fourth e)
            (dolist (id (intersection (gethash pos before) (gethash pos after)))
              (when (member (gethash id (allocation-locations allocation)) +registers+)
                (internal-error "Live value crosses a clobber in a register")))))))
    allocation))

(defun crosses-call-p (interval barriers)
  (some (lambda (position) (< (interval-start interval) position (interval-end interval))) barriers))

(defun allocate-function (function)
  (multiple-value-bind (intervals barriers order) (live-intervals function)
    (let ((locations (make-hash-table)) (active nil))
      (dolist (current intervals)
        (setf active (remove-if (lambda (i) (< (interval-end i) (interval-start current))) active))
        (let* ((used (mapcar (lambda (i) (gethash (interval-id i) locations)) active))
               (free (find-if (lambda (reg) (not (member reg used))) +registers+)))
          (cond
            ((crosses-call-p current barriers) (setf (gethash (interval-id current) locations) :spill))
            (free (setf (gethash (interval-id current) locations) free) (push current active))
            (t
             (let ((victim (first (sort (copy-list (cons current active))
                                (lambda (a b) (or (> (interval-end a) (interval-end b))
                                  (and (= (interval-end a) (interval-end b))
                                       (> (interval-id a) (interval-id b)))))))))
               (unless (eq victim current)
                 (setf (gethash (interval-id current) locations) (gethash (interval-id victim) locations)
                       active (cons current (remove victim active))))
               (setf (gethash (interval-id victim) locations) :spill))))))
      (let ((spills 0))
        (dolist (i (sort (copy-list intervals) #'< :key #'interval-id))
          (when (eq (gethash (interval-id i) locations) :spill)
            (setf (gethash (interval-id i) locations) (- (* 8 (incf spills))))))
        (let ((allocation (make-allocation :locations locations :intervals intervals
                            :barriers barriers :spill-count spills :order order :function function)))
          (verify-allocation allocation)
          allocation)))))

(defun verify-allocation (allocation)
  (verify-live-coverage allocation)
  ;; Pairwise checking is deliberately independent of the active-list algorithm.
  (let ((map (allocation-locations allocation)) (intervals (allocation-intervals allocation)))
    (loop for tail on intervals for a = (first tail) for location = (gethash (interval-id a) map) do
      (unless (or (member location +registers+)
                  (and (typep location '(integer * -8)) (zerop (mod location 8))
                       (<= (- location) (* 8 (allocation-spill-count allocation)))))
        (internal-error "Invalid allocated location"))
      (when (and (member location +registers+) (crosses-call-p a (allocation-barriers allocation)))
        (internal-error "Register survives a call barrier"))
      (dolist (b (rest tail))
        (when (and (eql location (gethash (interval-id b) map))
                   (or (integerp location)
                       (and (<= (interval-start a) (interval-end b))
                            (<= (interval-start b) (interval-end a)))))
          (internal-error "Overlapping allocated values")))))
  allocation)

(defun parallel-copies (copies temporary)
  (when (some (lambda (copy) (or (eql (car copy) temporary) (eql (cdr copy) temporary))) copies)
    (internal-error "Parallel copy temporary aliases a value"))
  (unless (= (length copies) (length (remove-duplicates copies :key #'car)))
    (internal-error "Duplicate parallel copy destination"))
  (let ((pending (remove-if (lambda (copy) (eql (car copy) (cdr copy))) (copy-tree copies))) (moves nil))
    (loop while pending do
      (let ((ready (find-if (lambda (copy) (not (member (car copy) pending :key #'cdr))) pending)))
        (if ready
            (progn (push ready moves) (setf pending (remove ready pending :test #'eq)))
            (let ((old (caar pending)))
              (push (cons temporary old) moves)
              (dolist (copy pending) (when (eql (cdr copy) old) (setf (cdr copy) temporary)))))))
    (nreverse moves)))
