(in-package #:mognitio.regalloc)

(defparameter +registers+ '(:r8 :r9 :r10 :r11))
(defstruct interval id start end)
(defstruct allocation locations intervals barriers spill-count order)

(defun block-order (function)
  ;; Iterative postorder, with stable then/else successor order.
  (let ((blocks (make-hash-table)) (seen (make-hash-table)) (order nil)
        (stack (list (cons (mognitio.ir:ir-function-entry function) nil))))
    (dolist (b (mognitio.ir:ir-function-blocks function))
      (setf (gethash (mognitio.ir:basic-block-id b) blocks) b))
    (loop while stack do
      (destructuring-bind (id . finish) (pop stack)
        (cond (finish (push (gethash id blocks) order))
              ((not (gethash id seen))
               (setf (gethash id seen) t)
               (push (cons id t) stack)
               (dolist (next (reverse (mognitio.ir:successors (gethash id blocks))))
                 (push (cons next nil) stack))))))
    order))

(defun live-intervals (function)
  (let ((table (make-hash-table)) (position 0) (barriers nil)
        (order (block-order function)))
    (labels ((define (id)
               (when (gethash id table) (internal-error "Duplicate allocation definition"))
               (setf (gethash id table) (make-interval :id id :start position :end position)))
             (use (id)
               (let ((interval (gethash id table)))
                 (unless interval (internal-error "Use precedes allocation definition"))
                 (setf (interval-end interval) (max position (interval-end interval))))))
      (dolist (block order)
        (dolist (p (mognitio.ir:basic-block-parameters block)) (define (car p)))
        (incf position)
        (dolist (i (mognitio.ir:basic-block-instructions block))
          (mapc #'use (mognitio.ir:instruction-operands i))
          (incf position)
          (when (eq (mognitio.ir:instruction-op i) :call) (push position barriers))
          (incf position)
          (define (mognitio.ir:instruction-result i))
          (incf position))
        (let ((term (mognitio.ir:basic-block-terminator block)))
          (ecase (first term)
            ((:return :branch) (use (second term)))
            (:jump (mapc #'use (third term)))))
        (incf position)))
    (values (sort (loop for interval being the hash-values of table collect interval)
                  (lambda (a b) (or (< (interval-start a) (interval-start b))
                                   (and (= (interval-start a) (interval-start b))
                                        (< (interval-id a) (interval-id b))))))
            (nreverse barriers) order)))

(defun crosses-call-p (interval barriers)
  (some (lambda (position) (< (interval-start interval) position (interval-end interval))) barriers))

(defun allocate-function (function)
  (multiple-value-bind (intervals barriers order) (live-intervals function)
    (let ((locations (make-hash-table)) (active nil))
      (dolist (current intervals)
        (setf active (remove-if (lambda (i) (< (interval-end i) (interval-start current))) active))
        (let* ((used (mapcar (lambda (i) (gethash (interval-id i) locations)) active))
               (free (find-if (lambda (reg) (not (member reg used))) +registers+)))
          (cond
            ((crosses-call-p current barriers) (setf (gethash (interval-id current) locations) :spill))
            (free (setf (gethash (interval-id current) locations) free) (push current active))
            (t
             (let ((victim (first (sort (copy-list (cons current active))
                                (lambda (a b) (or (> (interval-end a) (interval-end b))
                                  (and (= (interval-end a) (interval-end b))
                                       (> (interval-id a) (interval-id b)))))))))
               (unless (eq victim current)
                 (setf (gethash (interval-id current) locations) (gethash (interval-id victim) locations)
                       active (cons current (remove victim active))))
               (setf (gethash (interval-id victim) locations) :spill))))))
      (let ((spills 0))
        (dolist (i (sort (copy-list intervals) #'< :key #'interval-id))
          (when (eq (gethash (interval-id i) locations) :spill)
            (setf (gethash (interval-id i) locations) (- (* 8 (incf spills))))))
        (let ((allocation (make-allocation :locations locations :intervals intervals
                            :barriers barriers :spill-count spills :order order)))
          (verify-allocation allocation)
          allocation)))))

(defun verify-allocation (allocation)
  ;; Pairwise checking is deliberately independent of the active-list algorithm.
  (let ((map (allocation-locations allocation)) (intervals (allocation-intervals allocation)))
    (loop for tail on intervals for a = (first tail) for location = (gethash (interval-id a) map) do
      (unless (or (member location +registers+)
                  (and (typep location '(integer * -8)) (zerop (mod location 8))
                       (<= (- location) (* 8 (allocation-spill-count allocation)))))
        (internal-error "Invalid allocated location"))
      (when (and (member location +registers+) (crosses-call-p a (allocation-barriers allocation)))
        (internal-error "Register survives a call barrier"))
      (dolist (b (rest tail))
        (when (and (eql location (gethash (interval-id b) map))
                   (or (integerp location)
                       (and (<= (interval-start a) (interval-end b))
                            (<= (interval-start b) (interval-end a)))))
          (internal-error "Overlapping allocated values")))))
  allocation)

(defun parallel-copies (copies temporary)
  (when (some (lambda (copy) (or (eql (car copy) temporary) (eql (cdr copy) temporary))) copies)
    (internal-error "Parallel copy temporary aliases a value"))
  (unless (= (length copies) (length (remove-duplicates copies :key #'car)))
    (internal-error "Duplicate parallel copy destination"))
  (let ((pending (remove-if (lambda (copy) (eql (car copy) (cdr copy))) (copy-tree copies))) (moves nil))
    (loop while pending do
      (let ((ready (find-if (lambda (copy) (not (member (car copy) pending :key #'cdr))) pending)))
        (if ready
            (progn (push ready moves) (setf pending (remove ready pending :test #'eq)))
            (let ((old (caar pending)))
              (push (cons temporary old) moves)
              (dolist (copy pending) (when (eql (cdr copy) old) (setf (cdr copy) temporary)))))))
    (nreverse moves)))
