(in-package #:mognitio.roots)

(defstruct root-site block-id instruction-index values)
(defstruct root-plan function-id (capacity 0) sites)

(defun analyze-function-roots (function)
  ;; Block summaries retain parameters in live-in; each incoming edge replaces
  ;; those IDs with its own actual arguments. No allocation intervals are used.
  (let ((blocks (make-hash-table)) (types (make-hash-table))
        (uses (make-hash-table)) (defs (make-hash-table))
        (live-in (make-hash-table)) (live-out (make-hash-table))
        (order (sort (copy-list (ir-function-blocks function)) #'< :key #'basic-block-id)))
    (labels ((same-set (a b) (and (subsetp a b) (subsetp b a)))
             (terminal-use (block)
               (let ((term (basic-block-terminator block)))
                 (unless (eq (first term) :jump) (list (second term)))))
             (edge-live (block successor)
               (let* ((target (gethash successor blocks))
                      (term (basic-block-terminator block))
                      (substitutions (when (eq (first term) :jump)
                                       (pairlis (mapcar #'car (basic-block-parameters target)) (third term)))))
                 (remove-duplicates
                  (mapcar (lambda (v) (let ((pair (assoc v substitutions))) (if pair (cdr pair) v)))
                          (gethash successor live-in))))))
      (dolist (b order)
        (let ((id (basic-block-id b)) (defined nil) (used nil))
          (setf (gethash id blocks) b)
          (dolist (p (basic-block-parameters b)) (setf (gethash (car p) types) (cdr p)))
          (flet ((record-use (v) (unless (member v defined) (pushnew v used))))
            (dolist (i (basic-block-instructions b))
              (mapc #'record-use (instruction-operands i))
              (push (instruction-result i) defined)
              (setf (gethash (instruction-result i) types) (instruction-type i)))
            (mapc #'record-use (terminal-use b)))
          (setf (gethash id uses) used (gethash id defs) defined)))
      (loop with changed = t while changed do
        (setf changed nil)
        (dolist (b (reverse order))
          (let* ((id (basic-block-id b))
                 (out (reduce #'union (mapcar (lambda (next) (edge-live b next)) (successors b)) :initial-value nil))
                 (in (union (gethash id uses) (set-difference out (gethash id defs)))))
            (unless (and (same-set in (gethash id live-in)) (same-set out (gethash id live-out)))
              (setf (gethash id live-in) in (gethash id live-out) out changed t)))))
      (let ((sites nil) (capacity 0))
        (dolist (b order)
          (let ((live (union (terminal-use b) (gethash (basic-block-id b) live-out)))
                (local-sites nil))
            (loop for i in (reverse (basic-block-instructions b))
                  for index downfrom (1- (length (basic-block-instructions b))) do
              (setf live (union (remove-duplicates (instruction-operands i)) (remove (instruction-result i) live)))
              (when (member :may-allocate (instruction-effects i))
                (let ((values (sort (remove-if-not (lambda (v) (eq (gethash v types) :string))
                                                 (copy-list live)) #'<)))
                  (setf capacity (max capacity (length values)))
                  ;; List position is the root slot number, starting at zero.
                  (push (make-root-site :block-id (basic-block-id b) :instruction-index index :values values)
                        local-sites))))
            (setf sites (nconc sites local-sites))))
        (make-root-plan :function-id (ir-function-id function) :capacity capacity :sites sites)))))

(defun analyze-roots (module)
  (verify-module module)
  (let ((plans (mapcar #'analyze-function-roots
                      (sort (copy-list (module-functions module)) #'< :key #'ir-function-id))))
    (verify-roots module plans)
    plans))
