(in-package #:mognitio.semantic)

(defstruct local-symbol id name mutability type span)
(defstruct (checked-program (:constructor %make-checked-program (program types symbols literals bindings)))
  (program nil :read-only t) (types nil :read-only t) (symbols nil :read-only t)
  (literals nil :read-only t) (bindings nil :read-only t))
(defun checked-type (checked node)
  (or (gethash node (checked-program-types checked)) (internal-error "Missing checked type")))
(defun checked-symbol (checked node)
  (or (gethash node (checked-program-symbols checked)) (internal-error "Missing checked symbol")))
(defun checked-literal-p (checked node)
  (nth-value 1 (gethash node (checked-program-literals checked))))
(defun checked-literal (checked node)
  (multiple-value-bind (value found) (gethash node (checked-program-literals checked))
    (unless found (internal-error "Missing checked literal")) value))

(defun check-program (program)
  (unless (typep program 'program) (internal-error "Expected Program"))
  (let ((types (make-hash-table :test #'eq)) (resolved (make-hash-table :test #'eq))
        (literals (make-hash-table :test #'eq)) (bindings (make-array 0 :adjustable t :fill-pointer 0)))
    (labels ((lookup (token scopes)
               (loop for scope in scopes
                     for entry = (gethash (token-text token) scope)
                     when entry return entry))
             (reference (node token scopes)
               (let ((entry (lookup token scopes)))
                 (unless (and entry (eq (cdr entry) :visible))
                   (fail-at (token-span token) :semantic "Name is not visible"))
                 (setf (gethash node resolved) (car entry))
                 (car entry)))
             (require-type (node actual expected)
               (unless (eq actual expected)
                 (fail-at (node-span node) :semantic "Type mismatch")))
             (literal (node negative)
               (multiple-value-bind (magnitude valid)
                   (mognitio.integer:decimal-magnitude (token-text (integer-literal-token node)) negative)
                 (unless valid (fail-at (node-span node) :semantic "Integer literal is out of range"))
                 magnitude))
             (sequence-check (statements tail scopes)
               (map nil (lambda (s) (statement s scopes)) statements)
               (expression tail scopes))
             (statement (node scopes)
               (typecase node
                 (local-binding
                  (let ((token (local-binding-name node)))
                    (unless (member (local-binding-mutability node) '(:let :var))
                      (internal-error "Invalid binding mutability"))
                    (when (lookup token scopes)
                      (fail-at (token-span token) :semantic "Name is already declared or reserved"))
                    (let* ((symbol (make-local-symbol :id (length bindings) :name (token-text token)
                                     :mutability (local-binding-mutability node) :span (token-span token)))
                           (entry (cons symbol :reserved)))
                      (vector-push-extend symbol bindings)
                      (setf (gethash (token-text token) (first scopes)) entry
                            (gethash node resolved) symbol)
                      (setf (local-symbol-type symbol) (expression (local-binding-initializer node) scopes)
                            (cdr entry) :visible))))
                 (assignment
                  (let ((symbol (reference node (assignment-name node) scopes)))
                    (unless (eq (local-symbol-mutability symbol) :var)
                      (fail-at (token-span (assignment-name node)) :semantic "Cannot assign to let"))
                    (require-type (assignment-rhs node) (expression (assignment-rhs node) scopes)
                                  (local-symbol-type symbol))))
                 (t (internal-error "Invalid statement"))))
             (expression (node scopes)
               (let ((type
                       (typecase node
                         (boolean-literal
                          (unless (member (boolean-literal-value node) '(:true :false))
                            (internal-error "Invalid boolean literal")) :bool)
                         (integer-literal (setf (gethash node literals) (literal node nil)) :int)
                         (variable-reference (local-symbol-type (reference node (variable-reference-name node) scopes)))
                         (grouping (expression (grouping-expression node) scopes))
                         (sequence-node
                          (sequence-check (sequence-node-statements node) (sequence-node-tail node)
                                          (cons (make-hash-table :test #'equal) scopes)))
                         (unary-expression
                          (unless (eq (token-kind (unary-expression-operator node)) :sub)
                            (internal-error "Invalid unary operator"))
                          (let ((child (unary-expression-operand node)))
                            (if (typep child 'integer-literal)
                                (let ((magnitude (literal child t)))
                                  (if (= magnitude (- mognitio.integer:+minimum+))
                                      (setf (gethash node literals) (- magnitude)
                                            (gethash child types) :consumed)
                                      (expression child scopes)))
                                (require-type child (expression child scopes) :int)))
                          :int)
                         (binary-expression
                          (let* ((left (binary-expression-left node)) (right (binary-expression-right node))
                                 (a (expression left scopes)) (b (expression right scopes))
                                 (op (token-kind (binary-expression-operator node))))
                            (unless (member op '(:add :sub :mul :div :rem :eq :ne :lt :le :gt :ge))
                              (internal-error "Invalid binary operator"))
                            (require-type right b a)
                            (unless (member op '(:eq :ne)) (require-type left a :int))
                            (if (member op '(:add :sub :mul :div :rem)) :int :bool)))
                         (if-expression
                          (require-type (if-expression-condition node)
                            (expression (if-expression-condition node) scopes) :bool)
                          (let ((a (expression (if-expression-then-branch node) scopes))
                                (b (expression (if-expression-else-branch node) scopes)))
                            (require-type (if-expression-else-branch node) b a) a))
                         (t (internal-error "Invalid AST node or missing child")))))
                 (setf (gethash node types) type) type)))
      (require-type (program-root program)
        (sequence-check (program-statements program) (program-root program)
                        (list (make-hash-table :test #'equal))) :bool)
      (%make-checked-program program types resolved literals bindings))))
