(in-package #:mognitio.semantic)

(defstruct local-symbol id owner name mutability type span targets static-target)
(defstruct signature id declaration parameter-types result-type)
(defstruct completion normal-type may-return targets exits)
(defstruct loop-info id owner node normal-type targets plain valued types)
(defstruct call-info type targets owner)
(defstruct (checked-program (:constructor %make-checked-program))
  program summaries symbols literals consumed bindings signatures calls returns functions loops controls)
(defun function-type-p (type) (and (consp type) (eq (first type) :function) (= (length type) 3)))
(defun signature-type (signature)
  (list :function (signature-parameter-types signature) (signature-result-type signature)))
(defun checked-completion (checked node)
  (or (gethash node (checked-program-summaries checked)) (internal-error "Missing completion summary")))
(defun checked-normal-type (checked node) (completion-normal-type (checked-completion checked node)))
(defun checked-symbol (checked node)
  (or (gethash node (checked-program-symbols checked)) (internal-error "Missing checked symbol")))
(defun checked-call (checked node)
  (or (gethash node (checked-program-calls checked)) (internal-error "Missing checked call")))
(defun checked-function (checked node)
  (or (gethash node (checked-program-functions checked)) (internal-error "Missing function")))
(defun checked-loop (checked node)
  (or (gethash node (checked-program-loops checked)) (internal-error "Missing checked loop")))
(defun checked-control (checked node)
  (or (gethash node (checked-program-controls checked)) (internal-error "Missing control target")))
(defun checked-return (checked node)
  (or (gethash node (checked-program-returns checked)) (internal-error "Missing return owner")))
(defun checked-literal-p (checked node) (nth-value 1 (gethash node (checked-program-literals checked))))
(defun checked-literal (checked node)
  (multiple-value-bind (value found) (gethash node (checked-program-literals checked))
    (unless found (internal-error "Missing checked literal")) value))

(defun check-call-graph (ids edges report-cycle)
  ;; Explicit DFS frames avoid imposing the host call stack on call-chain length.
  (let ((colors (make-hash-table)))
    (dolist (root ids)
      (unless (gethash root colors)
        (let ((stack (list (list root (copy-list (gethash root edges))))))
          (setf (gethash root colors) :gray)
          (loop while stack do
            (let* ((frame (first stack)) (edge (pop (second frame))))
              (if (null edge)
                  (progn (setf (gethash (first frame) colors) :black) (pop stack))
                  (case (gethash (car edge) colors)
                    (:gray (funcall report-cycle (cdr edge)))
                    (:black nil)
                    (otherwise
                     (setf (gethash (car edge) colors) :gray)
                     (push (list (car edge) (copy-list (gethash (car edge) edges))) stack))))))))))
  t)

(defun check-program (program)
  (unless (and (typep program 'program) (program-root program)) (internal-error "Expected Program"))
  (let* ((summaries (make-hash-table :test #'eq)) (resolved (make-hash-table :test #'eq))
         (literals (make-hash-table :test #'eq)) (consumed (make-hash-table :test #'eq))
         (calls (make-hash-table :test #'eq)) (returns (make-hash-table :test #'eq))
         (bindings (make-array 0 :adjustable t :fill-pointer 0))
         (signatures (make-array 0 :adjustable t :fill-pointer 0))
         (functions (make-hash-table :test #'eq)) (loops (make-hash-table :test #'eq))
         (controls (make-hash-table :test #'eq)) (loop-stack nil) (edges (make-hash-table)) (owner 0))
    (labels ((lookup (token scopes)
               (loop for scope in scopes for entry = (gethash (token-text token) scope) when entry return entry))
             (reference (node token scopes)
               (let ((entry (lookup token scopes)))
                 (unless (and entry (eq (cdr entry) :visible))
                   (fail-at (token-span token) :semantic "Name is not visible"))
                 (let ((symbol (car entry)))
                   (unless (or (= owner (local-symbol-owner symbol)) (local-symbol-static-target symbol))
                     (fail-at (token-span token) :semantic "Runtime capture is not supported"))
                   (setf (gethash node resolved) symbol))))
             (require-type (node actual expected)
               (when (and actual (not (equal actual expected)))
                 (fail-at (node-span node) :semantic "Type mismatch")))
             (normal (summary) (completion-normal-type summary))
             (summary (node type children &optional targets returns-p extra-exits)
               (let ((may-return returns-p) (reachable t) (exits nil))
                 (dolist (child children)
                   (when reachable (setf may-return (or may-return (completion-may-return child))
                                         exits (union exits (completion-exits child) :test #'equal)))
                   (unless (normal child) (setf reachable nil)))
                 (setf (gethash node summaries)
                       (make-completion :normal-type type :may-return (not (null may-return)) :exits (union exits extra-exits :test #'equal)
                         :targets (when type (sort (remove-duplicates (copy-list targets)) #'<))))))
             (literal (node negative)
               (multiple-value-bind (magnitude valid)
                   (mognitio.integer:decimal-magnitude (token-text (integer-literal-token node)) negative)
                 (unless valid (fail-at (node-span node) :semantic "Integer literal is out of range")) magnitude))
             (declare-local (node token mutability scopes &optional type)
               (when (lookup token scopes)
                 (fail-at (token-span token) :semantic "Name is already declared or reserved"))
               (let* ((symbol (make-local-symbol :id (length bindings) :owner owner :name (token-text token)
                                :mutability mutability :type type :span (token-span token)))
                      (entry (cons symbol (if type :visible :reserved))))
                 (vector-push-extend symbol bindings)
                 (setf (gethash (token-text token) (first scopes)) entry (gethash node resolved) symbol)
                 entry))
             (static-target (node)
               (typecase node
                 (function-expression (signature-id (gethash node functions)))
                 (grouping (static-target (grouping-expression node)))
                 (variable-reference (local-symbol-static-target (gethash node resolved)))))
             (sequence-check (node statements terminal scopes)
               (let ((children nil) (reachable t))
                 (loop for child across statements do
                   (unless reachable (fail-at (node-span child) :semantic "Unreachable sequence element"))
                   (let ((result (expression child scopes))) (push result children) (setf reachable (normal result))))
                 (when terminal
                   (unless reachable (fail-at (node-span terminal) :semantic "Unreachable sequence tail"))
                   (push (expression terminal scopes) children))
                 (summary node (when reachable (if terminal (normal (first children)) :void))
                          (reverse children) (when terminal (completion-targets (first children))))))
             (expression (node scopes)
               (typecase node
                 (loop-expression
                  (let* ((info (make-loop-info :id (hash-table-count loops) :owner owner :node node))
                         (outer loop-stack))
                    (setf (gethash node loops) info loop-stack (cons info loop-stack))
                    (let* ((conditional (loop-expression-condition node))
                           (condition (when conditional (expression conditional scopes)))
                           (body (expression (loop-expression-body node) scopes))
                           (exits (if conditional
                                      (union (completion-exits condition)
                                             (when (normal condition) (completion-exits body)) :test #'equal)
                                      (completion-exits body)))
                           (breaks (remove-if-not (lambda (exit) (and (eq (first exit) :break)
                                                    (= (second exit) (loop-info-id info)))) exits))
                           (escaped (remove-if (lambda (exit) (and (member (first exit) '(:break :continue))
                                                    (= (second exit) (loop-info-id info)))) exits))
                           (type (if conditional (when (or (normal condition) breaks) :void)
                                     (third (first breaks))))
                           (targets (reduce (lambda (a b) (union a b)) (mapcar #'fourth breaks) :initial-value nil)))
                      (when conditional (require-type conditional (normal condition) :bool))
                      (require-type node (normal body) :void)
                      (when (and (loop-info-plain info) (loop-info-valued info))
                        (fail-at (node-span node) :semantic "Plain and valued breaks cannot be mixed"))
                      (when (> (length (loop-info-types info)) 1)
                        (fail-at (node-span node) :semantic "Break result types differ"))
                      (setf loop-stack outer (loop-info-normal-type info) type
                            (loop-info-targets info) (sort (copy-list targets) #'<))
                      (summary node type nil targets (find :return escaped :key #'first) escaped))))
                 (break-statement
                  (unless loop-stack (fail-at (node-span node) :semantic "Break requires a loop"))
                  (let* ((info (first loop-stack)) (operand (break-statement-value node))
                         (child (when operand (expression operand scopes)))
                         (type (if operand (normal child) :void)))
                    (setf (gethash node controls) info)
                    (if operand (setf (loop-info-valued info) t) (setf (loop-info-plain info) t))
                    (when (and operand (loop-expression-condition (loop-info-node info)))
                      (fail-at (node-span node) :semantic "Conditional loop forbids valued break"))
                    (when type (pushnew type (loop-info-types info) :test #'equal))
                    (summary node nil (when child (list child)) nil nil
                             (when type (list (list :break (loop-info-id info) type (when child (completion-targets child))))))))

                 (continue-statement
                  (unless loop-stack (fail-at (node-span node) :semantic "Continue requires a loop"))
                  (let ((info (first loop-stack)))
                    (setf (gethash node controls) info)
                    (summary node nil nil nil nil (list (list :continue (loop-info-id info) nil nil)))))
                 (void-literal (summary node :void nil))
                 (expression-statement
                  (let ((child (expression (expression-statement-expression node) scopes)))
                    (require-type node (normal child) :void)
                    (summary node (normal child) (list child))))
                 (boolean-literal
                  (unless (member (boolean-literal-value node) '(:true :false)) (internal-error "Invalid boolean literal"))
                  (summary node :bool nil))
                 (integer-literal (setf (gethash node literals) (literal node nil)) (summary node :int nil))
                 (variable-reference
                  (let ((symbol (reference node (variable-reference-name node) scopes)))
                    (summary node (local-symbol-type symbol) nil (local-symbol-targets symbol))))
                 (function-expression
                  (let* ((id (length signatures))
                         (signature (make-signature :id id :declaration node
                                      :parameter-types (map 'list (lambda (p) (token-kind (parameter-type p))) (function-expression-parameters node))
                                      :result-type (token-kind (function-expression-result-type node))))
                         (outer owner) (outer-loops loop-stack) (body-scope (cons (make-hash-table :test #'equal) scopes)))
                    (vector-push-extend signature signatures) (setf (gethash node functions) signature owner id loop-stack nil)
                    (loop for p across (function-expression-parameters node) do
                      (declare-local p (parameter-name p) :parameter body-scope (token-kind (parameter-type p)))
                      (summary p (token-kind (parameter-type p)) nil))
                    (let ((body (expression (function-expression-body node) body-scope)))
                      (require-type node (normal body) (signature-result-type signature)))
                    (setf owner outer loop-stack outer-loops)
                    (summary node (signature-type signature) nil (list id))))
                 (grouping
                  (let ((child (expression (grouping-expression node) scopes)))
                    (summary node (normal child) (list child) (completion-targets child))))
                 (sequence-node
                  (sequence-check node (sequence-node-statements node) (sequence-node-terminal node)
                                  (cons (make-hash-table :test #'equal) scopes)))
                 (local-binding
                  (unless (member (local-binding-mutability node) '(:let :var)) (internal-error "Invalid mutability"))
                  (let* ((entry (declare-local node (local-binding-name node) (local-binding-mutability node) scopes))
                         (child (expression (local-binding-initializer node) scopes)))
                    (unless (normal child) (fail-at (node-span node) :semantic "Initializer has no normal type"))
                    (when (and (eq (local-binding-mutability node) :var) (function-type-p (normal child)))
                      (fail-at (node-span node) :semantic "Mutable function values are not supported"))
                    (setf (local-symbol-type (car entry)) (normal child) (cdr entry) :visible
                          (local-symbol-targets (car entry)) (completion-targets child)
                          (local-symbol-static-target (car entry)) (static-target (local-binding-initializer node)))
                    (summary node :void (list child))))
                 (assignment
                  (let* ((symbol (reference node (assignment-name node) scopes))
                         (child (expression (assignment-rhs node) scopes)))
                    (unless (eq (local-symbol-mutability symbol) :var)
                      (fail-at (node-span node) :semantic "Cannot assign to immutable binding"))
                    (require-type node (normal child) (local-symbol-type symbol))
                    (summary node (when (normal child) :void) (list child))))
                 (return-statement
                  (when (zerop owner) (fail-at (node-span node) :semantic "Return requires a function"))
                  (let ((child (if (return-statement-value node) (expression (return-statement-value node) scopes) (make-completion :normal-type :void))))
                    (require-type node (normal child) (signature-result-type (aref signatures owner)))
                    (setf (gethash node returns) owner)
                    (summary node nil (list child) nil (not (null (normal child)))
                             (when (normal child) (list (list :return owner nil nil))))))
                 (call-expression
                  (let* ((callee (expression (call-expression-callee node) scopes)) (type (normal callee))
                         (children (loop for arg across (call-expression-arguments node) collect (expression arg scopes))))
                    (when type
                      (unless (function-type-p type) (fail-at (node-span node) :semantic "Callee is not a function"))
                      (unless (= (length (second type)) (length children))
                        (fail-at (node-span node) :semantic "Wrong argument count"))
                      (loop for child in children for expected in (second type) do (require-type node (normal child) expected)))
                    (setf (gethash node calls) (make-call-info :type type :targets (completion-targets callee) :owner owner))
                    (dolist (target (completion-targets callee)) (push (cons target (node-span node)) (gethash owner edges)))
                    (summary node (when (and type (every #'normal children)) (third type)) (cons callee children))))
                 (unary-expression
                  (unless (eq (token-kind (unary-expression-operator node)) :sub) (internal-error "Invalid unary operator"))
                  (let ((child (unary-expression-operand node)))
                    (if (and (typep child 'integer-literal) (= (literal child t) (- mognitio.integer:+minimum+)))
                        (progn (setf (gethash node literals) mognitio.integer:+minimum+ (gethash child consumed) t)
                               (summary child nil nil) (summary node :int nil))
                        (let ((result (expression child scopes)))
                          (require-type child (normal result) :int)
                          (summary node (when (normal result) :int) (list result))))))
                 (binary-expression
                  (let* ((left (binary-expression-left node)) (right (binary-expression-right node))
                         (a (expression left scopes)) (b (expression right scopes))
                         (op (token-kind (binary-expression-operator node))))
                    (unless (member op '(:add :sub :mul :div :rem :eq :ne :lt :le :gt :ge)) (internal-error "Invalid binary operator"))
                    (if (member op '(:eq :ne))
                        (progn
                          (dolist (child (list a b))
                            (when (and (normal child) (not (member (normal child) '(:int :bool))))
                              (fail-at (node-span node) :semantic "Equality requires primitive operands")))
                          (when (and (normal a) (normal b)) (require-type right (normal b) (normal a))))
                        (progn (require-type left (normal a) :int) (require-type right (normal b) :int)))
                    (summary node (when (and (normal a) (normal b)) (if (member op '(:add :sub :mul :div :rem)) :int :bool)) (list a b))))
                 (if-expression
                  (let* ((condition (expression (if-expression-condition node) scopes))
                         (a (expression (if-expression-then-branch node) scopes))
                         (b (if (if-expression-else-branch node) (expression (if-expression-else-branch node) scopes) (make-completion :normal-type :void))))
                    (require-type (if-expression-condition node) (normal condition) :bool)
                    (when (and (normal a) (normal b)) (require-type node (normal b) (normal a)))
                    (let ((result (summary node (when (normal condition) (or (normal a) (normal b))) (list condition)
                                          (union (completion-targets a) (completion-targets b)))))
                      (setf (completion-may-return result) (not (null (or (completion-may-return condition)
                              (and (normal condition) (or (completion-may-return a) (completion-may-return b)))))))
                      (when (normal condition)
                        (setf (completion-exits result) (union (completion-exits condition)
                          (union (completion-exits a) (completion-exits b) :test #'equal) :test #'equal))) result)))
                 (t (internal-error "Invalid AST node or missing child")))))
      (vector-push-extend (make-signature :id 0 :result-type :bool) signatures)
      (let ((entry (sequence-check program (program-statements program) (program-root program)
                                   (list (make-hash-table :test #'equal)))))
        (require-type (program-root program) (normal entry) :bool))
      (check-call-graph (loop for id below (length signatures) collect id) edges
                        (lambda (span) (fail-at span :semantic "Recursive call graph")))
      (%make-checked-program :program program :summaries summaries :symbols resolved
        :literals literals :consumed consumed :bindings bindings :signatures signatures :calls calls :returns returns :functions functions :loops loops :controls controls))))
