(in-package #:mognitio.semantic)

(defstruct local-symbol id owner name mutability type span targets static-target)
(defstruct signature id declaration parameter-types result-type receiver method)
(defstruct completion normal-type may-return targets exits)
(defstruct loop-info id owner node normal-type targets plain valued types)
(defstruct call-info type targets owner)
(defstruct operation-info kind operands parameter-types result-type)
(defstruct (checked-program (:constructor %make-checked-program))
  program summaries symbols literals consumed bindings signatures calls returns functions loops controls operations values)
(defun function-type-p (type) (and (consp type) (eq (first type) :function) (= (length type) 3)))
(defun signature-type (signature)
  (list :function (signature-parameter-types signature) (signature-result-type signature)))
(defun checked-completion (checked node)
  (or (gethash node (checked-program-summaries checked)) (internal-error "Missing completion summary")))
(defun checked-normal-type (checked node) (completion-normal-type (checked-completion checked node)))
(defun checked-symbol (checked node)
  (or (gethash node (checked-program-symbols checked)) (internal-error "Missing checked symbol")))
(defun checked-operation (checked node) (gethash node (checked-program-operations checked)))
(defun checked-call (checked node)
  (or (gethash node (checked-program-calls checked)) (internal-error "Missing checked call")))
(defun checked-function (checked node)
  (or (gethash node (checked-program-functions checked)) (internal-error "Missing function")))
(defun checked-loop (checked node)
  (or (gethash node (checked-program-loops checked)) (internal-error "Missing checked loop")))
(defun checked-control (checked node)
  (or (gethash node (checked-program-controls checked)) (internal-error "Missing control target")))
(defun checked-return (checked node)
  (or (gethash node (checked-program-returns checked)) (internal-error "Missing return owner")))
(defun checked-literal-p (checked node) (nth-value 1 (gethash node (checked-program-literals checked))))
(defun checked-literal (checked node)
  (multiple-value-bind (value found) (gethash node (checked-program-literals checked))
    (unless found (internal-error "Missing checked literal")) value))

(defun check-call-graph (ids edges report-cycle)
  ;; Explicit DFS frames avoid imposing the host call stack on call-chain length.
  (let ((colors (make-hash-table)))
    (dolist (root ids)
      (unless (gethash root colors)
        (let ((stack (list (list root (copy-list (gethash root edges))))))
          (setf (gethash root colors) :gray)
          (loop while stack do
            (let* ((frame (first stack)) (edge (pop (second frame))))
              (if (null edge)
                  (progn (setf (gethash (first frame) colors) :black) (pop stack))
                  (case (gethash (car edge) colors)
                    (:gray (funcall report-cycle (cdr edge)))
                    (:black nil)
                    (otherwise
                     (setf (gethash (car edge) colors) :gray)
                     (push (list (car edge) (copy-list (gethash (car edge) edges))) stack))))))))))
  t)
