(in-package #:mognitio.semantic)

(defstruct local-symbol id owner name mutability type span)
(defstruct signature id declaration parameter-types result-type)
(defstruct completion normal-type may-return)
(defstruct (checked-program (:constructor %make-checked-program))
  program summaries symbols literals consumed bindings signatures calls returns)
(defun checked-completion (checked node)
  (or (gethash node (checked-program-summaries checked)) (internal-error "Missing completion summary")))
(defun checked-normal-type (checked node) (completion-normal-type (checked-completion checked node)))
(defun checked-symbol (checked node)
  (or (gethash node (checked-program-symbols checked)) (internal-error "Missing checked symbol")))
(defun checked-call (checked node)
  (or (gethash node (checked-program-calls checked)) (internal-error "Missing checked call")))
(defun checked-return (checked node)
  (or (gethash node (checked-program-returns checked)) (internal-error "Missing return owner")))
(defun checked-literal-p (checked node) (nth-value 1 (gethash node (checked-program-literals checked))))
(defun checked-literal (checked node)
  (multiple-value-bind (value found) (gethash node (checked-program-literals checked))
    (unless found (internal-error "Missing checked literal")) value))

(defun check-call-graph (ids edges report-cycle)
  ;; Explicit DFS frames avoid imposing the host call stack on call-chain length.
  (let ((colors (make-hash-table)))
    (dolist (root ids)
      (unless (gethash root colors)
        (let ((stack (list (list root (copy-list (gethash root edges))))))
          (setf (gethash root colors) :gray)
          (loop while stack do
            (let* ((frame (first stack)) (edge (pop (second frame))))
              (if (null edge)
                  (progn (setf (gethash (first frame) colors) :black) (pop stack))
                  (case (gethash (car edge) colors)
                    (:gray (funcall report-cycle (cdr edge)))
                    (:black nil)
                    (otherwise
                     (setf (gethash (car edge) colors) :gray)
                     (push (list (car edge) (copy-list (gethash (car edge) edges))) stack))))))))))
  t)

(defun check-program (program)
  (unless (typep program 'program) (internal-error "Expected Program"))
  (let* ((summaries (make-hash-table :test #'eq)) (resolved (make-hash-table :test #'eq))
         (literals (make-hash-table :test #'eq)) (consumed (make-hash-table :test #'eq))
         (calls (make-hash-table :test #'eq)) (returns (make-hash-table :test #'eq))
         (bindings (make-array 0 :adjustable t :fill-pointer 0))
         (signatures (make-array (1+ (length (program-functions program)))))
         (functions (make-hash-table :test #'equal)) (edges (make-hash-table)) (owner 0))
    (labels ((lookup (token scopes)
               (loop for scope in scopes for entry = (gethash (token-text token) scope) when entry return entry))
             (reference (node token scopes)
               (let ((entry (lookup token scopes)))
                 (unless (and entry (eq (cdr entry) :visible))
                   (fail-at (token-span token) :semantic "Name is not visible"))
                 (setf (gethash node resolved) (car entry))))
             (require-type (node actual expected)
               (when (and actual (not (eq actual expected)))
                 (fail-at (node-span node) :semantic "Type mismatch")))
             (normal (summary) (completion-normal-type summary))
             (summary (node type children &optional returns-p)
               (setf (gethash node summaries)
                     (make-completion :normal-type type
                       :may-return (or returns-p (some #'completion-may-return children)))))
             (literal (node negative)
               (multiple-value-bind (magnitude valid)
                   (mognitio.integer:decimal-magnitude (token-text (integer-literal-token node)) negative)
                 (unless valid (fail-at (node-span node) :semantic "Integer literal is out of range")) magnitude))
             (declare-local (node token mutability scopes &optional type)
               (when (or (lookup token scopes) (gethash (token-text token) functions))
                 (fail-at (token-span token) :semantic "Name is already declared or reserved"))
               (let* ((symbol (make-local-symbol :id (length bindings) :owner owner :name (token-text token)
                                :mutability mutability :type type :span (token-span token)))
                      (entry (cons symbol (if type :visible :reserved))))
                 (vector-push-extend symbol bindings)
                 (setf (gethash (token-text token) (first scopes)) entry (gethash node resolved) symbol)
                 entry))
             (sequence-check (node statements terminal scopes)
               (let* ((children (loop for s across statements collect (expression s scopes)))
                      (tail (expression terminal scopes)))
                 (summary node (when (every #'normal children) (normal tail)) (append children (list tail)))))
             (expression (node scopes)
               (typecase node
                 (boolean-literal
                  (unless (member (boolean-literal-value node) '(:true :false)) (internal-error "Invalid boolean literal"))
                  (summary node :bool nil))
                 (integer-literal (setf (gethash node literals) (literal node nil)) (summary node :int nil))
                 (variable-reference (summary node (local-symbol-type (reference node (variable-reference-name node) scopes)) nil))
                 (grouping
                  (let ((child (expression (grouping-expression node) scopes))) (summary node (normal child) (list child))))
                 (sequence-node
                  (sequence-check node (sequence-node-statements node) (sequence-node-terminal node)
                                  (cons (make-hash-table :test #'equal) scopes)))
                 (local-binding
                  (unless (member (local-binding-mutability node) '(:let :var)) (internal-error "Invalid mutability"))
                  (let* ((entry (declare-local node (local-binding-name node) (local-binding-mutability node) scopes))
                         (child (expression (local-binding-initializer node) scopes)))
                    (unless (normal child) (fail-at (node-span node) :semantic "Initializer has no normal type"))
                    (setf (local-symbol-type (car entry)) (normal child) (cdr entry) :visible)
                    (summary node (normal child) (list child))))
                 (assignment
                  (let* ((symbol (reference node (assignment-name node) scopes))
                         (child (expression (assignment-rhs node) scopes)))
                    (unless (eq (local-symbol-mutability symbol) :var)
                      (fail-at (node-span node) :semantic "Cannot assign to immutable binding"))
                    (require-type node (normal child) (local-symbol-type symbol))
                    (summary node (normal child) (list child))))
                 (return-statement
                  (when (zerop owner) (fail-at (node-span node) :semantic "Return requires a function"))
                  (let ((child (expression (return-statement-value node) scopes)))
                    (require-type node (normal child) (signature-result-type (aref signatures owner)))
                    (setf (gethash node returns) owner)
                    (summary node nil (list child) t)))
                 (call-expression
                  (let ((callee (gethash (token-text (call-expression-callee node)) functions)))
                    (unless callee (fail-at (node-span node) :semantic "Unknown function"))
                    (unless (= (length (signature-parameter-types callee)) (length (call-expression-arguments node)))
                      (fail-at (node-span node) :semantic "Wrong argument count"))
                    (setf (gethash node calls) callee)
                    (push (cons (signature-id callee) (node-span node)) (gethash owner edges))
                    (let ((children
                            (loop for arg across (call-expression-arguments node)
                                  for type in (signature-parameter-types callee)
                                  for child = (expression arg scopes) do (require-type arg (normal child) type)
                                  collect child)))
                      (summary node (when (every #'normal children) (signature-result-type callee)) children))))
                 (unary-expression
                  (unless (eq (token-kind (unary-expression-operator node)) :sub) (internal-error "Invalid unary operator"))
                  (let ((child (unary-expression-operand node)))
                    (if (and (typep child 'integer-literal) (= (literal child t) (- mognitio.integer:+minimum+)))
                        (progn (setf (gethash node literals) mognitio.integer:+minimum+ (gethash child consumed) t)
                               (summary child nil nil) (summary node :int nil))
                        (let ((result (expression child scopes)))
                          (require-type child (normal result) :int)
                          (summary node (when (normal result) :int) (list result))))))
                 (binary-expression
                  (let* ((left (binary-expression-left node)) (right (binary-expression-right node))
                         (a (expression left scopes)) (b (expression right scopes))
                         (op (token-kind (binary-expression-operator node))))
                    (unless (member op '(:add :sub :mul :div :rem :eq :ne :lt :le :gt :ge))
                      (internal-error "Invalid binary operator"))
                    (if (member op '(:eq :ne))
                        (when (and (normal a) (normal b)) (require-type right (normal b) (normal a)))
                        (progn (require-type left (normal a) :int) (require-type right (normal b) :int)))
                    (summary node (when (and (normal a) (normal b))
                                    (if (member op '(:add :sub :mul :div :rem)) :int :bool)) (list a b))))
                 (if-expression
                  (let* ((condition (expression (if-expression-condition node) scopes))
                         (a (expression (if-expression-then-branch node) scopes))
                         (b (expression (if-expression-else-branch node) scopes)))
                    (require-type (if-expression-condition node) (normal condition) :bool)
                    (when (and (normal a) (normal b)) (require-type node (normal b) (normal a)))
                    (summary node (when (normal condition) (or (normal a) (normal b))) (list condition a b))))
                 (t (internal-error "Invalid AST node or missing child")))))
      (setf (aref signatures 0) (make-signature :id 0 :result-type :bool))
      (loop for declaration across (program-functions program) for id from 1 do
        (let* ((token (function-declaration-name declaration)) (name (token-text token))
               (signature (make-signature :id id :declaration declaration
                            :parameter-types (map 'list (lambda (p) (token-kind (parameter-type p)))
                                                  (function-declaration-parameters declaration))
                            :result-type (token-kind (function-declaration-result-type declaration)))))
          (when (gethash name functions) (fail-at (token-span token) :semantic "Duplicate function name"))
          (setf (gethash name functions) signature (aref signatures id) signature)))
      (loop for declaration across (program-functions program) for id from 1 do
        (setf owner id)
        (let ((scopes (list (make-hash-table :test #'equal))) (body (function-declaration-body declaration)))
          (loop for p across (function-declaration-parameters declaration) do
            (declare-local p (parameter-name p) :parameter scopes (token-kind (parameter-type p)))
            (summary p (token-kind (parameter-type p)) nil))
          (expression body scopes)
          ;; Check the terminal independently, including after an abrupt statement.
          (require-type body (normal (gethash (sequence-node-terminal body) summaries))
                        (signature-result-type (aref signatures id)))))
      (setf owner 0)
      (let ((entry (sequence-check program (program-statements program) (program-root program)
                                   (list (make-hash-table :test #'equal)))))
        (unless (eq (normal entry) :bool) (fail-at (node-span (program-root program)) :semantic "Entry requires bool")))
      (maphash (lambda (id value) (setf (gethash id edges) (nreverse value))) edges)
      (check-call-graph (loop for id below (length signatures) collect id) edges
                        (lambda (span) (fail-at span :semantic "Recursive call graph")))
      (%make-checked-program :program program :summaries summaries :symbols resolved
        :literals literals :consumed consumed :bindings bindings :signatures signatures :calls calls :returns returns))))
