(in-package #:mognitio.semantic)

(defun register-implementation (context node scopes signatures check-function)
  (let* ((concrete (resolve-type-token context (implementation-declaration-target node)))
         (contract (when (implementation-declaration-contract node)
                     (resolve-type-token context (implementation-declaration-contract node))))
         (existing (find-implementation context concrete contract))
         (seen (make-hash-table :test #'equal)) (pending nil))
    (unless (and (nominal-type-p concrete) (not (nominal-type-p concrete :interface))
                 (not (generic-origin-p context concrete)))
      (fail-at (node-span node) :semantic "Implementation requires a concrete type"))
    (when (and contract (not (nominal-type-p contract :interface)))
      (fail-at (node-span node) :semantic "Against requires an interface"))
    (when (and existing contract) (fail-at (node-span node) :semantic "Duplicate implementation"))
    (let* ((info (or existing (make-implementation-info :id (length (value-context-implementations context))
                                 :concrete concrete :contract contract)))
           (required (when contract (type-info-methods (context-type context contract)))))
      (loop for method across (implementation-declaration-methods node)
            for name = (token-text (local-binding-name method)) for function = (local-binding-initializer method) do
        (when (or (gethash name seen) (assoc name (implementation-info-methods info) :test #'string=)
                  (assoc name (type-info-fields (context-type context concrete)) :test #'string=))
          (fail-at (token-span (local-binding-name method)) :semantic "Duplicate method or field collision"))
        (setf (gethash name seen) t)
        (let* ((parameters (map 'list (lambda (p) (resolve-type-token context (parameter-type p))) (function-expression-parameters function)))
               (result (resolve-type-token context (function-expression-result-type function)))
               (requirement (find name required :key #'requirement-name :test #'string=)))
          (when (and contract (not (and requirement (equal parameters (requirement-parameters requirement))
                                        (equal result (requirement-result requirement)))))
            (fail-at (node-span method) :semantic "Method does not match the contract"))
          (let ((sig (make-signature :id (length signatures) :declaration function :parameter-types parameters
                       :result-type result :method (list concrete contract name))))
            (vector-push-extend sig signatures)
            (push (cons name sig) pending))))
      (when (and contract (/= (length required) (length pending)))
        (fail-at (node-span node) :semantic "Incomplete implementation"))
      (setf pending (nreverse pending)
            (implementation-info-methods info) (append (implementation-info-methods info) pending))
      (unless existing (vector-push-extend info (value-context-implementations context)))
      (setf (gethash node (value-context-members context)) (make-member-info :kind :implementation :implementation info))
      (loop for method across (implementation-declaration-methods node) for pair in pending do
        (funcall check-function (local-binding-initializer method) scopes (cdr pair) concrete))
      info)))

(defun check-value-node (node scopes context visit summarize require-type declare-local check-function owner signatures)
  (labels ((child (x &optional (env scopes)) (funcall visit x env))
           (nt (x) (completion-normal-type x))
           (record (info) (setf (gethash node (value-context-members context)) info))
           (summarize (type children &optional candidates exits)
             (funcall summarize node type children (when type candidates)
                      (not (null (find :return exits :key #'first))) exits))
           (require-type (n actual expected) (funcall require-type n actual expected))
           (require-arity (types values)
             (unless (= (length types) (length values)) (fail-at (node-span node) :semantic "Wrong argument count")))
           (variant (type token)
             (unless (nominal-type-p type :enum) (fail-at (token-span token) :semantic "Expected enum type"))
             (or (find (token-text token) (type-info-variants (context-type context type)) :key #'variant-info-name :test #'string=)
                 (fail-at (token-span token) :semantic "Unknown variant"))))
    (typecase node
      ((or data-declaration contract-declaration)
       (declare-value-type context node) (summarize :void nil))
      (implementation-declaration
       (register-implementation context node scopes signatures check-function) (summarize :void nil))
      (this-expression
       (let ((symbol (signature-receiver (aref signatures owner))))
         (unless symbol (fail-at (node-span node) :semantic "This requires its lexical method body"))
         (record (make-member-info :kind :this :index (local-symbol-id symbol) :type (local-symbol-type symbol)))
         (summarize (local-symbol-type symbol) nil)))
      (field-assignment
       (child (field-assignment-target node)) (child (field-assignment-value node))
       (fail-at (node-span node) :semantic "Data and receiver are immutable"))
      (struct-expression
       (let* ((type (resolve-type-token context (struct-expression-name node)))
              (fields (when (nominal-type-p type :struct) (type-info-fields (context-type context type))))
              (seen nil) (indices nil) (children nil))
         (unless (nominal-type-p type :struct) (fail-at (node-span node) :semantic "Expected struct type"))
         (loop for field across (struct-expression-fields node)
               for name = (token-text (named-member-name field))
               for index = (position name fields :key #'car :test #'string=) do
           (unless (and index (not (member index seen)))
             (fail-at (token-span (named-member-name field)) :semantic "Unknown or duplicate field"))
           (let ((value (child (named-member-value field))))
             (require-type (named-member-value field) (nt value) (cdr (nth index fields)))
             (push value children) (push index indices) (push index seen)))
         (unless (= (length fields) (length seen)) (fail-at (node-span node) :semantic "Missing field"))
         (record (make-member-info :kind :struct :type type :index (nreverse indices)))
         (summarize (when (every #'nt children) type) (nreverse children))))
      (enum-expression
       (let* ((type (resolve-type-token context (enum-expression-name node)))
              (variant (variant type (enum-expression-variant node)))
              (args (coerce (enum-expression-arguments node) 'list))
              (values (mapcar #'child args)) (types (variant-info-types variant)))
         (when (and (null types) (enum-expression-parenthesized-p node))
           (fail-at (node-span node) :semantic "A payload-free variant has no argument list"))
         (require-arity types values)
         (loop for arg in args for value in values for expected in types do (require-type arg (nt value) expected))
         (record (make-member-info :kind :enum :type type :variant (variant-info-id variant)))
         (summarize (when (every #'nt values) type) values)))
      (field-expression
       (let* ((head (child (field-expression-receiver node))) (type (nt head)))
         (if (null type) (summarize nil (list head))
             (let ((index (when (nominal-type-p type :struct)
                            (position (token-text (field-expression-name node)) (type-info-fields (context-type context type)) :key #'car :test #'string=))))
               (unless index (fail-at (token-span (field-expression-name node)) :semantic "Unknown field; methods require a call"))
               (record (make-member-info :kind :field :type type :index index))
               (summarize (cdr (nth index (type-info-fields (context-type context type)))) (list head))))))
      (branch-expression
       (let* ((on-p (eq (branch-expression-mode node) :on))
              (subject (when on-p (child (branch-expression-subject node))))
              (type (when subject (nt subject))) (seen nil) (fallback nil)
              (arm-types nil) (candidates nil) (normal-path nil)
              (reachable (if on-p (not (null type)) t))
              (exits (when subject (copy-list (completion-exits subject)))))
         (when (and type (not (nominal-type-p type :enum))) (fail-at (node-span node) :semantic "Branch on requires enum"))
         (loop for arm across (branch-expression-arms node) for selector = (branch-arm-selector arm)
               for inner = (cons (make-hash-table :test #'equal) scopes) do
           (when fallback (fail-at (node-span arm) :semantic "Else must be last"))
           (cond
             ((null selector) (setf fallback t))
             (on-p
              (let* ((selected (resolve-type-token context (variant-pattern-name selector)))
                     (variant (variant selected (variant-pattern-variant selector)))
                     (binders (variant-pattern-bindings selector)))
                (when (and type (not (equal type selected))) (fail-at (node-span selector) :semantic "Pattern enum mismatch"))
                (setf type selected)
                (when (member (variant-info-id variant) seen) (fail-at (node-span selector) :semantic "Duplicate variant"))
                (push (variant-info-id variant) seen)
                (require-arity (variant-info-types variant) binders)
                (setf (gethash selector (value-context-members context))
                      (make-member-info :kind :pattern :type type :variant (variant-info-id variant)))
                (loop for token across (or binders #()) for expected in (variant-info-types variant) do
                  (unless (string= (token-text token) "_")
                    (funcall declare-local token token :pattern inner expected)))))
             (t
              (let ((condition (child selector)))
                (require-type selector (nt condition) :bool)
                (when reachable
                  (setf exits (union exits (completion-exits condition) :test #'equal))
                  (unless (nt condition) (setf reachable nil))))))
           (let ((value (child (branch-arm-value arm) inner)))
             (when (nt value)
               (pushnew (nt value) arm-types :test #'equal)
               (setf candidates (union candidates (completion-targets value))))
             (when reachable
               (setf exits (union exits (completion-exits value) :test #'equal)
                     normal-path (or normal-path (nt value))))))
         (when (> (length arm-types) 1) (fail-at (node-span node) :semantic "Branch result types differ"))
         (if on-p
             (progn
               (unless type (fail-at (node-span node) :semantic "Cannot determine pattern enum"))
               (let ((total (length (type-info-variants (context-type context type)))))
                 (when (or (and (not fallback) (/= total (length seen)))
                           (and fallback (= total (length seen))))
                   (fail-at (node-span node) :semantic "Nonexhaustive branch or redundant else"))))
             (unless fallback
               (when (and arm-types (not (equal arm-types '(:void))))
                 (fail-at (node-span node) :semantic "A value branch requires else"))
               (when reachable (setf normal-path :void))))
         (record (make-member-info :kind :branch :type type))
         (summarize normal-path nil candidates exits)))
      (t (internal-error "Unsupported value AST")))))

(defun resolve-user-method (context receiver name)
  (if (nominal-type-p receiver :interface)
      (let* ((methods (type-info-methods (context-type context receiver)))
             (index (position name methods :key #'requirement-name :test #'string=)))
        (when index
          (values (make-member-info :kind :interface-call :type receiver :contract receiver :index index)
                  (requirement-parameters (nth index methods)) (requirement-result (nth index methods)))))
      (let ((candidates (method-candidates context receiver name)))
        (when candidates
          (if (cdr candidates) (values :ambiguous nil nil)
              (let ((sig (first candidates)))
                (values (make-member-info :kind :method :type receiver :signature sig)
                        (signature-parameter-types sig) (signature-result-type sig))))))))
