(in-package #:mognitio.source)

(defstruct source path octets text byte-offsets lines columns)
(defstruct (span (:constructor %make-span (source start end)))
  (source nil :read-only t) (start 0 :read-only t) (end 0 :read-only t))

(defun make-span (source start end)
  (unless (and (source-p source) (integerp start) (integerp end)
               (<= 0 start end (length (source-text source))))
    (internal-error "Invalid source span"))
  (%make-span source start end))

(defun span-diagnostic (span phase message)
  (let* ((source (span-source span)) (offset (span-start span)))
    (make-diagnostic :phase phase :message message :path (source-path source)
                     :line (aref (source-lines source) offset)
                     :column (aref (source-columns source) offset))))
(defun fail-at (span phase message &optional (kind 'source-failure))
  (error kind :diagnostic (span-diagnostic span phase message)))

(defun decode-source (path octets)
  (let ((text (make-array 0 :element-type 'character :adjustable t :fill-pointer 0))
        (offsets (make-array 0 :adjustable t :fill-pointer 0))
        (lines (make-array 0 :adjustable t :fill-pointer 0))
        (columns (make-array 0 :adjustable t :fill-pointer 0))
        (index 0) (line 1) (column 1) (previous-cr nil)
        (size (length octets)))
    (labels ((bad (message)
               (fail 'source-failure :source message
                     :path path :line line :column column))
             (boundary ()
               (vector-push-extend index offsets)
               (vector-push-extend line lines)
               (vector-push-extend column columns))
             (byte-at (delta low high)
               (when (>= (+ index delta) size) (bad "Incomplete UTF-8 sequence"))
               (let ((byte (aref octets (+ index delta))))
                 (unless (<= low byte high) (bad "Invalid UTF-8 sequence"))
                 byte)))
      (when (and (>= size 3) (= (aref octets 0) #xef)
                 (= (aref octets 1) #xbb) (= (aref octets 2) #xbf))
        (setf index 3))
      (loop while (< index size)
            for lead = (aref octets index)
            do (let ((width 1) (scalar lead))
                 (cond
                   ((<= lead #x7f))
                   ((<= #xc2 lead #xdf)
                    (setf width 2 scalar
                          (+ (ash (logand lead #x1f) 6)
                             (logand (byte-at 1 #x80 #xbf) #x3f))))
                   ((<= #xe0 lead #xef)
                    (setf width 3 scalar
                          (+ (ash (logand lead #x0f) 12)
                             (ash (logand (byte-at 1
                                                  (if (= lead #xe0) #xa0 #x80)
                                                  (if (= lead #xed) #x9f #xbf)) #x3f) 6)
                             (logand (byte-at 2 #x80 #xbf) #x3f))))
                   ((<= #xf0 lead #xf4)
                    (setf width 4 scalar
                          (+ (ash (logand lead #x07) 18)
                             (ash (logand (byte-at 1
                                                  (if (= lead #xf0) #x90 #x80)
                                                  (if (= lead #xf4) #x8f #xbf)) #x3f) 12)
                             (ash (logand (byte-at 2 #x80 #xbf) #x3f) 6)
                             (logand (byte-at 3 #x80 #xbf) #x3f))))
                   (t (bad "Invalid UTF-8 leading byte")))
                 (when (= scalar #xfeff) (bad "BOM is only allowed once at the start"))
                 (let ((character (code-char scalar)))
                   (unless character (internal-error "Host cannot represent Unicode scalar"))
                   (boundary)
                   (vector-push-extend character text))
                 (cond ((= scalar 13) (incf line) (setf column 1))
                       ((= scalar 10)
                        (unless previous-cr (incf line))
                        (setf column 1))
                       (t (incf column)))
                 (setf previous-cr (= scalar 13))
                 (incf index width)))
      (boundary))
    (make-source :path path :octets octets :text text
                 :byte-offsets offsets :lines lines :columns columns)))

(defun read-octets (path)
  ;; Limit the I/O handler to I/O: decoding has a different failure category.
  (when (find (code-char 0) path)
    (fail 'usage-or-io-failure nil "Invalid source path" :path path))
  (handler-case
      (with-open-file (stream (sb-ext:parse-native-namestring path)
                              :direction :input :element-type '(unsigned-byte 8))
        (let ((bytes (make-array 0 :element-type '(unsigned-byte 8)
                                  :adjustable t :fill-pointer 0)))
          (loop for byte = (read-byte stream nil nil)
                while byte do (vector-push-extend byte bytes))
          bytes))
    (file-error ()
      (fail 'usage-or-io-failure nil "Cannot read source" :path path))
    (stream-error ()
      (fail 'usage-or-io-failure nil "Cannot read source" :path path))))

(defun read-source (path)
  (decode-source path (read-octets path)))
