(in-package #:mognitio.semantic)

(defun rebuild-syntax-node (node replacements)
  ;; Constructors preserve read-only source objects. Only instance-local nodes
  ;; are created; no template slot or node-keyed table is modified.
  (let* ((name (type-of node)) (constructor (find-symbol (concatenate 'string "MAKE-" (symbol-name name)) (symbol-package name))))
    (unless (and constructor (fboundp constructor)) (internal-error "Missing syntax constructor"))
    (apply constructor
           (loop for slot in (sb-mop:class-slots (class-of node)) for key = (sb-mop:slot-definition-name slot)
                 for replacement = (assoc key replacements)
                 append (list (intern (symbol-name key) :keyword) (if replacement (cdr replacement) (slot-value node key)))))))

(defun specialize-program (checked)
  (verify-checked-program checked)
  (multiple-value-bind (instances context needed-types free) (plan-function-instances checked)
    (let* ((types (make-hash-table :test #'equal)) (keys (make-hash-table :test #'equal))
           (values (%make-value-context))
           (result (%make-checked-program
                     :summaries (make-hash-table :test #'eq) :symbols (make-hash-table :test #'eq)
                     :literals (make-hash-table :test #'eq) :consumed (make-hash-table :test #'eq)
                     :bindings (make-array 0 :adjustable t :fill-pointer 0)
                     :signatures (make-array (length instances)) :calls (make-hash-table :test #'eq)
                     :returns (make-hash-table :test #'eq) :functions (make-hash-table :test #'eq)
                     :loops (make-hash-table :test #'eq) :controls (make-hash-table :test #'eq)
                     :operations (make-hash-table :test #'eq) :values values :node-owners (make-hash-table :test #'eq))))
      (loop for type in needed-types for id from 0 do
        (setf (gethash type types) (list (type-info-kind (context-type context type)) id)))
      (loop for instance in instances for id from 0 do
        (setf (function-instance-id instance) id (gethash (function-instance-key instance) keys) instance))
      (labels ((remap-type (type)
                 (cond ((nominal-type-p type) (or (gethash type types) (internal-error "Unregistered concrete type")))
                       ((function-type-p type) (list :function (mapcar #'remap-type (second type)) (remap-type (third type))))
                       ((or (rigid-type-p type) (application-type-p type)) (internal-error "Opaque type reached runtime mapping"))
                       (t type)))
               (type-for (type instance)
                 (remap-type (substitute-generic-type context type (function-instance-environment instance))))
               (instance-for (declaration instance &optional arguments)
                 (let* ((env (instance-environment checked context free declaration arguments (function-instance-environment instance)))
                        (key (canonical-function-instance-key checked context free declaration arguments env)))
                   (or (gethash key keys) (internal-error "Missing function instance dependency"))))
               (id-for (id instance &optional arguments) (function-instance-id (instance-for id instance arguments)))
               (call-arguments (call instance)
                 (mapcar (lambda (type) (substitute-generic-type context type (function-instance-environment instance)))
                         (call-info-type-arguments call)))
               (targets-for (targets instance) (mapcar (lambda (id) (id-for id instance)) targets))
               (loop-for (info instance)
                 (or (gethash (loop-info-id info) (function-instance-loops instance)) (internal-error "Missing loop instance")))
               (exits-for (exits instance)
                 (mapcar (lambda (exit)
                           (ecase (first exit)
                             (:return
                              (unless (= (second exit) (function-instance-declaration instance)) (internal-error "Foreign return in instance"))
                              (list :return (function-instance-id instance) nil nil))
                             ((:break :continue)
                              (let ((loop (gethash (second exit) (function-instance-loops instance))))
                                (unless loop (internal-error "Foreign loop exit in instance"))
                                (list (first exit) (loop-info-id loop) (type-for (third exit) instance) (targets-for (fourth exit) instance)))))) exits))
               (implementation-for (info)
                 (when info (aref (value-context-implementations values) (implementation-info-id info))))
               (clone-node (node instance &optional concrete-callee)
                 (when (null node) (return-from clone-node nil))
                 (when (erased-template-p checked node) (return-from clone-node nil))
                 (or (gethash node (function-instance-nodes instance))
                     (let* ((static (and (typep node 'variable-reference) (local-symbol-static-target (checked-symbol checked node))))
                            (target (or concrete-callee
                                        (when (typep node 'function-expression) (instance-for (signature-id (checked-function checked node)) instance))
                                        (when static (instance-for static instance))))
                            (copy
                              (if target (make-concrete-function-reference :target (function-instance-id target) :span (node-span node))
                                  (rebuild-syntax-node node
                                    (append
                                     (when (typep node 'call-expression) (list (cons 'mognitio.syntax::type-arguments nil)))
                                     (loop for slot in (syntax-child-slots node) for child = (slot-value node slot)
                                           collect
                                           (cons slot
                                             (cond ((and (typep node 'call-expression) (eq slot 'mognitio.syntax::callee)
                                                         (call-expression-type-arguments node))
                                                    (let* ((call (checked-call checked node))
                                                           (callee (instance-for (call-info-template call) instance (call-arguments call instance))))
                                                      (clone-node child instance callee)))
                                                   ((and (vectorp child) (not (stringp child)))
                                                    (coerce (remove nil (map 'list (lambda (value) (clone-node value instance)) child)) 'vector))
                                                   (t (clone-node child instance))))))))))
                       (setf (gethash node (function-instance-nodes instance)) copy)
                       (when target (setf (gethash copy (checked-program-functions result)) (function-instance-signature target))) copy)))
               (copy-node-records (source target instance)
                 (let ((summary (gethash source (checked-program-summaries checked)))
                       (symbol (gethash source (checked-program-symbols checked)))
                       (call (gethash source (checked-program-calls checked)))
                       (member (checked-member checked source)) (operation (checked-operation checked source)))
                   (when summary
                     (let ((function (gethash target (checked-program-functions result))))
                       (setf (gethash target (checked-program-summaries result))
                             (make-completion :normal-type (if function (signature-type function) (type-for (completion-normal-type summary) instance))
                               :may-return (completion-may-return summary)
                               :targets (if function (list (signature-id function)) (targets-for (completion-targets summary) instance))
                               :exits (exits-for (completion-exits summary) instance))
                             (gethash target (checked-program-node-owners result)) (function-instance-id instance))))
                   (when (and symbol (not (typep target 'concrete-function-reference)))
                     (setf (gethash target (checked-program-symbols result))
                           (or (gethash (local-symbol-id symbol) (function-instance-locals instance)) (internal-error "Missing local instance"))))
                   (when (checked-literal-p checked source) (setf (gethash target (checked-program-literals result)) (checked-literal checked source)))
                   (when (gethash source (checked-program-consumed checked)) (setf (gethash target (checked-program-consumed result)) t))
                   (when call
                     (setf (gethash target (checked-program-calls result))
                           (make-call-info :type (type-for (call-info-type call) instance) :owner (function-instance-id instance)
                             :targets (mapcar (lambda (id) (id-for id instance (when (call-info-template call) (call-arguments call instance))))
                                              (call-info-targets call)))))
                   (when (gethash source (checked-program-returns checked))
                     (setf (gethash target (checked-program-returns result)) (function-instance-id instance)))
                   (when (gethash source (checked-program-loops checked))
                     (let ((loop (loop-for (checked-loop checked source) instance)))
                       (setf (loop-info-node loop) target (gethash target (checked-program-loops result)) loop)))
                   (when (gethash source (checked-program-controls checked))
                     (setf (gethash target (checked-program-controls result)) (loop-for (checked-control checked source) instance)))
                   (when operation
                     (setf (gethash target (checked-program-operations result))
                           (make-operation-info :kind (operation-info-kind operation)
                             :operands (mapcar (lambda (node) (gethash node (function-instance-nodes instance))) (operation-info-operands operation))
                             :parameter-types (mapcar (lambda (type) (type-for type instance)) (operation-info-parameter-types operation))
                             :result-type (type-for (operation-info-result-type operation) instance))))
                   (when member
                     (setf (gethash target (value-context-members values))
                           (make-member-info :kind (member-info-kind member) :type (type-for (member-info-type member) instance)
                             :index (if (eq (member-info-kind member) :this)
                                        (local-symbol-id (gethash (member-info-index member) (function-instance-locals instance)))
                                        (copy-tree (member-info-index member))) :variant (member-info-variant member)
                             :contract (type-for (member-info-contract member) instance)
                             :implementation (implementation-for (member-info-implementation member))
                             :signature (when (member-info-signature member)
                                          (function-instance-signature (instance-for (signature-id (member-info-signature member)) instance))))))
                   (when (checked-pack checked source)
                     (setf (gethash target (value-context-packs values)) (implementation-for (checked-pack checked source)))))))
        ;; All identities are fixed before node/table cloning starts.
        (dolist (type needed-types)
          (let* ((old (context-type context type)) (copy (copy-type-info old)))
            (setf (type-info-id copy) (second (gethash type types))
                  (type-info-source-id copy) (or (type-info-source-id old) (type-info-id old))
                  (type-info-arguments copy) (mapcar #'remap-type (type-info-arguments old))
                  (type-info-fields copy) (mapcar (lambda (field) (cons (car field) (remap-type (cdr field)))) (type-info-fields old))
                  (type-info-variants copy) (mapcar (lambda (variant) (make-variant-info :id (variant-info-id variant) :name (variant-info-name variant)
                                                                      :types (mapcar #'remap-type (variant-info-types variant)))) (type-info-variants old))
                  (type-info-methods copy) (mapcar (lambda (method) (make-requirement :name (requirement-name method)
                                                                   :parameters (mapcar #'remap-type (requirement-parameters method))
                                                                   :result (remap-type (requirement-result method)))) (type-info-methods old)))
            (vector-push-extend copy (value-context-types values))))
        (dolist (instance instances)
          (let* ((original (aref (checked-program-signatures checked) (function-instance-declaration instance)))
                 (sig (make-signature :id (function-instance-id instance)
                        :parameter-types (mapcar (lambda (type) (type-for type instance)) (signature-parameter-types original))
                        :result-type (type-for (signature-result-type original) instance)
                        :method (when (signature-method original)
                                  (list (remap-type (first (signature-method original))) (remap-type (second (signature-method original)))
                                        (third (signature-method original)))))))
            (setf (function-instance-signature instance) sig (aref (checked-program-signatures result) (signature-id sig)) sig)))
        (loop for implementation across (value-context-implementations (checked-program-values checked)) do
          (vector-push-extend
           (make-implementation-info :id (implementation-info-id implementation)
             :concrete (remap-type (implementation-info-concrete implementation)) :contract (remap-type (implementation-info-contract implementation))
             :methods (mapcar (lambda (pair) (cons (car pair) (function-instance-signature (instance-for (signature-id (cdr pair)) (first instances)))))
                              (implementation-info-methods implementation))) (value-context-implementations values)))
        (let ((next-loop 0))
          (dolist (instance instances)
            (loop for symbol across (checked-program-bindings checked)
                  when (and (= (local-symbol-owner symbol) (function-instance-declaration instance)) (null (local-symbol-template symbol))) do
              (let ((copy (make-local-symbol :id (length (checked-program-bindings result)) :owner (function-instance-id instance)
                            :name (local-symbol-name symbol) :mutability (local-symbol-mutability symbol) :span (local-symbol-span symbol)
                            :type (type-for (local-symbol-type symbol) instance) :targets (targets-for (local-symbol-targets symbol) instance)
                            :static-target (when (local-symbol-static-target symbol) (id-for (local-symbol-static-target symbol) instance)))))
                (setf (gethash (local-symbol-id symbol) (function-instance-locals instance)) copy)
                (vector-push-extend copy (checked-program-bindings result))))
            (let* ((signature (aref (checked-program-signatures checked) (function-instance-declaration instance)))
                   (receiver (signature-receiver signature)))
              (when receiver (setf (signature-receiver (function-instance-signature instance))
                                   (gethash (local-symbol-id receiver) (function-instance-locals instance)))))
            (dolist (loop (sort (loop for info being the hash-values of (checked-program-loops checked)
                                     when (= (loop-info-owner info) (function-instance-declaration instance)) collect info) #'< :key #'loop-info-id))
              (setf (gethash (loop-info-id loop) (function-instance-loops instance))
                    (make-loop-info :id next-loop :owner (function-instance-id instance) :normal-type (type-for (loop-info-normal-type loop) instance)
                      :targets (targets-for (loop-info-targets loop) instance) :plain (loop-info-plain loop) :valued (loop-info-valued loop)
                      :types (mapcar (lambda (type) (type-for type instance)) (loop-info-types loop))))
              (incf next-loop))))
        (dolist (instance instances)
          (let* ((id (function-instance-declaration instance)) (signature (function-instance-signature instance)))
            (if (zerop id) (setf (checked-program-program result) (clone-node (checked-program-program checked) instance))
                (let* ((declaration (signature-declaration (aref (checked-program-signatures checked) id)))
                       (copy (rebuild-syntax-node declaration
                               (list (cons 'mognitio.syntax::type-parameters #())
                                     (cons 'mognitio.syntax::parameters (map 'vector (lambda (p) (clone-node p instance)) (function-expression-parameters declaration)))
                                     (cons 'mognitio.syntax::body (clone-node (function-expression-body declaration) instance))))))
                  (setf (signature-declaration signature) copy (gethash declaration (function-instance-nodes instance)) copy
                        (gethash copy (checked-program-functions result)) signature)))))
        (dolist (instance instances)
          (maphash (lambda (source target) (copy-node-records source target instance)) (function-instance-nodes instance)))
        (setf (checked-program-specialization result)
              (make-specialization-proof :source checked :instances instances :free-parameters free :type-context context :type-map types))
        result))))
