(in-package #:mognitio.semantic)

(defun verify-specialization-internal (checked)
  (let* ((proof (checked-program-specialization checked))
         (source (specialization-proof-source proof)) (instances (specialization-proof-instances proof))
         (context (copy-instantiation-context (checked-program-values source)))
         (free (derive-function-free-parameters source))
         (actual (checked-program-values checked)) (keys (make-hash-table :test #'equal))
         (type-keys (make-hash-table :test #'equal)) (needed-types (make-hash-table :test #'equal))
         (environments (make-hash-table :test #'eq)) (edges (make-hash-table))
         (visited (make-hash-table :test #'eq)) (counts (make-hash-table))
         (local-count 0) (loop-count 0))
    (verify-checked-program source)
    (verification-ensure (equalp free (specialization-proof-free-parameters proof)) "Invalid free type dependency proof")
    (labels ((ensure (value message) (verification-ensure value message))
             (count-entry (kind) (incf (gethash kind counts 0)))
             (decode-type (key)
               ;; Decode canonical keys against source declarations, not the
               ;; producer's mutable instantiation context or substitution map.
               (cond ((member key '(:int :bool :void :string)) key)
                     ((and (consp key) (eq (first key) :nominal) (= (length key) 3))
                      (let ((type (list (second key) (third key))))
                        (ensure (not (type-info-origin (context-type context type))) "False nongeneric type identity") type))
                     ((and (consp key) (eq (first key) :generic) (= (length key) 4))
                      (let ((template (gethash (third key) (value-context-templates context)))
                            (arguments (mapcar #'decode-type (fourth key))))
                        (ensure (and template (eq (second key) (generic-template-kind template))
                                     (= (length arguments) (length (generic-template-parameters template)))
                                     (every #'generic-argument-p arguments)) "Invalid canonical type key")
                        (instantiate-generic-type context template arguments)))
                     (t (internal-error "Invalid type argument key"))))
             (track-type (type)
               (cond ((function-type-p type) (mapc #'track-type (second type)) (track-type (third type)))
                     ((nominal-type-p type)
                      (let ((key (concrete-type-key context type)))
                        (unless (gethash key needed-types)
                          (setf (gethash key needed-types) t)
                          (let ((info (context-type context type)))
                            (mapc #'track-type (type-info-arguments info))
                            (mapc (lambda (field) (track-type (cdr field))) (type-info-fields info))
                            (mapc (lambda (variant) (mapc #'track-type (variant-info-types variant))) (type-info-variants info))
                            (mapc (lambda (method) (mapc #'track-type (requirement-parameters method)) (track-type (requirement-result method)))
                                  (type-info-methods info))))))))
             (runtime-type (type &optional (track t))
               (when track (track-type type))
               (cond ((function-type-p type) (list :function (mapcar (lambda (x) (runtime-type x track)) (second type))
                                                     (runtime-type (third type) track)))
                     ((nominal-type-p type) (or (gethash (concrete-type-key context type) type-keys) (internal-error "Missing concrete descriptor")))
                     ((or (rigid-type-p type) (application-type-p type)) (internal-error "Unbound instance parameter"))
                     (t type)))
             (substitute-type (type instance)
               (substitute-generic-type context type (gethash instance environments)))
             (expected-type (type instance) (runtime-type (substitute-type type instance)))
             (require-instance (declaration arguments caller &optional root)
               (let* ((signature (aref (checked-program-signatures source) declaration))
                      (env (gethash caller environments))
                      (key (list declaration
                                 (mapcar (lambda (parameter) (concrete-type-key context (substitute-generic-type context parameter env)))
                                         (aref free declaration))
                                 (mapcar (lambda (type) (concrete-type-key context type)) arguments)))
                      (instance (gethash key keys)))
                 (ensure (and instance (= (length arguments) (length (signature-type-parameters signature)))) "Missing required function instance")
                 (unless root (pushnew (function-instance-id instance) (gethash (function-instance-id caller) edges))) instance))
             (target-id (declaration instance &optional arguments)
               (function-instance-id (require-instance declaration arguments instance)))
             (expected-targets (targets instance) (mapcar (lambda (id) (target-id id instance)) targets))
             (expected-exits (exits instance)
               (mapcar (lambda (exit)
                         (case (first exit)
                           (:return
                            (ensure (= (second exit) (function-instance-declaration instance)) "Invalid source return owner")
                            (list :return (function-instance-id instance) nil nil))
                           ((:break :continue)
                            (let ((loop (gethash (second exit) (function-instance-loops instance))))
                              (ensure loop "Missing concrete control target")
                              (list (first exit) (loop-info-id loop) (expected-type (third exit) instance) (expected-targets (fourth exit) instance))))
                           (otherwise (internal-error "Invalid instance exit")))) exits))
             (same-set (a b) (and (subsetp a b :test #'equal) (subsetp b a :test #'equal)))
             (same-implementation (a b)
               (if b (and a (eq a (aref (value-context-implementations actual) (implementation-info-id b)))) (null a)))
             (verify-records (old new instance &optional function)
               (let ((summary (gethash old (checked-program-summaries source)))
                     (member (checked-member source old)) (symbol (gethash old (checked-program-symbols source)))
                     (call (gethash old (checked-program-calls source))) (operation (checked-operation source old)))
                 (when summary
                   (let ((found (checked-completion checked new)))
                     (ensure (and (equal (if function (signature-type function) (expected-type (completion-normal-type summary) instance))
                                         (completion-normal-type found))
                                  (same-set (if function (list (signature-id function)) (expected-targets (completion-targets summary) instance))
                                            (completion-targets found))
                                  (eql (completion-may-return summary) (completion-may-return found))
                                  (same-set (expected-exits (completion-exits summary) instance) (completion-exits found))
                                  (eql (function-instance-id instance) (gethash new (checked-program-node-owners checked)))) "Invalid substituted completion"))
                   (count-entry :summary))
                 (when function
                   (ensure (eq function (gethash new (checked-program-functions checked))) "Invalid concrete function reference")
                   (count-entry :function))
                 (when (and symbol (not function))
                   (ensure (eq (gethash (local-symbol-id symbol) (function-instance-locals instance)) (checked-symbol checked new)) "Invalid substituted symbol")
                   (count-entry :symbol))
                 (when (checked-literal-p source old)
                   (ensure (and (checked-literal-p checked new) (= (checked-literal source old) (checked-literal checked new))) "Changed literal during specialization")
                   (count-entry :literal))
                 (when (gethash old (checked-program-consumed source))
                   (ensure (eq t (gethash new (checked-program-consumed checked))) "Changed consumed literal") (count-entry :consumed))
                 (when call
                   (let* ((found (checked-call checked new))
                          (arguments (mapcar (lambda (type) (substitute-type type instance)) (call-info-type-arguments call)))
                          (targets (mapcar (lambda (id) (target-id id instance arguments)) (call-info-targets call))))
                     (mapc #'track-type arguments)
                     (ensure (and (equal (expected-type (call-info-type call) instance) (call-info-type found))
                                  (= (function-instance-id instance) (call-info-owner found))
                                  (same-set targets (call-info-targets found)) (null (call-info-template found)) (null (call-info-type-arguments found)))
                             "Invalid substituted call")) (count-entry :call))
                 (when (gethash old (checked-program-returns source))
                   (ensure (eql (function-instance-id instance) (gethash new (checked-program-returns checked))) "Invalid substituted return") (count-entry :return))
                 (when (gethash old (checked-program-loops source))
                   (let ((loop (gethash (loop-info-id (checked-loop source old)) (function-instance-loops instance))))
                     (ensure (and (eq loop (checked-loop checked new)) (eq new (loop-info-node loop))) "Invalid cloned loop node")) (count-entry :loop))
                 (when (gethash old (checked-program-controls source))
                   (ensure (eq (gethash (loop-info-id (checked-control source old)) (function-instance-loops instance)) (checked-control checked new)) "Invalid cloned loop control")
                   (count-entry :control))
                 (when operation
                   (let ((found (checked-operation checked new)))
                     (ensure (and found (eq (operation-info-kind operation) (operation-info-kind found))
                                  (equal (mapcar (lambda (node) (gethash node (function-instance-nodes instance))) (operation-info-operands operation))
                                         (operation-info-operands found))
                                  (equal (expected-type (operation-info-result-type operation) instance) (operation-info-result-type found))
                                  (equal (mapcar (lambda (type) (expected-type type instance)) (operation-info-parameter-types operation))
                                         (operation-info-parameter-types found))) "Invalid substituted operation")) (count-entry :operation))
                 (when member
                   (let ((found (checked-member checked new)))
                     (ensure (and found (eq (member-info-kind member) (member-info-kind found))
                                  (equal (expected-type (member-info-type member) instance) (member-info-type found))
                                  (equal (expected-type (member-info-contract member) instance) (member-info-contract found))
                                  (equal (if (eq (member-info-kind member) :this)
                                             (local-symbol-id (gethash (member-info-index member) (function-instance-locals instance)))
                                             (member-info-index member)) (member-info-index found))
                                  (eql (member-info-variant member) (member-info-variant found))
                                  (same-implementation (member-info-implementation found) (member-info-implementation member))
                                  (eq (member-info-signature found)
                                      (when (member-info-signature member)
                                        (function-instance-signature (require-instance (signature-id (member-info-signature member)) nil instance)))))
                             "Invalid substituted member")) (count-entry :member))
                 (when (checked-pack source old)
                   (ensure (same-implementation (checked-pack checked new) (checked-pack source old)) "Invalid substituted adaptation") (count-entry :pack))))
             (verify-node (old new instance &optional forced-function declaration-p)
               (when (null old) (ensure (null new) "Unexpected cloned child") (return-from verify-node nil))
               (ensure (and new (eq new (gethash old (function-instance-nodes instance))) (not (gethash new visited)))
                       "Missing, shared, or inconsistent AST clone")
               (setf (gethash new visited) t)
               (let* ((static (and (typep old 'variable-reference) (local-symbol-static-target (checked-symbol source old))))
                      (function (or forced-function
                                    (when (and (not declaration-p) (typep old 'function-expression))
                                      (function-instance-signature (require-instance (signature-id (checked-function source old)) nil instance)))
                                    (when static (function-instance-signature (require-instance static nil instance))))))
                 (if (and function (not declaration-p))
                     (ensure (and (typep new 'concrete-function-reference) (= (signature-id function) (concrete-function-reference-target new))
                                  (eq (node-span old) (node-span new))) "Invalid concrete callee node")
                     (progn
                       (ensure (eq (type-of old) (type-of new)) "Changed AST node kind")
                       (dolist (slot (sb-mop:class-slots (class-of old)))
                         (let* ((name (sb-mop:slot-definition-name slot)) (a (slot-value old name)) (b (slot-value new name)))
                           (cond
                             ((and declaration-p (eq name 'mognitio.syntax::type-parameters)) (ensure (equalp b #()) "Remaining generic declaration parameters"))
                             ((and declaration-p (eq name 'mognitio.syntax::parameters))
                              (ensure (= (length a) (length b)) "Changed parameter arity")
                              (map nil (lambda (x y) (verify-node x y instance)) a b))
                             ((and declaration-p (eq name 'mognitio.syntax::body)) (verify-node a b instance))
                             ((and (typep old 'call-expression) (eq name 'mognitio.syntax::type-arguments)) (ensure (null b) "Unresolved explicit call arguments"))
                             ((and (typep old 'call-expression) (call-expression-type-arguments old) (eq name 'mognitio.syntax::callee))
                              (let* ((call (checked-call source old))
                                     (target (require-instance (call-info-template call)
                                               (mapcar (lambda (type) (substitute-type type instance)) (call-info-type-arguments call)) instance)))
                                (verify-node a b instance (function-instance-signature target))))
                             ((member name (syntax-child-slots old))
                              (if (and (vectorp a) (not (stringp a)))
                                  (let ((expected (remove-if (lambda (node) (erased-template-p source node)) (coerce a 'list))))
                                    (ensure (and (vectorp b) (= (length expected) (length b))) "Wrong compile-time statement erasure")
                                    (map nil (lambda (x y) (verify-node x y instance)) expected b))
                                  (verify-node a b instance)))
                             (t (ensure (equalp a b) "Changed source token or syntax field")))))))
                 (verify-records old new instance function))))
      (ensure (and (specialization-proof-p proof) (= (length instances) (length (checked-program-signatures checked)))
                   (equal instances (sort (copy-list instances) #'structural-key-before-p :key #'function-instance-key))) "Invalid instance ordering")
      (ensure (and (zerop (hash-table-count (value-context-names actual))) (zerop (hash-table-count (value-context-templates actual)))
                   (zerop (hash-table-count (value-context-instances actual)))) "Template registry leaked into backend")
      (loop for info across (value-context-types actual) for id from 0
            for key = (concrete-type-key actual (canonical-type info)) do
        (ensure (and (= id (type-info-id info)) (not (gethash key type-keys))) "Duplicate runtime type identity")
        (setf (gethash key type-keys) (canonical-type info)))
      (let ((order (loop for info across (value-context-types actual) collect (concrete-type-key actual (canonical-type info)))))
        (ensure (equal order (sort (copy-list order) #'structural-key-before-p)) "Nondeterministic runtime type order"))
      (loop for info across (value-context-types actual)
            for key = (concrete-type-key actual (canonical-type info)) for expected = (context-type context (decode-type key)) do
        (ensure (and (eq (type-info-kind info) (type-info-kind expected)) (string= (type-info-name info) (type-info-name expected))
                     (equal (type-info-fields info) (mapcar (lambda (x) (cons (car x) (runtime-type (cdr x) nil))) (type-info-fields expected)))
                     (equal (mapcar (lambda (v) (list (variant-info-id v) (variant-info-name v) (variant-info-types v))) (type-info-variants info))
                            (mapcar (lambda (v) (list (variant-info-id v) (variant-info-name v) (mapcar (lambda (type) (runtime-type type nil)) (variant-info-types v)))) (type-info-variants expected)))
                     (equal (mapcar (lambda (m) (list (requirement-name m) (requirement-parameters m) (requirement-result m))) (type-info-methods info))
                            (mapcar (lambda (m) (list (requirement-name m) (mapcar (lambda (type) (runtime-type type nil)) (requirement-parameters m)) (runtime-type (requirement-result m) nil))) (type-info-methods expected))))
                "Invalid concrete descriptor substitution"))
      (loop for instance in instances for id from 0 for key = (function-instance-key instance) do
        (ensure (and (= (length key) 3) (= id (function-instance-id instance))
                     (typep (first key) `(integer 0 ,(1- (length (checked-program-signatures source)))))
                     (= (first key) (function-instance-declaration instance)) (not (gethash key keys))) "Invalid function instance key")
        (let* ((signature (aref (checked-program-signatures source) (first key)))
               (free-types (mapcar #'decode-type (second key))) (arguments (mapcar #'decode-type (third key)))
               (env (append (pairlis (aref free (first key)) free-types) (pairlis (signature-type-parameters signature) arguments))))
          (ensure (and (= (length free-types) (length (aref free (first key))))
                       (= (length arguments) (length (signature-type-parameters signature)))
                       (every #'generic-argument-p (append free-types arguments))) "Invalid instance substitutions")
          (ensure (equal (third key) (mapcar (lambda (type) (concrete-type-key (specialization-proof-type-context proof) type)) (function-instance-arguments instance)))
                  "Wrong instance argument evidence")
          (ensure (and (= (length env) (length (function-instance-environment instance)))
                       (every (lambda (pair)
                                (let ((found (assoc (car pair) (function-instance-environment instance) :test #'equal)))
                                  (and found (equal (concrete-type-key context (cdr pair))
                                                    (concrete-type-key (specialization-proof-type-context proof) (cdr found)))))) env)) "Wrong instance environment evidence")
          (setf (gethash instance environments) env (gethash key keys) instance)))
      (dolist (instance instances)
        (let* ((declaration (function-instance-declaration instance))
               (original (aref (checked-program-signatures source) declaration)) (signature (function-instance-signature instance))
               (id (function-instance-id instance)) (expected-locals 0) (expected-loops 0))
          (ensure (and (eq signature (aref (checked-program-signatures checked) id)) (= id (signature-id signature))
                       (null (signature-type-parameters signature)) (null (signature-lexical-parameters signature)) (zerop (signature-parent signature))
                       (equal (mapcar (lambda (type) (expected-type type instance)) (signature-parameter-types original)) (signature-parameter-types signature))
                       (equal (expected-type (signature-result-type original) instance) (signature-result-type signature))
                       (equal (signature-method signature) (when (signature-method original)
                                                            (list (expected-type (first (signature-method original)) instance)
                                                                  (expected-type (second (signature-method original)) instance) (third (signature-method original))))))
                  "Invalid concrete signature")
          (loop for symbol across (checked-program-bindings source) when (and (= declaration (local-symbol-owner symbol)) (null (local-symbol-template symbol))) do
            (let ((copy (gethash (local-symbol-id symbol) (function-instance-locals instance))))
              (ensure (and copy (= local-count (local-symbol-id copy)) (eq copy (aref (checked-program-bindings checked) local-count))
                           (= id (local-symbol-owner copy)) (eq (local-symbol-mutability symbol) (local-symbol-mutability copy))
                           (string= (local-symbol-name symbol) (local-symbol-name copy)) (eq (local-symbol-span symbol) (local-symbol-span copy))
                           (equal (expected-type (local-symbol-type symbol) instance) (local-symbol-type copy)) (null (local-symbol-template copy))
                           (same-set (expected-targets (local-symbol-targets symbol) instance) (local-symbol-targets copy))
                           (eql (when (local-symbol-static-target symbol) (target-id (local-symbol-static-target symbol) instance)) (local-symbol-static-target copy)))
                      "Invalid concrete local")
              (incf local-count) (incf expected-locals)))
          (ensure (= expected-locals (hash-table-count (function-instance-locals instance))) "Unexpected local instance")
          (ensure (eq (signature-receiver signature) (when (signature-receiver original)
                                                     (gethash (local-symbol-id (signature-receiver original)) (function-instance-locals instance)))) "Invalid instance receiver")
          (dolist (loop (sort (loop for value being the hash-values of (checked-program-loops source) when (= declaration (loop-info-owner value)) collect value) #'< :key #'loop-info-id))
            (let ((copy (gethash (loop-info-id loop) (function-instance-loops instance))))
              (ensure (and copy (= loop-count (loop-info-id copy)) (= id (loop-info-owner copy))
                           (equal (expected-type (loop-info-normal-type loop) instance) (loop-info-normal-type copy))
                           (same-set (expected-targets (loop-info-targets loop) instance) (loop-info-targets copy))
                           (same-set (mapcar (lambda (type) (expected-type type instance)) (loop-info-types loop)) (loop-info-types copy))
                           (eql (loop-info-plain loop) (loop-info-plain copy)) (eql (loop-info-valued loop) (loop-info-valued copy))) "Invalid concrete loop")
              (incf loop-count) (incf expected-loops)))
          (ensure (= expected-loops (hash-table-count (function-instance-loops instance))) "Unexpected loop instance")
          (let ((before (hash-table-count visited)))
            (if (zerop declaration)
                (progn (ensure (null (signature-declaration signature)) "Concrete entry has a declaration")
                       (verify-node (checked-program-program source) (checked-program-program checked) instance))
                (verify-node (signature-declaration original) (signature-declaration signature) instance signature t))
            (ensure (= (- (hash-table-count visited) before) (hash-table-count (function-instance-nodes instance))) "Unexpected node correspondence"))))
      (ensure (= local-count (length (checked-program-bindings checked))) "Unexpected runtime local")
      (ensure (= (length (value-context-implementations actual)) (length (value-context-implementations (checked-program-values source)))) "Unexpected implementation instance")
      (loop for original across (value-context-implementations (checked-program-values source))
            for found across (value-context-implementations actual) do
        (ensure (and (= (implementation-info-id original) (implementation-info-id found))
                     (equal (runtime-type (implementation-info-concrete original)) (implementation-info-concrete found))
                     (equal (runtime-type (implementation-info-contract original)) (implementation-info-contract found))
                     (equal (mapcar (lambda (pair) (cons (car pair) (function-instance-signature (require-instance (signature-id (cdr pair)) nil (first instances)))))
                                    (implementation-info-methods original)) (implementation-info-methods found))) "Invalid instance implementation table"))
      (dolist (pair (list (cons :summary (checked-program-summaries checked)) (cons :summary (checked-program-node-owners checked))
                          (cons :symbol (checked-program-symbols checked)) (cons :literal (checked-program-literals checked))
                          (cons :consumed (checked-program-consumed checked)) (cons :function (checked-program-functions checked))
                          (cons :call (checked-program-calls checked)) (cons :return (checked-program-returns checked))
                          (cons :loop (checked-program-loops checked)) (cons :control (checked-program-controls checked))
                          (cons :operation (checked-program-operations checked)) (cons :member (value-context-members actual)) (cons :pack (value-context-packs actual))))
        (ensure (= (gethash (car pair) counts 0) (hash-table-count (cdr pair))) "Unexpected monomorphic metadata"))
      (ensure (= (hash-table-count needed-types) (hash-table-count type-keys)) "Unneeded runtime type instance")
      (let ((reachable (make-hash-table)) (pending nil))
        (loop for signature across (checked-program-signatures source) when (initial-function-root-p source signature)
              do (push (function-instance-id (require-instance (signature-id signature) nil (first instances) t)) pending))
        (loop while pending for id = (pop pending) unless (gethash id reachable) do
          (setf (gethash id reachable) t) (setf pending (append (gethash id edges) pending)))
        (ensure (= (hash-table-count reachable) (length instances)) "Unrequested function instance"))
      checked)))

(defun verify-specialization (checked)
  (handler-case (verify-specialization-internal checked)
    (internal-failure (condition) (error condition))
    (error () (internal-error "Malformed monomorphic program"))))

(defun prepare-runtime-program (checked)
  (unless (checked-program-p checked) (internal-error "Expected checked program"))
  (cond ((checked-program-specialization checked) (verify-specialization checked))
        ((or (> (hash-table-count (value-context-templates (checked-program-values checked))) 1)
             (some #'signature-type-parameters (checked-program-signatures checked))
             (some #'type-info-origin (value-context-types (checked-program-values checked))))
         (verify-specialization (specialize-program checked)))
        (t (verify-checked-program checked))))
