(in-package #:mognitio.semantic)

(defstruct function-instance key declaration arguments environment id signature
  (nodes (make-hash-table :test #'eq)) (locals (make-hash-table)) (loops (make-hash-table)))
(defstruct specialization-proof source instances free-parameters type-context type-map)

(defun syntax-child-slots (node)
  (mapcar (lambda (name) (intern (string name) :mognitio.syntax))
          (typecase node
            (program '(statements root)) (sequence-node '(statements terminal))
            (local-binding '(initializer)) (assignment '(rhs)) (return-statement '(value))
            (grouping '(expression)) (expression-statement '(expression))
            (call-expression '(callee arguments)) (method-call '(receiver arguments))
            (unary-expression '(operand)) (binary-expression '(left right))
            (if-expression '(condition then-branch else-branch))
            (loop-expression '(condition body)) (break-statement '(value))
            (struct-expression '(fields)) (enum-expression '(arguments))
            (named-member '(value)) (field-expression '(receiver))
            (branch-expression '(subject arms)) (branch-arm '(selector value))
            (variant-pattern '(bindings))
            (try-expression '(operand)) (panic-expression '(block)))))

(defun syntax-children (node)
  (loop for slot in (syntax-child-slots node) for value = (slot-value node slot)
        append (cond ((null value) nil) ((and (vectorp value) (not (stringp value))) (coerce value 'list)) (t (list value)))))

(defun erased-template-p (checked node)
  (or (and (typep node 'local-binding) (local-symbol-template (checked-symbol checked node)))
      (and (typep node 'data-declaration) (plusp (length (data-declaration-type-parameters node))))))

(defun walk-runtime-syntax (checked node visit)
  (when (and node (not (erased-template-p checked node)))
    (funcall visit node)
    (dolist (child (syntax-children node))
      ;; Explicit callee identifiers denote templates, not runtime values.
      (unless (and (typep node 'call-expression) (call-expression-type-arguments node)
                   (eq child (call-expression-callee node)))
        (walk-runtime-syntax checked child visit)))))

(defun type-parameters-in (type)
  (cond ((rigid-type-p type) (list type))
        ((application-type-p type) (remove-duplicates (mapcan #'type-parameters-in (copy-list (fourth type))) :test #'equal))
        ((function-type-p type) (remove-duplicates (mapcan #'type-parameters-in (append (second type) (list (third type)))) :test #'equal))))
(defun parameter-before-p (a b)
  (or (< (second (second a)) (second (second b)))
      (and (= (second (second a)) (second (second b))) (< (third a) (third b)))))
(defun source-function-root (checked id)
  (if (zerop id) (checked-program-program checked)
      (function-expression-body (signature-declaration (aref (checked-program-signatures checked) id)))))

(defun node-runtime-types (checked node)
  (let ((summary (gethash node (checked-program-summaries checked)))
        (member (checked-member checked node)) (call (gethash node (checked-program-calls checked)))
        (operation (checked-operation checked node)) (symbol (gethash node (checked-program-symbols checked))))
    (append (when summary (list (completion-normal-type summary)))
            (when member (list (member-info-type member) (member-info-contract member)))
            (when call (cons (call-info-type call) (call-info-type-arguments call)))
            (when operation (cons (operation-info-result-type operation) (operation-info-parameter-types operation)))
            (when symbol (list (local-symbol-type symbol))))))

(defun node-function-dependencies (checked node)
  (cond ((typep node 'function-expression) (list (signature-id (checked-function checked node))))
        ((gethash node (checked-program-calls checked)) (call-info-targets (checked-call checked node)))
        ((and (typep node 'variable-reference) (local-symbol-static-target (checked-symbol checked node)))
         (list (local-symbol-static-target (checked-symbol checked node))))))

(defun derive-function-free-parameters (checked)
  (let* ((signatures (checked-program-signatures checked)) (sets (make-array (length signatures) :initial-element nil))
         (dependencies (make-array (length signatures) :initial-element nil)))
    (loop for signature across signatures for id from 0 do
      (labels ((add-type (type) (setf (aref sets id) (union (aref sets id) (type-parameters-in type) :test #'equal))))
        (mapc #'add-type (cons (signature-result-type signature) (signature-parameter-types signature)))
        (walk-runtime-syntax checked (source-function-root checked id)
          (lambda (node)
            (mapc #'add-type (node-runtime-types checked node))
            (setf (aref dependencies id) (union (aref dependencies id) (node-function-dependencies checked node))))))
      (setf (aref sets id) (set-difference (aref sets id) (signature-type-parameters signature) :test #'equal)))
    (loop with changed = t while changed do
      (setf changed nil)
      (loop for signature across signatures for id from 0 do
        (dolist (dependency (aref dependencies id))
          (dolist (parameter (aref sets dependency))
            (unless (or (member parameter (signature-type-parameters signature) :test #'equal)
                        (member parameter (aref sets id) :test #'equal))
              (push parameter (aref sets id)) (setf changed t))))))
    (map 'vector (lambda (parameters) (sort parameters #'parameter-before-p)) sets)))

(defun copy-instantiation-context (source)
  (let ((context (%make-value-context)))
    (setf (value-context-names context) (copy-type-names (value-context-names source))
          (value-context-templates context) (copy-type-names (value-context-templates source))
          (value-context-instances context) (copy-type-names (value-context-instances source))
          (value-context-types context) (make-array (length (value-context-types source)) :adjustable t :fill-pointer t
                                                   :initial-contents (value-context-types source))) context))

(defun concrete-type-key (context type)
  (cond ((null type) nil) ((member type '(:int :bool :void :string)) type)
        ((or (rigid-type-p type) (application-type-p type)) (internal-error "Unresolved runtime type parameter"))
        ((function-type-p type) (list :function (mapcar (lambda (x) (concrete-type-key context x)) (second type))
                                     (concrete-type-key context (third type))))
        ((nominal-type-p type)
         (let ((info (context-type context type)))
           (if (type-info-origin info)
               (list :generic (type-info-kind info) (type-info-origin info)
                     (mapcar (lambda (x) (concrete-type-key context x)) (type-info-arguments info)))
               (list :nominal (type-info-kind info) (or (type-info-source-id info) (type-info-id info))))))
        (t (internal-error "Invalid concrete instance type"))))

(defun structural-key-before-p (a b)
  (labels ((rank (x) (cond ((null x) 0) ((integerp x) 1) ((symbolp x) 2) ((stringp x) 3) ((consp x) 4)
                          (t (internal-error "Invalid instance key component")))))
    (cond ((equal a b) nil) ((/= (rank a) (rank b)) (< (rank a) (rank b)))
          ((integerp a) (< a b)) ((symbolp a) (string< (symbol-name a) (symbol-name b)))
          ((stringp a) (string< a b))
          (t (if (equal (car a) (car b)) (structural-key-before-p (cdr a) (cdr b)) (structural-key-before-p (car a) (car b)))))))

(defun instance-environment (checked context free-parameters declaration arguments caller-environment)
  (let* ((signature (aref (checked-program-signatures checked) declaration))
         (free (aref free-parameters declaration)))
    (unless (= (length arguments) (length (signature-type-parameters signature))) (internal-error "Invalid instance argument arity"))
    (append (mapcar (lambda (parameter)
                      (let ((type (substitute-generic-type context parameter caller-environment)))
                        (concrete-type-key context type) (cons parameter type))) free)
            (mapcar (lambda (parameter argument)
                      (unless (generic-argument-p argument) (internal-error "Invalid instance argument domain"))
                      (concrete-type-key context argument) (cons parameter argument))
                    (signature-type-parameters signature) arguments))))

(defun canonical-function-instance-key (checked context free-parameters declaration arguments environment)
  (declare (ignore checked))
  (list declaration
        (mapcar (lambda (parameter) (concrete-type-key context (cdr (assoc parameter environment :test #'equal))))
                (aref free-parameters declaration))
        (mapcar (lambda (type) (concrete-type-key context type)) arguments)))

(defun initial-function-root-p (checked signature)
  (and (null (signature-type-parameters signature))
       (loop for parent = (signature-parent signature) then (signature-parent (aref (checked-program-signatures checked) parent))
             while (plusp parent) never (signature-type-parameters (aref (checked-program-signatures checked) parent)))))

(defun plan-function-instances (checked)
  (let* ((context (copy-instantiation-context (checked-program-values checked)))
         (free (derive-function-free-parameters checked)) (instances (make-hash-table :test #'equal)) (pending nil)
         (types (make-hash-table :test #'equal)))
    (labels ((note-type (type)
               (concrete-type-key context type)
               (cond ((function-type-p type) (mapc #'note-type (second type)) (note-type (third type)))
                     ((and (nominal-type-p type) (not (gethash type types)))
                      (setf (gethash type types) t)
                      (let ((info (context-type context type)))
                        (mapc #'note-type (type-info-arguments info))
                        (mapc (lambda (field) (note-type (cdr field))) (type-info-fields info))
                        (mapc (lambda (variant) (mapc #'note-type (variant-info-types variant))) (type-info-variants info))
                        (mapc (lambda (method) (mapc #'note-type (requirement-parameters method)) (note-type (requirement-result method)))
                              (type-info-methods info))))))
             (request (declaration arguments environment)
               (let* ((env (instance-environment checked context free declaration arguments environment))
                      (key (canonical-function-instance-key checked context free declaration arguments env)))
                 (or (gethash key instances)
                     (let ((instance (make-function-instance :key key :declaration declaration :arguments arguments :environment env)))
                       (setf (gethash key instances) instance) (push instance pending) instance)))))
      (loop for signature across (checked-program-signatures checked) when (initial-function-root-p checked signature)
            do (request (signature-id signature) nil nil))
      (loop while pending for instance = (pop pending) for environment = (function-instance-environment instance)
            for declaration = (function-instance-declaration instance)
            for signature = (aref (checked-program-signatures checked) declaration) do
        (flet ((substitute-type (type) (substitute-generic-type context type environment)))
          (mapc (lambda (type) (note-type (substitute-type type)))
                (cons (signature-result-type signature) (signature-runtime-types signature)))
          (walk-runtime-syntax checked (source-function-root checked declaration)
            (lambda (node)
              (mapc (lambda (type) (note-type (substitute-type type))) (node-runtime-types checked node))
              (let ((call (gethash node (checked-program-calls checked))))
                (dolist (target (node-function-dependencies checked node))
                  (request target (when (and call (call-info-template call))
                                    (mapcar #'substitute-type (call-info-type-arguments call))) environment)))))))
      (values (sort (loop for instance being the hash-values of instances collect instance) #'structural-key-before-p :key #'function-instance-key)
              context (sort (loop for type being the hash-keys of types collect type)
                            (lambda (a b) (structural-key-before-p (concrete-type-key context a) (concrete-type-key context b)))) free))))
