(in-package #:mognitio.syntax)

(defstruct text-payload (octets #() :read-only t) (scalar-count 0 :read-only t))
(defstruct token (kind nil :read-only t) (span nil :read-only t) (payload nil :read-only t))
(defstruct (type-syntax (:include token)) name (arguments #()))
(defstruct string-literal (payload nil :read-only t) (span nil :read-only t))
(defstruct method-call (receiver nil :read-only t) (name nil :read-only t)
  (arguments #() :read-only t) (span nil :read-only t))
(defstruct loop-expression (body nil :read-only t) (condition nil :read-only t) (span nil :read-only t))
(defstruct break-statement (value nil :read-only t) (span nil :read-only t))
(defstruct continue-statement (span nil :read-only t))
(defstruct void-literal (span nil :read-only t))
(defstruct expression-statement (expression nil :read-only t) (span nil :read-only t))
(defstruct boolean-literal (value nil :read-only t) (span nil :read-only t))
(defstruct if-expression (condition nil :read-only t) (then-branch nil :read-only t) (else-branch nil :read-only t) (span nil :read-only t))
(defstruct integer-literal (token nil :read-only t) (span nil :read-only t))
(defstruct variable-reference (name nil :read-only t) (span nil :read-only t))
(defstruct local-binding (annotation nil :read-only t) (mutability nil :read-only t) (name nil :read-only t) (initializer nil :read-only t) (span nil :read-only t))
(defstruct assignment (name nil :read-only t) (rhs nil :read-only t) (span nil :read-only t))
(defstruct sequence-node (statements nil :read-only t) (terminal nil :read-only t) (span nil :read-only t))
(defstruct grouping (expression nil :read-only t) (span nil :read-only t))
(defstruct unary-expression (operator nil :read-only t) (operand nil :read-only t) (span nil :read-only t))
(defstruct binary-expression (operator nil :read-only t) (left nil :read-only t) (right nil :read-only t) (span nil :read-only t))
(defstruct function-expression (type-parameters #() :read-only t) (parameters #() :read-only t)
  (result-type nil :read-only t) (body nil :read-only t) (span nil :read-only t))
(defstruct parameter (type nil :read-only t) (name nil :read-only t) (span nil :read-only t))
(defstruct call-expression (type-arguments nil :read-only t) (callee nil :read-only t) (arguments #() :read-only t) (span nil :read-only t))
(defstruct return-statement (keyword nil :read-only t) (value nil :read-only t) (span nil :read-only t))
(defstruct program (source nil :read-only t) (root nil :read-only t)
  (statements #() :read-only t))
(defun node-span (node)
  (typecase node
    (string-literal (string-literal-span node))
    (method-call (method-call-span node))
    (loop-expression (loop-expression-span node))
    (break-statement (break-statement-span node))
    (continue-statement (continue-statement-span node))
    (void-literal (void-literal-span node))
    (expression-statement (expression-statement-span node))
    (function-expression (function-expression-span node))
    (parameter (parameter-span node))
    (call-expression (call-expression-span node))
    (return-statement (return-statement-span node))
    (boolean-literal (boolean-literal-span node))
    (if-expression (if-expression-span node))
    (integer-literal (integer-literal-span node))
    (variable-reference (variable-reference-span node))
    (local-binding (local-binding-span node))
    (assignment (assignment-span node))
    (sequence-node (sequence-node-span node))
    (grouping (grouping-span node))
    (unary-expression (unary-expression-span node))
    (binary-expression (binary-expression-span node))
    (t (value-node-span node))))
(defun token-text (token)
  (when (typep token 'type-syntax) (return-from token-text (token-text (type-syntax-name token))))
  (let ((span (token-span token)))
    (subseq (source-text (span-source span)) (span-start span) (span-end span))))
