(in-package #:mognitio.syntax)

(defstruct data-declaration name kind target members span)
(defstruct contract-declaration name methods span)
(defstruct implementation-declaration target contract methods span)
(defstruct named-member name value span)
(defstruct struct-expression name fields span)
(defstruct enum-expression name variant arguments parenthesized-p span)
(defstruct field-expression receiver name span)
(defstruct field-assignment target value span)
(defstruct this-expression token span)
(defstruct branch-expression mode subject arms span)
(defstruct branch-arm selector value span)
(defstruct variant-pattern name variant bindings span)

(defun value-node-span (node)
  (typecase node
    (data-declaration (data-declaration-span node))
    (contract-declaration (contract-declaration-span node))
    (implementation-declaration (implementation-declaration-span node))
    (named-member (named-member-span node))
    (struct-expression (struct-expression-span node))
    (enum-expression (enum-expression-span node))
    (field-expression (field-expression-span node))
    (field-assignment (field-assignment-span node))
    (this-expression (this-expression-span node))
    (branch-expression (branch-expression-span node))
    (branch-arm (branch-arm-span node))
    (variant-pattern (variant-pattern-span node))))
