(in-package #:mognitio.text)

(defstruct (text-value (:constructor %make-text-value (octets scalar-count)))
  (octets #() :read-only t) (scalar-count 0 :read-only t))
(defparameter *empty* (%make-text-value (make-array 0 :element-type '(unsigned-byte 8)) 0))

(defun literal-value (payload)
  (if (zerop (mognitio.syntax:text-payload-scalar-count payload)) *empty*
      (%make-text-value (mognitio.syntax:text-payload-octets payload)
                        (mognitio.syntax:text-payload-scalar-count payload))))
(defun checked-size (a b)
  (let ((sum (+ a b)))
    (unless (<= 0 sum mognitio.integer:+maximum+)
      (mognitio.runtime:runtime-error :string-size-overflow))
    sum))
(defun allocate-bytes (size)
  (when (>= size array-dimension-limit) (mognitio.runtime:runtime-error :allocation-failed))
  (make-array size :element-type '(unsigned-byte 8)))
(defun allocate-text (size count fill)
  ;; Only program payload/object allocation converts host storage failures.
  (handler-case
      (let ((bytes (allocate-bytes size)))
        (funcall fill bytes)
        (%make-text-value bytes count))
    (storage-condition () (mognitio.runtime:runtime-error :allocation-failed))))
(defun text-length (text) (text-value-scalar-count text))
(defun text-equal (a b)
  (and (= (text-length a) (text-length b))
       (equalp (text-value-octets a) (text-value-octets b))))
(defun text-not-equal (a b) (not (text-equal a b)))
(defun text-concat (a b)
  (let* ((left (text-value-octets a)) (right (text-value-octets b))
         (size (checked-size (length left) (length right)))
         (count (checked-size (text-length a) (text-length b))))
    (cond ((zerop size) *empty*)
          (t (allocate-text size count
               (lambda (out) (replace out left) (replace out right :start1 (length left))))))))
(defun scalar-offset (bytes index)
  (loop with cursor = 0 repeat index do
    (incf cursor (let ((lead (aref bytes cursor)))
                   (cond ((< lead #x80) 1) ((< lead #xe0) 2) ((< lead #xf0) 3) (t 4))))
    finally (return cursor)))
(defun text-slice (text start end)
  (unless (<= 0 start end (text-length text))
    (mognitio.runtime:runtime-error :string-index-out-of-bounds))
  (cond ((= start end) *empty*)
        (t (let* ((bytes (text-value-octets text)) (first (scalar-offset bytes start))
                  (last (scalar-offset bytes end)))
             (allocate-text (- last first) (- end start)
               (lambda (out) (replace out bytes :start2 first :end2 last)))))))
