(in-package #:mognitio.semantic)

(defstruct type-info id kind name fields variants methods origin arguments source-id)
(defstruct variant-info id name types)
(defstruct requirement name parameters result)
(defstruct implementation-info id concrete contract methods)
(defstruct member-info kind type index variant implementation signature contract)
(defstruct (value-context (:constructor %make-value-context ()))
  (names (make-hash-table :test #'equal))
  (types (make-array 0 :adjustable t :fill-pointer 0))
  (implementations (make-array 0 :adjustable t :fill-pointer 0))
  (members (make-hash-table :test #'eq))
  (packs (make-hash-table :test #'eq))
  (interface-calls nil)
  (templates (make-hash-table :test #'equal))
  (instances (make-hash-table :test #'equal))
  (parameter-uses (make-hash-table :test #'equal))
  (next-template 0))

(defun make-value-context () (initialize-generic-context (%make-value-context)))

(defun nominal-type-p (type &optional kind)
  (or (and (application-type-p type) (member (second type) (if kind (list kind) '(:struct :enum))))
      (and (consp type) (= (length type) 2)
           (member (first type) (if kind (list kind) '(:struct :enum :interface)))
           (typep (second type) '(integer 0 *)))))
(defun reference-type-p (type)
  (or (eq type :string) (nominal-type-p type)))
(defun valid-value-type-p (type)
  (or (member type '(:int :bool :void :string)) (nominal-type-p type) (rigid-type-p type)))
(defun reject-function-type (type form message)
  (when (function-type-p type) (fail-at (form-span form) :semantic message))
  type)
(defun canonical-type (info) (list (type-info-kind info) (type-info-id info)))
(defun context-type (context type)
  (when (application-type-p type)
    (return-from context-type (generic-instance-shape context (gethash (third type) (value-context-templates context)) (fourth type))))
  (unless (and (nominal-type-p type) (< (second type) (length (value-context-types context))))
    (internal-error "Invalid nominal type"))
  (let ((info (aref (value-context-types context) (second type))))
    (unless (equal type (canonical-type info)) (internal-error "Nominal identity mismatch")) info))
(defun resolve-type-token (context token)
  (cond ((typep token 'function-type-syntax)
         (list :function
               (map 'list (lambda (part) (resolve-type-token context part)) (function-type-syntax-parameters token))
               (resolve-type-token context (function-type-syntax-result token))))
        ((typep token 'generic-signature-syntax)
         (fail-at (generic-signature-syntax-span token) :semantic "Generic function signature is not a type"))
        ((and (typep token 'token) (member (token-kind token) '(:int :bool :void :string))) (token-kind token))
        (t (resolve-generic-type context token))))
(defun find-implementation (context concrete contract)
  (find-if (lambda (info) (and (equal concrete (implementation-info-concrete info))
                             (equal contract (implementation-info-contract info))))
           (value-context-implementations context)))
(defun checked-member (checked node)
  (gethash node (value-context-members (checked-program-values checked))))
(defun checked-pack (checked node)
  (gethash node (value-context-packs (checked-program-values checked))))
(defun checked-value-type (checked node)
  (let ((pack (checked-pack checked node)))
    (if pack (implementation-info-contract pack) (checked-normal-type checked node))))
(defun signature-runtime-types (signature)
  (append (when (signature-receiver signature) (list (local-symbol-type (signature-receiver signature))))
          (signature-parameter-types signature)))
(defun method-candidates (context concrete name)
  (loop for info across (value-context-implementations context)
        when (equal concrete (implementation-info-concrete info))
          append (loop for pair in (implementation-info-methods info)
                       when (string= name (car pair)) collect (cdr pair))))

(defun declare-value-type (context node)
  (when (and (typep node 'data-declaration) (plusp (length (data-declaration-type-parameters node))))
    (return-from declare-value-type (declare-generic-type context node)))
  (let* ((contract-p (typep node 'contract-declaration))
         (name (if contract-p (contract-declaration-name node) (data-declaration-name node)))
         (kind (if contract-p :interface (data-declaration-kind node)))
         (seen (make-hash-table :test #'equal)))
    (when (gethash (token-text name) (value-context-names context))
      (fail-at (token-span name) :semantic "Duplicate type name"))
    (labels ((unique (token)
               (when (gethash (token-text token) seen) (fail-at (token-span token) :semantic "Duplicate member"))
               (setf (gethash (token-text token) seen) t))
             (data-type (token)
               (let ((type (resolve-type-token context token)))
                 (reject-function-type type token "Function storage is not supported")
                 (when (nominal-type-p type :interface) (fail-at (token-span token) :semantic "Interface storage is not supported")) type)))
      (let ((type
              (if (eq kind :alias) (resolve-type-token context (data-declaration-target node))
                  (let ((info (make-type-info :id (length (value-context-types context)) :kind kind :name (token-text name))))
                    (ecase kind
                      (:struct
                       (setf (type-info-fields info)
                             (loop for field across (data-declaration-members node) do (unique (named-member-name field))
                                   collect (cons (token-text (named-member-name field)) (data-type (named-member-value field))))))
                      (:enum
                       (setf (type-info-variants info)
                             (loop for variant across (data-declaration-members node) for id from 0 do (unique (named-member-name variant))
                                   collect (make-variant-info :id id :name (token-text (named-member-name variant))
                                             :types (map 'list #'data-type (named-member-value variant))))))
                      (:interface
                       (setf (type-info-methods info)
                             (loop for method across (contract-declaration-methods node)
                                   for function = (named-member-value method) do (unique (named-member-name method))
                                   collect (make-requirement :name (token-text (named-member-name method))
                                             :parameters (map 'list (lambda (p) (reject-function-type (resolve-type-token context (parameter-type p)) (parameter-type p) "Function type is not a parameter type"))
                                                              (function-expression-parameters function))
                                             :result (reject-function-type (resolve-type-token context (function-expression-result-type function)) (function-expression-result-type function) "Function type is not a return type"))))))
                    (setf (type-info-id info) (length (value-context-types context)))
                    (vector-push-extend info (value-context-types context)) (canonical-type info)))))
        (setf (gethash (token-text name) (value-context-names context)) type
              (gethash node (value-context-members context)) (make-member-info :kind :declaration :type type)) type))))

(defun check-adaptation (context node actual expected)
  (cond ((or (null actual) (equal actual expected)) t)
        ((and (nominal-type-p actual) (nominal-type-p expected :interface)
              (find-implementation context actual expected))
         (setf (gethash node (value-context-packs context)) (find-implementation context actual expected)))
        (t (fail-at (node-span node) :semantic "Type mismatch"))))
